:- package(dcg_phrase).
% (see dcg_phrase_doc for documentation)

:- use_package(dcg).

% Invoked from code generated by DCG translation
:- use_module(library(dcg/dcg_phrase_rt), [phrase/2, phrase/3]).

% The dcg_phrase package includes this callback in the module. This
% hook is used by the phrase/{2,3} predicates, which translate the
% input goal and call the expanded code in the context of the caller
% module.

:- if(defined('SHELL')).
:- else.
:- use_module(engine(hiord_rt), [call/1]).
:- '\6\use_call_in_module'. % (treated by dcg_tr)
:- multifile('\6\call_in_module'/2).
:- endif.

