/*
 * PhoneInsert.java
 *
 * Created on April 26, 2001, 9:08 PM
 */
import CiaoJava.*;


/**
 *
 * @author  jcorreas
 * @version 
 */
public class PhoneInsert extends javax.swing.JDialog {

    /** Creates new form PhoneInsert */
    public PhoneInsert(java.awt.Frame parent,boolean modal) {
        super (parent, modal);
        initComponents ();
        pack ();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPosition = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnOk = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        getContentPane().setLayout(new java.awt.GridLayout(6, 2));
        setTitle("Insert Dialog");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        }
        );
        
        jLabel1.setText("Name");
        
        getContentPane().add(jLabel1);
        
        
        
        getContentPane().add(txtName);
        
        
        jLabel2.setText("Telephone");
        
        getContentPane().add(jLabel2);
        
        
        
        getContentPane().add(txtPhone);
        
        
        jLabel3.setText("E-mail");
        
        getContentPane().add(jLabel3);
        
        
        
        getContentPane().add(txtEmail);
        
        
        jLabel4.setText("Address");
        
        getContentPane().add(jLabel4);
        
        
        
        getContentPane().add(txtAddress);
        
        
        jLabel5.setText("Position");
        
        getContentPane().add(jLabel5);
        
        
        
        getContentPane().add(txtPosition);
        
        
        getContentPane().add(jPanel2);
        
        
        jPanel1.setLayout(new java.awt.GridLayout(1, 2));
        
        btnOk.setText("OK");
          btnOk.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
                  btnOkActionPerformed(evt);
              }
          }
          );
          jPanel1.add(btnOk);
          
          
        btnCancel.setText("Cancel");
          btnCancel.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
                  btnCancelActionPerformed(evt);
              }
          }
          );
          jPanel1.add(btnCancel);
          
          
        getContentPane().add(jPanel1);
        
        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setSize(new java.awt.Dimension(400, 200));
        setLocation((screenSize.width-400)/2,(screenSize.height-200)/2);
    }//GEN-END:initComponents
 
  private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
      // Begin Ciao specific code.
      // Gets the form data and invokes PhoneList method to do
      // the actual insertion.
 
      String values[] = new String[5];
      values[0] = txtName.getText();
      values[1] = txtPhone.getText();
      values[2] = txtEmail.getText();
      values[3] = txtAddress.getText();
      values[4] = txtPosition.getText();
      
      ((PhoneList)getOwner()).insertRow(values);
      setVisible(false);
      dispose();
      // End Ciao specific code.
  }//GEN-LAST:event_btnOkActionPerformed

  private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
      // Begin Ciao specific code.
      // Closes this form.
      setVisible(false);
      dispose();
      // End Ciao specific code.
  }//GEN-LAST:event_btnCancelActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible (false);
        dispose ();
    }//GEN-LAST:event_closeDialog

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtPosition;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtName;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnCancel;
    // End of variables declaration//GEN-END:variables

}


