/***************************************************************************/
/*                             WARNING!!!                                  */
/*                      D O   N O T   M O D I F Y                          */
/*                This file is autogenerated by emugen                     */
/***************************************************************************/

#define SetB(X) (pt1 = (tagged_t *)(X))
#define LoadH (H = w->global_top)
#define StoreH (w->global_top = H)
#define Htab ((sw_on_key_t *)pt1)
#define SetHtab(X) (pt1 = (tagged_t *)(X))
#define HtabNode ((sw_on_key_node_t *)P)
#define SetHtabNode(X) (P = (bcp_t)(X))
#define Alts ((try_node_t *)pt1)
#define SetAlts(X) (pt1 = (tagged_t *)(X))
#define PoffR(X) BCoff(P, ((X)-1)*FTYPE_size(f_o))
#define BcOPCODE BcFetchOPCODE()
#define BcP(Ty,X) (*(FTYPE_ctype(Ty) *)PoffR((X)))
CFUN__PROTO(wam__2,int,goal_descriptor_t * desc,definition_t * start_func);
CFUN__PROTO(wam,int,goal_descriptor_t * desc) {
definition_t *func;
func = (definition_t *)NULL;
goto again;
again:
EXCEPTION__CATCH({
return wam__2(Arg, desc, func);
}, {
tagged_t *pt1; int i;
if (w->next_alt) {
SetB(w->node);
if (B->next_alt) {
B->next_alt = w->next_alt;
  } else {
B->next_alt = w->next_alt; /* 4 contiguous moves */
B->frame = w->frame;
B->next_insn = w->next_insn;
SaveLtop(B);
i=B->next_alt->node_offset;
if (i>ArityToOffset(0)) {
i = OffsetToArity(i);
SetB(w->next_node);
ON_DEBUG({
if (debug_choicepoints) {
fprintf(stderr, "Storing %d registers (r) in node %x\n", i, (int)w->next_node);
      }
});
do {
ChoicePush(pt1,(w->term-1)[i]);} while (--i);      }
if (ChoiceYounger(ChoiceOffset(B,CHOICEPAD),w->trail_top)) {
choice_overflow(Arg,CHOICEPAD);
      }
    }
w->next_alt = NULL;
SetE(w->local_top);
  }
X(0) = MakeSmall(ErrCode);
X(1) = init_atom_check(ErrFuncName);
X(2) = MakeSmall(ErrFuncArity);
X(4) = Culprit;
X(3) = MakeSmall(ErrArgNo);
func = address_error;
goto again;
});
}
CFUN__PROTO(wam__2,int,goal_descriptor_t * desc,definition_t * start_func) {
CIAO_REG_1(bcp_t, p);
CIAO_REG_2(tagged_t *, pt1);
CIAO_REG_3(tagged_t *, pt2);
intmach_t i;
tagged_t t0;
tagged_t t1;
tagged_t t2;
tagged_t t3;
bcp_t ptemp = NULL;
int wam_exit_code = 0;
instance_t * ins;
worker_t * new_worker;
pt1 = NULL;
pt2 = NULL;
t0 = ~0;
t1 = ~0;
t2 = ~0;
t3 = ~0;
i = ~0;
ON_DEBUG({
if (debug_threads) {
printf("Worker state address is %p\n", desc);  }
});
if (start_func != NULL) {
P = (bcp_t)start_func;
SetB(w->node);
LoadH;
goto switch_on_pred;
  }
if (desc && (desc->action & BACKTRACKING)) {
RECOVER_WAM_STATE;
goto fail;
  }
goto r_proceed;
unify_t0_t1:
SwitchOnVar(t0,i,{
goto t0_is_hva;
},{
goto t0_is_cva;
},{
goto t0_is_sva;
},{
;});
SwitchOnVar(t1,i,{
BindHVA(t1,t0);
goto unify_t0t1_done;
},{
BindCVA(t1,t0);
goto unify_t0t1_done;
},{
BindSVA(t1,t0);
goto unify_t0t1_done;
},{
;});
if (!(t1 ^= t0)) {
goto unify_t0t1_done;
  } else if (t1>=QMask) {
goto fail;
  } else if (!(t0 & TagBitComplex)) {
goto fail;
  } else if (!(t0 & TagBitFunctor)) {
t1 ^= t0;if (cunify_args(Arg,2,TagToCar(t0),TagToCar(t1))) {
goto unify_t0t1_done;
    } else {
goto fail;
    }
  } else {
t1 ^= t0;if (TagToHeadfunctor(t0) != (i=TagToHeadfunctor(t1))) {
goto fail;
    } else if (i&QMask) {
for (i = LargeArity(i)-1; i>0; i--) {
if (*TagToArg(t0,i) != *TagToArg(t1,i)) {
goto fail;
        }
}
goto unify_t0t1_done;
    } else if (cunify_args(Arg,Arity(i),TagToArg(t0,1),TagToArg(t1,1))) {
goto unify_t0t1_done;
    } else {
goto fail;
    }
  }
t0_is_hva:
SwitchOnVar(t1,i,{
if (t0==t1) {
;  } else if (YoungerHeapVar(TagToHVA(t1),TagToHVA(t0))) {
BindHVA(t1,t0);
  } else {
BindHVA(t0,t1);
  }
},{
BindHVA(t0,t1);
},{
BindSVA(t1,t0);
},{
BindHVA(t0,t1);
});
goto unify_t0t1_done;
t0_is_cva:
SwitchOnVar(t1,i,{
BindHVA(t1,t0);
},{
if (t0==t1) {
;  } else if (YoungerHeapVar(TagToCVA(t1),TagToCVA(t0))) {
BindCVA(t1,t0);
  } else {
BindCVA(t0,t1);
  }
},{
BindSVA(t1,t0);
},{
BindCVA(t0,t1);
});
goto unify_t0t1_done;
t0_is_sva:
for (; TagIsSVA(t1); t1 = i) {
RefSVA(i,t1);if (t1 == i) {
if (t0==t1) {
goto unify_t0t1_done;
      } else if (YoungerStackVar(TagToSVA(t1),TagToSVA(t0))) {
BindSVA(t1,t0);
      } else {
BindSVA(t0,t1);
      }
goto unify_t0t1_done;
    }
}
BindSVA(t0,t1);
goto unify_t0t1_done;
unify_t0t1_done:
goto ReadMode;
suspend_on_t1:
if (Func->arity==0) {
t3 = Func->printname;
  } else {
t3 = Tag(STR,H);
HeapPush(H,SetArity(Func->printname,Func->arity));
for (i=0; i<Func->arity; i++) {
t1 = X(i);
if (TagIsSVA(t1)) {
do {
RefSVA(t0,t1);
if (t0 == t1) {
BindSVA(t1,TagHVA(H));
PreLoadHVA(t1,H);
break;
          }
} while (TagIsSVA(t1=t0));        }
HeapPush(H,t1);
}
    }
if (TagIsSVA(t1=X(0))) {
RefSVA(t1,X(0));
    }
suspend_t3_on_t1:
if (TagIsHVA(t1)) {
LoadCVA(t0,H);
pt1 = w->trail_top;
if (CondHVA(t1)) {
TrailPush(pt1,t1);*TagToHVA(t1) = t0;
      } else {
*TagToHVA(t1) = t0;
      }
goto check_trail;
    } else if (!CondCVA(t1)) {
HeapPush(H,*TagToGoal(t1));
HeapPush(H,*TagToDef(t1));
*TagToGoal(t1) = Tag(LST,HeapOffset(H,-2));
*TagToDef(t1) = Tag(LST,H);
goto no_check_trail;
    } else {
LoadCVA(t0,H);
HeapPush(H,Tag(LST,TagToGoal(t1)));
HeapPush(H,Tag(LST,HeapOffset(H,1)));
pt1 = w->trail_top;
TrailPush(pt1,t1);*TagToCVA(t1) = t0;
goto check_trail;
    }
check_trail:
w->trail_top = pt1;
if (ChoiceYounger(w->node,TrailOffset(pt1,CHOICEPAD))) {
choice_overflow(Arg,CHOICEPAD);    }
goto no_check_trail;
no_check_trail:
HeapPush(H,t3);
HeapPush(H,PointerToTerm(Func));
goto w_proceed;
escape_to_p2:
t2 = PointerToTerm(Func->code.intinfo);
goto escape_to_p;
escape_to_p:
if (Func->arity==0) {
t3 = Func->printname;
    } else {
t3 = Tag(STR,H);
HeapPush(H,SetArity(Func->printname,Func->arity));
for (i=0; i<Func->arity; i++) {
t1 = X(i);
if (TagIsSVA(t1)) {
do {
RefSVA(t0,t1);
if (t0 == t1) {
BindSVA(t1,TagHVA(H));
PreLoadHVA(t1,H);
break;
            }
} while (TagIsSVA(t1=t0));          }
HeapPush(H,t1);
}
      }
P = ptemp;
X(0) = t3;
X(1) = t2;
goto switch_on_pred;
undo:
w->trail_top = pt2;
w->frame = B->frame;
w->next_insn = B->next_insn;
SetE(NodeLocalTop(B));
E->frame = w->frame;
E->next_insn = w->next_insn;
w->frame = E;
w->next_insn = failcode;
SetA(E,Offset(E,EToY0));
LoadH;
X(0) = t0;
goto call1;
fail:
PROFILE__HOOK_FAIL;
ON_DEBUG({
if (debug_choicepoints) {
fprintf(stderr, "Failing: node = %x, next_node = %x, conc. node = %x\n", (int)w->node, (int)w->next_node, (int)TopConcChpt);
      }
if ((w->misc->top_conc_chpt < w->node) && 	    (w->misc->top_conc_chpt < w->next_node)) {
fprintf(stderr, "********** what happened here?\n");
      }
});
Heap_Warn_Soft = Int_Heap_Warn;
SetB(w->node);
ON_TABLING( MAKE_TRAIL_CACTUS_STACK; );
if (TrailYounger(pt2=w->trail_top,t1=(tagged_t)TagToPointer(B->trail_top))) {
do {
PlainUntrail(pt2,t0,{
goto undo;
});
} while (TrailYounger(pt2,t1));w->trail_top = pt2;
        }
RestoreGtop(B);
if ((P = (bcp_t)w->next_alt) == NULL) {
ON_DEBUG({
if (debug_choicepoints) {
fprintf(stderr, "deep backtracking, node = %x\n", (int)w->node);
          }
});
P = (bcp_t)B->next_alt;
w->frame = B->frame;
w->next_insn = B->next_insn;
RestoreLtop(B);
i = ((try_node_t *)P)->node_offset;
w->next_node = ChoiceCharOffset(B,-i);
if (i>ArityToOffset(0)) {
tagged_t *wt = w->term;
S = (tagged_t *)w->next_node;
i = OffsetToArity(i) - 1;
ON_DEBUG({
if (debug_choicepoints) {
fprintf(stderr, "Reloading %d words from node %x\n", i, (int)w->node);
            }
});
while(i >= 0) wt[i--] = ChoiceNext(S);
          }
        }
PROFILE__HOOK_REDO;
if ((w->next_alt = ((try_node_t *)P)->next)==NULL) {
SetB(w->next_node);
w->node = B;
ON_TABLING({
if (FrozenChpt(B)) {
push_choicept(w,address_nd_fake_choicept);
          }
});
SetShadowregs(B);
        }
P = ((try_node_t *)P)->emul_p;
t0 = X(0);
if (!IsVar(t0)) {
goto ReadMode;
        }
LoadH;
goto WriteMode;
enter_predicate:
ON_ANDPARALLEL({
if (Suspend == TOSUSPEND) {
Suspend = SUSPENDED;
Wait_Acquire_lock(Waiting_For_Work_Lock);Cond_Var_Wait(Waiting_For_Work_Cond_Var,Waiting_For_Work_Lock);Suspend = RELEASED;
Release_lock(Waiting_For_Work_Lock);        }
});if (OffHeaptop(H,Heap_Warn_Soft)) {
int wake_count;if (Stop_This_Goal(Arg)) {
goto exit_toplevel;
          }
wake_count = WakeCount;
if (OffHeaptop(H+4*wake_count,Heap_Warn)) {
SETUP_PENDING_CALL(address_true);StoreH;
heap_overflow(Arg,SOFT_HEAPPAD+4*wake_count);LoadH;
          }
if (wake_count>0) {
if (wake_count==1) {
SETUP_PENDING_CALL(address_uvc);collect_one_pending_unification(Arg);DEREF(t0,X(1));if (TagIsCVA(t0)) {
X(1) = t0;
Setfunc(address_ucc);
              }
            } else {
SETUP_PENDING_CALL(address_pending_unifications);StoreH;
collect_pending_unifications(Arg,wake_count);LoadH;
            }
          }
if (OffStacktop(w->frame,Stack_Warn)) {
SETUP_PENDING_CALL(address_true);stack_overflow(Arg);          }
if (Int_Heap_Warn != (Heap_Warn_Soft = Heap_Warn)) {
SETUP_PENDING_CALL(address_help);control_c_normal(Arg);          }
        }
goto switch_on_pred;
switch_on_pred:
i = Func->enter_instr;
goto switch_on_pred_sub;
switch_on_pred_sub:
switch (i) {
case ENTER_FASTCODE_INDEXED:

goto enter_undefined;
case ENTER_FASTCODE:

goto enter_undefined;
case ENTER_UNDEFINED:

enter_undefined:
PredTrace("U",Func);
ptemp = (bcp_t)address_undefined_goal;
goto escape_to_p;
case ENTER_INTERPRETED:

ptemp = (bcp_t)address_interpret_c_goal;
goto escape_to_p2;
case ENTER_C:

PredTrace("C",Func);
StoreH;
i = (*Func->code.cinfo)(Arg);
if (Expanded_Worker) {
ON_DEBUG({
printf("wam() detected worker expanded by C predicate\n");
});
if (desc == NULL) {
fprintf(stderr, "bug: invalid WAM expansion\n");
abort();
            }
desc->worker_registers = Arg = Expanded_Worker;
Expanded_Worker = NULL;
          }
if (i) {
goto r_proceed;
          } else {
goto fail;
          }
case BUILTIN_TRUE:
PredTrace("B",Func);
goto w_proceed;
case BUILTIN_FAIL:
PredTrace("B",Func);
goto fail;
case BUILTIN_CURRENT_INSTANCE:
PredTrace("B",Func);
StoreH;
ins = current_instance(Arg);
if (!ins) {
goto fail;
          }
P = (bcp_t)ins->emulcode;
goto ReadMode;
case BUILTIN_COMPILE_TERM:
PredTrace("B",Func);
StoreH;
if (!compile_term(Arg, &new_worker)) {
goto fail;
          }
if (new_worker) {
if (desc == NULL) {
fprintf(stderr, "bug: invalid WAM expansion\n");
abort();
            }
desc->worker_registers = Arg = new_worker;
ON_DEBUG({
fprintf(stderr, "Reallocation of wrb detected in wam()\n");
});
          }
goto r_proceed;
case BUILTIN_INSTANCE:
PredTrace("B",Func);
LoadHVA(X(3),H);
ins = TagToInstance(X(2));
P = (bcp_t)ins->emulcode;
goto WriteMode;
case BUILTIN_GELER:
PredTrace("B",Func);
t1 = X(0);
DerefSwitch(t1,t0, {
;});
t3 = X(1);
DerefSwitch(t3,t0, {
;});
Setfunc(find_definition(predicates_location,t3,&w->structure,TRUE));
goto suspend_t3_on_t1;
case BUILTIN_NODEBUGCALL:
PredTrace("B",Func);
t0 = X(0);
DerefSwitch(t0,X(0), {
;});
Setfunc(find_definition(predicates_location,t0,&w->structure,FALSE));
if (Func==NULL) {
goto fail;
          }
i = Func->enter_instr;
goto call4;
case BUILTIN_SYSCALL:
PredTrace("B",Func);
t0 = X(0);
DerefSwitch(t0,X(0), {
;});
goto call1;
call1:
Setfunc(find_definition(predicates_location,t0,&w->structure,FALSE));
if (Func==NULL) {
Setfunc(address_undefined_goal);
goto switch_on_pred;
          }
i = Func->enter_instr;
goto call4;
case BUILTIN_CALL:
PredTrace("B",Func);
t0 = X(0);
DerefSwitch(t0,X(0), {
;});
Setfunc(find_definition(predicates_location,t0,&w->structure,FALSE));
if (Func==NULL) {
Setfunc(address_undefined_goal);
goto switch_on_pred;
          }
if (Current_Debugger_Mode != atom_off) {
Setfunc(address_trace);
goto switch_on_pred;
          }
i = Func->enter_instr;
goto call4;
call4:
switch (i) {
case ENTER_INTERPRETED:
X(1) = PointerToTerm(Func->code.intinfo);
Setfunc(address_interpret_goal);
goto switch_on_pred;
case BUILTIN_DIF:
PredTrace("B",Func);
pt1 = w->structure;
RefHeapNext(t0,pt1);
DerefHeapSwitch(t0,t2, {
;});
RefHeapNext(t1,pt1);
DerefHeapSwitch(t1,t2, {
;});
goto dif1;
case SPYPOINT:
if (!Func->properties.wait) {
goto call5;
            }
case WAITPOINT:
RefHeap(t0,w->structure);
DerefHeapSwitch(t0,t1, {
t3 = X(0);
goto suspend_t3_on_t1;
});
goto call5;
call5:
i = Func->predtyp;
goto call4;
default:
if ((t0 = Func->arity)) {
StoreH;
pt1 = w->term;
pt2 = w->structure;
do {
PushRefHeapNext(pt1,pt2);
} while (--t0);LoadH;
              }
goto switch_on_pred_sub;
}case BUILTIN_DIF:
PredTrace("B",Func);
t0 = X(0);
DerefSwitch(t0,t2, {
;});
t1 = X(1);
DerefSwitch(t1,t2, {
;});
w->structure = NULL;
goto dif1;
dif1:
if (t0==t1) {
goto fail;
              } else if ((!IsVar(t0 & t1)) && (IsAtomic(t0) || IsAtomic(t1))) {
goto w_proceed;
              } else {
X(0) = t0;
X(1) = t1;
StoreH;
goto dif2;
              }
dif2:
if (!prolog_dif(Arg,Func)) {
goto fail;
              }
goto r_proceed;
case BUILTIN_ABORT:
PredTrace("B",Func);
t0 = X(0);
DerefSwitch(t0,t1, {
;});
wam_exit_code = GetSmall(t0);
w->next_node = InitialNode;
PROFILE__HOOK_CUT;
SetB(w->next_node);
w->node = B;
SetShadowregs(B);
TRACE_CHPT_CUT(w->node);
ConcChptCleanUp(TopConcChpt, w->node);
goto fail;
case SPYPOINT:
if (Current_Debugger_Mode != atom_off) {
ptemp = (bcp_t)address_trace;
goto escape_to_p;
              }
if (!Func->properties.wait) {
goto nowait;
              }
goto waitpoint;
case WAITPOINT:
waitpoint:
t1 = X(0);
DerefSwitch(t1,X(0), {
goto suspend_on_t1;
});
goto nowait;
nowait:
i = Func->predtyp;
goto switch_on_pred_sub;
case BREAKPOINT:
i = Func->predtyp;
goto switch_on_pred_sub;
case ENTER_PROFILEDCODE_INDEXED:
goto enter_compactcode_indexed;
case ENTER_COMPACTCODE_INDEXED:
enter_compactcode_indexed:
PredTrace("E",Func);
t0 = X(0);
DerefSwitch(t0,X(0), {
{SetAlts(Func->code.incoreinfo->varcase);
goto tryeach_w;
}});
StoreH;
if (t0 & TagBitComplex) {
if (t0 & TagBitFunctor) {
S = TagToArg(t0,0);
t1 = HeapNext(S);
                } else {
S = TagToLST(t0);
{SetAlts(Func->code.incoreinfo->lstcase);
goto tryeach_r;
}                }
              } else {
t1 = t0;
              }
SetHtab(Func->code.incoreinfo->othercase);
for (i=0, t2=t1, t1 &= Htab->mask;;i+=sizeof(sw_on_key_node_t), t1=(t1+i) & Htab->mask) {
SetHtabNode(SW_ON_KEY_NODE_FROM_OFFSET(Htab, t1));
if (HtabNode->key==t2 || !HtabNode->key) {
{SetAlts(HtabNode->value.try_chain);
goto tryeach_r;
}                }
}
case ENTER_PROFILEDCODE:
goto enter_compactcode;
case ENTER_COMPACTCODE:
enter_compactcode:
PredTrace("E",Func);
{SetAlts(Func->code.incoreinfo->varcase);
goto tryeach_w;
}}tryeach_r:
#if defined(GAUGE)
INCR_COUNTER(Alts->entry_counter+1);
#endif
P = Alts->emul_p2;
w->next_node = w->node;
if ((w->next_alt=Alts->next)!=NULL) {
SetB(w->node);
if (w->local_top) {
;                } else if (!StackYounger(w->local_top = NodeLocalTop(B),w->frame)) {
w->local_top = StackCharOffset(w->frame,FrameSize(w->next_insn));
                }
SetB(ChoiceCharOffset(B,w->next_alt->node_offset));
w->node = B;
ON_DEBUG_NODE({B->functor = NULL;
});
B->next_alt = NULL;
B->trail_top = w->trail_top;
SaveGtop(B,w->global_top);
NewShadowregs(w->global_top);
ON_DEBUG({
if (debug_choicepoints) {
fprintf(stderr, "WAM created choicepoint (r), node = %x\n", (int)w->node);
                }
});
if (ChoiceYounger(ChoiceOffset(B,CHOICEPAD),w->trail_top)) {
choice_overflow(Arg,CHOICEPAD);
                }
              }
goto ReadMode;
ReadMode:
switch (BcOPCODE) {
case INITTRUE:
LoadH;
goto w_inittrue;
case FIRSTTRUE_N:
LoadH;
goto w_firsttrue_n;
case INITCALLQ:
P += FTYPE_size(f_Q);
goto r_initcall;
r_initcall:
case INITCALL:
LoadH;
goto w_initcall;
case FIRSTCALL_NQ:
P += FTYPE_size(f_Q);
goto r_firstcall_n;
r_firstcall_n:
case FIRSTCALL_N:
LoadH;
goto w_firstcall_n;
case FIRSTCALL_8Q:
P += FTYPE_size(f_Q);
goto r_firstcall_8;
r_firstcall_8:
case FIRSTCALL_8:
LoadH;
goto w_firstcall_8;
case FIRSTCALL_7Q:
P += FTYPE_size(f_Q);
goto r_firstcall_7;
r_firstcall_7:
case FIRSTCALL_7:
LoadH;
goto w_firstcall_7;
case FIRSTCALL_6Q:
P += FTYPE_size(f_Q);
goto r_firstcall_6;
r_firstcall_6:
case FIRSTCALL_6:
LoadH;
goto w_firstcall_6;
case FIRSTCALL_5Q:
P += FTYPE_size(f_Q);
goto r_firstcall_5;
r_firstcall_5:
case FIRSTCALL_5:
LoadH;
goto w_firstcall_5;
case FIRSTCALL_4Q:
P += FTYPE_size(f_Q);
goto r_firstcall_4;
r_firstcall_4:
case FIRSTCALL_4:
LoadH;
goto w_firstcall_4;
case FIRSTCALL_3Q:
P += FTYPE_size(f_Q);
goto r_firstcall_3;
r_firstcall_3:
case FIRSTCALL_3:
LoadH;
goto w_firstcall_3;
case FIRSTCALL_2Q:
P += FTYPE_size(f_Q);
goto r_firstcall_2;
r_firstcall_2:
case FIRSTCALL_2:
LoadH;
goto w_firstcall_2;
case FIRSTCALL_1Q:
P += FTYPE_size(f_Q);
goto r_firstcall_1;
r_firstcall_1:
case FIRSTCALL_1:
LoadH;
goto w_firstcall_1;
case FIRSTCALLQ:
P += FTYPE_size(f_Q);
goto r_firstcall;
r_firstcall:
case FIRSTCALL:
LoadH;
goto w_firstcall;
case CALL_NQ:
P += FTYPE_size(f_Q);
goto r_call_n;
r_call_n:
case CALL_N:
LoadH;
goto w_call_n;
case CALL_8Q:
P += FTYPE_size(f_Q);
goto r_call_8;
r_call_8:
case CALL_8:
LoadH;
goto w_call_8;
case CALL_7Q:
P += FTYPE_size(f_Q);
goto r_call_7;
r_call_7:
case CALL_7:
LoadH;
goto w_call_7;
case CALL_6Q:
P += FTYPE_size(f_Q);
goto r_call_6;
r_call_6:
case CALL_6:
LoadH;
goto w_call_6;
case CALL_5Q:
P += FTYPE_size(f_Q);
goto r_call_5;
r_call_5:
case CALL_5:
LoadH;
goto w_call_5;
case CALL_4Q:
P += FTYPE_size(f_Q);
goto r_call_4;
r_call_4:
case CALL_4:
LoadH;
goto w_call_4;
case CALL_3Q:
P += FTYPE_size(f_Q);
goto r_call_3;
r_call_3:
case CALL_3:
LoadH;
goto w_call_3;
case CALL_2Q:
P += FTYPE_size(f_Q);
goto r_call_2;
r_call_2:
case CALL_2:
LoadH;
goto w_call_2;
case CALL_1Q:
P += FTYPE_size(f_Q);
goto r_call_1;
r_call_1:
case CALL_1:
LoadH;
goto w_call_1;
case CALLQ:
P += FTYPE_size(f_Q);
goto r_call;
r_call:
case CALL:
LoadH;
goto w_call;
case LASTCALL_NQ:
P += FTYPE_size(f_Q);
goto r_lastcall_n;
r_lastcall_n:
case LASTCALL_N:
LoadH;
goto w_lastcall_n;
case LASTCALL_8Q:
P += FTYPE_size(f_Q);
goto r_lastcall_8;
r_lastcall_8:
case LASTCALL_8:
LoadH;
goto w_lastcall_8;
case LASTCALL_7Q:
P += FTYPE_size(f_Q);
goto r_lastcall_7;
r_lastcall_7:
case LASTCALL_7:
LoadH;
goto w_lastcall_7;
case LASTCALL_6Q:
P += FTYPE_size(f_Q);
goto r_lastcall_6;
r_lastcall_6:
case LASTCALL_6:
LoadH;
goto w_lastcall_6;
case LASTCALL_5Q:
P += FTYPE_size(f_Q);
goto r_lastcall_5;
r_lastcall_5:
case LASTCALL_5:
LoadH;
goto w_lastcall_5;
case LASTCALL_4Q:
P += FTYPE_size(f_Q);
goto r_lastcall_4;
r_lastcall_4:
case LASTCALL_4:
LoadH;
goto w_lastcall_4;
case LASTCALL_3Q:
P += FTYPE_size(f_Q);
goto r_lastcall_3;
r_lastcall_3:
case LASTCALL_3:
LoadH;
goto w_lastcall_3;
case LASTCALL_2Q:
P += FTYPE_size(f_Q);
goto r_lastcall_2;
r_lastcall_2:
case LASTCALL_2:
LoadH;
goto w_lastcall_2;
case LASTCALL_1Q:
P += FTYPE_size(f_Q);
goto r_lastcall_1;
r_lastcall_1:
case LASTCALL_1:
LoadH;
goto w_lastcall_1;
case LASTCALLQ:
P += FTYPE_size(f_Q);
goto r_lastcall;
r_lastcall:
case LASTCALL:
LoadH;
goto w_lastcall;
case EXECUTEQ:
LoadH;
P = BcP(f_p, 2);
goto enter_predicate;
case EXECUTE:
LoadH;
P = BcP(f_p, 1);
goto enter_predicate;
case PUT_X_VOID:
LoadH;
goto w_put_x_void;
case PUT_X_VARIABLE:
LoadH;
goto w_put_x_variable;
case PUT_XVAL_XVAL:
Xb(BcP(f_x, 1)) = Xb(BcP(f_x, 2));
Xb(BcP(f_x, 3)) = Xb(BcP(f_x, 4));
P += (FTYPE_size(f_x)+FTYPE_size(f_x)+FTYPE_size(f_x)+FTYPE_size(f_x));
goto ReadMode;
case PUT_X_VALUE:
Xb(BcP(f_x, 1)) = Xb(BcP(f_x, 2));
P += (FTYPE_size(f_x)+FTYPE_size(f_x));
goto ReadMode;
case PUT_X_UNSAFE_VALUE:
LoadH;
goto w_put_x_unsafe_value;
case PUT_Y_FIRST_VARIABLE:
LoadH;
goto w_put_y_first_variable;
case PUT_Y_VARIABLE:
LoadH;
goto w_put_y_variable;
case PUT_YFVAR_YVAR:
LoadH;
goto w_put_yfvar_yvar;
case PUT_YVAR_YVAR:
LoadH;
goto w_put_yvar_yvar;
case PUT_YVAL_YVAL:
RefStack(Xb(BcP(f_x, 1)),&Yb(BcP(f_y, 2)));
RefStack(Xb(BcP(f_x, 3)),&Yb(BcP(f_y, 4)));
P += (FTYPE_size(f_x)+FTYPE_size(f_y)+FTYPE_size(f_x)+FTYPE_size(f_y));
goto ReadMode;
case PUT_Y_VALUE:
RefStack(Xb(BcP(f_x, 1)),&Yb(BcP(f_y, 2)));
P += (FTYPE_size(f_x)+FTYPE_size(f_y));
goto ReadMode;
case PUT_Y_UNSAFE_VALUE:
LoadH;
goto w_put_y_unsafe_value;
case PUT_CONSTANTQ:
Xb(BcP(f_x, 2)) = BcP(f_t, 3);
P += (FTYPE_size(f_Q)+FTYPE_size(f_x))+FTYPE_size(f_t);
goto ReadMode;
case PUT_CONSTANT:
Xb(BcP(f_x, 1)) = BcP(f_t, 2);
P += FTYPE_size(f_x)+FTYPE_size(f_t);
goto ReadMode;
case PUT_NIL:
Xb(BcP(f_x, 1)) = atom_nil;
P += FTYPE_size(f_x);
goto ReadMode;
case PUT_LARGEQ:
LoadH;
goto w_put_largeq;
case PUT_LARGE:
LoadH;
goto w_put_large;
case PUT_STRUCTUREQ:
LoadH;
goto w_put_structureq;
case PUT_STRUCTURE:
LoadH;
goto w_put_structure;
case PUT_LIST:
LoadH;
goto w_put_list;
case PUT_YVAL_YUVAL:
LoadH;
goto w_put_yval_yuval;
case PUT_YUVAL_YVAL:
LoadH;
goto w_put_yuval_yval;
case PUT_YUVAL_YUVAL:
LoadH;
goto w_put_yuval_yuval;
r_get_x_value:
case GET_X_VALUE:
t0 = Xb(BcP(f_x, 2));
t1 = Xb(BcP(f_x, 1));
P += (FTYPE_size(f_x)+FTYPE_size(f_x));
goto unify_t0_t1;
r_get_y_first_value:
case GET_Y_FIRST_VALUE:
if (CondStackvar(Yb(BcP(f_y, 2)))) {
TrailPushCheck(w->trail_top,TagSVA(&Yb(BcP(f_y, 2))));
Yb(BcP(f_y, 2)) = Xb(BcP(f_x, 1));
                } else {
Yb(BcP(f_y, 2)) = Xb(BcP(f_x, 1));
                }
P += (FTYPE_size(f_x)+FTYPE_size(f_y));
goto ReadMode;
r_get_y_value:
case GET_Y_VALUE:
RefStack(t1,&Yb(BcP(f_y, 2)));
t0 = Xb(BcP(f_x, 1));
P += (FTYPE_size(f_x)+FTYPE_size(f_y));
goto unify_t0_t1;
case GET_CONSTANTQ:
P += FTYPE_size(f_Q);
goto r_get_constant;
r_get_constant:
case GET_CONSTANT:
t1 = Xb(BcP(f_x, 1));
SwitchOnVar(t1,t0,{
BindHVA(t1,BcP(f_t, 2));
},{
BindCVA(t1,BcP(f_t, 2));
},{
BindSVA(t1,BcP(f_t, 2));
},{
if (t1!=BcP(f_t, 2)) {
goto fail;
                }
});
P += FTYPE_size(f_x)+FTYPE_size(f_t);
goto ReadMode;
case GET_LARGEQ:
P += FTYPE_size(f_Q);
goto r_get_large;
r_get_large:
case GET_LARGE:
t1 = Xb(BcP(f_x, 1));
SwitchOnVar(t1,t0,{
BindHVA(t1,BC_MakeLarge(Arg,&BcP(f_t, 2)));
},{
BindCVA(t1,BC_MakeLarge(Arg,&BcP(f_t, 2)));
},{
BindSVA(t1,BC_MakeLarge(Arg,&BcP(f_t, 2)));
},{
BC_EqLarge(t1,&BcP(f_t, 2), {
goto fail;
});
});
P += FTYPE_size(f_x)+LargeSize(BcP(f_t, 2));
goto ReadMode;
case GET_STRUCTUREQ:
P += FTYPE_size(f_Q);
goto r_get_structure;
r_get_structure:
case GET_STRUCTURE:
t1 = Xb(BcP(f_x, 1));
SwitchOnVar(t1,t0,{
LoadH;
BindHVA(t1,Tag(STR,H));
HeapPush(H,BcP(f_f, 2));
P += FTYPE_size(f_x)+FTYPE_size(f_f);
goto WriteMode;
},{
LoadH;
BindCVA(t1,Tag(STR,H));
HeapPush(H,BcP(f_f, 2));
P += FTYPE_size(f_x)+FTYPE_size(f_f);
goto WriteMode;
},{
LoadH;
BindSVA(t1,Tag(STR,H));
HeapPush(H,BcP(f_f, 2));
P += FTYPE_size(f_x)+FTYPE_size(f_f);
goto WriteMode;
},{
if(!TagIsSTR(t1) || (TagToHeadfunctor(t1)!=BcP(f_f, 2))) goto fail;S = TagToArg(t1,1);
P += FTYPE_size(f_x)+FTYPE_size(f_f);
goto ReadMode;
});
r_get_nil:
case GET_NIL:
t1 = Xb(BcP(f_x, 1));
SwitchOnVar(t1,t0,{
BindHVA(t1,atom_nil);
},{
BindCVA(t1,atom_nil);
},{
BindSVA(t1,atom_nil);
},{
if (t1!=atom_nil) {
goto fail;
                }
});
P += FTYPE_size(f_x);
goto ReadMode;
r_get_list:
case GET_LIST:
t1 = Xb(BcP(f_x, 1));
SwitchOnVar(t1,t0,{
LoadH;
BindHVA(t1,Tag(LST,H));
P += FTYPE_size(f_x);
goto WriteMode;
},{
LoadH;
BindCVA(t1,Tag(LST,H));
P += FTYPE_size(f_x);
goto WriteMode;
},{
LoadH;
BindSVA(t1,Tag(LST,H));
P += FTYPE_size(f_x);
goto WriteMode;
},{
if (!TermIsLST(t1)) {
goto fail;
                }
S = TagToLST(t1);
P += FTYPE_size(f_x);
goto ReadMode;
});
case GET_CONSTANT_NECK_PROCEEDQ:
P += FTYPE_size(f_Q);
goto r_get_constant_neck_proceed;
r_get_constant_neck_proceed:
case GET_CONSTANT_NECK_PROCEED:
t1 = Xb(BcP(f_x, 1));
SwitchOnVar(t1,t0,{
BindHVA(t1,BcP(f_t, 2));
},{
BindCVA(t1,BcP(f_t, 2));
},{
BindSVA(t1,BcP(f_t, 2));
},{
if (t1!=BcP(f_t, 2)) {
goto fail;
                }
});
LoadH;
goto w_neck_proceed;
r_get_nil_neck_proceed:
case GET_NIL_NECK_PROCEED:
t1 = Xb(BcP(f_x, 1));
SwitchOnVar(t1,t0,{
BindHVA(t1,atom_nil);
},{
BindCVA(t1,atom_nil);
},{
BindSVA(t1,atom_nil);
},{
if (t1!=atom_nil) {
goto fail;
                }
});
LoadH;
goto w_neck_proceed;
r_cutb_x:
case CUTB_X:
w->local_top = 0;
w->next_node = ChoiceFromInt(Xb(BcP(f_x, 1)));
;
PROFILE__HOOK_CUT;
SetB(w->next_node);
w->node = B;
SetShadowregs(B);
TRACE_CHPT_CUT(w->node);
ConcChptCleanUp(TopConcChpt, w->node);
P += FTYPE_size(f_x);
goto ReadMode;
r_cutb_x_neck:
case CUTB_X_NECK:
w->local_top = 0;
w->next_node = ChoiceFromInt(Xb(BcP(f_x, 1)));
;
P += FTYPE_size(f_x);
goto r_cutb_neck;
r_cutb_neck:
case CUTB_NECK:
PROFILE__HOOK_CUT;
SetB(w->next_node);
w->node = B;
SetShadowregs(B);
TRACE_CHPT_CUT(w->node);
ConcChptCleanUp(TopConcChpt, w->node);
if (w->next_alt) {
w->next_alt = NULL;
if (ChoiceYounger(ChoiceOffset(B,CHOICEPAD),w->trail_top)) {
choice_overflow(Arg,CHOICEPAD);
                  }
                }
P += 0;
goto ReadMode;
r_cutb_x_neck_proceed:
case CUTB_X_NECK_PROCEED:
w->next_node = ChoiceFromInt(Xb(BcP(f_x, 1)));
;
goto r_cutb_neck_proceed;
r_cutb_neck_proceed:
case CUTB_NECK_PROCEED:
PROFILE__HOOK_CUT;
SetB(w->next_node);
w->node = B;
SetShadowregs(B);
TRACE_CHPT_CUT(w->node);
ConcChptCleanUp(TopConcChpt, w->node);
if (w->next_alt) {
w->next_alt = NULL;
if (ChoiceYounger(ChoiceOffset(B,CHOICEPAD),w->trail_top)) {
choice_overflow(Arg,CHOICEPAD);
                  }
                }
goto r_proceed;
r_cute_x:
case CUTE_X:
w->next_node = ChoiceFromInt(Xb(BcP(f_x, 1)));
;
w->local_top = E;
PROFILE__HOOK_CUT;
SetB(w->next_node);
w->node = B;
SetShadowregs(B);
TRACE_CHPT_CUT(w->node);
ConcChptCleanUp(TopConcChpt, w->node);
SetE(w->local_top);
P += FTYPE_size(f_x);
goto ReadMode;
r_cute_x_neck:
case CUTE_X_NECK:
w->next_node = ChoiceFromInt(Xb(BcP(f_x, 1)));
;
P += FTYPE_size(f_x);
goto r_cute_neck;
r_cute_neck:
case CUTE_NECK:
w->local_top = E;
PROFILE__HOOK_CUT;
SetB(w->next_node);
w->node = B;
SetShadowregs(B);
TRACE_CHPT_CUT(w->node);
ConcChptCleanUp(TopConcChpt, w->node);
w->next_alt = NULL;
if (ChoiceYounger(ChoiceOffset(B,CHOICEPAD),w->trail_top)) {
choice_overflow(Arg,CHOICEPAD);
                }
SetE(w->local_top);
P += 0;
goto ReadMode;
r_cutf_x:
case CUTF_X:
w->next_node = ChoiceFromInt(Xb(BcP(f_x, 1)));
;
P += FTYPE_size(f_x);
goto r_cutf;
r_cutf:
case CUTF:
PROFILE__HOOK_CUT;
SetB(w->next_node);
w->node = B;
SetShadowregs(B);
TRACE_CHPT_CUT(w->node);
ConcChptCleanUp(TopConcChpt, w->node);
SetE(w->frame);
P += 0;
goto ReadMode;
r_cut_y:
case CUT_Y:
RefStack(t1,&Yb(BcP(f_y, 1)));
w->next_node = ChoiceFromInt(t1);
PROFILE__HOOK_CUT;
SetB(w->next_node);
w->node = B;
SetShadowregs(B);
TRACE_CHPT_CUT(w->node);
ConcChptCleanUp(TopConcChpt, w->node);
SetE(w->frame);
P += FTYPE_size(f_y);
goto ReadMode;
case CHOICE_X:
Xb(BcP(f_x, 1)) = ChoiceToInt(w->next_node);
P += FTYPE_size(f_x);
goto ReadMode;
case CHOICE_YF:
ComputeE;
goto r_choice_y;
r_choice_y:
case CHOICE_Y:
Yb(BcP(f_y, 1)) = ChoiceToInt(w->next_node);
P += FTYPE_size(f_y);
goto ReadMode;
case KONTINUE:
LoadH;
goto w_kontinue;
r_leave:
case LEAVE:
goto r_exit_toplevel;
r_exit_toplevel:
case EXIT_TOPLEVEL:
goto exit_toplevel;
r_retry_cq:
case RETRY_CQ:
if (w->next_alt) {
B->next_alt = w->next_alt;
w->next_alt = NULL;
                }
if (!(BcP(f_Cb, 2))(Arg)) {
goto fail;
                }
goto r_proceed;
r_retry_c:
case RETRY_C:
if (w->next_alt) {
B->next_alt = w->next_alt;
w->next_alt = NULL;
                }
if (!(BcP(f_Cb, 1))(Arg)) {
goto fail;
                }
goto r_proceed;
case GET_STRUCTURE_X0Q:
S = TagToArg(t0,1);
P += FTYPE_size(f_Q)+FTYPE_size(f_f);
goto ReadMode;
case GET_STRUCTURE_X0:
S = TagToArg(t0,1);
P += FTYPE_size(f_f);
goto ReadMode;
case GET_LARGE_X0Q:
t1 = t0;
SwitchOnVar(t1,t0,{
BindHVA(t1,BC_MakeLarge(Arg,&BcP(f_t, 2)));
},{
BindCVA(t1,BC_MakeLarge(Arg,&BcP(f_t, 2)));
},{
BindSVA(t1,BC_MakeLarge(Arg,&BcP(f_t, 2)));
},{
BC_EqLarge(t1,&BcP(f_t, 2), {
goto fail;
});
});
P += FTYPE_size(f_x)+LargeSize(BcP(f_t, 2));
goto ReadMode;
case GET_LARGE_X0:
t1 = t0;
SwitchOnVar(t1,t0,{
BindHVA(t1,BC_MakeLarge(Arg,&BcP(f_t, 1)));
},{
BindCVA(t1,BC_MakeLarge(Arg,&BcP(f_t, 1)));
},{
BindSVA(t1,BC_MakeLarge(Arg,&BcP(f_t, 1)));
},{
BC_EqLarge(t1,&BcP(f_t, 1), {
goto fail;
});
});
P += LargeSize(BcP(f_t, 1));
goto ReadMode;
case GET_CONSTANT_X0Q:
P += FTYPE_size(f_Q)+FTYPE_size(f_t);
goto ReadMode;
case GET_CONSTANT_X0:
P += FTYPE_size(f_t);
goto ReadMode;
case GET_NIL_X0:
P += 0;
goto ReadMode;
case GET_LIST_X0:
S = TagToLST(t0);
P += 0;
goto ReadMode;
case GET_XVAR_XVAR:
Xb(BcP(f_x, 2)) = Xb(BcP(f_x, 1));
Xb(BcP(f_x, 4)) = Xb(BcP(f_x, 3));
P += (FTYPE_size(f_x)+FTYPE_size(f_x)+FTYPE_size(f_x)+FTYPE_size(f_x));
goto ReadMode;
case GET_X_VARIABLE:
Xb(BcP(f_x, 2)) = Xb(BcP(f_x, 1));
P += (FTYPE_size(f_x)+FTYPE_size(f_x));
goto ReadMode;
case GET_Y_FIRST_VARIABLE:
ComputeE;
goto r_get_y_variable;
r_get_y_variable:
case GET_Y_VARIABLE:
Yb(BcP(f_y, 2)) = Xb(BcP(f_x, 1));
P += (FTYPE_size(f_x)+FTYPE_size(f_y));
goto ReadMode;
case GET_YFVAR_YVAR:
ComputeE;
goto r_get_yvar_yvar;
r_get_yvar_yvar:
case GET_YVAR_YVAR:
Yb(BcP(f_y, 2)) = Xb(BcP(f_x, 1));
Yb(BcP(f_y, 4)) = Xb(BcP(f_x, 3));
P += (FTYPE_size(f_x)+FTYPE_size(f_y)+FTYPE_size(f_x)+FTYPE_size(f_y));
goto ReadMode;
case BRANCH:
P = BCoff(P, BcP(f_i, 1));
P += 0;
goto ReadMode;
r_function_1q:
case FUNCTION_1Q:
Numstack_End = NULL;
if (ERRORTAG==(Xb(BcP(f_x, 2)) = (tagged_t)(BcP(f_Cf, 4))(Arg,Xb(BcP(f_x, 3)),&BcP(f_l, 6)))) {
goto fail;
                }
P += (FTYPE_size(f_Q)+FTYPE_size(f_x)+FTYPE_size(f_x))+FTYPE_size(f_C)+FTYPE_size(f_l)+FTYPE_size(f_i);
goto ReadMode;
r_function_1:
case FUNCTION_1:
Numstack_End = NULL;
if (ERRORTAG==(Xb(BcP(f_x, 1)) = (tagged_t)(BcP(f_Cf, 3))(Arg,Xb(BcP(f_x, 2)),&BcP(f_l, 5)))) {
goto fail;
                }
P += (FTYPE_size(f_x)+FTYPE_size(f_x))+FTYPE_size(f_C)+FTYPE_size(f_l)+FTYPE_size(f_i);
goto ReadMode;
r_function_2q:
case FUNCTION_2Q:
Numstack_End = NULL;
if (ERRORTAG==(Xb(BcP(f_x, 2)) = (tagged_t)(BcP(f_Cf, 5))(Arg,Xb(BcP(f_x, 3)),Xb(BcP(f_x, 4)),&BcP(f_l, 7)))) {
goto fail;
                }
P += (FTYPE_size(f_Q)+FTYPE_size(f_x)+FTYPE_size(f_x)+FTYPE_size(f_x))+FTYPE_size(f_C)+FTYPE_size(f_l)+FTYPE_size(f_i);
goto ReadMode;
r_function_2:
case FUNCTION_2:
Numstack_End = NULL;
if (ERRORTAG==(Xb(BcP(f_x, 1)) = (tagged_t)(BcP(f_Cf, 4))(Arg,Xb(BcP(f_x, 2)),Xb(BcP(f_x, 3)),&BcP(f_l, 6)))) {
goto fail;
                }
P += (FTYPE_size(f_x)+FTYPE_size(f_x)+FTYPE_size(f_x))+FTYPE_size(f_C)+FTYPE_size(f_l)+FTYPE_size(f_i);
goto ReadMode;
r_builtin_1q:
case BUILTIN_1Q:
if (!(BcP(f_Cb, 3))(Arg,Xb(BcP(f_x, 2)))) {
goto fail;
                }
P += (FTYPE_size(f_Q)+FTYPE_size(f_x))+FTYPE_size(f_C);
goto ReadMode;
r_builtin_1:
case BUILTIN_1:
if (!(BcP(f_Cb, 2))(Arg,Xb(BcP(f_x, 1)))) {
goto fail;
                }
P += FTYPE_size(f_x)+FTYPE_size(f_C);
goto ReadMode;
r_builtin_2q:
case BUILTIN_2Q:
if (!(BcP(f_Cb, 4))(Arg,Xb(BcP(f_x, 2)),Xb(BcP(f_x, 3)))) {
goto fail;
                }
P += (FTYPE_size(f_Q)+FTYPE_size(f_x)+FTYPE_size(f_x))+FTYPE_size(f_C);
goto ReadMode;
r_builtin_2:
case BUILTIN_2:
if (!(BcP(f_Cb, 3))(Arg,Xb(BcP(f_x, 1)),Xb(BcP(f_x, 2)))) {
goto fail;
                }
P += (FTYPE_size(f_x)+FTYPE_size(f_x))+FTYPE_size(f_C);
goto ReadMode;
r_builtin_3q:
case BUILTIN_3Q:
if (!(BcP(f_Cb, 5))(Arg,Xb(BcP(f_x, 2)),Xb(BcP(f_x, 3)),Xb(BcP(f_x, 4)))) {
goto fail;
                }
P += (FTYPE_size(f_Q)+FTYPE_size(f_x)+FTYPE_size(f_x)+FTYPE_size(f_x))+FTYPE_size(f_C);
goto ReadMode;
r_builtin_3:
case BUILTIN_3:
if (!(BcP(f_Cb, 4))(Arg,Xb(BcP(f_x, 1)),Xb(BcP(f_x, 2)),Xb(BcP(f_x, 3)))) {
goto fail;
                }
P += (FTYPE_size(f_x)+FTYPE_size(f_x)+FTYPE_size(f_x))+FTYPE_size(f_C);
goto ReadMode;
r_retry_instance:
case RETRY_INSTANCE:
if ((TagToRoot(X(RootArg))->behavior_on_failure != DYNAMIC &&
!next_instance_conc(Arg, &ins))
||
(TagToRoot(X(RootArg))->behavior_on_failure == DYNAMIC &&
!next_instance(Arg, &ins))
) {
w->next_alt = NULL;
SetB(w->next_node);
w->node = B;
SetShadowregs(B);
                }
if (!ins) {
ON_DEBUG({
if (debug_concchoicepoints) {
if ((TagToRoot(X(RootArg))->behavior_on_failure != CONC_CLOSED) && (IS_BLOCKING(X(InvocationAttr)))) {
fprintf(stderr,
"**wam(): failing on a concurrent closed pred, chpt=%x, failing chpt=%x .\n",
(int)w->node,(int)TopConcChpt);
                    }
                  }
if (debug_conc) {
if (TagToRoot(X(RootArg))->x2_pending_on_instance || TagToRoot(X(RootArg))->x5_pending_on_instance) {
fprintf(stderr, 
        "**wam(): failing with invokations pending from root, type = %d.\n",
        (TagToRoot(X(RootArg))->behavior_on_failure));                    }
                  }
});
TopConcChpt = (node_t *)TermToPointerOrNull(X(PrevDynChpt));
ON_DEBUG({
if (debug_concchoicepoints) {
  fprintf(stderr,"New topmost concurrent chpt = %x\n", (int)TopConcChpt);
                  }
});
goto fail;
                }
ON_DEBUG({
if (debug_conc && TagToRoot(X(RootArg))->behavior_on_failure != DYNAMIC) {
  fprintf(stderr, 
         "*** %d(%d)  backtracking on a concurrent predicate.\n",
          (int)Thread_Id, (int)GET_INC_COUNTER);
                }
if (debug_concchoicepoints && TagToRoot(X(RootArg))->behavior_on_failure != DYNAMIC) {
fprintf(stderr, 
         "backtracking to chpt. = %x\n", (int)w->node);
                }
});
P = (bcp_t)ins->emulcode;
goto ReadMode;
case GET_CONSTRAINT:
LoadH;
goto w_get_constraint;
case UNIFY_VOID:
S = HeapOffset(S,BcP(f_i, 1));
;
P += FTYPE_size(f_i);
goto ReadMode;
case UNIFY_VOID_1:
S = HeapOffset(S,1);
;
P += 0;
goto ReadMode;
case UNIFY_VOID_2:
S = HeapOffset(S,2);
;
P += 0;
goto ReadMode;
case UNIFY_VOID_3:
S = HeapOffset(S,3);
;
P += 0;
goto ReadMode;
case UNIFY_VOID_4:
S = HeapOffset(S,4);
;
P += 0;
goto ReadMode;
case UNIFY_X_VARIABLE:
RefHeapNext(Xb(BcP(f_x, 1)),S);
P += FTYPE_size(f_x);
goto ReadMode;
case UNIFY_X_VALUE:
goto r_unify_x_local_value;
r_unify_x_local_value:
case UNIFY_X_LOCAL_VALUE:
RefHeapNext(t1,S);
t0 = Xb(BcP(f_x, 1));
P += FTYPE_size(f_x);
goto unify_t0_t1;
case UNIFY_Y_FIRST_VARIABLE:
ComputeE;
goto r_unify_y_variable;
r_unify_y_variable:
case UNIFY_Y_VARIABLE:
RefHeapNext(Yb(BcP(f_y, 1)),S);
P += FTYPE_size(f_y);
goto ReadMode;
case UNIFY_Y_FIRST_VALUE:
RefHeapNext(t0,S);
if (CondStackvar(Yb(BcP(f_y, 1)))) {
TrailPushCheck(w->trail_top,TagSVA(&Yb(BcP(f_y, 1))));
Yb(BcP(f_y, 1)) = t0;
                } else {
Yb(BcP(f_y, 1)) = t0;
                }
P += FTYPE_size(f_y);
goto ReadMode;
case UNIFY_Y_VALUE:
goto r_unify_y_local_value;
r_unify_y_local_value:
case UNIFY_Y_LOCAL_VALUE:
RefHeapNext(t1,S);
RefStack(t0,&Yb(BcP(f_y, 1)));
P += FTYPE_size(f_y);
goto unify_t0_t1;
case UNIFY_CONSTANTQ:
P += FTYPE_size(f_Q);
goto r_unify_constant;
r_unify_constant:
case UNIFY_CONSTANT:
RefHeapNext(t1,S);
SwitchOnHeapVar(t1,t0,{
BindHVA(t1,BcP(f_t, 1));
},{
BindCVA(t1,BcP(f_t, 1));
},{
if (t1!=BcP(f_t, 1)) {
goto fail;
                }
});
P += FTYPE_size(f_t);
goto ReadMode;
case UNIFY_LARGEQ:
P += FTYPE_size(f_Q);
goto r_unify_large;
r_unify_large:
case UNIFY_LARGE:
RefHeapNext(t1,S);
SwitchOnHeapVar(t1,t0,{
BindHVA(t1,BC_MakeLarge(Arg,&BcP(f_t, 1)));
},{
BindCVA(t1,BC_MakeLarge(Arg,&BcP(f_t, 1)));
},{
BC_EqLarge(t1,&BcP(f_t, 1), {
goto fail;
});
});
P += LargeSize(BcP(f_t, 1));
goto ReadMode;
case UNIFY_STRUCTUREQ:
P += FTYPE_size(f_Q);
goto r_unify_structure;
r_unify_structure:
case UNIFY_STRUCTURE:
RefHeapNext(t1,S);
SwitchOnHeapVar(t1,t0,{
LoadH;
BindHVA(t1,Tag(STR,H));
HeapPush(H,BcP(f_f, 1));
P += FTYPE_size(f_f);
goto WriteMode;
},{
LoadH;
BindCVA(t1,Tag(STR,H));
HeapPush(H,BcP(f_f, 1));
P += FTYPE_size(f_f);
goto WriteMode;
},{
if(!TagIsSTR(t1) || (TagToHeadfunctor(t1)!=BcP(f_f, 1))) goto fail;S = TagToArg(t1,1);
P += FTYPE_size(f_f);
goto ReadMode;
});
case UNIFY_NIL:
RefHeapNext(t1,S);
SwitchOnHeapVar(t1,t0,{
BindHVA(t1,atom_nil);
},{
BindCVA(t1,atom_nil);
},{
if (t1!=atom_nil) {
goto fail;
                }
});
P += 0;
goto ReadMode;
case UNIFY_LIST:
RefHeapNext(t1,S);
SwitchOnHeapVar(t1,t0,{
LoadH;
BindHVA(t1,Tag(LST,H));
P += 0;
goto WriteMode;
},{
LoadH;
BindCVA(t1,Tag(LST,H));
P += 0;
goto WriteMode;
},{
if (!TermIsLST(t1)) {
goto fail;
                }
S = TagToLST(t1);
P += 0;
goto ReadMode;
});
case UNIFY_CONSTANT_NECK_PROCEEDQ:
P += FTYPE_size(f_Q);
goto r_unify_constant_neck_proceed;
r_unify_constant_neck_proceed:
case UNIFY_CONSTANT_NECK_PROCEED:
RefHeapNext(t1,S);
SwitchOnHeapVar(t1,t0,{
BindHVA(t1,BcP(f_t, 1));
},{
BindCVA(t1,BcP(f_t, 1));
},{
if (t1!=BcP(f_t, 1)) {
goto fail;
                }
});
LoadH;
goto w_neck_proceed;
case UNIFY_NIL_NECK_PROCEED:
RefHeapNext(t1,S);
SwitchOnHeapVar(t1,t0,{
BindHVA(t1,atom_nil);
},{
BindCVA(t1,atom_nil);
},{
if (t1!=atom_nil) {
goto fail;
                }
});
LoadH;
goto w_neck_proceed;
case U2_VOID_XVAR:
S = HeapOffset(S,BcP(f_i, 1));
;
RefHeapNext(Xb(BcP(f_x, 2)),S);
P += (FTYPE_size(f_i)+FTYPE_size(f_x));
goto ReadMode;
case U2_VOID_YFVAR:
ComputeE;
goto r_u2_void_yvar;
r_u2_void_yvar:
case U2_VOID_YVAR:
S = HeapOffset(S,BcP(f_i, 1));
;
RefHeapNext(Yb(BcP(f_y, 2)),S);
P += (FTYPE_size(f_i)+FTYPE_size(f_y));
goto ReadMode;
case U2_VOID_XVAL:
goto r_u2_void_xlval;
r_u2_void_xlval:
case U2_VOID_XLVAL:
S = HeapOffset(S,BcP(f_i, 1));
;
RefHeapNext(t1,S);
t0 = Xb(BcP(f_x, 2));
P += (FTYPE_size(f_i)+FTYPE_size(f_x));
goto unify_t0_t1;
case U2_VOID_YFVAL:
S = HeapOffset(S,BcP(f_i, 1));
;
RefHeapNext(t0,S);
if (CondStackvar(Yb(BcP(f_y, 2)))) {
TrailPushCheck(w->trail_top,TagSVA(&Yb(BcP(f_y, 2))));
Yb(BcP(f_y, 2)) = t0;
                } else {
Yb(BcP(f_y, 2)) = t0;
                }
P += (FTYPE_size(f_i)+FTYPE_size(f_y));
goto ReadMode;
case U2_VOID_YVAL:
goto r_u2_void_ylval;
r_u2_void_ylval:
case U2_VOID_YLVAL:
S = HeapOffset(S,BcP(f_i, 1));
;
RefHeapNext(t1,S);
RefStack(t0,&Yb(BcP(f_y, 2)));
P += (FTYPE_size(f_i)+FTYPE_size(f_y));
goto unify_t0_t1;
case U2_XVAR_VOID:
RefHeapNext(Xb(BcP(f_x, 1)),S);
S = HeapOffset(S,BcP(f_i, 2));
;
P += (FTYPE_size(f_x)+FTYPE_size(f_i));
goto ReadMode;
case U2_XVAR_XVAR:
RefHeapNext(Xb(BcP(f_x, 1)),S);
RefHeapNext(Xb(BcP(f_x, 2)),S);
P += (FTYPE_size(f_x)+FTYPE_size(f_x));
goto ReadMode;
case U2_XVAR_YFVAR:
ComputeE;
goto r_u2_xvar_yvar;
r_u2_xvar_yvar:
case U2_XVAR_YVAR:
RefHeapNext(Xb(BcP(f_x, 1)),S);
RefHeapNext(Yb(BcP(f_y, 2)),S);
P += (FTYPE_size(f_x)+FTYPE_size(f_y));
goto ReadMode;
case U2_XVAR_XVAL:
goto r_u2_xvar_xlval;
r_u2_xvar_xlval:
case U2_XVAR_XLVAL:
RefHeapNext(Xb(BcP(f_x, 1)),S);
RefHeapNext(t1,S);
t0 = Xb(BcP(f_x, 2));
P += (FTYPE_size(f_x)+FTYPE_size(f_x));
goto unify_t0_t1;
case U2_XVAR_YFVAL:
RefHeapNext(Xb(BcP(f_x, 1)),S);
RefHeapNext(t0,S);
if (CondStackvar(Yb(BcP(f_y, 2)))) {
TrailPushCheck(w->trail_top,TagSVA(&Yb(BcP(f_y, 2))));
Yb(BcP(f_y, 2)) = t0;
                } else {
Yb(BcP(f_y, 2)) = t0;
                }
P += (FTYPE_size(f_x)+FTYPE_size(f_y));
goto ReadMode;
case U2_XVAR_YVAL:
goto r_u2_xvar_ylval;
r_u2_xvar_ylval:
case U2_XVAR_YLVAL:
RefHeapNext(Xb(BcP(f_x, 1)),S);
RefHeapNext(t1,S);
RefStack(t0,&Yb(BcP(f_y, 2)));
P += (FTYPE_size(f_x)+FTYPE_size(f_y));
goto unify_t0_t1;
case U2_YFVAR_VOID:
ComputeE;
goto r_u2_yvar_void;
r_u2_yvar_void:
case U2_YVAR_VOID:
RefHeapNext(Yb(BcP(f_y, 1)),S);
S = HeapOffset(S,BcP(f_i, 2));
;
P += (FTYPE_size(f_y)+FTYPE_size(f_i));
goto ReadMode;
case U2_YFVAR_XVAR:
ComputeE;
goto r_u2_yvar_xvar;
r_u2_yvar_xvar:
case U2_YVAR_XVAR:
RefHeapNext(Yb(BcP(f_y, 1)),S);
RefHeapNext(Xb(BcP(f_x, 2)),S);
P += (FTYPE_size(f_y)+FTYPE_size(f_x));
goto ReadMode;
case U2_YFVAR_YVAR:
ComputeE;
goto r_u2_yvar_yvar;
r_u2_yvar_yvar:
case U2_YVAR_YVAR:
RefHeapNext(Yb(BcP(f_y, 1)),S);
RefHeapNext(Yb(BcP(f_y, 2)),S);
P += (FTYPE_size(f_y)+FTYPE_size(f_y));
goto ReadMode;
case U2_YFVAR_XVAL:
goto r_u2_yfvar_xlval;
r_u2_yfvar_xlval:
case U2_YFVAR_XLVAL:
ComputeE;
goto r_u2_yvar_xlval;
case U2_YVAR_XVAL:
goto r_u2_yvar_xlval;
r_u2_yvar_xlval:
case U2_YVAR_XLVAL:
RefHeapNext(Yb(BcP(f_y, 1)),S);
RefHeapNext(t1,S);
t0 = Xb(BcP(f_x, 2));
P += (FTYPE_size(f_y)+FTYPE_size(f_x));
goto unify_t0_t1;
case U2_YFVAR_YVAL:
goto r_u2_yfvar_ylval;
r_u2_yfvar_ylval:
case U2_YFVAR_YLVAL:
ComputeE;
goto r_u2_yvar_ylval;
case U2_YVAR_YVAL:
goto r_u2_yvar_ylval;
r_u2_yvar_ylval:
case U2_YVAR_YLVAL:
RefHeapNext(Yb(BcP(f_y, 1)),S);
RefHeapNext(t1,S);
RefStack(t0,&Yb(BcP(f_y, 2)));
P += (FTYPE_size(f_y)+FTYPE_size(f_y));
goto unify_t0_t1;
case U2_YFVAL_VOID:
RefHeapNext(t0,S);
if (CondStackvar(Yb(BcP(f_y, 1)))) {
TrailPushCheck(w->trail_top,TagSVA(&Yb(BcP(f_y, 1))));
Yb(BcP(f_y, 1)) = t0;
                } else {
Yb(BcP(f_y, 1)) = t0;
                }
S = HeapOffset(S,BcP(f_i, 2));
;
P += (FTYPE_size(f_y)+FTYPE_size(f_i));
goto ReadMode;
case U2_YFVAL_XVAR:
RefHeapNext(t0,S);
if (CondStackvar(Yb(BcP(f_y, 1)))) {
TrailPushCheck(w->trail_top,TagSVA(&Yb(BcP(f_y, 1))));
Yb(BcP(f_y, 1)) = t0;
                } else {
Yb(BcP(f_y, 1)) = t0;
                }
RefHeapNext(Xb(BcP(f_x, 2)),S);
P += (FTYPE_size(f_y)+FTYPE_size(f_x));
goto ReadMode;
case U2_YFVAL_YFVAL:
RefHeapNext(t0,S);
if (CondStackvar(Yb(BcP(f_y, 1)))) {
TrailPushCheck(w->trail_top,TagSVA(&Yb(BcP(f_y, 1))));
Yb(BcP(f_y, 1)) = t0;
                } else {
Yb(BcP(f_y, 1)) = t0;
                }
RefHeapNext(t0,S);
if (CondStackvar(Yb(BcP(f_y, 2)))) {
TrailPushCheck(w->trail_top,TagSVA(&Yb(BcP(f_y, 2))));
Yb(BcP(f_y, 2)) = t0;
                } else {
Yb(BcP(f_y, 2)) = t0;
                }
P += (FTYPE_size(f_y)+FTYPE_size(f_y));
goto ReadMode;
case U2_YFVAL_XVAL:
goto r_u2_yfval_xlval;
r_u2_yfval_xlval:
case U2_YFVAL_XLVAL:
RefHeapNext(t0,S);
if (CondStackvar(Yb(BcP(f_y, 1)))) {
TrailPushCheck(w->trail_top,TagSVA(&Yb(BcP(f_y, 1))));
Yb(BcP(f_y, 1)) = t0;
                } else {
Yb(BcP(f_y, 1)) = t0;
                }
RefHeapNext(t1,S);
t0 = Xb(BcP(f_x, 2));
P += (FTYPE_size(f_y)+FTYPE_size(f_x));
goto unify_t0_t1;
case U2_YFVAL_YVAL:
goto r_u2_yfval_ylval;
r_u2_yfval_ylval:
case U2_YFVAL_YLVAL:
RefHeapNext(t0,S);
if (CondStackvar(Yb(BcP(f_y, 1)))) {
TrailPushCheck(w->trail_top,TagSVA(&Yb(BcP(f_y, 1))));
Yb(BcP(f_y, 1)) = t0;
                } else {
Yb(BcP(f_y, 1)) = t0;
                }
RefHeapNext(t1,S);
RefStack(t0,&Yb(BcP(f_y, 2)));
P += (FTYPE_size(f_y)+FTYPE_size(f_y));
goto unify_t0_t1;
case U2_XVAL_VOID:
goto r_u2_xlval_void;
r_u2_xlval_void:
case U2_XLVAL_VOID:
RefHeapNext(t1,S);
S = HeapOffset(S,BcP(f_i, 2));
;
t0 = Xb(BcP(f_x, 1));
P += (FTYPE_size(f_x)+FTYPE_size(f_i));
goto unify_t0_t1;
case U2_XVAL_XVAR:
goto r_u2_xlval_xvar;
r_u2_xlval_xvar:
case U2_XLVAL_XVAR:
t0 = Xb(BcP(f_x, 1));
RefHeapNext(t1,S);
RefHeapNext(Xb(BcP(f_x, 2)),S);
P += (FTYPE_size(f_x)+FTYPE_size(f_x));
goto unify_t0_t1;
case U2_XVAL_YFVAR:
goto r_u2_xlval_yfvar;
r_u2_xlval_yfvar:
case U2_XLVAL_YFVAR:
ComputeE;
goto r_u2_xlval_yvar;
case U2_XVAL_YVAR:
goto r_u2_xlval_yvar;
r_u2_xlval_yvar:
case U2_XLVAL_YVAR:
RefHeapNext(t1,S);
t0 = Xb(BcP(f_x, 1));
if (t0!=t1) {
if (!cunify(Arg,t0,t1)) {
goto fail;
                  }
                }
RefHeapNext(Yb(BcP(f_y, 2)),S);
P += (FTYPE_size(f_x)+FTYPE_size(f_y));
goto ReadMode;
case U2_XVAL_XVAL:
goto r_u2_xval_xlval;
r_u2_xval_xlval:
case U2_XVAL_XLVAL:
goto r_u2_xlval_xval;
r_u2_xlval_xval:
case U2_XLVAL_XVAL:
goto r_u2_xlval_xlval;
r_u2_xlval_xlval:
case U2_XLVAL_XLVAL:
RefHeapNext(t1,S);
t0 = Xb(BcP(f_x, 1));
if (t0!=t1) {
if (!cunify(Arg,t0,t1)) {
goto fail;
                  }
                }
RefHeapNext(t1,S);
t0 = Xb(BcP(f_x, 2));
P += (FTYPE_size(f_x)+FTYPE_size(f_x));
goto unify_t0_t1;
case U2_XVAL_YFVAL:
goto r_u2_xlval_yfval;
r_u2_xlval_yfval:
case U2_XLVAL_YFVAL:
RefHeapNext(t1,S);
t0 = Xb(BcP(f_x, 1));
if (t0!=t1) {
if (!cunify(Arg,t0,t1)) {
goto fail;
                  }
                }
RefHeapNext(t0,S);
if (CondStackvar(Yb(BcP(f_y, 2)))) {
TrailPushCheck(w->trail_top,TagSVA(&Yb(BcP(f_y, 2))));
Yb(BcP(f_y, 2)) = t0;
                } else {
Yb(BcP(f_y, 2)) = t0;
                }
P += (FTYPE_size(f_x)+FTYPE_size(f_y));
goto ReadMode;
case U2_XVAL_YVAL:
goto r_u2_xval_ylval;
r_u2_xval_ylval:
case U2_XVAL_YLVAL:
goto r_u2_xlval_yval;
r_u2_xlval_yval:
case U2_XLVAL_YVAL:
goto r_u2_xlval_ylval;
r_u2_xlval_ylval:
case U2_XLVAL_YLVAL:
RefHeapNext(t1,S);
t0 = Xb(BcP(f_x, 1));
if (t0!=t1) {
if (!cunify(Arg,t0,t1)) {
goto fail;
                  }
                }
RefHeapNext(t1,S);
RefStack(t0,&Yb(BcP(f_y, 2)));
P += (FTYPE_size(f_x)+FTYPE_size(f_y));
goto unify_t0_t1;
case U2_YVAL_VOID:
goto r_u2_ylval_void;
r_u2_ylval_void:
case U2_YLVAL_VOID:
RefHeapNext(t1,S);
S = HeapOffset(S,BcP(f_i, 2));
;
t0 = Yb(BcP(f_y, 1));
P += (FTYPE_size(f_y)+FTYPE_size(f_i));
goto unify_t0_t1;
case U2_YVAL_XVAR:
goto r_u2_ylval_xvar;
r_u2_ylval_xvar:
case U2_YLVAL_XVAR:
RefHeapNext(t1,S);
RefHeapNext(Xb(BcP(f_x, 2)),S);
t0 = Yb(BcP(f_y, 1));
P += (FTYPE_size(f_y)+FTYPE_size(f_x));
goto unify_t0_t1;
case U2_YVAL_YVAR:
goto r_u2_ylval_yvar;
r_u2_ylval_yvar:
case U2_YLVAL_YVAR:
RefHeapNext(t1,S);
RefStack(t0,&Yb(BcP(f_y, 1)));
if (t0!=t1) {
if (!cunify(Arg,t0,t1)) {
goto fail;
                  }
                }
RefHeapNext(Yb(BcP(f_y, 2)),S);
P += (FTYPE_size(f_y)+FTYPE_size(f_y));
goto ReadMode;
case U2_YVAL_YFVAL:
goto r_u2_ylval_yfval;
r_u2_ylval_yfval:
case U2_YLVAL_YFVAL:
RefHeapNext(t1,S);
RefStack(t0,&Yb(BcP(f_y, 1)));
if (t0!=t1) {
if (!cunify(Arg,t0,t1)) {
goto fail;
                  }
                }
RefHeapNext(t0,S);
if (CondStackvar(Yb(BcP(f_y, 2)))) {
TrailPushCheck(w->trail_top,TagSVA(&Yb(BcP(f_y, 2))));
Yb(BcP(f_y, 2)) = t0;
                } else {
Yb(BcP(f_y, 2)) = t0;
                }
P += (FTYPE_size(f_y)+FTYPE_size(f_y));
goto ReadMode;
case U2_YVAL_XVAL:
goto r_u2_yval_xlval;
r_u2_yval_xlval:
case U2_YVAL_XLVAL:
goto r_u2_ylval_xval;
r_u2_ylval_xval:
case U2_YLVAL_XVAL:
goto r_u2_ylval_xlval;
r_u2_ylval_xlval:
case U2_YLVAL_XLVAL:
RefHeapNext(t1,S);
RefStack(t0,&Yb(BcP(f_y, 1)));
if (t0!=t1) {
if (!cunify(Arg,t0,t1)) {
goto fail;
                  }
                }
RefHeapNext(t1,S);
t0 = Xb(BcP(f_x, 2));
P += (FTYPE_size(f_y)+FTYPE_size(f_x));
goto unify_t0_t1;
case U2_YVAL_YVAL:
goto r_u2_yval_ylval;
r_u2_yval_ylval:
case U2_YVAL_YLVAL:
goto r_u2_ylval_yval;
r_u2_ylval_yval:
case U2_YLVAL_YVAL:
goto r_u2_ylval_ylval;
r_u2_ylval_ylval:
case U2_YLVAL_YLVAL:
RefHeapNext(t1,S);
RefStack(t0,&Yb(BcP(f_y, 1)));
if (t0!=t1) {
if (!cunify(Arg,t0,t1)) {
goto fail;
                  }
                }
RefHeapNext(t1,S);
RefStack(t0,&Yb(BcP(f_y, 2)));
P += (FTYPE_size(f_y)+FTYPE_size(f_y));
goto unify_t0_t1;
case BUMP_COUNTERQ:
P += FTYPE_size(f_Q);
goto r_bump_counter;
r_bump_counter:
case BUMP_COUNTER:
#if defined(GAUGE)
INCR_COUNTER(BcP(f_l, 1));
#endif
P += FTYPE_size(f_l);
goto ReadMode;
case COUNTED_NECKQ:
P += FTYPE_size(f_Q);
goto r_counted_neck;
r_counted_neck:
case COUNTED_NECK:
#if defined(GAUGE)
if (w->next_alt) {
SetB(w->node);
if (B->next_alt) {
#if defined(GAUGE)
INCR_COUNTER(BcP(f_l, 1));
#endif
                  } else {
#if defined(GAUGE)
INCR_COUNTER(BcP(f_l, 3));
#endif
                  }
                }
#endif
P += (FTYPE_size(f_l)+FTYPE_size(f_l));
goto r_neck;
case FAIL:
goto fail;
case HEAPMARGIN_CALLQ:
P += FTYPE_size(f_Q);
goto r_heapmargin_call;
r_heapmargin_call:
case HEAPMARGIN_CALL:
if (HeapDifference(w->global_top,Heap_End) < (intmach_t)BcP(f_l, 1)) {
explicit_heap_overflow(Arg,(intmach_t)BcP(f_l, 1),(FTYPE_ctype(f_i_signed))BcP(f_i, 3));
t0 = X(0);
                }
P += FTYPE_size(f_l)+FTYPE_size(f_i);
goto ReadMode;
r_neck:
case NECK:
if (w->next_alt) {
SetB(w->node);
if (B->next_alt) {
B->next_alt = w->next_alt;
                  } else {
B->next_alt = w->next_alt; /* 4 contiguous moves */
B->frame = w->frame;
B->next_insn = w->next_insn;
SaveLtop(B);
i=B->next_alt->node_offset;
if (i>ArityToOffset(0)) {
i = OffsetToArity(i);
SetB(w->next_node);
ON_DEBUG({
if (debug_choicepoints) {
fprintf(stderr, "Storing %d registers (r) in node %x\n", i, (int)w->next_node);
                      }
});
do {
ChoicePush(pt1,(w->term-1)[i]);} while (--i);                      }
if (ChoiceYounger(ChoiceOffset(B,CHOICEPAD),w->trail_top)) {
choice_overflow(Arg,CHOICEPAD);
                      }
                    }
w->next_alt = NULL;
SetE(w->local_top);
                  }
P += 0;
goto ReadMode;
case DYNAMIC_NECK_PROCEED:
LoadH;
goto w_dynamic_neck_proceed;
case NECK_PROCEED:
LoadH;
goto w_neck_proceed;
r_proceed:
case PROCEED:
w->local_top = 0;
SetE(w->frame);
P = w->next_insn;
PROFILE__HOOK_PROCEED;
P += 0;
goto ReadMode;
#if defined(PARBACK)
case RESTART_POINT:
w->global_top = TagToPointer(w->node->term[0]);
LoadH;
P = (bcp_t)*TagToPointer(w->node->term[0]);
w->next_insn = w->node->next_insn;
pop_choicept(Arg);
goto enter_predicate;
#endif
default:
goto illop;
}tryeach_w:
#if defined(GAUGE)
INCR_COUNTER(Alts->entry_counter);
#endif
P = Alts->emul_p;
w->next_node = w->node;
if ((w->next_alt=Alts->next)!=NULL) {
SetB(w->node);
if (w->local_top) {
;                  } else if (!StackYounger(w->local_top = NodeLocalTop(B),w->frame)) {
w->local_top = StackCharOffset(w->frame,FrameSize(w->next_insn));
                  }
SetB(ChoiceCharOffset(B,w->next_alt->node_offset));
w->node = B;
ON_DEBUG_NODE({B->functor = NULL;
});
B->next_alt = NULL;
B->trail_top = w->trail_top;
SaveGtop(B,H);
NewShadowregs(H);
ON_DEBUG({
if (debug_choicepoints) {
fprintf(stderr, "WAM created choicepoint (r), node = %x\n", (int)w->node);
                  }
});
if (ChoiceYounger(ChoiceOffset(B,CHOICEPAD),w->trail_top)) {
choice_overflow(Arg,CHOICEPAD);
                  }
                }
goto WriteMode;
WriteMode:
switch (BcOPCODE) {
w_inittrue:
case INITTRUE:
ComputeE;
for (t0 = BcP(f_e, 1)-sizeof(tagged_t); t0 >= EToY0*sizeof(tagged_t); t0 -= sizeof(tagged_t)) {
LoadSVA(Yb(t0));
}
goto firsttrue;
w_firsttrue_n:
case FIRSTTRUE_N:
i = (FTYPE_ctype(f_i_signed))BcP(f_i, 1);
P += FTYPE_size(f_i);
for (; i>0; --i) {
t0 = BcP(f_y, 1);
P += FTYPE_size(f_y);
LoadSVA(Yb(t0));
}
goto firsttrue;
firsttrue:
E->next_insn = w->next_insn;
E->frame = w->frame;
w->frame = E;
w->next_insn = PoffR(2);
w->local_top = StackCharOffset(E,BcP(f_e, 1));
if (OffStacktop(E,Stack_Warn)) {
SetEvent;
                  }
P += FTYPE_size(f_i);
goto WriteMode;
case INITCALLQ:
P += FTYPE_size(f_Q);
goto w_initcall;
w_initcall:
case INITCALL:
ComputeE;
for (t0 = BcP(f_e,3)-sizeof(tagged_t); t0 >= EToY0*sizeof(tagged_t); t0 -= sizeof(tagged_t)) {
LoadSVA(Yb(t0));
}
goto w_firstcall;
case FIRSTCALL_NQ:
P += FTYPE_size(f_Q);
goto w_firstcall_n;
case FIRSTCALL_8Q:
P += FTYPE_size(f_Q);
goto w_firstcall_8;
case FIRSTCALL_7Q:
P += FTYPE_size(f_Q);
goto w_firstcall_7;
case FIRSTCALL_6Q:
P += FTYPE_size(f_Q);
goto w_firstcall_6;
case FIRSTCALL_5Q:
P += FTYPE_size(f_Q);
goto w_firstcall_5;
case FIRSTCALL_4Q:
P += FTYPE_size(f_Q);
goto w_firstcall_4;
case FIRSTCALL_3Q:
P += FTYPE_size(f_Q);
goto w_firstcall_3;
case FIRSTCALL_2Q:
P += FTYPE_size(f_Q);
goto w_firstcall_2;
case FIRSTCALL_1Q:
P += FTYPE_size(f_Q);
goto w_firstcall_1;
case FIRSTCALLQ:
P += FTYPE_size(f_Q);
goto w_firstcall;
case CALL_NQ:
P += FTYPE_size(f_Q);
goto w_call_n;
case CALL_8Q:
P += FTYPE_size(f_Q);
goto w_call_8;
case CALL_7Q:
P += FTYPE_size(f_Q);
goto w_call_7;
case CALL_6Q:
P += FTYPE_size(f_Q);
goto w_call_6;
case CALL_5Q:
P += FTYPE_size(f_Q);
goto w_call_5;
case CALL_4Q:
P += FTYPE_size(f_Q);
goto w_call_4;
case CALL_3Q:
P += FTYPE_size(f_Q);
goto w_call_3;
case CALL_2Q:
P += FTYPE_size(f_Q);
goto w_call_2;
case CALL_1Q:
P += FTYPE_size(f_Q);
goto w_call_1;
case CALLQ:
P += FTYPE_size(f_Q);
goto w_call;
case LASTCALL_NQ:
P += FTYPE_size(f_Q);
goto w_lastcall_n;
case LASTCALL_8Q:
P += FTYPE_size(f_Q);
goto w_lastcall_8;
case LASTCALL_7Q:
P += FTYPE_size(f_Q);
goto w_lastcall_7;
case LASTCALL_6Q:
P += FTYPE_size(f_Q);
goto w_lastcall_6;
case LASTCALL_5Q:
P += FTYPE_size(f_Q);
goto w_lastcall_5;
case LASTCALL_4Q:
P += FTYPE_size(f_Q);
goto w_lastcall_4;
case LASTCALL_3Q:
P += FTYPE_size(f_Q);
goto w_lastcall_3;
case LASTCALL_2Q:
P += FTYPE_size(f_Q);
goto w_lastcall_2;
case LASTCALL_1Q:
P += FTYPE_size(f_Q);
goto w_lastcall_1;
case LASTCALLQ:
P += FTYPE_size(f_Q);
goto w_lastcall;
w_firstcall_n:
case FIRSTCALL_N:
i = (FTYPE_ctype(f_i_signed))BcP(f_i, 1);
P += FTYPE_size(f_i);
for (; i>8; --i) {
t0 = BcP(f_y, 1);
P += FTYPE_size(f_y);
LoadSVA(Yb(t0));
}
goto w_firstcall_8;
w_firstcall_8:
case FIRSTCALL_8:
t0 = BcP(f_y, 1);
P += FTYPE_size(f_y);
LoadSVA(Yb(t0));
goto w_firstcall_7;
w_firstcall_7:
case FIRSTCALL_7:
t0 = BcP(f_y, 1);
P += FTYPE_size(f_y);
LoadSVA(Yb(t0));
goto w_firstcall_6;
w_firstcall_6:
case FIRSTCALL_6:
t0 = BcP(f_y, 1);
P += FTYPE_size(f_y);
LoadSVA(Yb(t0));
goto w_firstcall_5;
w_firstcall_5:
case FIRSTCALL_5:
t0 = BcP(f_y, 1);
P += FTYPE_size(f_y);
LoadSVA(Yb(t0));
goto w_firstcall_4;
w_firstcall_4:
case FIRSTCALL_4:
t0 = BcP(f_y, 1);
P += FTYPE_size(f_y);
LoadSVA(Yb(t0));
goto w_firstcall_3;
w_firstcall_3:
case FIRSTCALL_3:
t0 = BcP(f_y, 1);
P += FTYPE_size(f_y);
LoadSVA(Yb(t0));
goto w_firstcall_2;
w_firstcall_2:
case FIRSTCALL_2:
t0 = BcP(f_y, 1);
P += FTYPE_size(f_y);
LoadSVA(Yb(t0));
goto w_firstcall_1;
w_firstcall_1:
case FIRSTCALL_1:
t0 = BcP(f_y, 1);
P += FTYPE_size(f_y);
LoadSVA(Yb(t0));
goto w_firstcall;
w_firstcall:
case FIRSTCALL:
E->next_insn = w->next_insn;
E->frame = w->frame;
w->frame = E;
w->next_insn = BCoff(P, FTYPE_size(f_E)+FTYPE_size(f_e));
w->local_top = StackCharOffset(E,BcP(f_e,3));
P = BcP(f_p, 1);
if (OffStacktop(E,Stack_Warn)) {
SetEvent;
                  }
goto enter_predicate;
w_call_n:
case CALL_N:
i = (FTYPE_ctype(f_i_signed))BcP(f_i, 1);
P += FTYPE_size(f_i);
for (; i>8; --i) {
t1 = BcP(f_z, 1);
P += FTYPE_size(f_z);
if (t1&1) {
RefStack(t0,&Yb(t1+1));
if (TagIsSVA(t0)) {
do {
RefSVA(t1,t0);
if (t1 == t0) {
if ((!YoungerStackVar(TagSVA(Offset(E,EToY0)),t0))) {
LoadHVA(t0,H);
BindSVA(t1,t0);
                            }
break;
                          }
} while (TagIsSVA(t0=t1));                        }
X(i-1) = t0;
                      } else {
RefStack(X(i-1),&Yb(t1));
                      }
}
goto w_call_8;
w_call_8:
case CALL_8:
t1 = BcP(f_z, 1);
P += FTYPE_size(f_z);
if (t1&1) {
RefStack(t0,&Yb(t1+1));
if (TagIsSVA(t0)) {
do {
RefSVA(t1,t0);
if (t1 == t0) {
if ((!YoungerStackVar(TagSVA(Offset(E,EToY0)),t0))) {
LoadHVA(t0,H);
BindSVA(t1,t0);
                          }
break;
                        }
} while (TagIsSVA(t0=t1));                      }
X(7) = t0;
                    } else {
RefStack(X(7),&Yb(t1));
                    }
goto w_call_7;
w_call_7:
case CALL_7:
t1 = BcP(f_z, 1);
P += FTYPE_size(f_z);
if (t1&1) {
RefStack(t0,&Yb(t1+1));
if (TagIsSVA(t0)) {
do {
RefSVA(t1,t0);
if (t1 == t0) {
if ((!YoungerStackVar(TagSVA(Offset(E,EToY0)),t0))) {
LoadHVA(t0,H);
BindSVA(t1,t0);
                          }
break;
                        }
} while (TagIsSVA(t0=t1));                      }
X(6) = t0;
                    } else {
RefStack(X(6),&Yb(t1));
                    }
goto w_call_6;
w_call_6:
case CALL_6:
t1 = BcP(f_z, 1);
P += FTYPE_size(f_z);
if (t1&1) {
RefStack(t0,&Yb(t1+1));
if (TagIsSVA(t0)) {
do {
RefSVA(t1,t0);
if (t1 == t0) {
if ((!YoungerStackVar(TagSVA(Offset(E,EToY0)),t0))) {
LoadHVA(t0,H);
BindSVA(t1,t0);
                          }
break;
                        }
} while (TagIsSVA(t0=t1));                      }
X(5) = t0;
                    } else {
RefStack(X(5),&Yb(t1));
                    }
goto w_call_5;
w_call_5:
case CALL_5:
t1 = BcP(f_z, 1);
P += FTYPE_size(f_z);
if (t1&1) {
RefStack(t0,&Yb(t1+1));
if (TagIsSVA(t0)) {
do {
RefSVA(t1,t0);
if (t1 == t0) {
if ((!YoungerStackVar(TagSVA(Offset(E,EToY0)),t0))) {
LoadHVA(t0,H);
BindSVA(t1,t0);
                          }
break;
                        }
} while (TagIsSVA(t0=t1));                      }
X(4) = t0;
                    } else {
RefStack(X(4),&Yb(t1));
                    }
goto w_call_4;
w_call_4:
case CALL_4:
t1 = BcP(f_z, 1);
P += FTYPE_size(f_z);
if (t1&1) {
RefStack(t0,&Yb(t1+1));
if (TagIsSVA(t0)) {
do {
RefSVA(t1,t0);
if (t1 == t0) {
if ((!YoungerStackVar(TagSVA(Offset(E,EToY0)),t0))) {
LoadHVA(t0,H);
BindSVA(t1,t0);
                          }
break;
                        }
} while (TagIsSVA(t0=t1));                      }
X(3) = t0;
                    } else {
RefStack(X(3),&Yb(t1));
                    }
goto w_call_3;
w_call_3:
case CALL_3:
t1 = BcP(f_z, 1);
P += FTYPE_size(f_z);
if (t1&1) {
RefStack(t0,&Yb(t1+1));
if (TagIsSVA(t0)) {
do {
RefSVA(t1,t0);
if (t1 == t0) {
if ((!YoungerStackVar(TagSVA(Offset(E,EToY0)),t0))) {
LoadHVA(t0,H);
BindSVA(t1,t0);
                          }
break;
                        }
} while (TagIsSVA(t0=t1));                      }
X(2) = t0;
                    } else {
RefStack(X(2),&Yb(t1));
                    }
goto w_call_2;
w_call_2:
case CALL_2:
t1 = BcP(f_z, 1);
P += FTYPE_size(f_z);
if (t1&1) {
RefStack(t0,&Yb(t1+1));
if (TagIsSVA(t0)) {
do {
RefSVA(t1,t0);
if (t1 == t0) {
if ((!YoungerStackVar(TagSVA(Offset(E,EToY0)),t0))) {
LoadHVA(t0,H);
BindSVA(t1,t0);
                          }
break;
                        }
} while (TagIsSVA(t0=t1));                      }
X(1) = t0;
                    } else {
RefStack(X(1),&Yb(t1));
                    }
goto w_call_1;
w_call_1:
case CALL_1:
t1 = BcP(f_z, 1);
P += FTYPE_size(f_z);
if (t1&1) {
RefStack(t0,&Yb(t1+1));
if (TagIsSVA(t0)) {
do {
RefSVA(t1,t0);
if (t1 == t0) {
if ((!YoungerStackVar(TagSVA(Offset(E,EToY0)),t0))) {
LoadHVA(t0,H);
BindSVA(t1,t0);
                          }
break;
                        }
} while (TagIsSVA(t0=t1));                      }
X(0) = t0;
                    } else {
RefStack(X(0),&Yb(t1));
                    }
goto w_call;
w_call:
case CALL:
w->next_insn = BCoff(P, FTYPE_size(f_E)+FTYPE_size(f_e));
P = BcP(f_p, 1);
goto enter_predicate;
w_lastcall_n:
case LASTCALL_N:
i = (FTYPE_ctype(f_i_signed))BcP(f_i, 1);
P += FTYPE_size(f_i);
for (; i>8; --i) {
t1 = BcP(f_z, 1);
P += FTYPE_size(f_z);
if (t1&1) {
RefStack(t0,&Yb(t1+1));
if (TagIsSVA(t0)) {
do {
RefSVA(t1,t0);
if (t1 == t0) {
if ((!YoungerStackVar(TagSVA(Offset(E,EToY0)),t0))) {
LoadHVA(t0,H);
BindSVA(t1,t0);
                            }
break;
                          }
} while (TagIsSVA(t0=t1));                        }
X(i-1) = t0;
                      } else {
RefStack(X(i-1),&Yb(t1));
                      }
}
goto w_lastcall_8;
w_lastcall_8:
case LASTCALL_8:
t1 = BcP(f_z, 1);
P += FTYPE_size(f_z);
if (t1&1) {
RefStack(t0,&Yb(t1+1));
if (TagIsSVA(t0)) {
do {
RefSVA(t1,t0);
if (t1 == t0) {
if ((!YoungerStackVar(TagSVA(Offset(E,EToY0)),t0))) {
LoadHVA(t0,H);
BindSVA(t1,t0);
                          }
break;
                        }
} while (TagIsSVA(t0=t1));                      }
X(7) = t0;
                    } else {
RefStack(X(7),&Yb(t1));
                    }
goto w_lastcall_7;
w_lastcall_7:
case LASTCALL_7:
t1 = BcP(f_z, 1);
P += FTYPE_size(f_z);
if (t1&1) {
RefStack(t0,&Yb(t1+1));
if (TagIsSVA(t0)) {
do {
RefSVA(t1,t0);
if (t1 == t0) {
if ((!YoungerStackVar(TagSVA(Offset(E,EToY0)),t0))) {
LoadHVA(t0,H);
BindSVA(t1,t0);
                          }
break;
                        }
} while (TagIsSVA(t0=t1));                      }
X(6) = t0;
                    } else {
RefStack(X(6),&Yb(t1));
                    }
goto w_lastcall_6;
w_lastcall_6:
case LASTCALL_6:
t1 = BcP(f_z, 1);
P += FTYPE_size(f_z);
if (t1&1) {
RefStack(t0,&Yb(t1+1));
if (TagIsSVA(t0)) {
do {
RefSVA(t1,t0);
if (t1 == t0) {
if ((!YoungerStackVar(TagSVA(Offset(E,EToY0)),t0))) {
LoadHVA(t0,H);
BindSVA(t1,t0);
                          }
break;
                        }
} while (TagIsSVA(t0=t1));                      }
X(5) = t0;
                    } else {
RefStack(X(5),&Yb(t1));
                    }
goto w_lastcall_5;
w_lastcall_5:
case LASTCALL_5:
t1 = BcP(f_z, 1);
P += FTYPE_size(f_z);
if (t1&1) {
RefStack(t0,&Yb(t1+1));
if (TagIsSVA(t0)) {
do {
RefSVA(t1,t0);
if (t1 == t0) {
if ((!YoungerStackVar(TagSVA(Offset(E,EToY0)),t0))) {
LoadHVA(t0,H);
BindSVA(t1,t0);
                          }
break;
                        }
} while (TagIsSVA(t0=t1));                      }
X(4) = t0;
                    } else {
RefStack(X(4),&Yb(t1));
                    }
goto w_lastcall_4;
w_lastcall_4:
case LASTCALL_4:
t1 = BcP(f_z, 1);
P += FTYPE_size(f_z);
if (t1&1) {
RefStack(t0,&Yb(t1+1));
if (TagIsSVA(t0)) {
do {
RefSVA(t1,t0);
if (t1 == t0) {
if ((!YoungerStackVar(TagSVA(Offset(E,EToY0)),t0))) {
LoadHVA(t0,H);
BindSVA(t1,t0);
                          }
break;
                        }
} while (TagIsSVA(t0=t1));                      }
X(3) = t0;
                    } else {
RefStack(X(3),&Yb(t1));
                    }
goto w_lastcall_3;
w_lastcall_3:
case LASTCALL_3:
t1 = BcP(f_z, 1);
P += FTYPE_size(f_z);
if (t1&1) {
RefStack(t0,&Yb(t1+1));
if (TagIsSVA(t0)) {
do {
RefSVA(t1,t0);
if (t1 == t0) {
if ((!YoungerStackVar(TagSVA(Offset(E,EToY0)),t0))) {
LoadHVA(t0,H);
BindSVA(t1,t0);
                          }
break;
                        }
} while (TagIsSVA(t0=t1));                      }
X(2) = t0;
                    } else {
RefStack(X(2),&Yb(t1));
                    }
goto w_lastcall_2;
w_lastcall_2:
case LASTCALL_2:
t1 = BcP(f_z, 1);
P += FTYPE_size(f_z);
if (t1&1) {
RefStack(t0,&Yb(t1+1));
if (TagIsSVA(t0)) {
do {
RefSVA(t1,t0);
if (t1 == t0) {
if ((!YoungerStackVar(TagSVA(Offset(E,EToY0)),t0))) {
LoadHVA(t0,H);
BindSVA(t1,t0);
                          }
break;
                        }
} while (TagIsSVA(t0=t1));                      }
X(1) = t0;
                    } else {
RefStack(X(1),&Yb(t1));
                    }
goto w_lastcall_1;
w_lastcall_1:
case LASTCALL_1:
t1 = BcP(f_z, 1);
P += FTYPE_size(f_z);
if (t1&1) {
RefStack(t0,&Yb(t1+1));
if (TagIsSVA(t0)) {
do {
RefSVA(t1,t0);
if (t1 == t0) {
if ((!YoungerStackVar(TagSVA(Offset(E,EToY0)),t0))) {
LoadHVA(t0,H);
BindSVA(t1,t0);
                          }
break;
                        }
} while (TagIsSVA(t0=t1));                      }
X(0) = t0;
                    } else {
RefStack(X(0),&Yb(t1));
                    }
goto w_lastcall;
w_lastcall:
case LASTCALL:
w->next_insn = E->next_insn;
w->frame = E->frame;
goto w_execute;
w_execute:
case EXECUTE:
P = BcP(f_p, 1);
goto enter_predicate;
case EXECUTEQ:
P = BcP(f_p, 2);
goto enter_predicate;
w_put_x_void:
case PUT_X_VOID:
LoadHVA(Xb(BcP(f_x, 1)),H);
P += FTYPE_size(f_x);
goto WriteMode;
w_put_x_variable:
case PUT_X_VARIABLE:
Load2HVA(Xb(BcP(f_x, 1)),Xb(BcP(f_x, 2)),H);
P += (FTYPE_size(f_x)+FTYPE_size(f_x));
goto WriteMode;
case PUT_XVAL_XVAL:
Xb(BcP(f_x, 1)) = Xb(BcP(f_x, 2));
Xb(BcP(f_x, 3)) = Xb(BcP(f_x, 4));
P += (FTYPE_size(f_x)+FTYPE_size(f_x)+FTYPE_size(f_x)+FTYPE_size(f_x));
goto WriteMode;
case PUT_X_VALUE:
Xb(BcP(f_x, 1)) = Xb(BcP(f_x, 2));
P += (FTYPE_size(f_x)+FTYPE_size(f_x));
goto WriteMode;
w_put_x_unsafe_value:
case PUT_X_UNSAFE_VALUE:
RefStack(t0,&Xb(BcP(f_x, 2)));
if (TagIsSVA(t0)) {
do {
RefSVA(t1,t0);
if (t1 == t0) {
if ((!YoungerStackVar(TagSVA(Offset(E,EToY0)),t0))) {
LoadHVA(t0,H);
BindSVA(t1,t0);
                        }
break;
                      }
} while (TagIsSVA(t0=t1));                    }
Xb(BcP(f_x, 1)) = t0;
Xb(BcP(f_x, 2)) = t0;
P += (FTYPE_size(f_x)+FTYPE_size(f_x));
goto WriteMode;
w_put_y_first_variable:
case PUT_Y_FIRST_VARIABLE:
ComputeE;
goto w_put_y_variable;
w_put_y_variable:
case PUT_Y_VARIABLE:
t0 = BcP(f_y, 2);
Load2SVA(Xb(BcP(f_x, 1)),Yb(t0));
P += (FTYPE_size(f_x)+FTYPE_size(f_y));
goto WriteMode;
w_put_yfvar_yvar:
case PUT_YFVAR_YVAR:
ComputeE;
goto w_put_yvar_yvar;
w_put_yvar_yvar:
case PUT_YVAR_YVAR:
t0 = BcP(f_y, 2);
Load2SVA(Xb(BcP(f_x, 1)),Yb(t0));
t0 = BcP(f_y, 4);
Load2SVA(Xb(BcP(f_x, 3)),Yb(t0));
P += (FTYPE_size(f_x)+FTYPE_size(f_y)+FTYPE_size(f_x)+FTYPE_size(f_y));
goto WriteMode;
case PUT_CONSTANTQ:
Xb(BcP(f_x, 2)) = BcP(f_t, 3);
P += (FTYPE_size(f_Q)+FTYPE_size(f_x))+FTYPE_size(f_t);
goto WriteMode;
case PUT_CONSTANT:
Xb(BcP(f_x, 1)) = BcP(f_t, 2);
P += FTYPE_size(f_x)+FTYPE_size(f_t);
goto WriteMode;
case PUT_NIL:
Xb(BcP(f_x, 1)) = atom_nil;
P += FTYPE_size(f_x);
goto WriteMode;
w_put_largeq:
case PUT_LARGEQ:
StoreH;
Xb(BcP(f_x, 2)) = BC_MakeLarge(Arg,&BcP(f_t, 3));
LoadH;
P += (FTYPE_size(f_Q)+FTYPE_size(f_x))+LargeSize(BcP(f_t, 3));
goto WriteMode;
w_put_large:
case PUT_LARGE:
StoreH;
Xb(BcP(f_x, 1)) = BC_MakeLarge(Arg,&BcP(f_t, 2));
LoadH;
P += FTYPE_size(f_x)+LargeSize(BcP(f_t, 2));
goto WriteMode;
w_put_structureq:
case PUT_STRUCTUREQ:
Xb(BcP(f_x, 2)) = Tag(STR,H);
HeapPush(H,BcP(f_f, 3));
P += (FTYPE_size(f_Q)+FTYPE_size(f_x))+FTYPE_size(f_f);
goto WriteMode;
w_put_structure:
case PUT_STRUCTURE:
Xb(BcP(f_x, 1)) = Tag(STR,H);
HeapPush(H,BcP(f_f, 2));
P += FTYPE_size(f_x)+FTYPE_size(f_f);
goto WriteMode;
w_put_list:
case PUT_LIST:
Xb(BcP(f_x, 1)) = Tag(LST,H);
P += FTYPE_size(f_x);
goto WriteMode;
case PUT_Y_VALUE:
RefStack(Xb(BcP(f_x, 1)),&Yb(BcP(f_y, 2)));
P += (FTYPE_size(f_x)+FTYPE_size(f_y));
goto WriteMode;
w_put_y_unsafe_value:
case PUT_Y_UNSAFE_VALUE:
RefStack(t0,&Yb(BcP(f_y, 2)));
if (TagIsSVA(t0)) {
do {
RefSVA(t1,t0);
if (t1 == t0) {
if ((!YoungerStackVar(TagSVA(Offset(E,EToY0)),t0))) {
LoadHVA(t0,H);
BindSVA(t1,t0);
                        }
break;
                      }
} while (TagIsSVA(t0=t1));                    }
Xb(BcP(f_x, 1)) = t0;
P += (FTYPE_size(f_x)+FTYPE_size(f_y));
goto WriteMode;
case PUT_YVAL_YVAL:
RefStack(Xb(BcP(f_x, 1)),&Yb(BcP(f_y, 2)));
RefStack(Xb(BcP(f_x, 3)),&Yb(BcP(f_y, 4)));
P += (FTYPE_size(f_x)+FTYPE_size(f_y)+FTYPE_size(f_x)+FTYPE_size(f_y));
goto WriteMode;
w_put_yval_yuval:
case PUT_YVAL_YUVAL:
RefStack(Xb(BcP(f_x, 1)),&Yb(BcP(f_y, 2)));
RefStack(t0,&Yb(BcP(f_y, 4)));
if (TagIsSVA(t0)) {
do {
RefSVA(t1,t0);
if (t1 == t0) {
if ((!YoungerStackVar(TagSVA(Offset(E,EToY0)),t0))) {
LoadHVA(t0,H);
BindSVA(t1,t0);
                        }
break;
                      }
} while (TagIsSVA(t0=t1));                    }
Xb(BcP(f_x, 3)) = t0;
P += (FTYPE_size(f_x)+FTYPE_size(f_y)+FTYPE_size(f_x)+FTYPE_size(f_y));
goto WriteMode;
w_put_yuval_yval:
case PUT_YUVAL_YVAL:
RefStack(t0,&Yb(BcP(f_y, 2)));
if (TagIsSVA(t0)) {
do {
RefSVA(t1,t0);
if (t1 == t0) {
if ((!YoungerStackVar(TagSVA(Offset(E,EToY0)),t0))) {
LoadHVA(t0,H);
BindSVA(t1,t0);
                        }
break;
                      }
} while (TagIsSVA(t0=t1));                    }
Xb(BcP(f_x, 1)) = t0;
RefStack(Xb(BcP(f_x, 3)),&Yb(BcP(f_y, 4)));
P += (FTYPE_size(f_x)+FTYPE_size(f_y)+FTYPE_size(f_x)+FTYPE_size(f_y));
goto WriteMode;
w_put_yuval_yuval:
case PUT_YUVAL_YUVAL:
RefStack(t0,&Yb(BcP(f_y, 2)));
if (TagIsSVA(t0)) {
do {
RefSVA(t1,t0);
if (t1 == t0) {
if ((!YoungerStackVar(TagSVA(Offset(E,EToY0)),t0))) {
LoadHVA(t0,H);
BindSVA(t1,t0);
                        }
break;
                      }
} while (TagIsSVA(t0=t1));                    }
Xb(BcP(f_x, 1)) = t0;
RefStack(t0,&Yb(BcP(f_y, 4)));
if (TagIsSVA(t0)) {
do {
RefSVA(t1,t0);
if (t1 == t0) {
if ((!YoungerStackVar(TagSVA(Offset(E,EToY0)),t0))) {
LoadHVA(t0,H);
BindSVA(t1,t0);
                          }
break;
                        }
} while (TagIsSVA(t0=t1));                      }
Xb(BcP(f_x, 3)) = t0;
P += (FTYPE_size(f_x)+FTYPE_size(f_y)+FTYPE_size(f_x)+FTYPE_size(f_y));
goto WriteMode;
case GET_X_VALUE:
StoreH;
goto r_get_x_value;
case GET_Y_FIRST_VALUE:
StoreH;
goto r_get_y_first_value;
case GET_Y_VALUE:
StoreH;
goto r_get_y_value;
case GET_CONSTANTQ:
P += FTYPE_size(f_Q);
goto w_get_constant;
w_get_constant:
case GET_CONSTANT:
StoreH;
goto r_get_constant;
case GET_LARGEQ:
P += FTYPE_size(f_Q);
goto w_get_large;
w_get_large:
case GET_LARGE:
StoreH;
goto r_get_large;
case GET_STRUCTUREQ:
P += FTYPE_size(f_Q);
goto w_get_structure;
w_get_structure:
case GET_STRUCTURE:
StoreH;
goto r_get_structure;
case GET_NIL:
StoreH;
goto r_get_nil;
case GET_LIST:
StoreH;
goto r_get_list;
case GET_CONSTANT_NECK_PROCEEDQ:
P += FTYPE_size(f_Q);
goto w_get_constant_neck_proceed;
w_get_constant_neck_proceed:
case GET_CONSTANT_NECK_PROCEED:
StoreH;
goto r_get_constant_neck_proceed;
case GET_NIL_NECK_PROCEED:
StoreH;
goto r_get_nil_neck_proceed;
case CUTB_X:
StoreH;
goto r_cutb_x;
case CUTB_X_NECK:
StoreH;
goto r_cutb_x_neck;
case CUTB_NECK:
StoreH;
goto r_cutb_neck;
case CUTB_X_NECK_PROCEED:
StoreH;
goto r_cutb_x_neck_proceed;
case CUTB_NECK_PROCEED:
StoreH;
goto r_cutb_neck_proceed;
case CUTE_X:
StoreH;
goto r_cute_x;
case CUTE_X_NECK:
StoreH;
goto r_cute_x_neck;
case CUTE_NECK:
StoreH;
goto r_cute_neck;
case CUTF:
StoreH;
goto r_cutf;
case CUTF_X:
StoreH;
goto r_cutf_x;
case CUT_Y:
StoreH;
goto r_cut_y;
case CHOICE_X:
Xb(BcP(f_x, 1)) = ChoiceToInt(w->next_node);
P += FTYPE_size(f_x);
goto WriteMode;
case CHOICE_YF:
ComputeE;
goto w_choice_y;
w_choice_y:
case CHOICE_Y:
Yb(BcP(f_y, 1)) = ChoiceToInt(w->next_node);
P += FTYPE_size(f_y);
goto WriteMode;
w_kontinue:
case KONTINUE:
Setfunc(TagToFunctor(Y(0)));
for (i=0; i<Func->arity; i++) {
X(i) = Y(i+1);
}
w->next_insn = E->next_insn;
w->frame = E->frame;
goto enter_predicate;
case LEAVE:
StoreH;
goto r_leave;
case EXIT_TOPLEVEL:
StoreH;
goto r_exit_toplevel;
case RETRY_CQ:
StoreH;
goto r_retry_cq;
case RETRY_C:
StoreH;
goto r_retry_c;
case GET_STRUCTURE_X0Q:
P += FTYPE_size(f_Q);
goto w_get_structure_x0;
w_get_structure_x0:
case GET_STRUCTURE_X0:
t1 = Tag(STR,H);
if (TagIsHVA(t0)) {
BindHVA(t0,t1);
                  } else if (t0 & TagBitSVA) {
BindSVA(t0,t1);
                  } else {
BindCVA(t0,t1);
                  }
HeapPush(H,BcP(f_f, 1));
P += FTYPE_size(f_f);
goto WriteMode;
case GET_LARGE_X0Q:
P += FTYPE_size(f_Q);
goto w_get_large_x0;
w_get_large_x0:
case GET_LARGE_X0:
StoreH;
t1 = BC_MakeLarge(Arg,&BcP(f_p, 1));
LoadH;
if (TagIsHVA(t0)) {
BindHVA(t0,t1);
                  } else if (t0 & TagBitSVA) {
BindSVA(t0,t1);
                  } else {
BindCVA(t0,t1);
                  }
P += LargeSize(BcP(f_t, 1));
goto WriteMode;
case GET_CONSTANT_X0Q:
P += FTYPE_size(f_Q);
goto w_get_constant_x0;
w_get_constant_x0:
case GET_CONSTANT_X0:
if (TagIsHVA(t0)) {
BindHVA(t0,BcP(f_t, 1));
                  } else if (t0 & TagBitSVA) {
BindSVA(t0,BcP(f_t, 1));
                  } else {
BindCVA(t0,BcP(f_t, 1));
                  }
P += FTYPE_size(f_t);
goto WriteMode;
case GET_NIL_X0:
if (TagIsHVA(t0)) {
BindHVA(t0,atom_nil);
                  } else if (t0 & TagBitSVA) {
BindSVA(t0,atom_nil);
                  } else {
BindCVA(t0,atom_nil);
                  }
P += 0;
goto WriteMode;
case GET_LIST_X0:
t1 = Tag(LST,H);
if (TagIsHVA(t0)) {
BindHVA(t0,t1);
                  } else if (t0 & TagBitSVA) {
BindSVA(t0,t1);
                  } else {
BindCVA(t0,t1);
                  }
P += 0;
goto WriteMode;
case GET_XVAR_XVAR:
Xb(BcP(f_x, 2)) = Xb(BcP(f_x, 1));
Xb(BcP(f_x, 4)) = Xb(BcP(f_x, 3));
P += (FTYPE_size(f_x)+FTYPE_size(f_x)+FTYPE_size(f_x)+FTYPE_size(f_x));
goto WriteMode;
case GET_X_VARIABLE:
Xb(BcP(f_x, 2)) = Xb(BcP(f_x, 1));
P += (FTYPE_size(f_x)+FTYPE_size(f_x));
goto WriteMode;
case GET_Y_FIRST_VARIABLE:
ComputeE;
goto w_get_y_variable;
w_get_y_variable:
case GET_Y_VARIABLE:
Yb(BcP(f_y, 2)) = Xb(BcP(f_x, 1));
P += (FTYPE_size(f_x)+FTYPE_size(f_y));
goto WriteMode;
case GET_YFVAR_YVAR:
ComputeE;
goto w_get_yvar_yvar;
w_get_yvar_yvar:
case GET_YVAR_YVAR:
Yb(BcP(f_y, 2)) = Xb(BcP(f_x, 1));
Yb(BcP(f_y, 4)) = Xb(BcP(f_x, 3));
P += (FTYPE_size(f_x)+FTYPE_size(f_y)+FTYPE_size(f_x)+FTYPE_size(f_y));
goto WriteMode;
case BRANCH:
P = BCoff(P, BcP(f_i, 1));
P += 0;
goto WriteMode;
case FUNCTION_1Q:
StoreH;
goto r_function_1q;
case FUNCTION_1:
StoreH;
goto r_function_1;
case FUNCTION_2Q:
StoreH;
goto r_function_2q;
case FUNCTION_2:
StoreH;
goto r_function_2;
case BUILTIN_1Q:
StoreH;
goto r_builtin_1q;
case BUILTIN_1:
StoreH;
goto r_builtin_1;
case BUILTIN_2Q:
StoreH;
goto r_builtin_2q;
case BUILTIN_2:
StoreH;
goto r_builtin_2;
case BUILTIN_3Q:
StoreH;
goto r_builtin_3q;
case BUILTIN_3:
StoreH;
goto r_builtin_3;
case RETRY_INSTANCE:
StoreH;
goto r_retry_instance;
w_get_constraint:
case GET_CONSTRAINT:
t1 = Xb(BcP(f_x, 1));
LoadCVA(t2,H);
SwitchOnVar(t1,t0,{
BindHVA(t1,t2);
Xb(BcP(f_x, 1)) = t2;
},{
BindCVA(t2,t1);
},{
BindSVA(t1,t2);
Xb(BcP(f_x, 1)) = t2;
},{
BindCVA(t2,t1);
});
P += FTYPE_size(f_x);
goto WriteMode;
case UNIFY_VOID:
i = (FTYPE_ctype(f_i_signed))BcP(f_i, 1);
P += FTYPE_size(f_i);
for (; i>4; --i) {
ConstrHVA(H);
}
goto w_unify_void_4;
w_unify_void_4:
case UNIFY_VOID_4:
ConstrHVA(H);
goto w_unify_void_3;
w_unify_void_3:
case UNIFY_VOID_3:
ConstrHVA(H);
goto w_unify_void_2;
w_unify_void_2:
case UNIFY_VOID_2:
ConstrHVA(H);
goto w_unify_void_1;
w_unify_void_1:
case UNIFY_VOID_1:
ConstrHVA(H);
P += 0;
goto WriteMode;
case UNIFY_X_VARIABLE:
LoadHVA(Xb(BcP(f_x, 1)),H);
P += FTYPE_size(f_x);
goto WriteMode;
case UNIFY_X_VALUE:
HeapPush(H,Xb(BcP(f_x, 1)));
P += FTYPE_size(f_x);
goto WriteMode;
case UNIFY_X_LOCAL_VALUE:
t1 = Xb(BcP(f_x, 1));
if (TagIsSVA(t1)) {
do {
RefSVA(t0,t1);
if (t0 == t1) {
BindSVA(t1,TagHVA(H));
PreLoadHVA(t1,H);
break;
                      }
} while (TagIsSVA(t1=t0));                    }
HeapPush(H,t1);
P += FTYPE_size(f_x);
goto WriteMode;
case UNIFY_Y_FIRST_VARIABLE:
ComputeE;
goto w_unify_y_variable;
w_unify_y_variable:
case UNIFY_Y_VARIABLE:
LoadHVA(Yb(BcP(f_y, 1)),H);
P += FTYPE_size(f_y);
goto WriteMode;
case UNIFY_Y_FIRST_VALUE:
LoadHVA(t0,H);
if (CondStackvar(Yb(BcP(f_y, 1)))) {
TrailPushCheck(w->trail_top,TagSVA(&Yb(BcP(f_y, 1))));
Yb(BcP(f_y, 1)) = t0;
                  } else {
Yb(BcP(f_y, 1)) = t0;
                  }
P += FTYPE_size(f_y);
goto WriteMode;
case UNIFY_Y_VALUE:
HeapPushRefStack(H,&Yb(BcP(f_y, 1)));
P += FTYPE_size(f_y);
goto WriteMode;
case UNIFY_Y_LOCAL_VALUE:
RefStack(t1,&Yb(BcP(f_y, 1)));
if (TagIsSVA(t1)) {
do {
RefSVA(t0,t1);
if (t0 == t1) {
BindSVA(t1,TagHVA(H));
PreLoadHVA(t1,H);
break;
                      }
} while (TagIsSVA(t1=t0));                    }
HeapPush(H,t1);
P += FTYPE_size(f_y);
goto WriteMode;
case UNIFY_CONSTANTQ:
HeapPush(H,BcP(f_t, 2));
P += FTYPE_size(f_Q)+FTYPE_size(f_t);
goto WriteMode;
case UNIFY_CONSTANT:
HeapPush(H,BcP(f_t, 1));
P += FTYPE_size(f_t);
goto WriteMode;
case UNIFY_LARGEQ:
P += FTYPE_size(f_Q);
goto w_unify_large;
w_unify_large:
case UNIFY_LARGE:
w->global_top = HeapOffset(H,1);
*H = BC_MakeLarge(Arg,&BcP(f_t, 1));
P += LargeSize(BcP(f_t, 1));
goto ReadMode;
case UNIFY_STRUCTUREQ:
HeapPush(H,Tag(STR,HeapOffset(H,1)));
HeapPush(H,BcP(f_f, 2));
P += FTYPE_size(f_Q)+FTYPE_size(f_f);
goto WriteMode;
case UNIFY_STRUCTURE:
HeapPush(H,Tag(STR,HeapOffset(H,1)));
HeapPush(H,BcP(f_f, 1));
P += FTYPE_size(f_f);
goto WriteMode;
case UNIFY_NIL:
HeapPush(H,atom_nil);
P += 0;
goto WriteMode;
case UNIFY_LIST:
HeapPush(H,Tag(LST,HeapOffset(H,1)));
P += 0;
goto WriteMode;
case UNIFY_CONSTANT_NECK_PROCEEDQ:
HeapPush(H,BcP(f_t, 2));
goto w_neck_proceed;
case UNIFY_CONSTANT_NECK_PROCEED:
HeapPush(H,BcP(f_t, 1));
goto w_neck_proceed;
case UNIFY_NIL_NECK_PROCEED:
HeapPush(H,atom_nil);
goto w_neck_proceed;
case U2_VOID_XVAR:
i = (FTYPE_ctype(f_i_signed))BcP(f_i, 1);
do {
ConstrHVA(H);} while (--i);LoadHVA(Xb(BcP(f_x, 2)),H);
P += (FTYPE_size(f_i)+FTYPE_size(f_x));
goto WriteMode;
case U2_VOID_YFVAR:
ComputeE;
goto w_u2_void_yvar;
w_u2_void_yvar:
case U2_VOID_YVAR:
i = (FTYPE_ctype(f_i_signed))BcP(f_i, 1);
do {
ConstrHVA(H);} while (--i);LoadHVA(Yb(BcP(f_y, 2)),H);
P += (FTYPE_size(f_i)+FTYPE_size(f_y));
goto WriteMode;
case U2_VOID_XVAL:
i = (FTYPE_ctype(f_i_signed))BcP(f_i, 1);
do {
ConstrHVA(H);} while (--i);HeapPush(H,Xb(BcP(f_x, 2)));
P += (FTYPE_size(f_i)+FTYPE_size(f_x));
goto WriteMode;
case U2_VOID_XLVAL:
i = (FTYPE_ctype(f_i_signed))BcP(f_i, 1);
do {
ConstrHVA(H);} while (--i);t1 = Xb(BcP(f_x, 2));
if (TagIsSVA(t1)) {
do {
RefSVA(t0,t1);
if (t0 == t1) {
BindSVA(t1,TagHVA(H));
PreLoadHVA(t1,H);
break;
                        }
} while (TagIsSVA(t1=t0));                      }
HeapPush(H,t1);
P += (FTYPE_size(f_i)+FTYPE_size(f_x));
goto WriteMode;
case U2_VOID_YFVAL:
i = (FTYPE_ctype(f_i_signed))BcP(f_i, 1);
do {
ConstrHVA(H);} while (--i);LoadHVA(t0,H);
if (CondStackvar(Yb(BcP(f_y, 2)))) {
TrailPushCheck(w->trail_top,TagSVA(&Yb(BcP(f_y, 2))));
Yb(BcP(f_y, 2)) = t0;
                    } else {
Yb(BcP(f_y, 2)) = t0;
                    }
P += (FTYPE_size(f_i)+FTYPE_size(f_y));
goto WriteMode;
case U2_VOID_YVAL:
i = (FTYPE_ctype(f_i_signed))BcP(f_i, 1);
do {
ConstrHVA(H);} while (--i);HeapPushRefStack(H,&Yb(BcP(f_y, 2)));
P += (FTYPE_size(f_i)+FTYPE_size(f_y));
goto WriteMode;
case U2_VOID_YLVAL:
i = (FTYPE_ctype(f_i_signed))BcP(f_i, 1);
do {
ConstrHVA(H);} while (--i);RefStack(t1,&Yb(BcP(f_y, 2)));
if (TagIsSVA(t1)) {
do {
RefSVA(t0,t1);
if (t0 == t1) {
BindSVA(t1,TagHVA(H));
PreLoadHVA(t1,H);
break;
                        }
} while (TagIsSVA(t1=t0));                      }
HeapPush(H,t1);
P += (FTYPE_size(f_i)+FTYPE_size(f_y));
goto WriteMode;
case U2_XVAR_VOID:
LoadHVA(Xb(BcP(f_x, 1)),H);
i = (FTYPE_ctype(f_i_signed))BcP(f_i, 2);
do {
ConstrHVA(H);} while (--i);P += (FTYPE_size(f_x)+FTYPE_size(f_i));
goto WriteMode;
case U2_XVAR_XVAR:
LoadHVA(Xb(BcP(f_x, 1)),H);
LoadHVA(Xb(BcP(f_x, 2)),H);
P += (FTYPE_size(f_x)+FTYPE_size(f_x));
goto WriteMode;
case U2_XVAR_YFVAR:
ComputeE;
goto w_u2_xvar_yvar;
w_u2_xvar_yvar:
case U2_XVAR_YVAR:
LoadHVA(Xb(BcP(f_x, 1)),H);
LoadHVA(Yb(BcP(f_y, 2)),H);
P += (FTYPE_size(f_x)+FTYPE_size(f_y));
goto WriteMode;
case U2_XVAR_XVAL:
LoadHVA(Xb(BcP(f_x, 1)),H);
HeapPush(H,Xb(BcP(f_x, 2)));
P += (FTYPE_size(f_x)+FTYPE_size(f_x));
goto WriteMode;
case U2_XVAR_XLVAL:
LoadHVA(Xb(BcP(f_x, 1)),H);
t1 = Xb(BcP(f_x, 2));
if (TagIsSVA(t1)) {
do {
RefSVA(t0,t1);
if (t0 == t1) {
BindSVA(t1,TagHVA(H));
PreLoadHVA(t1,H);
break;
                      }
} while (TagIsSVA(t1=t0));                    }
HeapPush(H,t1);
P += (FTYPE_size(f_x)+FTYPE_size(f_x));
goto WriteMode;
case U2_XVAR_YFVAL:
LoadHVA(Xb(BcP(f_x, 1)),H);
LoadHVA(t0,H);
if (CondStackvar(Yb(BcP(f_y, 2)))) {
TrailPushCheck(w->trail_top,TagSVA(&Yb(BcP(f_y, 2))));
Yb(BcP(f_y, 2)) = t0;
                  } else {
Yb(BcP(f_y, 2)) = t0;
                  }
P += (FTYPE_size(f_x)+FTYPE_size(f_y));
goto WriteMode;
case U2_XVAR_YVAL:
LoadHVA(Xb(BcP(f_x, 1)),H);
HeapPushRefStack(H,&Yb(BcP(f_y, 2)));
P += (FTYPE_size(f_x)+FTYPE_size(f_y));
goto WriteMode;
case U2_XVAR_YLVAL:
LoadHVA(Xb(BcP(f_x, 1)),H);
RefStack(t1,&Yb(BcP(f_y, 2)));
if (TagIsSVA(t1)) {
do {
RefSVA(t0,t1);
if (t0 == t1) {
BindSVA(t1,TagHVA(H));
PreLoadHVA(t1,H);
break;
                      }
} while (TagIsSVA(t1=t0));                    }
HeapPush(H,t1);
P += (FTYPE_size(f_x)+FTYPE_size(f_y));
goto WriteMode;
case U2_YFVAR_VOID:
ComputeE;
goto w_u2_yvar_void;
w_u2_yvar_void:
case U2_YVAR_VOID:
LoadHVA(Yb(BcP(f_y, 1)),H);
i = (FTYPE_ctype(f_i_signed))BcP(f_i, 2);
do {
ConstrHVA(H);} while (--i);P += (FTYPE_size(f_y)+FTYPE_size(f_i));
goto WriteMode;
case U2_YFVAR_XVAR:
ComputeE;
goto w_u2_yvar_xvar;
w_u2_yvar_xvar:
case U2_YVAR_XVAR:
LoadHVA(Yb(BcP(f_y, 1)),H);
LoadHVA(Xb(BcP(f_x, 2)),H);
P += (FTYPE_size(f_y)+FTYPE_size(f_x));
goto WriteMode;
case U2_YFVAR_YVAR:
ComputeE;
goto w_u2_yvar_yvar;
w_u2_yvar_yvar:
case U2_YVAR_YVAR:
LoadHVA(Yb(BcP(f_y, 1)),H);
LoadHVA(Yb(BcP(f_y, 2)),H);
P += (FTYPE_size(f_y)+FTYPE_size(f_y));
goto WriteMode;
case U2_YFVAR_XVAL:
ComputeE;
goto w_u2_yvar_xval;
w_u2_yvar_xval:
case U2_YVAR_XVAL:
LoadHVA(Yb(BcP(f_y, 1)),H);
HeapPush(H,Xb(BcP(f_x, 2)));
P += (FTYPE_size(f_y)+FTYPE_size(f_x));
goto WriteMode;
case U2_YFVAR_XLVAL:
ComputeE;
goto w_u2_yvar_xlval;
w_u2_yvar_xlval:
case U2_YVAR_XLVAL:
LoadHVA(Yb(BcP(f_y, 1)),H);
t1 = Xb(BcP(f_x, 2));
if (TagIsSVA(t1)) {
do {
RefSVA(t0,t1);
if (t0 == t1) {
BindSVA(t1,TagHVA(H));
PreLoadHVA(t1,H);
break;
                      }
} while (TagIsSVA(t1=t0));                    }
HeapPush(H,t1);
P += (FTYPE_size(f_y)+FTYPE_size(f_x));
goto WriteMode;
case U2_YFVAR_YVAL:
ComputeE;
goto w_u2_yvar_yval;
w_u2_yvar_yval:
case U2_YVAR_YVAL:
LoadHVA(Yb(BcP(f_y, 1)),H);
HeapPushRefStack(H,&Yb(BcP(f_y, 2)));
P += (FTYPE_size(f_y)+FTYPE_size(f_y));
goto WriteMode;
case U2_YFVAR_YLVAL:
ComputeE;
goto w_u2_yvar_ylval;
w_u2_yvar_ylval:
case U2_YVAR_YLVAL:
LoadHVA(Yb(BcP(f_y, 1)),H);
RefStack(t1,&Yb(BcP(f_y, 2)));
if (TagIsSVA(t1)) {
do {
RefSVA(t0,t1);
if (t0 == t1) {
BindSVA(t1,TagHVA(H));
PreLoadHVA(t1,H);
break;
                      }
} while (TagIsSVA(t1=t0));                    }
HeapPush(H,t1);
P += (FTYPE_size(f_y)+FTYPE_size(f_y));
goto WriteMode;
case U2_YFVAL_VOID:
LoadHVA(t0,H);
if (CondStackvar(Yb(BcP(f_y, 1)))) {
TrailPushCheck(w->trail_top,TagSVA(&Yb(BcP(f_y, 1))));
Yb(BcP(f_y, 1)) = t0;
                  } else {
Yb(BcP(f_y, 1)) = t0;
                  }
i = (FTYPE_ctype(f_i_signed))BcP(f_i, 2);
do {
ConstrHVA(H);} while (--i);P += (FTYPE_size(f_y)+FTYPE_size(f_i));
goto WriteMode;
case U2_YFVAL_XVAR:
LoadHVA(t0,H);
if (CondStackvar(Yb(BcP(f_y, 1)))) {
TrailPushCheck(w->trail_top,TagSVA(&Yb(BcP(f_y, 1))));
Yb(BcP(f_y, 1)) = t0;
                  } else {
Yb(BcP(f_y, 1)) = t0;
                  }
LoadHVA(Xb(BcP(f_x, 2)),H);
P += (FTYPE_size(f_y)+FTYPE_size(f_x));
goto WriteMode;
case U2_YFVAL_YFVAL:
LoadHVA(t0,H);
if (CondStackvar(Yb(BcP(f_y, 1)))) {
TrailPushCheck(w->trail_top,TagSVA(&Yb(BcP(f_y, 1))));
Yb(BcP(f_y, 1)) = t0;
                  } else {
Yb(BcP(f_y, 1)) = t0;
                  }
LoadHVA(t0,H);
if (CondStackvar(Yb(BcP(f_y, 2)))) {
TrailPushCheck(w->trail_top,TagSVA(&Yb(BcP(f_y, 2))));
Yb(BcP(f_y, 2)) = t0;
                  } else {
Yb(BcP(f_y, 2)) = t0;
                  }
P += (FTYPE_size(f_y)+FTYPE_size(f_y));
goto WriteMode;
case U2_YFVAL_XVAL:
LoadHVA(t0,H);
if (CondStackvar(Yb(BcP(f_y, 1)))) {
TrailPushCheck(w->trail_top,TagSVA(&Yb(BcP(f_y, 1))));
Yb(BcP(f_y, 1)) = t0;
                  } else {
Yb(BcP(f_y, 1)) = t0;
                  }
HeapPush(H,Xb(BcP(f_x, 2)));
P += (FTYPE_size(f_y)+FTYPE_size(f_x));
goto WriteMode;
case U2_YFVAL_XLVAL:
LoadHVA(t0,H);
if (CondStackvar(Yb(BcP(f_y, 1)))) {
TrailPushCheck(w->trail_top,TagSVA(&Yb(BcP(f_y, 1))));
Yb(BcP(f_y, 1)) = t0;
                  } else {
Yb(BcP(f_y, 1)) = t0;
                  }
t1 = Xb(BcP(f_x, 2));
if (TagIsSVA(t1)) {
do {
RefSVA(t0,t1);
if (t0 == t1) {
BindSVA(t1,TagHVA(H));
PreLoadHVA(t1,H);
break;
                      }
} while (TagIsSVA(t1=t0));                    }
HeapPush(H,t1);
P += (FTYPE_size(f_y)+FTYPE_size(f_x));
goto WriteMode;
case U2_YFVAL_YVAL:
LoadHVA(t0,H);
if (CondStackvar(Yb(BcP(f_y, 1)))) {
TrailPushCheck(w->trail_top,TagSVA(&Yb(BcP(f_y, 1))));
Yb(BcP(f_y, 1)) = t0;
                  } else {
Yb(BcP(f_y, 1)) = t0;
                  }
HeapPushRefStack(H,&Yb(BcP(f_y, 2)));
P += (FTYPE_size(f_y)+FTYPE_size(f_y));
goto WriteMode;
case U2_YFVAL_YLVAL:
LoadHVA(t0,H);
if (CondStackvar(Yb(BcP(f_y, 1)))) {
TrailPushCheck(w->trail_top,TagSVA(&Yb(BcP(f_y, 1))));
Yb(BcP(f_y, 1)) = t0;
                  } else {
Yb(BcP(f_y, 1)) = t0;
                  }
RefStack(t1,&Yb(BcP(f_y, 2)));
if (TagIsSVA(t1)) {
do {
RefSVA(t0,t1);
if (t0 == t1) {
BindSVA(t1,TagHVA(H));
PreLoadHVA(t1,H);
break;
                      }
} while (TagIsSVA(t1=t0));                    }
HeapPush(H,t1);
P += (FTYPE_size(f_y)+FTYPE_size(f_y));
goto WriteMode;
case U2_XVAL_VOID:
HeapPush(H,Xb(BcP(f_x, 1)));
i = (FTYPE_ctype(f_i_signed))BcP(f_i, 2);
do {
ConstrHVA(H);} while (--i);P += (FTYPE_size(f_x)+FTYPE_size(f_i));
goto WriteMode;
case U2_XLVAL_VOID:
t1 = Xb(BcP(f_x, 1));
if (TagIsSVA(t1)) {
do {
RefSVA(t0,t1);
if (t0 == t1) {
BindSVA(t1,TagHVA(H));
PreLoadHVA(t1,H);
break;
                      }
} while (TagIsSVA(t1=t0));                    }
HeapPush(H,t1);
i = (FTYPE_ctype(f_i_signed))BcP(f_i, 2);
do {
ConstrHVA(H);} while (--i);P += (FTYPE_size(f_x)+FTYPE_size(f_i));
goto WriteMode;
case U2_XVAL_XVAR:
HeapPush(H,Xb(BcP(f_x, 1)));
LoadHVA(Xb(BcP(f_x, 2)),H);
P += (FTYPE_size(f_x)+FTYPE_size(f_x));
goto WriteMode;
case U2_XLVAL_XVAR:
t1 = Xb(BcP(f_x, 1));
if (TagIsSVA(t1)) {
do {
RefSVA(t0,t1);
if (t0 == t1) {
BindSVA(t1,TagHVA(H));
PreLoadHVA(t1,H);
break;
                      }
} while (TagIsSVA(t1=t0));                    }
HeapPush(H,t1);
LoadHVA(Xb(BcP(f_x, 2)),H);
P += (FTYPE_size(f_x)+FTYPE_size(f_x));
goto WriteMode;
case U2_XVAL_YFVAR:
ComputeE;
goto w_u2_xval_yvar;
w_u2_xval_yvar:
case U2_XVAL_YVAR:
HeapPush(H,Xb(BcP(f_x, 1)));
LoadHVA(Yb(BcP(f_y, 2)),H);
P += (FTYPE_size(f_x)+FTYPE_size(f_y));
goto WriteMode;
case U2_XLVAL_YFVAR:
ComputeE;
goto w_u2_xlval_yvar;
w_u2_xlval_yvar:
case U2_XLVAL_YVAR:
t1 = Xb(BcP(f_x, 1));
if (TagIsSVA(t1)) {
do {
RefSVA(t0,t1);
if (t0 == t1) {
BindSVA(t1,TagHVA(H));
PreLoadHVA(t1,H);
break;
                      }
} while (TagIsSVA(t1=t0));                    }
HeapPush(H,t1);
LoadHVA(Yb(BcP(f_y, 2)),H);
P += (FTYPE_size(f_x)+FTYPE_size(f_y));
goto WriteMode;
case U2_XVAL_XVAL:
HeapPush(H,Xb(BcP(f_x, 1)));
HeapPush(H,Xb(BcP(f_x, 2)));
P += (FTYPE_size(f_x)+FTYPE_size(f_x));
goto WriteMode;
case U2_XVAL_XLVAL:
HeapPush(H,Xb(BcP(f_x, 1)));
t1 = Xb(BcP(f_x, 2));
if (TagIsSVA(t1)) {
do {
RefSVA(t0,t1);
if (t0 == t1) {
BindSVA(t1,TagHVA(H));
PreLoadHVA(t1,H);
break;
                      }
} while (TagIsSVA(t1=t0));                    }
HeapPush(H,t1);
P += (FTYPE_size(f_x)+FTYPE_size(f_x));
goto WriteMode;
case U2_XLVAL_XVAL:
t1 = Xb(BcP(f_x, 1));
if (TagIsSVA(t1)) {
do {
RefSVA(t0,t1);
if (t0 == t1) {
BindSVA(t1,TagHVA(H));
PreLoadHVA(t1,H);
break;
                      }
} while (TagIsSVA(t1=t0));                    }
HeapPush(H,t1);
HeapPush(H,Xb(BcP(f_x, 2)));
P += (FTYPE_size(f_x)+FTYPE_size(f_x));
goto WriteMode;
case U2_XLVAL_XLVAL:
t1 = Xb(BcP(f_x, 1));
if (TagIsSVA(t1)) {
do {
RefSVA(t0,t1);
if (t0 == t1) {
BindSVA(t1,TagHVA(H));
PreLoadHVA(t1,H);
break;
                      }
} while (TagIsSVA(t1=t0));                    }
HeapPush(H,t1);
t1 = Xb(BcP(f_x, 2));
if (TagIsSVA(t1)) {
do {
RefSVA(t0,t1);
if (t0 == t1) {
BindSVA(t1,TagHVA(H));
PreLoadHVA(t1,H);
break;
                        }
} while (TagIsSVA(t1=t0));                      }
HeapPush(H,t1);
P += (FTYPE_size(f_x)+FTYPE_size(f_x));
goto WriteMode;
case U2_XVAL_YFVAL:
HeapPush(H,Xb(BcP(f_x, 1)));
LoadHVA(t0,H);
if (CondStackvar(Yb(BcP(f_y, 2)))) {
TrailPushCheck(w->trail_top,TagSVA(&Yb(BcP(f_y, 2))));
Yb(BcP(f_y, 2)) = t0;
                  } else {
Yb(BcP(f_y, 2)) = t0;
                  }
P += (FTYPE_size(f_x)+FTYPE_size(f_y));
goto WriteMode;
case U2_XLVAL_YFVAL:
t1 = Xb(BcP(f_x, 1));
if (TagIsSVA(t1)) {
do {
RefSVA(t0,t1);
if (t0 == t1) {
BindSVA(t1,TagHVA(H));
PreLoadHVA(t1,H);
break;
                      }
} while (TagIsSVA(t1=t0));                    }
HeapPush(H,t1);
LoadHVA(t0,H);
if (CondStackvar(Yb(BcP(f_y, 2)))) {
TrailPushCheck(w->trail_top,TagSVA(&Yb(BcP(f_y, 2))));
Yb(BcP(f_y, 2)) = t0;
                    } else {
Yb(BcP(f_y, 2)) = t0;
                    }
P += (FTYPE_size(f_x)+FTYPE_size(f_y));
goto WriteMode;
case U2_XVAL_YVAL:
HeapPush(H,Xb(BcP(f_x, 1)));
HeapPushRefStack(H,&Yb(BcP(f_y, 2)));
P += (FTYPE_size(f_x)+FTYPE_size(f_y));
goto WriteMode;
case U2_XVAL_YLVAL:
HeapPush(H,Xb(BcP(f_x, 1)));
RefStack(t1,&Yb(BcP(f_y, 2)));
if (TagIsSVA(t1)) {
do {
RefSVA(t0,t1);
if (t0 == t1) {
BindSVA(t1,TagHVA(H));
PreLoadHVA(t1,H);
break;
                      }
} while (TagIsSVA(t1=t0));                    }
HeapPush(H,t1);
P += (FTYPE_size(f_x)+FTYPE_size(f_y));
goto WriteMode;
case U2_XLVAL_YVAL:
t1 = Xb(BcP(f_x, 1));
if (TagIsSVA(t1)) {
do {
RefSVA(t0,t1);
if (t0 == t1) {
BindSVA(t1,TagHVA(H));
PreLoadHVA(t1,H);
break;
                      }
} while (TagIsSVA(t1=t0));                    }
HeapPush(H,t1);
HeapPushRefStack(H,&Yb(BcP(f_y, 2)));
P += (FTYPE_size(f_x)+FTYPE_size(f_y));
goto WriteMode;
case U2_XLVAL_YLVAL:
t1 = Xb(BcP(f_x, 1));
if (TagIsSVA(t1)) {
do {
RefSVA(t0,t1);
if (t0 == t1) {
BindSVA(t1,TagHVA(H));
PreLoadHVA(t1,H);
break;
                      }
} while (TagIsSVA(t1=t0));                    }
HeapPush(H,t1);
RefStack(t1,&Yb(BcP(f_y, 2)));
if (TagIsSVA(t1)) {
do {
RefSVA(t0,t1);
if (t0 == t1) {
BindSVA(t1,TagHVA(H));
PreLoadHVA(t1,H);
break;
                        }
} while (TagIsSVA(t1=t0));                      }
HeapPush(H,t1);
P += (FTYPE_size(f_x)+FTYPE_size(f_y));
goto WriteMode;
case U2_YVAL_VOID:
HeapPushRefStack(H,&Yb(BcP(f_y, 1)));
i = (FTYPE_ctype(f_i_signed))BcP(f_i, 2);
do {
ConstrHVA(H);} while (--i);P += (FTYPE_size(f_y)+FTYPE_size(f_i));
goto WriteMode;
case U2_YLVAL_VOID:
RefStack(t1,&Yb(BcP(f_y, 1)));
if (TagIsSVA(t1)) {
do {
RefSVA(t0,t1);
if (t0 == t1) {
BindSVA(t1,TagHVA(H));
PreLoadHVA(t1,H);
break;
                      }
} while (TagIsSVA(t1=t0));                    }
HeapPush(H,t1);
i = (FTYPE_ctype(f_i_signed))BcP(f_i, 2);
do {
ConstrHVA(H);} while (--i);P += (FTYPE_size(f_y)+FTYPE_size(f_i));
goto WriteMode;
case U2_YVAL_XVAR:
HeapPushRefStack(H,&Yb(BcP(f_y, 1)));
LoadHVA(Xb(BcP(f_x, 2)),H);
P += (FTYPE_size(f_y)+FTYPE_size(f_x));
goto WriteMode;
case U2_YLVAL_XVAR:
RefStack(t1,&Yb(BcP(f_y, 1)));
if (TagIsSVA(t1)) {
do {
RefSVA(t0,t1);
if (t0 == t1) {
BindSVA(t1,TagHVA(H));
PreLoadHVA(t1,H);
break;
                      }
} while (TagIsSVA(t1=t0));                    }
HeapPush(H,t1);
LoadHVA(Xb(BcP(f_x, 2)),H);
P += (FTYPE_size(f_y)+FTYPE_size(f_x));
goto WriteMode;
case U2_YVAL_YVAR:
HeapPushRefStack(H,&Yb(BcP(f_y, 1)));
LoadHVA(Yb(BcP(f_y, 2)),H);
P += (FTYPE_size(f_y)+FTYPE_size(f_y));
goto WriteMode;
case U2_YLVAL_YVAR:
RefStack(t1,&Yb(BcP(f_y, 1)));
if (TagIsSVA(t1)) {
do {
RefSVA(t0,t1);
if (t0 == t1) {
BindSVA(t1,TagHVA(H));
PreLoadHVA(t1,H);
break;
                      }
} while (TagIsSVA(t1=t0));                    }
HeapPush(H,t1);
LoadHVA(Yb(BcP(f_y, 2)),H);
P += (FTYPE_size(f_y)+FTYPE_size(f_y));
goto WriteMode;
case U2_YVAL_YFVAL:
HeapPushRefStack(H,&Yb(BcP(f_y, 1)));
LoadHVA(t0,H);
if (CondStackvar(Yb(BcP(f_y, 2)))) {
TrailPushCheck(w->trail_top,TagSVA(&Yb(BcP(f_y, 2))));
Yb(BcP(f_y, 2)) = t0;
                  } else {
Yb(BcP(f_y, 2)) = t0;
                  }
P += (FTYPE_size(f_y)+FTYPE_size(f_y));
goto WriteMode;
case U2_YLVAL_YFVAL:
RefStack(t1,&Yb(BcP(f_y, 1)));
if (TagIsSVA(t1)) {
do {
RefSVA(t0,t1);
if (t0 == t1) {
BindSVA(t1,TagHVA(H));
PreLoadHVA(t1,H);
break;
                      }
} while (TagIsSVA(t1=t0));                    }
HeapPush(H,t1);
LoadHVA(t0,H);
if (CondStackvar(Yb(BcP(f_y, 2)))) {
TrailPushCheck(w->trail_top,TagSVA(&Yb(BcP(f_y, 2))));
Yb(BcP(f_y, 2)) = t0;
                    } else {
Yb(BcP(f_y, 2)) = t0;
                    }
P += (FTYPE_size(f_y)+FTYPE_size(f_y));
goto WriteMode;
case U2_YVAL_XVAL:
HeapPushRefStack(H,&Yb(BcP(f_y, 1)));
HeapPush(H,Xb(BcP(f_x, 2)));
P += (FTYPE_size(f_y)+FTYPE_size(f_x));
goto WriteMode;
case U2_YVAL_XLVAL:
HeapPushRefStack(H,&Yb(BcP(f_y, 1)));
t1 = Xb(BcP(f_x, 2));
if (TagIsSVA(t1)) {
do {
RefSVA(t0,t1);
if (t0 == t1) {
BindSVA(t1,TagHVA(H));
PreLoadHVA(t1,H);
break;
                      }
} while (TagIsSVA(t1=t0));                    }
HeapPush(H,t1);
P += (FTYPE_size(f_y)+FTYPE_size(f_x));
goto WriteMode;
case U2_YLVAL_XVAL:
RefStack(t1,&Yb(BcP(f_y, 1)));
if (TagIsSVA(t1)) {
do {
RefSVA(t0,t1);
if (t0 == t1) {
BindSVA(t1,TagHVA(H));
PreLoadHVA(t1,H);
break;
                      }
} while (TagIsSVA(t1=t0));                    }
HeapPush(H,t1);
HeapPush(H,Xb(BcP(f_x, 2)));
P += (FTYPE_size(f_y)+FTYPE_size(f_x));
goto WriteMode;
case U2_YLVAL_XLVAL:
RefStack(t1,&Yb(BcP(f_y, 1)));
if (TagIsSVA(t1)) {
do {
RefSVA(t0,t1);
if (t0 == t1) {
BindSVA(t1,TagHVA(H));
PreLoadHVA(t1,H);
break;
                      }
} while (TagIsSVA(t1=t0));                    }
HeapPush(H,t1);
t1 = Xb(BcP(f_x, 2));
if (TagIsSVA(t1)) {
do {
RefSVA(t0,t1);
if (t0 == t1) {
BindSVA(t1,TagHVA(H));
PreLoadHVA(t1,H);
break;
                        }
} while (TagIsSVA(t1=t0));                      }
HeapPush(H,t1);
P += (FTYPE_size(f_y)+FTYPE_size(f_x));
goto WriteMode;
case U2_YVAL_YVAL:
HeapPushRefStack(H,&Yb(BcP(f_y, 1)));
HeapPushRefStack(H,&Yb(BcP(f_y, 2)));
P += (FTYPE_size(f_y)+FTYPE_size(f_y));
goto WriteMode;
case U2_YVAL_YLVAL:
HeapPushRefStack(H,&Yb(BcP(f_y, 1)));
RefStack(t1,&Yb(BcP(f_y, 2)));
if (TagIsSVA(t1)) {
do {
RefSVA(t0,t1);
if (t0 == t1) {
BindSVA(t1,TagHVA(H));
PreLoadHVA(t1,H);
break;
                      }
} while (TagIsSVA(t1=t0));                    }
HeapPush(H,t1);
P += (FTYPE_size(f_y)+FTYPE_size(f_y));
goto WriteMode;
case U2_YLVAL_YVAL:
RefStack(t1,&Yb(BcP(f_y, 1)));
if (TagIsSVA(t1)) {
do {
RefSVA(t0,t1);
if (t0 == t1) {
BindSVA(t1,TagHVA(H));
PreLoadHVA(t1,H);
break;
                      }
} while (TagIsSVA(t1=t0));                    }
HeapPush(H,t1);
HeapPushRefStack(H,&Yb(BcP(f_y, 2)));
P += (FTYPE_size(f_y)+FTYPE_size(f_y));
goto WriteMode;
case U2_YLVAL_YLVAL:
RefStack(t1,&Yb(BcP(f_y, 1)));
if (TagIsSVA(t1)) {
do {
RefSVA(t0,t1);
if (t0 == t1) {
BindSVA(t1,TagHVA(H));
PreLoadHVA(t1,H);
break;
                      }
} while (TagIsSVA(t1=t0));                    }
HeapPush(H,t1);
RefStack(t1,&Yb(BcP(f_y, 2)));
if (TagIsSVA(t1)) {
do {
RefSVA(t0,t1);
if (t0 == t1) {
BindSVA(t1,TagHVA(H));
PreLoadHVA(t1,H);
break;
                        }
} while (TagIsSVA(t1=t0));                      }
HeapPush(H,t1);
P += (FTYPE_size(f_y)+FTYPE_size(f_y));
goto WriteMode;
case BUMP_COUNTERQ:
P += FTYPE_size(f_Q);
goto w_bump_counter;
w_bump_counter:
case BUMP_COUNTER:
#if defined(GAUGE)
INCR_COUNTER(BcP(f_l, 1));
#endif
P += FTYPE_size(f_l);
goto WriteMode;
case COUNTED_NECKQ:
P += FTYPE_size(f_Q);
goto w_counted_neck;
w_counted_neck:
case COUNTED_NECK:
#if defined(GAUGE)
if (w->next_alt) {
SetB(w->node);
if (B->next_alt) {
#if defined(GAUGE)
INCR_COUNTER(BcP(f_l, 1));
#endif
                    } else {
#if defined(GAUGE)
INCR_COUNTER(BcP(f_l, 3));
#endif
                    }
                  }
#endif
P += (FTYPE_size(f_l)+FTYPE_size(f_l));
goto w_neck;
case FAIL:
goto fail;
case HEAPMARGIN_CALLQ:
P += FTYPE_size(f_Q);
goto w_heapmargin_call;
w_heapmargin_call:
case HEAPMARGIN_CALL:
if (HeapDifference(H,Heap_End) < (intmach_t)BcP(f_l, 1)) {
StoreH;
explicit_heap_overflow(Arg,(intmach_t)BcP(f_l, 1),(FTYPE_ctype(f_i_signed))BcP(f_i, 3));
LoadH;
t0 = X(0);
                  }
P += FTYPE_size(f_l)+FTYPE_size(f_i);
goto WriteMode;
w_neck:
case NECK:
if (w->next_alt) {
SetB(w->node);
if (B->next_alt) {
B->next_alt = w->next_alt;
                    } else {
B->next_alt = w->next_alt; /* 4 contiguous moves */
B->frame = w->frame;
B->next_insn = w->next_insn;
SaveLtop(B);
i=B->next_alt->node_offset;
if (i>ArityToOffset(0)) {
i = OffsetToArity(i);
SetB(w->next_node);
ON_DEBUG({
if (debug_choicepoints) {
fprintf(stderr, "Storing %d registers (r) in node %x\n", i, (int)w->next_node);
                        }
});
do {
ChoicePush(pt1,(w->term-1)[i]);} while (--i);                        }
if (ChoiceYounger(ChoiceOffset(B,CHOICEPAD),w->trail_top)) {
choice_overflow(Arg,CHOICEPAD);
                        }
                      }
w->next_alt = NULL;
SetE(w->local_top);
                    }
P += 0;
goto WriteMode;
w_dynamic_neck_proceed:
case DYNAMIC_NECK_PROCEED:
t1 = X(3);
if (t1&TagBitSVA) {
BindSVA(t1,PointerToTerm(ins));
                  } else {
BindHVA(t1,PointerToTerm(ins));
                  }
if (!w->next_alt) {
goto w_proceed;
                  }
SetB(w->node);
if (!B->next_alt && (def_clock = use_clock+1)==0xffff) {
StoreH;
clock_overflow(Arg);
LoadH;
                  }
goto w_neck_proceed;
w_neck_proceed:
case NECK_PROCEED:
if (w->next_alt) {
SetB(w->node);
if (B->next_alt) {
B->next_alt = w->next_alt;
                    } else {
B->next_alt = w->next_alt; /* 4 contiguous moves */
B->frame = w->frame;
B->next_insn = w->next_insn;
SaveLtop(B);
i=B->next_alt->node_offset;
if (i>ArityToOffset(0)) {
i = OffsetToArity(i);
SetB(w->next_node);
ON_DEBUG({
if (debug_choicepoints) {
fprintf(stderr, "Storing %d registers (r) in node %x\n", i, (int)w->next_node);
                        }
});
do {
ChoicePush(pt1,(w->term-1)[i]);} while (--i);                        }
if (ChoiceYounger(ChoiceOffset(B,CHOICEPAD),w->trail_top)) {
choice_overflow(Arg,CHOICEPAD);
                        }
                      }
w->next_alt = NULL;
                    } else {
w->local_top = 0;
                    }
SetE(w->frame);
P = w->next_insn;
PROFILE__HOOK_NECK_PROCEED;
goto WriteMode;
w_proceed:
case PROCEED:
w->local_top = 0;
SetE(w->frame);
P = w->next_insn;
PROFILE__HOOK_PROCEED;
P += 0;
goto WriteMode;
#if defined(PARBACK)
case RESTART_POINT:
w->global_top = TagToPointer(w->node->term[0]);
LoadH;
P = (bcp_t)*TagToPointer(w->node->term[0]);
w->next_insn = w->node->next_insn;
pop_choicept(Arg);
goto enter_predicate;
#endif
default:
goto illop;
}exit_toplevel:
w->insn = P;
if (desc && (desc->action & KEEP_STACKS)) {
SAVE_WAM_STATE;
                  }
if (Stop_This_Goal(Arg)) {
wam_exit_code = WAM_INTERRUPTED;
                  }
ON_DEBUG({
});
return wam_exit_code;illop:
SERIOUS_FAULT("unimplemented WAM instruction");
}
