/***************************************************************************/
/*                             WARNING!!!                                  */
/*                      D O   N O T   M O D I F Y                          */
/*                This file is autogenerated by emugen                     */
/***************************************************************************/

extern instance_clock_t def_clock;
extern instance_clock_t use_clock;
#define BcOPCODE BcFetchOPCODE()
#define BcP(Ty,X) ((*(FTYPE_ctype(Ty) *)BCoff(P,(X))))
#define Fs(Ty) FTYPE_size(Ty)
CVOID__PROTO(wam__2,goal_descriptor_t * desc,definition_t * start_func);
CVOID__PROTO(wam,goal_descriptor_t * desc) {
definition_t * func = (definition_t *)NULL;
goto again;
again:
{
EXCEPTION__CATCH({
CVOID__CALL(wam__2, desc, func);
return;
}
, {
choice_t * b;
if (!IsDeep()) {
B = w->choice;
if (!IsShallowTry()) {
NECK_RETRY_PATCH(B);
    }
 else {
B->next_alt = w->next_alt;
B->frame = w->frame;
B->next_insn = w->next_insn;
B->local_top = w->local_top;
intmach_t vr0 = ChoiceArity(B);
for (intmach_t vr1 = 0;
vr1<vr0;vr1++) {
B->x[vr1] = w->x[vr1];
      }

if (ChoiceYounger(ChoiceOffset(B,CHOICEPAD),w->trail_top)) {
choice_overflow(w,2*CHOICEPAD*sizeof(tagged_t),TRUE);
      }

    }

SetDeep();
  }

X(0) = MakeSmall(ErrCode);
X(1) = GET_ATOM(ErrFuncName);
X(2) = MakeSmall(ErrFuncArity);
X(4) = Culprit;
X(3) = MakeSmall(ErrArgNo);
func = address_error;
goto again;
}
);
}
}
CVOID__PROTO(wam__2,goal_descriptor_t * desc,definition_t * start_func) {
bcp_t p;
try_node_t * alts;
choice_t * b;
frame_t * e;
tagged_t * cached_r_h;
tagged_t * r_s;
intmach_t ei;
bcp_t ptemp = NULL;
alts = NULL;
b = NULL;
e = NULL;
cached_r_h = NULL;
r_s = NULL;
ei = ~0;
ON_DEBUG({
if (debug_threads) {
fprintf(stderr,"Worker state address is %p\n",desc);
    }

  }
);
if (start_func!=NULL) {
P = (bcp_t)start_func;
B = w->choice;
H = w->heap_top;
goto switch_on_pred;
  }

if (desc!=NULL&&desc->action&BACKTRACKING) {
RECOVER_WAM_STATE;
goto fail;
  }

goto r_op64;
escape_to_p2:
{
tagged_t vr2;
tagged_t vr3;
vr2 = PointerToTerm(Func->code.intinfo);
if (Func->arity==0) {
vr3 = Func->printname;
  }
 else {
vr3 = Tagp(STR,H);
HeapPush(H,SetArity(Func->printname,Func->arity));
for (intmach_t vr4 = 0;
vr4<Func->arity;vr4++) {
tagged_t vr5 = X(vr4);
if (TaggedIsSVA(vr5)) {
tagged_t vr6;
do {
RefSVA(vr6,vr5);
if (vr6==vr5) {
BindSVA(vr5,Tagp(HVA,H));
PreLoadHVA(vr5,H);
break;
          }

vr5 = vr6;
        }
 while (TaggedIsSVA(vr5));
      }

HeapPush(H,vr5);
    }

  }

P = ptemp;
X(0) = vr3;
X(1) = vr2;
goto switch_on_pred;
  }
escape_to_p:
{
tagged_t vr7;
if (Func->arity==0) {
vr7 = Func->printname;
  }
 else {
vr7 = Tagp(STR,H);
HeapPush(H,SetArity(Func->printname,Func->arity));
for (intmach_t vr8 = 0;
vr8<Func->arity;vr8++) {
tagged_t vr9 = X(vr8);
if (TaggedIsSVA(vr9)) {
tagged_t vr10;
do {
RefSVA(vr10,vr9);
if (vr10==vr9) {
BindSVA(vr9,Tagp(HVA,H));
PreLoadHVA(vr9,H);
break;
          }

vr9 = vr10;
        }
 while (TaggedIsSVA(vr9));
      }

HeapPush(H,vr9);
    }

  }

P = ptemp;
X(0) = vr7;
goto switch_on_pred;
  }
enter_predicate:
{
ON_ANDPARALLEL({
if (Suspend==TOSUSPEND) {
Suspend = SUSPENDED;
Wait_Acquire_lock(Waiting_For_Work_Lock);
Cond_Var_Wait(Waiting_For_Work_Cond_Var,Waiting_For_Work_Lock);
Suspend = RELEASED;
Release_lock(Waiting_For_Work_Lock);
    }

  }
);
if (TestEventOrHeapWarnOverflow(H)) {
int wake_cnt;
if (Stop_This_Goal(w)) {
goto exit_toplevel;
    }

wake_cnt = WakeCount();
if (HeapCharAvailable(H)<=CALLPAD+4*wake_cnt*sizeof(tagged_t)) {
SETUP_PENDING_CALL(E,address_true);
w->heap_top = H;
heap_overflow(w,2*(CALLPAD+4*wake_cnt*sizeof(tagged_t)));
H = w->heap_top;
    }

if (wake_cnt>0) {
if (wake_cnt==1) {
SETUP_PENDING_CALL(E,address_uvc);
collect_one_pending_unification(w);
tagged_t vr11;
DEREF(vr11,X(1));
if (TaggedIsCVA(vr11)) {
X(1) = vr11;
Setfunc(address_ucc);
        }

      }
 else {
SETUP_PENDING_CALL(E,address_pending_unifications);
w->heap_top = H;
collect_pending_unifications(w,wake_cnt);
H = w->heap_top;
      }

    }

if (OffStacktop(w->frame,Stack_Warn)) {
SETUP_PENDING_CALL(E,address_true);
stack_overflow(w);
    }

UnsetEvent();
if (TestCIntEvent()) {
SETUP_PENDING_CALL(E,address_help);
control_c_normal(w);
    }

  }

goto switch_on_pred;
  }
switch_on_pred:
ei = Func->enter_instr;
goto switch_on_pred_sub;
switch_on_pred_sub:
{
switch (ei) {
case ENTER_FASTCODE_INDEXED:
goto enter_undefined;
case ENTER_FASTCODE:
goto enter_undefined;
case ENTER_UNDEFINED:
enter_undefined:
PRED_HOOK("U",Func);
ptemp = (bcp_t)address_undefined_goal;
goto escape_to_p;
case ENTER_INTERPRETED:
ptemp = (bcp_t)address_interpret_c_goal;
goto escape_to_p2;
case ENTER_C:
{
PRED_HOOK("C",Func);
w->heap_top = H;
intmach_t vr12 = ((cbool0_t)Func->code.proc)(w);
if (Expanded_Worker!=NULL) {
ON_DEBUG({
fprintf(stderr,"wam() detected worker expanded by C predicate\n");
      }
);
if (desc==NULL) {
fprintf(stderr,"bug: invalid WAM expansion\n");
abort();
      }

w = Expanded_Worker;
desc->worker_registers = w;
Expanded_Worker = NULL;
    }

if (vr12) {
goto r_op64;
    }
 else {
goto fail;
    }

    }
case BUILTIN_TRUE:
PRED_HOOK("B",Func);
goto w_op64;
case BUILTIN_FAIL:
PRED_HOOK("B",Func);
goto fail;
case BUILTIN_CURRENT_INSTANCE:
PRED_HOOK("B",Func);
w->heap_top = H;
w->misc->ins = CFUN__EVAL(current_instance0);
if (w->misc->ins==NULL) {
goto fail;
    }

P = (bcp_t)w->misc->ins->emulcode;
goto r_dispatch;
case BUILTIN_COMPILE_TERM:
{
PRED_HOOK("B",Func);
w->heap_top = H;
{worker_t * vr13;
if (!compile_term(w,&vr13)) {
goto fail;
    }

if (vr13!=NULL) {
if (desc==NULL) {
fprintf(stderr,"bug: invalid WAM expansion\n");
abort();
      }

w = vr13;
desc->worker_registers = w;
ON_DEBUG({
fprintf(stderr,"Reallocation of wrb detected in wam()\n");
      }
);
    }

}goto r_op64;
    }
case BUILTIN_INSTANCE:
PRED_HOOK("B",Func);
LoadHVA(X(3),H);
w->misc->ins = TaggedToInstance(X(2));
P = (bcp_t)w->misc->ins->emulcode;
goto w_dispatch;
case BUILTIN_GELER:
{
PRED_HOOK("B",Func);
tagged_t vr14 = X(0);
DerefSw_HVAorCVAorSVA_Other(vr14,{
;    }
,{
;    }
);
tagged_t vr15 = X(1);
DerefSw_HVAorCVAorSVA_Other(vr15,{
;    }
,{
;    }
);
Setfunc(find_definition(predicates_location,vr15,&w->structure,TRUE));
w->heap_top = H;
CVOID__CALL(SUSPEND_T3_ON_T1,Func,vr15,vr14);
H = w->heap_top;
goto w_op64;
    }
case BUILTIN_NODEBUGCALL:
{
PRED_HOOK("B",Func);
DerefSw_HVAorCVAorSVA_Other(X(0),{
;    }
,{
;    }
);
tagged_t vr16 = X(0);
Setfunc(find_definition(predicates_location,vr16,&w->structure,FALSE));
if (Func==NULL) {
goto fail;
    }

ei = Func->enter_instr;
goto call4;
    }
case BUILTIN_SYSCALL:
{
PRED_HOOK("B",Func);
DerefSw_HVAorCVAorSVA_Other(X(0),{
;    }
,{
;    }
);
tagged_t vr17 = X(0);
Setfunc(find_definition(predicates_location,vr17,&w->structure,FALSE));
if (Func==NULL) {
Setfunc(address_undefined_goal);
goto switch_on_pred;
    }

ei = Func->enter_instr;
goto call4;
    }
call4:
{
switch (ei) {
case ENTER_INTERPRETED:
X(1) = PointerToTerm(Func->code.intinfo);
Setfunc(address_interpret_goal);
goto switch_on_pred;
case BUILTIN_DIF:
{
PRED_HOOK("B",Func);
tagged_t * vr18 = w->structure;
tagged_t vr19;
RefHeapNext(vr19,vr18);
X(0) = vr19;
tagged_t vr20;
RefHeapNext(vr20,vr18);
X(1) = vr20;
goto dif0;
      }
case SPYPOINT:
if (!Func->properties.wait) {
goto call5;
      }

goto call_waitpoint;
case WAITPOINT:
{
call_waitpoint:
{
tagged_t vr21;
RefHeap(vr21,w->structure);
DerefSw_HVAorCVAorSVA_Other(vr21,{
tagged_t vr22;
vr22 = X(0);
w->heap_top = H;
CVOID__CALL(SUSPEND_T3_ON_T1,Func,vr22,vr21);
H = w->heap_top;
goto w_op64;
      }
,{
;      }
);
goto call5;
      }
      }
call5:
ei = Func->predtyp;
goto call4;
default:
{
intmach_t vr23 = Func->arity;
if (vr23!=0) {
tagged_t * vr24 = w->x;
tagged_t * vr25 = w->structure;
do {
PushRefHeapNext(vr24,vr25);
        }
 while (--vr23);
      }

goto switch_on_pred_sub;
      }
    }
    }
case BUILTIN_CALL:
{
PRED_HOOK("B",Func);
DerefSw_HVAorCVAorSVA_Other(X(0),{
;    }
,{
;    }
);
tagged_t vr26 = X(0);
Setfunc(find_definition(predicates_location,vr26,&w->structure,FALSE));
if (Func==NULL) {
Setfunc(address_undefined_goal);
goto switch_on_pred;
    }

if (Current_Debugger_Mode!=atom_off) {
Setfunc(address_trace);
goto switch_on_pred;
    }

ei = Func->enter_instr;
goto call4;
    }
case BUILTIN_DIF:
{
dif0:
{
PRED_HOOK("B",Func);
tagged_t vr27 = X(0);
DerefSw_HVAorCVAorSVA_Other(vr27,{
;    }
,{
;    }
);
tagged_t vr28 = X(1);
DerefSw_HVAorCVAorSVA_Other(vr28,{
;    }
,{
;    }
);
w->structure = NULL;
if (vr27==vr28) {
goto fail;
    }
 else if (!IsVar(vr27&vr28)&&(IsAtomic(vr27)||IsAtomic(vr28))) {
goto w_op64;
    }
 else {
X(0) = vr27;
X(1) = vr28;
w->heap_top = H;
if (!prolog_dif(w,Func)) {
goto fail;
      }

goto r_op64;
    }

    }
    }
case BUILTIN_ABORT:
{
PRED_HOOK("B",Func);
tagged_t vr29 = X(0);
DerefSw_HVAorCVAorSVA_Other(vr29,{
;    }
,{
;    }
);
w->misc->exit_code = GetSmall(vr29);
w->previous_choice = InitialChoice;
PROFILE__HOOK_CUT;
B = w->previous_choice;
SetChoice(B);
TRACE_CHPT_CUT(w->choice);
ConcChptCleanUp(TopConcChpt,w->choice);
goto fail;
    }
case SPYPOINT:
if (Current_Debugger_Mode!=atom_off) {
ptemp = (bcp_t)address_trace;
goto escape_to_p;
    }

if (!Func->properties.wait) {
goto nowait;
    }

goto waitpoint;
case WAITPOINT:
{
waitpoint:
{
DerefSw_HVAorCVAorSVA_Other(X(0),{
tagged_t vr30;
tagged_t vr31;
if (Func->arity==0) {
vr30 = Func->printname;
      }
 else {
vr30 = Tagp(STR,H);
HeapPush(H,SetArity(Func->printname,Func->arity));
for (intmach_t vr32 = 0;
vr32<Func->arity;vr32++) {
tagged_t vr33 = X(vr32);
if (TaggedIsSVA(vr33)) {
tagged_t vr34;
do {
RefSVA(vr34,vr33);
if (vr34==vr33) {
BindSVA(vr33,Tagp(HVA,H));
PreLoadHVA(vr33,H);
break;
              }

vr33 = vr34;
            }
 while (TaggedIsSVA(vr33));
          }

HeapPush(H,vr33);
        }

      }

vr31 = X(0);
if (TaggedIsSVA(vr31)) {
RefSVA(vr31,X(0));
      }

w->heap_top = H;
CVOID__CALL(SUSPEND_T3_ON_T1,Func,vr30,vr31);
H = w->heap_top;
goto w_op64;
    }
,{
;    }
);
goto nowait;
nowait:
ei = Func->predtyp;
goto switch_on_pred_sub;
    }
    }
case BREAKPOINT:
ei = Func->predtyp;
goto switch_on_pred_sub;
case ENTER_PROFILEDCODE_INDEXED:
goto enter_compactcode_indexed;
case ENTER_COMPACTCODE_INDEXED:
{
enter_compactcode_indexed:
{
PRED_HOOK("E",Func);
DerefSw_HVAorCVAorSVA_Other(X(0),{
alts = Func->code.incoreinfo->varcase;
goto w_tryeach;
    }
,{
;    }
);
tagged_t vr35 = X(0);
tagged_t vr36;
w->heap_top = H;
if (vr35&TagBitComplex) {
if (vr35&TagBitFunctor) {
S = TaggedToArg(vr35,0);
vr36 = HeapNext(S);
      }
 else {
S = TagpPtr(LST,vr35);
alts = Func->code.incoreinfo->lstcase;
goto r_tryeach;
      }

    }
 else {
vr36 = vr35;
    }

intmach_t vr37;
sw_on_key_t * Htab = Func->code.incoreinfo->othercase;
vr37 = 0;
tagged_t vr38;
vr38 = vr36;
vr36&=Htab->mask;
sw_on_key_node_t * HtabNode;
do {
HtabNode = SW_ON_KEY_NODE_FROM_OFFSET(Htab,vr36);
if (HtabNode->key==vr38||!HtabNode->key) {
break;
      }

vr37+=sizeof(sw_on_key_node_t);
vr36 = (vr36+vr37)&Htab->mask;
    }
 while (TRUE);
alts = HtabNode->value.try_chain;
goto r_tryeach;
    }
    }
case ENTER_PROFILEDCODE:
goto enter_compactcode;
case ENTER_COMPACTCODE:
enter_compactcode:
PRED_HOOK("E",Func);
alts = Func->code.incoreinfo->varcase;
goto w_tryeach;
  }
  }
fail:
{
PROFILE__HOOK_FAIL;
ON_DEBUG({
if (debug_choicepoints) {
fprintf(stderr,"Failing: node = %p, previous_choice = %p, conc. node = %p\n",w->choice,w->previous_choice,TopConcChpt);
    }

if (w->misc->top_conc_chpt<w->choice&&w->misc->top_conc_chpt<w->previous_choice) {
fprintf(stderr,"********** what happened here?\n");
    }

  }
);
ResetWakeCount();
B = w->choice;
ON_TABLING({
MAKE_TRAIL_CACTUS_STACK;  }
);
{tagged_t vr39;
tagged_t vr40;
tagged_t * vr41;
vr41 = w->trail_top;
vr40 = (tagged_t)TrailTopUnmark(B->trail_top);
if (TrailYounger(vr41,vr40)) {
do {
PlainUntrail(vr41,vr39,{
w->trail_top = vr41;
w->frame = B->frame;
w->next_insn = B->next_insn;
SetE(NodeLocalTop(B));
E->frame = w->frame;
E->next_insn = w->next_insn;
w->frame = E;
w->next_insn = failcode;
w->local_top = (frame_t *)Offset(E,EToY0);
H = w->heap_top;
X(0) = vr39;
Setfunc(find_definition(predicates_location,vr39,&w->structure,FALSE));
if (Func==NULL) {
Setfunc(address_undefined_goal);
goto switch_on_pred;
        }

ei = Func->enter_instr;
goto call4;
      }
);
    }
 while (TrailYounger(vr41,vr40));
w->trail_top = vr41;
  }

}w->heap_top = NodeGlobalTop(B);
if (IsDeep()) {
ON_DEBUG({
if (debug_choicepoints) {
fprintf(stderr,"deep backtracking, node = %p\n",w->choice);
      }

    }
);
w->frame = B->frame;
w->next_insn = B->next_insn;
w->next_alt = B->next_alt;
w->local_top = NodeLocalTop(B);
intmach_t vr42 = B->next_alt->arity;
w->previous_choice = ChoiceCont0(B,vr42);
SetShallowRetry();
for (intmach_t vr43 = 0;
vr43<vr42;vr43++) {
w->x[vr43] = B->x[vr43];
    }

  }

PROFILE__HOOK_REDO;
P = (bcp_t)w->next_alt;
try_node_t * vr44;
vr44 = ((try_node_t *)P)->next;
if (vr44==NULL) {
SetDeep();
B = w->previous_choice;
SetChoice(B);
ON_TABLING({
if (FrozenChpt(B)) {
push_choicept(w,address_nd_fake_choicept);
      }

    }
);
P = ((try_node_t *)P)->emul_p;
if (!IsVar(X(0))) {
goto r_dispatch;
    }

H = w->heap_top;
goto w_dispatch;
  }
 else {
CODE_CHOICE_PATCH(w->choice,vr44);
P = ((try_node_t *)P)->emul_p;
if (!IsVar(X(0))) {
goto r_dispatch;
    }

H = w->heap_top;
goto w_dispatch;
  }

  }
r_tryeach:
{
#if defined(GAUGE)
INCR_COUNTER(alts->entry_counter+1);
#endif
P = alts->emul_p2;
w->previous_choice = w->choice;
try_node_t * vr45 = alts->next;
if (vr45!=NULL) {
B = w->choice;
GetFrameTop(w->local_top,B,G->frame);
CODE_CHOICE_NEW0(B,vr45,w->heap_top);
ON_DEBUG({
if (debug_choicepoints) {
fprintf(stderr,"WAM created choicepoint (r), node = %p\n",w->choice);
      }

    }
);
if (ChoiceYounger(ChoiceOffset(B,CHOICEPAD),w->trail_top)) {
choice_overflow(w,2*CHOICEPAD*sizeof(tagged_t),TRUE);
    }

  }
 else {
SetDeep();
  }

goto r_dispatch;
  }
r_dispatch:
{
switch (BcOPCODE) {
case 260:
H = w->heap_top;
goto w_op260;
case 261:
H = w->heap_top;
goto w_op261;
case 0:
P+=Fs(f_Q);
goto r_op1;
case 1:
r_op1:
H = w->heap_top;
goto w_op1;
case 20:
P+=Fs(f_Q);
goto r_op21;
case 21:
r_op21:
H = w->heap_top;
goto w_op21;
case 18:
P+=Fs(f_Q);
goto r_op19;
case 19:
r_op19:
H = w->heap_top;
goto w_op19;
case 16:
P+=Fs(f_Q);
goto r_op17;
case 17:
r_op17:
H = w->heap_top;
goto w_op17;
case 14:
P+=Fs(f_Q);
goto r_op15;
case 15:
r_op15:
H = w->heap_top;
goto w_op15;
case 12:
P+=Fs(f_Q);
goto r_op13;
case 13:
r_op13:
H = w->heap_top;
goto w_op13;
case 10:
P+=Fs(f_Q);
goto r_op11;
case 11:
r_op11:
H = w->heap_top;
goto w_op11;
case 8:
P+=Fs(f_Q);
goto r_op9;
case 9:
r_op9:
H = w->heap_top;
goto w_op9;
case 6:
P+=Fs(f_Q);
goto r_op7;
case 7:
r_op7:
H = w->heap_top;
goto w_op7;
case 4:
P+=Fs(f_Q);
goto r_op5;
case 5:
r_op5:
H = w->heap_top;
goto w_op5;
case 2:
P+=Fs(f_Q);
goto r_op3;
case 3:
r_op3:
H = w->heap_top;
goto w_op3;
case 40:
P+=Fs(f_Q);
goto r_op41;
case 41:
r_op41:
H = w->heap_top;
goto w_op41;
case 38:
P+=Fs(f_Q);
goto r_op39;
case 39:
r_op39:
H = w->heap_top;
goto w_op39;
case 36:
P+=Fs(f_Q);
goto r_op37;
case 37:
r_op37:
H = w->heap_top;
goto w_op37;
case 34:
P+=Fs(f_Q);
goto r_op35;
case 35:
r_op35:
H = w->heap_top;
goto w_op35;
case 32:
P+=Fs(f_Q);
goto r_op33;
case 33:
r_op33:
H = w->heap_top;
goto w_op33;
case 30:
P+=Fs(f_Q);
goto r_op31;
case 31:
r_op31:
H = w->heap_top;
goto w_op31;
case 28:
P+=Fs(f_Q);
goto r_op29;
case 29:
r_op29:
H = w->heap_top;
goto w_op29;
case 26:
P+=Fs(f_Q);
goto r_op27;
case 27:
r_op27:
H = w->heap_top;
goto w_op27;
case 24:
P+=Fs(f_Q);
goto r_op25;
case 25:
r_op25:
H = w->heap_top;
goto w_op25;
case 22:
P+=Fs(f_Q);
goto r_op23;
case 23:
r_op23:
H = w->heap_top;
goto w_op23;
case 60:
P+=Fs(f_Q);
goto r_op61;
case 61:
r_op61:
H = w->heap_top;
goto w_op61;
case 58:
P+=Fs(f_Q);
goto r_op59;
case 59:
r_op59:
H = w->heap_top;
goto w_op59;
case 56:
P+=Fs(f_Q);
goto r_op57;
case 57:
r_op57:
H = w->heap_top;
goto w_op57;
case 54:
P+=Fs(f_Q);
goto r_op55;
case 55:
r_op55:
H = w->heap_top;
goto w_op55;
case 52:
P+=Fs(f_Q);
goto r_op53;
case 53:
r_op53:
H = w->heap_top;
goto w_op53;
case 50:
P+=Fs(f_Q);
goto r_op51;
case 51:
r_op51:
H = w->heap_top;
goto w_op51;
case 48:
P+=Fs(f_Q);
goto r_op49;
case 49:
r_op49:
H = w->heap_top;
goto w_op49;
case 46:
P+=Fs(f_Q);
goto r_op47;
case 47:
r_op47:
H = w->heap_top;
goto w_op47;
case 44:
P+=Fs(f_Q);
goto r_op45;
case 45:
r_op45:
H = w->heap_top;
goto w_op45;
case 42:
P+=Fs(f_Q);
goto r_op43;
case 43:
r_op43:
H = w->heap_top;
goto w_op43;
case 62:
H = w->heap_top;
P = BcP(f_p,0+Fs(f_Q));
goto enter_predicate;
case 63:
H = w->heap_top;
P = BcP(f_p,0);
goto enter_predicate;
case 69:
H = w->heap_top;
goto w_op69;
case 70:
H = w->heap_top;
goto w_op70;
case 85:
Xb(BcP(f_x,0)) = Xb(BcP(f_x,0+Fs(f_x)));
Xb(BcP(f_x,0+Fs(f_x)+Fs(f_x))) = Xb(BcP(f_x,0+Fs(f_x)+Fs(f_x)+Fs(f_x)));
P+=Fs(f_x)+Fs(f_x)+Fs(f_x)+Fs(f_x);
goto r_dispatch;
case 71:
Xb(BcP(f_x,0)) = Xb(BcP(f_x,0+Fs(f_x)));
P+=Fs(f_x)+Fs(f_x);
goto r_dispatch;
case 72:
H = w->heap_top;
goto w_op72;
case 73:
H = w->heap_top;
goto w_op73;
case 74:
H = w->heap_top;
goto w_op74;
case 83:
H = w->heap_top;
goto w_op83;
case 84:
H = w->heap_top;
goto w_op84;
case 75:
Xb(BcP(f_x,0)) = Yb(BcP(f_y,0+Fs(f_x)));
P+=Fs(f_x)+Fs(f_y);
goto r_dispatch;
case 76:
H = w->heap_top;
goto w_op76;
case 77:
Xb(BcP(f_x,0+Fs(f_Q))) = BcP(f_t,0+Fs(f_Q)+Fs(f_x));
P+=Fs(f_Q)+Fs(f_x)+Fs(f_t);
goto r_dispatch;
case 78:
Xb(BcP(f_x,0)) = BcP(f_t,0+Fs(f_x));
P+=Fs(f_x)+Fs(f_t);
goto r_dispatch;
case 81:
Xb(BcP(f_x,0)) = atom_nil;
P+=Fs(f_x);
goto r_dispatch;
case 252:
H = w->heap_top;
goto w_op252;
case 253:
H = w->heap_top;
goto w_op253;
case 79:
H = w->heap_top;
goto w_op79;
case 80:
H = w->heap_top;
goto w_op80;
case 82:
H = w->heap_top;
goto w_op82;
case 86:
Xb(BcP(f_x,0)) = Yb(BcP(f_y,0+Fs(f_x)));
Xb(BcP(f_x,0+Fs(f_x)+Fs(f_y))) = Yb(BcP(f_y,0+Fs(f_x)+Fs(f_y)+Fs(f_x)));
P+=Fs(f_x)+Fs(f_y)+Fs(f_x)+Fs(f_y);
goto r_dispatch;
case 87:
H = w->heap_top;
goto w_op87;
case 88:
H = w->heap_top;
goto w_op88;
case 89:
H = w->heap_top;
goto w_op89;
case 91:
r_op91:
if (!CBOOL__SUCCEED(cunify,Xb(BcP(f_x,0)),Xb(BcP(f_x,0+Fs(f_x))))) {
goto fail;
    }

P+=Fs(f_x)+Fs(f_x);
goto r_dispatch;
case 94:
r_op94:
if (CondStackvar(Yb(BcP(f_y,0+Fs(f_x))))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0+Fs(f_x)))));
    }

Yb(BcP(f_y,0+Fs(f_x))) = Xb(BcP(f_x,0));
P+=Fs(f_x)+Fs(f_y);
goto r_dispatch;
case 95:
r_op95:
if (!CBOOL__SUCCEED(cunify,Xb(BcP(f_x,0)),Yb(BcP(f_y,0+Fs(f_x))))) {
goto fail;
    }

P+=Fs(f_x)+Fs(f_y);
goto r_dispatch;
case 96:
P+=Fs(f_Q);
goto r_op97;
case 97:
{
r_op97:
{
tagged_t vr46 = Xb(BcP(f_x,0));
DerefSw_HVA_CVA_SVA_Other(vr46,{
BindHVA(vr46,BcP(f_t,0+Fs(f_x)));
    }
,{
BindCVA(vr46,BcP(f_t,0+Fs(f_x)));
    }
,{
BindSVA(vr46,BcP(f_t,0+Fs(f_x)));
    }
,{
if (vr46!=BcP(f_t,0+Fs(f_x))) {
goto fail;
      }

    }
);
P+=Fs(f_x)+Fs(f_t);
goto r_dispatch;
    }
    }
case 254:
P+=Fs(f_Q);
goto r_op255;
case 255:
{
r_op255:
{
{tagged_t vr47;
vr47 = Xb(BcP(f_x,0));
DerefSw_HVA_CVA_SVA_Other(vr47,{
BindHVA(vr47,BC_MakeBlob(w,&BcP(f_t,0+Fs(f_x))));
    }
,{
BindCVA(vr47,BC_MakeBlob(w,&BcP(f_t,0+Fs(f_x))));
    }
,{
BindSVA(vr47,BC_MakeBlob(w,&BcP(f_t,0+Fs(f_x))));
    }
,{
BC_EqBlob(vr47,&BcP(f_t,0+Fs(f_x)),{
goto fail;
      }
)    }
);
}P+=Fs(f_x)+LargeSize(*&BcP(f_t,0+Fs(f_x)));
goto r_dispatch;
    }
    }
case 98:
P+=Fs(f_Q);
goto r_op99;
case 99:
{
r_op99:
{
tagged_t vr48 = Xb(BcP(f_x,0));
DerefSw_HVA_CVA_SVA_Other(vr48,{
H = w->heap_top;
BindHVA(vr48,Tagp(STR,H));
HeapPush(H,BcP(f_f,0+Fs(f_x)));
P+=Fs(f_x)+Fs(f_f);
goto w_dispatch;
    }
,{
H = w->heap_top;
BindCVA(vr48,Tagp(STR,H));
HeapPush(H,BcP(f_f,0+Fs(f_x)));
P+=Fs(f_x)+Fs(f_f);
goto w_dispatch;
    }
,{
H = w->heap_top;
BindSVA(vr48,Tagp(STR,H));
HeapPush(H,BcP(f_f,0+Fs(f_x)));
P+=Fs(f_x)+Fs(f_f);
goto w_dispatch;
    }
,{
if (!TaggedIsSTR(vr48)||TaggedToHeadfunctor(vr48)!=BcP(f_f,0+Fs(f_x))) {
goto fail;
      }

S = TaggedToArg(vr48,1);
P+=Fs(f_x)+Fs(f_f);
goto r_dispatch;
    }
);
    }
    }
case 100:
{
r_op100:
{
tagged_t vr49 = Xb(BcP(f_x,0));
DerefSw_HVA_CVA_SVA_Other(vr49,{
BindHVA(vr49,atom_nil);
    }
,{
BindCVA(vr49,atom_nil);
    }
,{
BindSVA(vr49,atom_nil);
    }
,{
if (vr49!=atom_nil) {
goto fail;
      }

    }
);
P+=Fs(f_x);
goto r_dispatch;
    }
    }
case 101:
{
r_op101:
{
{tagged_t vr50 = Xb(BcP(f_x,0));
DerefSw_HVA_CVA_SVA_Other(vr50,{
H = w->heap_top;
BindHVA(vr50,Tagp(LST,H));
P+=Fs(f_x);
goto w_dispatch;
    }
,{
H = w->heap_top;
BindCVA(vr50,Tagp(LST,H));
P+=Fs(f_x);
goto w_dispatch;
    }
,{
H = w->heap_top;
BindSVA(vr50,Tagp(LST,H));
P+=Fs(f_x);
goto w_dispatch;
    }
,{
if (!TermIsLST(vr50)) {
goto fail;
      }

S = TagpPtr(LST,vr50);
P+=Fs(f_x);
goto r_dispatch;
    }
);
}    }
    }
case 111:
P+=Fs(f_Q);
goto r_op112;
case 112:
{
r_op112:
{
tagged_t vr51 = Xb(BcP(f_x,0));
DerefSw_HVA_CVA_SVA_Other(vr51,{
BindHVA(vr51,BcP(f_t,0+Fs(f_x)));
    }
,{
BindCVA(vr51,BcP(f_t,0+Fs(f_x)));
    }
,{
BindSVA(vr51,BcP(f_t,0+Fs(f_x)));
    }
,{
if (vr51!=BcP(f_t,0+Fs(f_x))) {
goto fail;
      }

    }
);
H = w->heap_top;
goto w_op66;
    }
    }
case 113:
{
r_op113:
{
tagged_t vr52 = Xb(BcP(f_x,0));
DerefSw_HVA_CVA_SVA_Other(vr52,{
BindHVA(vr52,atom_nil);
    }
,{
BindCVA(vr52,atom_nil);
    }
,{
BindSVA(vr52,atom_nil);
    }
,{
if (vr52!=atom_nil) {
goto fail;
      }

    }
);
H = w->heap_top;
goto w_op66;
    }
    }
case 208:
r_op208:
w->local_top = 0;
w->previous_choice = ChoiceFromTagged(Xb(BcP(f_x,0)));
PROFILE__HOOK_CUT;
B = w->previous_choice;
SetChoice(B);
TRACE_CHPT_CUT(w->choice);
ConcChptCleanUp(TopConcChpt,w->choice);
P+=Fs(f_x);
goto r_dispatch;
case 210:
r_op210:
w->local_top = 0;
w->previous_choice = ChoiceFromTagged(Xb(BcP(f_x,0)));
P+=Fs(f_x);
goto r_op211;
case 211:
r_op211:
PROFILE__HOOK_CUT;
B = w->previous_choice;
SetChoice(B);
TRACE_CHPT_CUT(w->choice);
ConcChptCleanUp(TopConcChpt,w->choice);
if (!IsDeep()) {
SetDeep();
if (ChoiceYounger(ChoiceOffset(B,CHOICEPAD),w->trail_top)) {
choice_overflow(w,2*CHOICEPAD*sizeof(tagged_t),TRUE);
      }

    }

P+=0;
goto r_dispatch;
case 212:
r_op212:
w->previous_choice = ChoiceFromTagged(Xb(BcP(f_x,0)));
goto r_op213;
case 213:
r_op213:
PROFILE__HOOK_CUT;
B = w->previous_choice;
SetChoice(B);
TRACE_CHPT_CUT(w->choice);
ConcChptCleanUp(TopConcChpt,w->choice);
if (!IsDeep()) {
SetDeep();
if (ChoiceYounger(ChoiceOffset(B,CHOICEPAD),w->trail_top)) {
choice_overflow(w,2*CHOICEPAD*sizeof(tagged_t),TRUE);
      }

    }

goto r_op64;
case 214:
r_op214:
w->previous_choice = ChoiceFromTagged(Xb(BcP(f_x,0)));
w->local_top = E;
PROFILE__HOOK_CUT;
B = w->previous_choice;
SetChoice(B);
TRACE_CHPT_CUT(w->choice);
ConcChptCleanUp(TopConcChpt,w->choice);
SetE(w->local_top);
P+=Fs(f_x);
goto r_dispatch;
case 216:
r_op216:
w->previous_choice = ChoiceFromTagged(Xb(BcP(f_x,0)));
P+=Fs(f_x);
goto r_op217;
case 217:
r_op217:
w->local_top = E;
PROFILE__HOOK_CUT;
B = w->previous_choice;
SetChoice(B);
TRACE_CHPT_CUT(w->choice);
ConcChptCleanUp(TopConcChpt,w->choice);
SetDeep();
if (ChoiceYounger(ChoiceOffset(B,CHOICEPAD),w->trail_top)) {
choice_overflow(w,2*CHOICEPAD*sizeof(tagged_t),TRUE);
    }

SetE(w->local_top);
P+=0;
goto r_dispatch;
case 215:
r_op215:
w->previous_choice = ChoiceFromTagged(Xb(BcP(f_x,0)));
P+=Fs(f_x);
goto r_op209;
case 209:
r_op209:
PROFILE__HOOK_CUT;
B = w->previous_choice;
SetChoice(B);
TRACE_CHPT_CUT(w->choice);
ConcChptCleanUp(TopConcChpt,w->choice);
SetE(w->frame);
P+=0;
goto r_dispatch;
case 218:
{
r_op218:
{
tagged_t vr53;
vr53 = Yb(BcP(f_y,0));
w->previous_choice = ChoiceFromTagged(vr53);
PROFILE__HOOK_CUT;
B = w->previous_choice;
SetChoice(B);
TRACE_CHPT_CUT(w->choice);
ConcChptCleanUp(TopConcChpt,w->choice);
SetE(w->frame);
P+=Fs(f_y);
goto r_dispatch;
P+=Fs(f_y);
goto r_dispatch;
    }
    }
case 219:
Xb(BcP(f_x,0)) = ChoiceToTagged(w->previous_choice);
P+=Fs(f_x);
goto r_dispatch;
case 220:
CODE_ALLOC(E);
goto r_op221;
case 221:
r_op221:
Yb(BcP(f_y,0)) = ChoiceToTagged(w->previous_choice);
P+=Fs(f_y);
goto r_dispatch;
case 233:
H = w->heap_top;
goto w_op233;
case 234:
r_op234:
goto r_op235;
case 235:
r_op235:
goto exit_toplevel;
case 237:
r_op237:
if (!IsDeep()) {
NECK_RETRY_PATCH(B);
SetDeep();
    }

if (!((cbool0_t)BcP(f_C,0+Fs(f_Q)))(w)) {
goto fail;
    }

goto r_op64;
case 238:
r_op238:
if (!IsDeep()) {
NECK_RETRY_PATCH(B);
SetDeep();
    }

if (!((cbool0_t)BcP(f_C,0))(w)) {
goto fail;
    }

goto r_op64;
case 104:
{
{
tagged_t vr54 = X(0);
S = TaggedToArg(vr54,1);
P+=Fs(f_Q)+Fs(f_f);
goto r_dispatch;
    }
    }
case 105:
{
{
tagged_t vr55 = X(0);
S = TaggedToArg(vr55,1);
P+=Fs(f_f);
goto r_dispatch;
    }
    }
case 256:
{
{
tagged_t vr56 = X(0);
{tagged_t vr57;
vr57 = vr56;
DerefSw_HVA_CVA_SVA_Other(vr57,{
BindHVA(vr57,BC_MakeBlob(w,&BcP(f_t,0+Fs(f_Q))));
    }
,{
BindCVA(vr57,BC_MakeBlob(w,&BcP(f_t,0+Fs(f_Q))));
    }
,{
BindSVA(vr57,BC_MakeBlob(w,&BcP(f_t,0+Fs(f_Q))));
    }
,{
BC_EqBlob(vr57,&BcP(f_t,0+Fs(f_Q)),{
goto fail;
      }
)    }
);
}P+=Fs(f_Q)+LargeSize(*&BcP(f_t,0+Fs(f_Q)));
goto r_dispatch;
    }
    }
case 257:
{
{
tagged_t vr58 = X(0);
{tagged_t vr59;
vr59 = vr58;
DerefSw_HVA_CVA_SVA_Other(vr59,{
BindHVA(vr59,BC_MakeBlob(w,&BcP(f_t,0)));
    }
,{
BindCVA(vr59,BC_MakeBlob(w,&BcP(f_t,0)));
    }
,{
BindSVA(vr59,BC_MakeBlob(w,&BcP(f_t,0)));
    }
,{
BC_EqBlob(vr59,&BcP(f_t,0),{
goto fail;
      }
)    }
);
}P+=LargeSize(*&BcP(f_t,0));
goto r_dispatch;
    }
    }
case 102:
P+=Fs(f_Q)+Fs(f_t);
goto r_dispatch;
case 103:
P+=Fs(f_t);
goto r_dispatch;
case 106:
P+=0;
goto r_dispatch;
case 107:
{
{
tagged_t vr60 = X(0);
S = TagpPtr(LST,vr60);
P+=0;
goto r_dispatch;
    }
    }
case 108:
Xb(BcP(f_x,0+Fs(f_x))) = Xb(BcP(f_x,0));
Xb(BcP(f_x,0+Fs(f_x)+Fs(f_x)+Fs(f_x))) = Xb(BcP(f_x,0+Fs(f_x)+Fs(f_x)));
P+=Fs(f_x)+Fs(f_x)+Fs(f_x)+Fs(f_x);
goto r_dispatch;
case 90:
Xb(BcP(f_x,0+Fs(f_x))) = Xb(BcP(f_x,0));
P+=Fs(f_x)+Fs(f_x);
goto r_dispatch;
case 92:
CODE_ALLOC(E);
goto r_op93;
case 93:
r_op93:
Yb(BcP(f_y,0+Fs(f_x))) = Xb(BcP(f_x,0));
P+=Fs(f_x)+Fs(f_y);
goto r_dispatch;
case 109:
CODE_ALLOC(E);
goto r_op110;
case 110:
r_op110:
Yb(BcP(f_y,0+Fs(f_x))) = Xb(BcP(f_x,0));
Yb(BcP(f_y,0+Fs(f_x)+Fs(f_y)+Fs(f_x))) = Xb(BcP(f_x,0+Fs(f_x)+Fs(f_y)));
P+=Fs(f_x)+Fs(f_y)+Fs(f_x)+Fs(f_y);
goto r_dispatch;
case 68:
P = BCoff(P,BcP(f_i,0));
goto r_dispatch;
case 222:
{
r_op222:
{
w->liveinfo = &BcP(f_l,0+Fs(f_Q)+Fs(f_x)+Fs(f_x)+Fs(f_C));
tagged_t vr61 = (tagged_t)((ctagged1_t)BcP(f_C,0+Fs(f_Q)+Fs(f_x)+Fs(f_x)))(w,Xb(BcP(f_x,0+Fs(f_Q)+Fs(f_x))));
Xb(BcP(f_x,0+Fs(f_Q))) = vr61;
if (ERRORTAG==vr61) {
goto fail;
    }

P+=Fs(f_Q)+Fs(f_x)+Fs(f_x)+Fs(f_C)+Fs(f_g);
goto r_dispatch;
    }
    }
case 223:
{
r_op223:
{
w->liveinfo = &BcP(f_l,0+Fs(f_x)+Fs(f_x)+Fs(f_C));
tagged_t vr62 = (tagged_t)((ctagged1_t)BcP(f_C,0+Fs(f_x)+Fs(f_x)))(w,Xb(BcP(f_x,0+Fs(f_x))));
Xb(BcP(f_x,0)) = vr62;
if (ERRORTAG==vr62) {
goto fail;
    }

P+=Fs(f_x)+Fs(f_x)+Fs(f_C)+Fs(f_g);
goto r_dispatch;
    }
    }
case 224:
{
r_op224:
{
w->liveinfo = &BcP(f_l,0+Fs(f_Q)+Fs(f_x)+Fs(f_x)+Fs(f_x)+Fs(f_C));
tagged_t vr63 = (tagged_t)((ctagged2_t)BcP(f_C,0+Fs(f_Q)+Fs(f_x)+Fs(f_x)+Fs(f_x)))(w,Xb(BcP(f_x,0+Fs(f_Q)+Fs(f_x))),Xb(BcP(f_x,0+Fs(f_Q)+Fs(f_x)+Fs(f_x))));
Xb(BcP(f_x,0+Fs(f_Q))) = vr63;
if (ERRORTAG==vr63) {
goto fail;
    }

P+=Fs(f_Q)+Fs(f_x)+Fs(f_x)+Fs(f_x)+Fs(f_C)+Fs(f_g);
goto r_dispatch;
    }
    }
case 225:
{
r_op225:
{
w->liveinfo = &BcP(f_l,0+Fs(f_x)+Fs(f_x)+Fs(f_x)+Fs(f_C));
tagged_t vr64 = (tagged_t)((ctagged2_t)BcP(f_C,0+Fs(f_x)+Fs(f_x)+Fs(f_x)))(w,Xb(BcP(f_x,0+Fs(f_x))),Xb(BcP(f_x,0+Fs(f_x)+Fs(f_x))));
Xb(BcP(f_x,0)) = vr64;
if (ERRORTAG==vr64) {
goto fail;
    }

P+=Fs(f_x)+Fs(f_x)+Fs(f_x)+Fs(f_C)+Fs(f_g);
goto r_dispatch;
    }
    }
case 226:
r_op226:
if (!((cbool1_t)BcP(f_C,0+Fs(f_Q)+Fs(f_x)))(w,Xb(BcP(f_x,0+Fs(f_Q))))) {
goto fail;
    }

P+=Fs(f_Q)+Fs(f_x)+Fs(f_C);
goto r_dispatch;
case 227:
r_op227:
if (!((cbool1_t)BcP(f_C,0+Fs(f_x)))(w,Xb(BcP(f_x,0)))) {
goto fail;
    }

P+=Fs(f_x)+Fs(f_C);
goto r_dispatch;
case 228:
r_op228:
if (!((cbool2_t)BcP(f_C,0+Fs(f_Q)+Fs(f_x)+Fs(f_x)))(w,Xb(BcP(f_x,0+Fs(f_Q))),Xb(BcP(f_x,0+Fs(f_Q)+Fs(f_x))))) {
goto fail;
    }

P+=Fs(f_Q)+Fs(f_x)+Fs(f_x)+Fs(f_C);
goto r_dispatch;
case 229:
r_op229:
if (!((cbool2_t)BcP(f_C,0+Fs(f_x)+Fs(f_x)))(w,Xb(BcP(f_x,0)),Xb(BcP(f_x,0+Fs(f_x))))) {
goto fail;
    }

P+=Fs(f_x)+Fs(f_x)+Fs(f_C);
goto r_dispatch;
case 230:
r_op230:
if (!((cbool3_t)BcP(f_C,0+Fs(f_Q)+Fs(f_x)+Fs(f_x)+Fs(f_x)))(w,Xb(BcP(f_x,0+Fs(f_Q))),Xb(BcP(f_x,0+Fs(f_Q)+Fs(f_x))),Xb(BcP(f_x,0+Fs(f_Q)+Fs(f_x)+Fs(f_x))))) {
goto fail;
    }

P+=Fs(f_Q)+Fs(f_x)+Fs(f_x)+Fs(f_x)+Fs(f_C);
goto r_dispatch;
case 231:
r_op231:
if (!((cbool3_t)BcP(f_C,0+Fs(f_x)+Fs(f_x)+Fs(f_x)))(w,Xb(BcP(f_x,0)),Xb(BcP(f_x,0+Fs(f_x))),Xb(BcP(f_x,0+Fs(f_x)+Fs(f_x))))) {
goto fail;
    }

P+=Fs(f_x)+Fs(f_x)+Fs(f_x)+Fs(f_C);
goto r_dispatch;
case 232:
r_op232:
if ((TaggedToRoot(X(RootArg))->behavior_on_failure!=DYNAMIC&&!next_instance_conc(w,&w->misc->ins))||(TaggedToRoot(X(RootArg))->behavior_on_failure==DYNAMIC&&!next_instance(w,&w->misc->ins))) {
SetDeep();
B = w->previous_choice;
SetChoice(B);
    }

if (w->misc->ins==NULL) {
ON_DEBUG({
if (debug_concchoicepoints) {
if (TaggedToRoot(X(RootArg))->behavior_on_failure!=CONC_CLOSED&&IS_BLOCKING(X(InvocationAttr))) {
fprintf(stderr,"**wam(): failing on a concurrent closed pred, chpt=%p, failing chpt=%p .\n",w->choice,TopConcChpt);
          }

        }

if (debug_conc) {
if (TaggedToRoot(X(RootArg))->x2_pending_on_instance||TaggedToRoot(X(RootArg))->x5_pending_on_instance) {
fprintf(stderr,"**wam(): failing with invokations pending from root, type = %d.\n",TaggedToRoot(X(RootArg))->behavior_on_failure);
          }

        }

      }
);
TopConcChpt = TermToPointerOrNull(choice_t,X(PrevDynChpt));
ON_DEBUG({
if (debug_concchoicepoints) {
fprintf(stderr,"New topmost concurrent chpt = %p\n",TopConcChpt);
        }

      }
);
goto fail;
    }

ON_DEBUG({
if (debug_conc&&TaggedToRoot(X(RootArg))->behavior_on_failure!=DYNAMIC) {
fprintf(stderr,"*** %" PRIdm " (%" PRIdm ") backtracking on a concurrent predicate.\n",(intmach_t)Thread_Id,(intmach_t)GET_INC_COUNTER);
      }

if (debug_concchoicepoints&&TaggedToRoot(X(RootArg))->behavior_on_failure!=DYNAMIC) {
fprintf(stderr,"backtracking to chpt. = %p\n",w->choice);
      }

    }
);
P = (bcp_t)w->misc->ins->emulcode;
goto r_dispatch;
case 247:
H = w->heap_top;
goto w_op247;
case 114:
S = HeapOffset(S,BcP(f_i,0));
P+=Fs(f_i);
goto r_dispatch;
case 115:
S = HeapOffset(S,1);
P+=0;
goto r_dispatch;
case 116:
S = HeapOffset(S,2);
P+=0;
goto r_dispatch;
case 117:
S = HeapOffset(S,3);
P+=0;
goto r_dispatch;
case 118:
S = HeapOffset(S,4);
P+=0;
goto r_dispatch;
case 119:
RefHeapNext(Xb(BcP(f_x,0)),S);
P+=Fs(f_x);
goto r_dispatch;
case 120:
goto r_op121;
case 121:
{
r_op121:
{
{tagged_t vr65;
RefHeapNext(vr65,S);
if (!CBOOL__SUCCEED(cunify,Xb(BcP(f_x,0)),vr65)) {
goto fail;
    }

}P+=Fs(f_x);
goto r_dispatch;
    }
    }
case 122:
CODE_ALLOC(E);
goto r_op123;
case 123:
r_op123:
RefHeapNext(Yb(BcP(f_y,0)),S);
P+=Fs(f_y);
goto r_dispatch;
case 124:
{
{
{tagged_t vr66;
RefHeapNext(vr66,S);
if (CondStackvar(Yb(BcP(f_y,0)))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0))));
    }

Yb(BcP(f_y,0)) = vr66;
}P+=Fs(f_y);
goto r_dispatch;
    }
    }
case 125:
goto r_op126;
case 126:
{
r_op126:
{
{tagged_t vr67;
RefHeapNext(vr67,S);
if (!CBOOL__SUCCEED(cunify,Yb(BcP(f_y,0)),vr67)) {
goto fail;
    }

}P+=Fs(f_y);
goto r_dispatch;
    }
    }
case 127:
P+=Fs(f_Q);
goto r_op128;
case 128:
{
r_op128:
{
tagged_t vr68;
RefHeapNext(vr68,S);
tagged_t vr69 = vr68;
tagged_t vr70;
SwitchOnHeapVar(vr69,vr70,{
BindHVA(vr69,BcP(f_t,0));
    }
,{
BindCVA(vr69,BcP(f_t,0));
    }
,{
if (vr69!=BcP(f_t,0)) {
goto fail;
      }

    }
);
P+=Fs(f_t);
goto r_dispatch;
    }
    }
case 258:
P+=Fs(f_Q);
goto r_op259;
case 259:
{
r_op259:
{
tagged_t vr71;
RefHeapNext(vr71,S);
{tagged_t vr72 = vr71;
tagged_t vr73;
SwitchOnHeapVar(vr72,vr73,{
BindHVA(vr72,BC_MakeBlob(w,&BcP(f_t,0)));
    }
,{
BindCVA(vr72,BC_MakeBlob(w,&BcP(f_t,0)));
    }
,{
BC_EqBlob(vr72,&BcP(f_t,0),{
goto fail;
      }
)    }
);
}P+=LargeSize(*&BcP(f_t,0));
goto r_dispatch;
    }
    }
case 129:
P+=Fs(f_Q);
goto r_op130;
case 130:
{
r_op130:
{
tagged_t vr74;
RefHeapNext(vr74,S);
tagged_t vr75 = vr74;
tagged_t vr76;
SwitchOnHeapVar(vr75,vr76,{
H = w->heap_top;
BindHVA(vr75,Tagp(STR,H));
HeapPush(H,BcP(f_f,0));
P+=Fs(f_f);
goto w_dispatch;
    }
,{
H = w->heap_top;
BindCVA(vr75,Tagp(STR,H));
HeapPush(H,BcP(f_f,0));
P+=Fs(f_f);
goto w_dispatch;
    }
,{
if (!TaggedIsSTR(vr75)||TaggedToHeadfunctor(vr75)!=BcP(f_f,0)) {
goto fail;
      }

S = TaggedToArg(vr75,1);
P+=Fs(f_f);
goto r_dispatch;
    }
);
    }
    }
case 131:
{
{
tagged_t vr77;
RefHeapNext(vr77,S);
tagged_t vr78 = vr77;
tagged_t vr79;
SwitchOnHeapVar(vr78,vr79,{
BindHVA(vr78,atom_nil);
    }
,{
BindCVA(vr78,atom_nil);
    }
,{
if (vr78!=atom_nil) {
goto fail;
      }

    }
);
P+=0;
goto r_dispatch;
    }
    }
case 132:
{
{
tagged_t vr80;
RefHeapNext(vr80,S);
{tagged_t vr81 = vr80;
tagged_t vr82;
SwitchOnHeapVar(vr81,vr82,{
H = w->heap_top;
BindHVA(vr81,Tagp(LST,H));
P+=0;
goto w_dispatch;
    }
,{
H = w->heap_top;
BindCVA(vr81,Tagp(LST,H));
P+=0;
goto w_dispatch;
    }
,{
if (!TermIsLST(vr81)) {
goto fail;
      }

S = TagpPtr(LST,vr81);
P+=0;
goto r_dispatch;
    }
);
}    }
    }
case 133:
P+=Fs(f_Q);
goto r_op134;
case 134:
{
r_op134:
{
tagged_t vr83;
RefHeapNext(vr83,S);
tagged_t vr84 = vr83;
tagged_t vr85;
SwitchOnHeapVar(vr84,vr85,{
BindHVA(vr84,BcP(f_t,0));
    }
,{
BindCVA(vr84,BcP(f_t,0));
    }
,{
if (vr84!=BcP(f_t,0)) {
goto fail;
      }

    }
);
H = w->heap_top;
goto w_op66;
    }
    }
case 135:
{
{
tagged_t vr86;
RefHeapNext(vr86,S);
tagged_t vr87 = vr86;
tagged_t vr88;
SwitchOnHeapVar(vr87,vr88,{
BindHVA(vr87,atom_nil);
    }
,{
BindCVA(vr87,atom_nil);
    }
,{
if (vr87!=atom_nil) {
goto fail;
      }

    }
);
H = w->heap_top;
goto w_op66;
    }
    }
case 136:
S = HeapOffset(S,BcP(f_i,0));
RefHeapNext(Xb(BcP(f_x,0+Fs(f_i))),S);
P+=Fs(f_i)+Fs(f_x);
goto r_dispatch;
case 139:
CODE_ALLOC(E);
goto r_op140;
case 140:
r_op140:
S = HeapOffset(S,BcP(f_i,0));
RefHeapNext(Yb(BcP(f_y,0+Fs(f_i))),S);
P+=Fs(f_i)+Fs(f_y);
goto r_dispatch;
case 137:
goto r_op138;
case 138:
{
r_op138:
{
S = HeapOffset(S,BcP(f_i,0));
{tagged_t vr89;
RefHeapNext(vr89,S);
if (!CBOOL__SUCCEED(cunify,Xb(BcP(f_x,0+Fs(f_i))),vr89)) {
goto fail;
    }

}P+=Fs(f_i)+Fs(f_x);
goto r_dispatch;
    }
    }
case 141:
{
{
S = HeapOffset(S,BcP(f_i,0));
{tagged_t vr90;
RefHeapNext(vr90,S);
if (CondStackvar(Yb(BcP(f_y,0+Fs(f_i))))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0+Fs(f_i)))));
    }

Yb(BcP(f_y,0+Fs(f_i))) = vr90;
}P+=Fs(f_i)+Fs(f_y);
goto r_dispatch;
    }
    }
case 142:
goto r_op143;
case 143:
{
r_op143:
{
S = HeapOffset(S,BcP(f_i,0));
{tagged_t vr91;
RefHeapNext(vr91,S);
if (!CBOOL__SUCCEED(cunify,Yb(BcP(f_y,0+Fs(f_i))),vr91)) {
goto fail;
    }

}P+=Fs(f_i)+Fs(f_y);
goto r_dispatch;
    }
    }
case 144:
RefHeapNext(Xb(BcP(f_x,0)),S);
S = HeapOffset(S,BcP(f_i,0+Fs(f_x)));
P+=Fs(f_x)+Fs(f_i);
goto r_dispatch;
case 145:
RefHeapNext(Xb(BcP(f_x,0)),S);
RefHeapNext(Xb(BcP(f_x,0+Fs(f_x))),S);
P+=Fs(f_x)+Fs(f_x);
goto r_dispatch;
case 148:
CODE_ALLOC(E);
goto r_op149;
case 149:
r_op149:
RefHeapNext(Xb(BcP(f_x,0)),S);
RefHeapNext(Yb(BcP(f_y,0+Fs(f_x))),S);
P+=Fs(f_x)+Fs(f_y);
goto r_dispatch;
case 146:
goto r_op147;
case 147:
{
r_op147:
{
RefHeapNext(Xb(BcP(f_x,0)),S);
{tagged_t vr92;
RefHeapNext(vr92,S);
if (!CBOOL__SUCCEED(cunify,Xb(BcP(f_x,0+Fs(f_x))),vr92)) {
goto fail;
    }

}P+=Fs(f_x)+Fs(f_x);
goto r_dispatch;
    }
    }
case 150:
{
{
RefHeapNext(Xb(BcP(f_x,0)),S);
{tagged_t vr93;
RefHeapNext(vr93,S);
if (CondStackvar(Yb(BcP(f_y,0+Fs(f_x))))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0+Fs(f_x)))));
    }

Yb(BcP(f_y,0+Fs(f_x))) = vr93;
}P+=Fs(f_x)+Fs(f_y);
goto r_dispatch;
    }
    }
case 151:
goto r_op152;
case 152:
{
r_op152:
{
RefHeapNext(Xb(BcP(f_x,0)),S);
{tagged_t vr94;
RefHeapNext(vr94,S);
if (!CBOOL__SUCCEED(cunify,Yb(BcP(f_y,0+Fs(f_x))),vr94)) {
goto fail;
    }

}P+=Fs(f_x)+Fs(f_y);
goto r_dispatch;
    }
    }
case 153:
CODE_ALLOC(E);
goto r_op154;
case 154:
r_op154:
RefHeapNext(Yb(BcP(f_y,0)),S);
S = HeapOffset(S,BcP(f_i,0+Fs(f_y)));
P+=Fs(f_y)+Fs(f_i);
goto r_dispatch;
case 155:
CODE_ALLOC(E);
goto r_op156;
case 156:
r_op156:
RefHeapNext(Yb(BcP(f_y,0)),S);
RefHeapNext(Xb(BcP(f_x,0+Fs(f_y))),S);
P+=Fs(f_y)+Fs(f_x);
goto r_dispatch;
case 157:
CODE_ALLOC(E);
goto r_op158;
case 158:
r_op158:
RefHeapNext(Yb(BcP(f_y,0)),S);
RefHeapNext(Yb(BcP(f_y,0+Fs(f_y))),S);
P+=Fs(f_y)+Fs(f_y);
goto r_dispatch;
case 159:
goto r_op161;
case 161:
r_op161:
CODE_ALLOC(E);
goto r_op162;
case 160:
goto r_op162;
case 162:
{
r_op162:
{
RefHeapNext(Yb(BcP(f_y,0)),S);
{tagged_t vr95;
RefHeapNext(vr95,S);
if (!CBOOL__SUCCEED(cunify,Xb(BcP(f_x,0+Fs(f_y))),vr95)) {
goto fail;
    }

}P+=Fs(f_y)+Fs(f_x);
goto r_dispatch;
    }
    }
case 163:
goto r_op165;
case 165:
r_op165:
CODE_ALLOC(E);
goto r_op166;
case 164:
goto r_op166;
case 166:
{
r_op166:
{
RefHeapNext(Yb(BcP(f_y,0)),S);
{tagged_t vr96;
RefHeapNext(vr96,S);
if (!CBOOL__SUCCEED(cunify,Yb(BcP(f_y,0+Fs(f_y))),vr96)) {
goto fail;
    }

}P+=Fs(f_y)+Fs(f_y);
goto r_dispatch;
    }
    }
case 185:
{
{
{tagged_t vr97;
RefHeapNext(vr97,S);
if (CondStackvar(Yb(BcP(f_y,0)))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0))));
    }

Yb(BcP(f_y,0)) = vr97;
}S = HeapOffset(S,BcP(f_i,0+Fs(f_y)));
P+=Fs(f_y)+Fs(f_i);
goto r_dispatch;
    }
    }
case 188:
{
{
{tagged_t vr98;
RefHeapNext(vr98,S);
if (CondStackvar(Yb(BcP(f_y,0)))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0))));
    }

Yb(BcP(f_y,0)) = vr98;
}RefHeapNext(Xb(BcP(f_x,0+Fs(f_y))),S);
P+=Fs(f_y)+Fs(f_x);
goto r_dispatch;
    }
    }
case 199:
{
{
{tagged_t vr99;
RefHeapNext(vr99,S);
if (CondStackvar(Yb(BcP(f_y,0)))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0))));
    }

Yb(BcP(f_y,0)) = vr99;
}{tagged_t vr100;
RefHeapNext(vr100,S);
if (CondStackvar(Yb(BcP(f_y,0+Fs(f_y))))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0+Fs(f_y)))));
    }

Yb(BcP(f_y,0+Fs(f_y))) = vr100;
}P+=Fs(f_y)+Fs(f_y);
goto r_dispatch;
    }
    }
case 193:
goto r_op196;
case 196:
{
r_op196:
{
{tagged_t vr101;
RefHeapNext(vr101,S);
if (CondStackvar(Yb(BcP(f_y,0)))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0))));
    }

Yb(BcP(f_y,0)) = vr101;
}{tagged_t vr102;
RefHeapNext(vr102,S);
if (!CBOOL__SUCCEED(cunify,Xb(BcP(f_x,0+Fs(f_y))),vr102)) {
goto fail;
    }

}P+=Fs(f_y)+Fs(f_x);
goto r_dispatch;
    }
    }
case 202:
goto r_op205;
case 205:
{
r_op205:
{
{tagged_t vr103;
RefHeapNext(vr103,S);
if (CondStackvar(Yb(BcP(f_y,0)))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0))));
    }

Yb(BcP(f_y,0)) = vr103;
}{tagged_t vr104;
RefHeapNext(vr104,S);
if (!CBOOL__SUCCEED(cunify,Yb(BcP(f_y,0+Fs(f_y))),vr104)) {
goto fail;
    }

}P+=Fs(f_y)+Fs(f_y);
goto r_dispatch;
    }
    }
case 167:
goto r_op168;
case 168:
{
r_op168:
{
{tagged_t vr105;
RefHeapNext(vr105,S);
if (!CBOOL__SUCCEED(cunify,Xb(BcP(f_x,0)),vr105)) {
goto fail;
    }

}S = HeapOffset(S,BcP(f_i,0+Fs(f_x)));
P+=Fs(f_x)+Fs(f_i);
goto r_dispatch;
    }
    }
case 169:
goto r_op170;
case 170:
{
r_op170:
{
{tagged_t vr106;
RefHeapNext(vr106,S);
if (!CBOOL__SUCCEED(cunify,Xb(BcP(f_x,0)),vr106)) {
goto fail;
    }

}RefHeapNext(Xb(BcP(f_x,0+Fs(f_x))),S);
P+=Fs(f_x)+Fs(f_x);
goto r_dispatch;
    }
    }
case 171:
goto r_op172;
case 172:
r_op172:
CODE_ALLOC(E);
goto r_op174;
case 173:
goto r_op174;
case 174:
{
r_op174:
{
{tagged_t vr107;
RefHeapNext(vr107,S);
if (!CBOOL__SUCCEED(cunify,Xb(BcP(f_x,0)),vr107)) {
goto fail;
    }

}RefHeapNext(Yb(BcP(f_y,0+Fs(f_x))),S);
P+=Fs(f_x)+Fs(f_y);
goto r_dispatch;
    }
    }
case 175:
goto r_op177;
case 177:
r_op177:
goto r_op176;
case 176:
r_op176:
goto r_op178;
case 178:
{
r_op178:
{
{tagged_t vr108;
RefHeapNext(vr108,S);
if (!CBOOL__SUCCEED(cunify,Xb(BcP(f_x,0)),vr108)) {
goto fail;
    }

}{tagged_t vr109;
RefHeapNext(vr109,S);
if (!CBOOL__SUCCEED(cunify,Xb(BcP(f_x,0+Fs(f_x))),vr109)) {
goto fail;
    }

}P+=Fs(f_x)+Fs(f_x);
goto r_dispatch;
    }
    }
case 179:
goto r_op180;
case 180:
{
r_op180:
{
{tagged_t vr110;
RefHeapNext(vr110,S);
if (!CBOOL__SUCCEED(cunify,Xb(BcP(f_x,0)),vr110)) {
goto fail;
    }

}{tagged_t vr111;
RefHeapNext(vr111,S);
if (CondStackvar(Yb(BcP(f_y,0+Fs(f_x))))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0+Fs(f_x)))));
    }

Yb(BcP(f_y,0+Fs(f_x))) = vr111;
}P+=Fs(f_x)+Fs(f_y);
goto r_dispatch;
    }
    }
case 181:
goto r_op183;
case 183:
r_op183:
goto r_op182;
case 182:
r_op182:
goto r_op184;
case 184:
{
r_op184:
{
{tagged_t vr112;
RefHeapNext(vr112,S);
if (!CBOOL__SUCCEED(cunify,Xb(BcP(f_x,0)),vr112)) {
goto fail;
    }

}{tagged_t vr113;
RefHeapNext(vr113,S);
if (!CBOOL__SUCCEED(cunify,Yb(BcP(f_y,0+Fs(f_x))),vr113)) {
goto fail;
    }

}P+=Fs(f_x)+Fs(f_y);
goto r_dispatch;
    }
    }
case 186:
goto r_op187;
case 187:
{
r_op187:
{
{tagged_t vr114;
RefHeapNext(vr114,S);
if (!CBOOL__SUCCEED(cunify,Yb(BcP(f_y,0)),vr114)) {
goto fail;
    }

}S = HeapOffset(S,BcP(f_i,0+Fs(f_y)));
P+=Fs(f_y)+Fs(f_i);
goto r_dispatch;
    }
    }
case 189:
goto r_op190;
case 190:
{
r_op190:
{
{tagged_t vr115;
RefHeapNext(vr115,S);
if (!CBOOL__SUCCEED(cunify,Yb(BcP(f_y,0)),vr115)) {
goto fail;
    }

}RefHeapNext(Xb(BcP(f_x,0+Fs(f_y))),S);
P+=Fs(f_y)+Fs(f_x);
goto r_dispatch;
    }
    }
case 191:
goto r_op192;
case 192:
{
r_op192:
{
{tagged_t vr116;
RefHeapNext(vr116,S);
if (!CBOOL__SUCCEED(cunify,Yb(BcP(f_y,0)),vr116)) {
goto fail;
    }

}RefHeapNext(Yb(BcP(f_y,0+Fs(f_y))),S);
P+=Fs(f_y)+Fs(f_y);
goto r_dispatch;
    }
    }
case 200:
goto r_op201;
case 201:
{
r_op201:
{
{tagged_t vr117;
RefHeapNext(vr117,S);
if (!CBOOL__SUCCEED(cunify,Yb(BcP(f_y,0)),vr117)) {
goto fail;
    }

}{tagged_t vr118;
RefHeapNext(vr118,S);
if (CondStackvar(Yb(BcP(f_y,0+Fs(f_y))))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0+Fs(f_y)))));
    }

Yb(BcP(f_y,0+Fs(f_y))) = vr118;
}P+=Fs(f_y)+Fs(f_y);
goto r_dispatch;
    }
    }
case 194:
goto r_op197;
case 197:
r_op197:
goto r_op195;
case 195:
r_op195:
goto r_op198;
case 198:
{
r_op198:
{
{tagged_t vr119;
RefHeapNext(vr119,S);
if (!CBOOL__SUCCEED(cunify,Yb(BcP(f_y,0)),vr119)) {
goto fail;
    }

}{tagged_t vr120;
RefHeapNext(vr120,S);
if (!CBOOL__SUCCEED(cunify,Xb(BcP(f_x,0+Fs(f_y))),vr120)) {
goto fail;
    }

}P+=Fs(f_y)+Fs(f_x);
goto r_dispatch;
    }
    }
case 203:
goto r_op206;
case 206:
r_op206:
goto r_op204;
case 204:
r_op204:
goto r_op207;
case 207:
{
r_op207:
{
{tagged_t vr121;
RefHeapNext(vr121,S);
if (!CBOOL__SUCCEED(cunify,Yb(BcP(f_y,0)),vr121)) {
goto fail;
    }

}{tagged_t vr122;
RefHeapNext(vr122,S);
if (!CBOOL__SUCCEED(cunify,Yb(BcP(f_y,0+Fs(f_y))),vr122)) {
goto fail;
    }

}P+=Fs(f_y)+Fs(f_y);
goto r_dispatch;
    }
    }
case 248:
P+=Fs(f_Q);
goto r_op249;
case 249:
r_op249:
#if defined(GAUGE)
INCR_COUNTER(BcP(f_l,0));
#endif
P+=Fs(f_l);
goto r_dispatch;
case 250:
P+=Fs(f_Q);
goto r_op251;
case 251:
r_op251:
#if defined(GAUGE)
if (!IsDeep()) {
B = w->choice;
if (!IsShallowTry()) {
#if defined(GAUGE)
INCR_COUNTER(BcP(f_l,0));
#endif
      }
 else {
#if defined(GAUGE)
INCR_COUNTER(BcP(f_l,0+Fs(f_l)));
#endif
      }

    }

#endif
P+=Fs(f_l)+Fs(f_l);
goto r_op65;
case 67:
goto fail;
case 245:
P+=Fs(f_Q);
goto r_op246;
case 246:
r_op246:
if (HeapCharDifference(w->heap_top,Heap_End)<(intmach_t)BcP(f_l,0)) {
explicit_heap_overflow(w,(intmach_t)BcP(f_l,0)*2,(FTYPE_ctype(f_i_signed))BcP(f_i,0+Fs(f_l)));
    }

P+=Fs(f_l)+Fs(f_i);
goto r_dispatch;
case 65:
{
r_op65:
{
if (!IsDeep()) {
B = w->choice;
if (!IsShallowTry()) {
NECK_RETRY_PATCH(B);
      }
 else {
B->next_alt = w->next_alt;
B->frame = w->frame;
B->next_insn = w->next_insn;
B->local_top = w->local_top;
intmach_t vr123 = ChoiceArity(B);
for (intmach_t vr124 = 0;
vr124<vr123;vr124++) {
B->x[vr124] = w->x[vr124];
        }

if (ChoiceYounger(ChoiceOffset(B,CHOICEPAD),w->trail_top)) {
choice_overflow(w,2*CHOICEPAD*sizeof(tagged_t),TRUE);
        }

      }

SetDeep();
SetE(w->local_top);
    }

P+=0;
goto r_dispatch;
    }
    }
case 236:
H = w->heap_top;
goto w_op236;
case 66:
H = w->heap_top;
goto w_op66;
case 64:
r_op64:
w->local_top = 0;
SetE(w->frame);
P = w->next_insn;
PROFILE__HOOK_PROCEED;
P+=0;
goto r_dispatch;
#if defined(PARBACK)
case 262:
w->heap_top = TaggedToPointer(w->choice->x[0]);
H = w->heap_top;
P = (bcp_t)*TaggedToPointer(w->choice->x[0]);
w->next_insn = w->choice->next_insn;
pop_choicept(w);
goto enter_predicate;
#endif
default:
goto illop;
  }
  }
w_tryeach:
{
#if defined(GAUGE)
INCR_COUNTER(alts->entry_counter);
#endif
P = alts->emul_p;
w->previous_choice = w->choice;
try_node_t * vr125 = alts->next;
if (vr125!=NULL) {
B = w->choice;
GetFrameTop(w->local_top,B,G->frame);
CODE_CHOICE_NEW0(B,vr125,H);
ON_DEBUG({
if (debug_choicepoints) {
fprintf(stderr,"WAM created choicepoint (r), node = %p\n",w->choice);
      }

    }
);
if (ChoiceYounger(ChoiceOffset(B,CHOICEPAD),w->trail_top)) {
choice_overflow(w,2*CHOICEPAD*sizeof(tagged_t),TRUE);
    }

  }
 else {
SetDeep();
  }

goto w_dispatch;
  }
w_dispatch:
{
switch (BcOPCODE) {
case 260:
{
w_op260:
{
CODE_ALLOC(E);
for (intmach_t vr126 = BcP(f_e,0)-sizeof(tagged_t);
vr126>=EToY0*sizeof(tagged_t);vr126-=sizeof(tagged_t)) {
LoadSVA(Yb(vr126));
    }

goto firsttrue;
    }
    }
case 261:
{
w_op261:
{
intmach_t vr127 = (FTYPE_ctype(f_i_signed))BcP(f_i,0);
P+=Fs(f_i);
for (intmach_t vr128 = vr127;
vr128>0;vr128--) {
tagged_t vr129 = BcP(f_y,0);
P+=Fs(f_y);
LoadSVA(Yb(vr129));
    }

goto firsttrue;
firsttrue:
E->next_insn = w->next_insn;
E->frame = w->frame;
w->frame = E;
w->next_insn = BCoff(P,Fs(f_e));
w->local_top = StackCharOffset(E,BcP(f_e,0));
if (OffStacktop(E,Stack_Warn)) {
SetEvent();
    }

P+=Fs(f_e);
goto w_dispatch;
    }
    }
case 0:
P+=Fs(f_Q);
goto w_op1;
case 1:
{
w_op1:
{
CODE_ALLOC(E);
for (intmach_t vr130 = BcP(f_e,0+Fs(f_E))-sizeof(tagged_t);
vr130>=EToY0*sizeof(tagged_t);vr130-=sizeof(tagged_t)) {
LoadSVA(Yb(vr130));
    }

goto w_op3;
    }
    }
case 20:
P+=Fs(f_Q);
goto w_op21;
case 21:
{
w_op21:
{
intmach_t vr131 = (FTYPE_ctype(f_i_signed))BcP(f_i,0);
P+=Fs(f_i);
for (intmach_t vr132 = vr131;
vr132>8;vr132--) {
tagged_t vr133 = BcP(f_y,0);
P+=Fs(f_y);
LoadSVA(Yb(vr133));
    }

goto w_op19;
    }
    }
case 18:
P+=Fs(f_Q);
goto w_op19;
case 19:
{
w_op19:
{
{
tagged_t vr134 = BcP(f_y,0);
P+=Fs(f_y);
LoadSVA(Yb(vr134));
    }
goto w_op17;
    }
    }
case 16:
P+=Fs(f_Q);
goto w_op17;
case 17:
{
w_op17:
{
{
tagged_t vr135 = BcP(f_y,0);
P+=Fs(f_y);
LoadSVA(Yb(vr135));
    }
goto w_op15;
    }
    }
case 14:
P+=Fs(f_Q);
goto w_op15;
case 15:
{
w_op15:
{
{
tagged_t vr136 = BcP(f_y,0);
P+=Fs(f_y);
LoadSVA(Yb(vr136));
    }
goto w_op13;
    }
    }
case 12:
P+=Fs(f_Q);
goto w_op13;
case 13:
{
w_op13:
{
{
tagged_t vr137 = BcP(f_y,0);
P+=Fs(f_y);
LoadSVA(Yb(vr137));
    }
goto w_op11;
    }
    }
case 10:
P+=Fs(f_Q);
goto w_op11;
case 11:
{
w_op11:
{
{
tagged_t vr138 = BcP(f_y,0);
P+=Fs(f_y);
LoadSVA(Yb(vr138));
    }
goto w_op9;
    }
    }
case 8:
P+=Fs(f_Q);
goto w_op9;
case 9:
{
w_op9:
{
{
tagged_t vr139 = BcP(f_y,0);
P+=Fs(f_y);
LoadSVA(Yb(vr139));
    }
goto w_op7;
    }
    }
case 6:
P+=Fs(f_Q);
goto w_op7;
case 7:
{
w_op7:
{
{
tagged_t vr140 = BcP(f_y,0);
P+=Fs(f_y);
LoadSVA(Yb(vr140));
    }
goto w_op5;
    }
    }
case 4:
P+=Fs(f_Q);
goto w_op5;
case 5:
{
w_op5:
{
{
tagged_t vr141 = BcP(f_y,0);
P+=Fs(f_y);
LoadSVA(Yb(vr141));
    }
goto w_op3;
    }
    }
case 2:
P+=Fs(f_Q);
goto w_op3;
case 3:
w_op3:
E->next_insn = w->next_insn;
E->frame = w->frame;
w->frame = E;
w->next_insn = BCoff(P,Fs(f_E)+Fs(f_e));
w->local_top = StackCharOffset(E,BcP(f_e,0+Fs(f_E)));
if (OffStacktop(E,Stack_Warn)) {
SetEvent();
    }

P = BcP(f_p,0);
goto enter_predicate;
case 40:
P+=Fs(f_Q);
goto w_op41;
case 41:
{
w_op41:
{
intmach_t vr142 = (FTYPE_ctype(f_i_signed))BcP(f_i,0);
P+=Fs(f_i);
for (intmach_t vr143 = vr142;
vr143>8;vr143--) {
tagged_t vr144 = BcP(f_z,0);
P+=Fs(f_z);
if (vr144&1) {
tagged_t vr145;
tagged_t vr146;
vr145 = Yb(vr144+1);
if (TaggedIsSVA(vr145)) {
do {
RefSVA(vr146,vr145);
if (vr146==vr145) {
if (!YoungerStackVar(Tagp(SVA,Offset(E,EToY0)),vr145)) {
LoadHVA(vr145,H);
BindSVA(vr146,vr145);
              }

break;
            }

vr145 = vr146;
          }
 while (TaggedIsSVA(vr145));
        }

X(vr143-1) = vr145;
      }
 else {
X(vr143-1) = Yb(vr144);
      }

    }

goto w_op39;
    }
    }
case 38:
P+=Fs(f_Q);
goto w_op39;
case 39:
{
w_op39:
{
{
tagged_t vr147 = BcP(f_z,0);
P+=Fs(f_z);
if (vr147&1) {
tagged_t vr148;
tagged_t vr149;
vr148 = Yb(vr147+1);
if (TaggedIsSVA(vr148)) {
do {
RefSVA(vr149,vr148);
if (vr149==vr148) {
if (!YoungerStackVar(Tagp(SVA,Offset(E,EToY0)),vr148)) {
LoadHVA(vr148,H);
BindSVA(vr149,vr148);
            }

break;
          }

vr148 = vr149;
        }
 while (TaggedIsSVA(vr148));
      }

X(7) = vr148;
    }
 else {
X(7) = Yb(vr147);
    }

    }
goto w_op37;
    }
    }
case 36:
P+=Fs(f_Q);
goto w_op37;
case 37:
{
w_op37:
{
{
tagged_t vr150 = BcP(f_z,0);
P+=Fs(f_z);
if (vr150&1) {
tagged_t vr151;
tagged_t vr152;
vr151 = Yb(vr150+1);
if (TaggedIsSVA(vr151)) {
do {
RefSVA(vr152,vr151);
if (vr152==vr151) {
if (!YoungerStackVar(Tagp(SVA,Offset(E,EToY0)),vr151)) {
LoadHVA(vr151,H);
BindSVA(vr152,vr151);
            }

break;
          }

vr151 = vr152;
        }
 while (TaggedIsSVA(vr151));
      }

X(6) = vr151;
    }
 else {
X(6) = Yb(vr150);
    }

    }
goto w_op35;
    }
    }
case 34:
P+=Fs(f_Q);
goto w_op35;
case 35:
{
w_op35:
{
{
tagged_t vr153 = BcP(f_z,0);
P+=Fs(f_z);
if (vr153&1) {
tagged_t vr154;
tagged_t vr155;
vr154 = Yb(vr153+1);
if (TaggedIsSVA(vr154)) {
do {
RefSVA(vr155,vr154);
if (vr155==vr154) {
if (!YoungerStackVar(Tagp(SVA,Offset(E,EToY0)),vr154)) {
LoadHVA(vr154,H);
BindSVA(vr155,vr154);
            }

break;
          }

vr154 = vr155;
        }
 while (TaggedIsSVA(vr154));
      }

X(5) = vr154;
    }
 else {
X(5) = Yb(vr153);
    }

    }
goto w_op33;
    }
    }
case 32:
P+=Fs(f_Q);
goto w_op33;
case 33:
{
w_op33:
{
{
tagged_t vr156 = BcP(f_z,0);
P+=Fs(f_z);
if (vr156&1) {
tagged_t vr157;
tagged_t vr158;
vr157 = Yb(vr156+1);
if (TaggedIsSVA(vr157)) {
do {
RefSVA(vr158,vr157);
if (vr158==vr157) {
if (!YoungerStackVar(Tagp(SVA,Offset(E,EToY0)),vr157)) {
LoadHVA(vr157,H);
BindSVA(vr158,vr157);
            }

break;
          }

vr157 = vr158;
        }
 while (TaggedIsSVA(vr157));
      }

X(4) = vr157;
    }
 else {
X(4) = Yb(vr156);
    }

    }
goto w_op31;
    }
    }
case 30:
P+=Fs(f_Q);
goto w_op31;
case 31:
{
w_op31:
{
{
tagged_t vr159 = BcP(f_z,0);
P+=Fs(f_z);
if (vr159&1) {
tagged_t vr160;
tagged_t vr161;
vr160 = Yb(vr159+1);
if (TaggedIsSVA(vr160)) {
do {
RefSVA(vr161,vr160);
if (vr161==vr160) {
if (!YoungerStackVar(Tagp(SVA,Offset(E,EToY0)),vr160)) {
LoadHVA(vr160,H);
BindSVA(vr161,vr160);
            }

break;
          }

vr160 = vr161;
        }
 while (TaggedIsSVA(vr160));
      }

X(3) = vr160;
    }
 else {
X(3) = Yb(vr159);
    }

    }
goto w_op29;
    }
    }
case 28:
P+=Fs(f_Q);
goto w_op29;
case 29:
{
w_op29:
{
{
tagged_t vr162 = BcP(f_z,0);
P+=Fs(f_z);
if (vr162&1) {
tagged_t vr163;
tagged_t vr164;
vr163 = Yb(vr162+1);
if (TaggedIsSVA(vr163)) {
do {
RefSVA(vr164,vr163);
if (vr164==vr163) {
if (!YoungerStackVar(Tagp(SVA,Offset(E,EToY0)),vr163)) {
LoadHVA(vr163,H);
BindSVA(vr164,vr163);
            }

break;
          }

vr163 = vr164;
        }
 while (TaggedIsSVA(vr163));
      }

X(2) = vr163;
    }
 else {
X(2) = Yb(vr162);
    }

    }
goto w_op27;
    }
    }
case 26:
P+=Fs(f_Q);
goto w_op27;
case 27:
{
w_op27:
{
{
tagged_t vr165 = BcP(f_z,0);
P+=Fs(f_z);
if (vr165&1) {
tagged_t vr166;
tagged_t vr167;
vr166 = Yb(vr165+1);
if (TaggedIsSVA(vr166)) {
do {
RefSVA(vr167,vr166);
if (vr167==vr166) {
if (!YoungerStackVar(Tagp(SVA,Offset(E,EToY0)),vr166)) {
LoadHVA(vr166,H);
BindSVA(vr167,vr166);
            }

break;
          }

vr166 = vr167;
        }
 while (TaggedIsSVA(vr166));
      }

X(1) = vr166;
    }
 else {
X(1) = Yb(vr165);
    }

    }
goto w_op25;
    }
    }
case 24:
P+=Fs(f_Q);
goto w_op25;
case 25:
{
w_op25:
{
{
tagged_t vr168 = BcP(f_z,0);
P+=Fs(f_z);
if (vr168&1) {
tagged_t vr169;
tagged_t vr170;
vr169 = Yb(vr168+1);
if (TaggedIsSVA(vr169)) {
do {
RefSVA(vr170,vr169);
if (vr170==vr169) {
if (!YoungerStackVar(Tagp(SVA,Offset(E,EToY0)),vr169)) {
LoadHVA(vr169,H);
BindSVA(vr170,vr169);
            }

break;
          }

vr169 = vr170;
        }
 while (TaggedIsSVA(vr169));
      }

X(0) = vr169;
    }
 else {
X(0) = Yb(vr168);
    }

    }
goto w_op23;
    }
    }
case 22:
P+=Fs(f_Q);
goto w_op23;
case 23:
w_op23:
w->next_insn = BCoff(P,Fs(f_E)+Fs(f_e));
P = BcP(f_p,0);
goto enter_predicate;
case 60:
P+=Fs(f_Q);
goto w_op61;
case 61:
{
w_op61:
{
intmach_t vr171 = (FTYPE_ctype(f_i_signed))BcP(f_i,0);
P+=Fs(f_i);
for (intmach_t vr172 = vr171;
vr172>8;vr172--) {
tagged_t vr173 = BcP(f_z,0);
P+=Fs(f_z);
if (vr173&1) {
tagged_t vr174;
tagged_t vr175;
vr174 = Yb(vr173+1);
if (TaggedIsSVA(vr174)) {
do {
RefSVA(vr175,vr174);
if (vr175==vr174) {
if (!YoungerStackVar(Tagp(SVA,Offset(E,EToY0)),vr174)) {
LoadHVA(vr174,H);
BindSVA(vr175,vr174);
              }

break;
            }

vr174 = vr175;
          }
 while (TaggedIsSVA(vr174));
        }

X(vr172-1) = vr174;
      }
 else {
X(vr172-1) = Yb(vr173);
      }

    }

goto w_op59;
    }
    }
case 58:
P+=Fs(f_Q);
goto w_op59;
case 59:
{
w_op59:
{
{
tagged_t vr176 = BcP(f_z,0);
P+=Fs(f_z);
if (vr176&1) {
tagged_t vr177;
tagged_t vr178;
vr177 = Yb(vr176+1);
if (TaggedIsSVA(vr177)) {
do {
RefSVA(vr178,vr177);
if (vr178==vr177) {
if (!YoungerStackVar(Tagp(SVA,Offset(E,EToY0)),vr177)) {
LoadHVA(vr177,H);
BindSVA(vr178,vr177);
            }

break;
          }

vr177 = vr178;
        }
 while (TaggedIsSVA(vr177));
      }

X(7) = vr177;
    }
 else {
X(7) = Yb(vr176);
    }

    }
goto w_op57;
    }
    }
case 56:
P+=Fs(f_Q);
goto w_op57;
case 57:
{
w_op57:
{
{
tagged_t vr179 = BcP(f_z,0);
P+=Fs(f_z);
if (vr179&1) {
tagged_t vr180;
tagged_t vr181;
vr180 = Yb(vr179+1);
if (TaggedIsSVA(vr180)) {
do {
RefSVA(vr181,vr180);
if (vr181==vr180) {
if (!YoungerStackVar(Tagp(SVA,Offset(E,EToY0)),vr180)) {
LoadHVA(vr180,H);
BindSVA(vr181,vr180);
            }

break;
          }

vr180 = vr181;
        }
 while (TaggedIsSVA(vr180));
      }

X(6) = vr180;
    }
 else {
X(6) = Yb(vr179);
    }

    }
goto w_op55;
    }
    }
case 54:
P+=Fs(f_Q);
goto w_op55;
case 55:
{
w_op55:
{
{
tagged_t vr182 = BcP(f_z,0);
P+=Fs(f_z);
if (vr182&1) {
tagged_t vr183;
tagged_t vr184;
vr183 = Yb(vr182+1);
if (TaggedIsSVA(vr183)) {
do {
RefSVA(vr184,vr183);
if (vr184==vr183) {
if (!YoungerStackVar(Tagp(SVA,Offset(E,EToY0)),vr183)) {
LoadHVA(vr183,H);
BindSVA(vr184,vr183);
            }

break;
          }

vr183 = vr184;
        }
 while (TaggedIsSVA(vr183));
      }

X(5) = vr183;
    }
 else {
X(5) = Yb(vr182);
    }

    }
goto w_op53;
    }
    }
case 52:
P+=Fs(f_Q);
goto w_op53;
case 53:
{
w_op53:
{
{
tagged_t vr185 = BcP(f_z,0);
P+=Fs(f_z);
if (vr185&1) {
tagged_t vr186;
tagged_t vr187;
vr186 = Yb(vr185+1);
if (TaggedIsSVA(vr186)) {
do {
RefSVA(vr187,vr186);
if (vr187==vr186) {
if (!YoungerStackVar(Tagp(SVA,Offset(E,EToY0)),vr186)) {
LoadHVA(vr186,H);
BindSVA(vr187,vr186);
            }

break;
          }

vr186 = vr187;
        }
 while (TaggedIsSVA(vr186));
      }

X(4) = vr186;
    }
 else {
X(4) = Yb(vr185);
    }

    }
goto w_op51;
    }
    }
case 50:
P+=Fs(f_Q);
goto w_op51;
case 51:
{
w_op51:
{
{
tagged_t vr188 = BcP(f_z,0);
P+=Fs(f_z);
if (vr188&1) {
tagged_t vr189;
tagged_t vr190;
vr189 = Yb(vr188+1);
if (TaggedIsSVA(vr189)) {
do {
RefSVA(vr190,vr189);
if (vr190==vr189) {
if (!YoungerStackVar(Tagp(SVA,Offset(E,EToY0)),vr189)) {
LoadHVA(vr189,H);
BindSVA(vr190,vr189);
            }

break;
          }

vr189 = vr190;
        }
 while (TaggedIsSVA(vr189));
      }

X(3) = vr189;
    }
 else {
X(3) = Yb(vr188);
    }

    }
goto w_op49;
    }
    }
case 48:
P+=Fs(f_Q);
goto w_op49;
case 49:
{
w_op49:
{
{
tagged_t vr191 = BcP(f_z,0);
P+=Fs(f_z);
if (vr191&1) {
tagged_t vr192;
tagged_t vr193;
vr192 = Yb(vr191+1);
if (TaggedIsSVA(vr192)) {
do {
RefSVA(vr193,vr192);
if (vr193==vr192) {
if (!YoungerStackVar(Tagp(SVA,Offset(E,EToY0)),vr192)) {
LoadHVA(vr192,H);
BindSVA(vr193,vr192);
            }

break;
          }

vr192 = vr193;
        }
 while (TaggedIsSVA(vr192));
      }

X(2) = vr192;
    }
 else {
X(2) = Yb(vr191);
    }

    }
goto w_op47;
    }
    }
case 46:
P+=Fs(f_Q);
goto w_op47;
case 47:
{
w_op47:
{
{
tagged_t vr194 = BcP(f_z,0);
P+=Fs(f_z);
if (vr194&1) {
tagged_t vr195;
tagged_t vr196;
vr195 = Yb(vr194+1);
if (TaggedIsSVA(vr195)) {
do {
RefSVA(vr196,vr195);
if (vr196==vr195) {
if (!YoungerStackVar(Tagp(SVA,Offset(E,EToY0)),vr195)) {
LoadHVA(vr195,H);
BindSVA(vr196,vr195);
            }

break;
          }

vr195 = vr196;
        }
 while (TaggedIsSVA(vr195));
      }

X(1) = vr195;
    }
 else {
X(1) = Yb(vr194);
    }

    }
goto w_op45;
    }
    }
case 44:
P+=Fs(f_Q);
goto w_op45;
case 45:
{
w_op45:
{
{
tagged_t vr197 = BcP(f_z,0);
P+=Fs(f_z);
if (vr197&1) {
tagged_t vr198;
tagged_t vr199;
vr198 = Yb(vr197+1);
if (TaggedIsSVA(vr198)) {
do {
RefSVA(vr199,vr198);
if (vr199==vr198) {
if (!YoungerStackVar(Tagp(SVA,Offset(E,EToY0)),vr198)) {
LoadHVA(vr198,H);
BindSVA(vr199,vr198);
            }

break;
          }

vr198 = vr199;
        }
 while (TaggedIsSVA(vr198));
      }

X(0) = vr198;
    }
 else {
X(0) = Yb(vr197);
    }

    }
goto w_op43;
    }
    }
case 42:
P+=Fs(f_Q);
goto w_op43;
case 43:
w_op43:
w->next_insn = E->next_insn;
w->frame = E->frame;
goto w_op63;
case 62:
P = BcP(f_p,0+Fs(f_Q));
goto enter_predicate;
case 63:
w_op63:
P = BcP(f_p,0);
goto enter_predicate;
case 69:
w_op69:
LoadHVA(Xb(BcP(f_x,0)),H);
P+=Fs(f_x);
goto w_dispatch;
case 70:
{
w_op70:
{
{
tagged_t vr200;
vr200 = Tagp(HVA,H);
Xb(BcP(f_x,0+Fs(f_x))) = vr200;
Xb(BcP(f_x,0)) = vr200;
HeapPush(H,vr200);
    }
P+=Fs(f_x)+Fs(f_x);
goto w_dispatch;
    }
    }
case 85:
Xb(BcP(f_x,0)) = Xb(BcP(f_x,0+Fs(f_x)));
Xb(BcP(f_x,0+Fs(f_x)+Fs(f_x))) = Xb(BcP(f_x,0+Fs(f_x)+Fs(f_x)+Fs(f_x)));
P+=Fs(f_x)+Fs(f_x)+Fs(f_x)+Fs(f_x);
goto w_dispatch;
case 71:
Xb(BcP(f_x,0)) = Xb(BcP(f_x,0+Fs(f_x)));
P+=Fs(f_x)+Fs(f_x);
goto w_dispatch;
case 72:
{
w_op72:
{
tagged_t vr201;
tagged_t vr202;
tagged_t vr203;
vr202 = Xb(BcP(f_x,0+Fs(f_x)));
if (TaggedIsSVA(vr202)) {
do {
RefSVA(vr203,vr202);
if (vr203==vr202) {
if (!YoungerStackVar(Tagp(SVA,Offset(E,EToY0)),vr202)) {
LoadHVA(vr202,H);
BindSVA(vr203,vr202);
          }

break;
        }

vr202 = vr203;
      }
 while (TaggedIsSVA(vr202));
    }

vr201 = vr202;
Xb(BcP(f_x,0)) = vr201;
Xb(BcP(f_x,0+Fs(f_x))) = vr201;
P+=Fs(f_x)+Fs(f_x);
goto w_dispatch;
    }
    }
case 73:
w_op73:
CODE_ALLOC(E);
goto w_op74;
case 74:
{
w_op74:
{
{
tagged_t vr204;
vr204 = Tagp(SVA,&Yb(BcP(f_y,0+Fs(f_x))));
Yb(BcP(f_y,0+Fs(f_x))) = vr204;
Xb(BcP(f_x,0)) = vr204;
    }
P+=Fs(f_x)+Fs(f_y);
goto w_dispatch;
    }
    }
case 83:
w_op83:
CODE_ALLOC(E);
goto w_op84;
case 84:
{
w_op84:
{
{
tagged_t vr205;
vr205 = Tagp(SVA,&Yb(BcP(f_y,0+Fs(f_x))));
Yb(BcP(f_y,0+Fs(f_x))) = vr205;
Xb(BcP(f_x,0)) = vr205;
    }
{
tagged_t vr206;
vr206 = Tagp(SVA,&Yb(BcP(f_y,0+Fs(f_x)+Fs(f_y)+Fs(f_x))));
Yb(BcP(f_y,0+Fs(f_x)+Fs(f_y)+Fs(f_x))) = vr206;
Xb(BcP(f_x,0+Fs(f_x)+Fs(f_y))) = vr206;
    }
P+=Fs(f_x)+Fs(f_y)+Fs(f_x)+Fs(f_y);
goto w_dispatch;
    }
    }
case 75:
Xb(BcP(f_x,0)) = Yb(BcP(f_y,0+Fs(f_x)));
P+=Fs(f_x)+Fs(f_y);
goto w_dispatch;
case 76:
{
w_op76:
{
tagged_t vr207;
tagged_t vr208;
vr207 = Yb(BcP(f_y,0+Fs(f_x)));
if (TaggedIsSVA(vr207)) {
do {
RefSVA(vr208,vr207);
if (vr208==vr207) {
if (!YoungerStackVar(Tagp(SVA,Offset(E,EToY0)),vr207)) {
LoadHVA(vr207,H);
BindSVA(vr208,vr207);
          }

break;
        }

vr207 = vr208;
      }
 while (TaggedIsSVA(vr207));
    }

Xb(BcP(f_x,0)) = vr207;
P+=Fs(f_x)+Fs(f_y);
goto w_dispatch;
    }
    }
case 77:
Xb(BcP(f_x,0+Fs(f_Q))) = BcP(f_t,0+Fs(f_Q)+Fs(f_x));
P+=Fs(f_Q)+Fs(f_x)+Fs(f_t);
goto w_dispatch;
case 78:
Xb(BcP(f_x,0)) = BcP(f_t,0+Fs(f_x));
P+=Fs(f_x)+Fs(f_t);
goto w_dispatch;
case 81:
Xb(BcP(f_x,0)) = atom_nil;
P+=Fs(f_x);
goto w_dispatch;
case 252:
w_op252:
w->heap_top = H;
Xb(BcP(f_x,0+Fs(f_Q))) = BC_MakeBlob(w,&BcP(f_t,0+Fs(f_Q)+Fs(f_x)));
H = w->heap_top;
P+=Fs(f_Q)+Fs(f_x)+LargeSize(*&BcP(f_t,0+Fs(f_Q)+Fs(f_x)));
goto w_dispatch;
case 253:
w_op253:
w->heap_top = H;
Xb(BcP(f_x,0)) = BC_MakeBlob(w,&BcP(f_t,0+Fs(f_x)));
H = w->heap_top;
P+=Fs(f_x)+LargeSize(*&BcP(f_t,0+Fs(f_x)));
goto w_dispatch;
case 79:
w_op79:
Xb(BcP(f_x,0+Fs(f_Q))) = Tagp(STR,H);
HeapPush(H,BcP(f_f,0+Fs(f_Q)+Fs(f_x)));
P+=Fs(f_Q)+Fs(f_x)+Fs(f_f);
goto w_dispatch;
case 80:
w_op80:
Xb(BcP(f_x,0)) = Tagp(STR,H);
HeapPush(H,BcP(f_f,0+Fs(f_x)));
P+=Fs(f_x)+Fs(f_f);
goto w_dispatch;
case 82:
w_op82:
Xb(BcP(f_x,0)) = Tagp(LST,H);
P+=Fs(f_x);
goto w_dispatch;
case 86:
Xb(BcP(f_x,0)) = Yb(BcP(f_y,0+Fs(f_x)));
Xb(BcP(f_x,0+Fs(f_x)+Fs(f_y))) = Yb(BcP(f_y,0+Fs(f_x)+Fs(f_y)+Fs(f_x)));
P+=Fs(f_x)+Fs(f_y)+Fs(f_x)+Fs(f_y);
goto w_dispatch;
case 87:
{
w_op87:
{
Xb(BcP(f_x,0)) = Yb(BcP(f_y,0+Fs(f_x)));
tagged_t vr209;
tagged_t vr210;
vr209 = Yb(BcP(f_y,0+Fs(f_x)+Fs(f_y)+Fs(f_x)));
if (TaggedIsSVA(vr209)) {
do {
RefSVA(vr210,vr209);
if (vr210==vr209) {
if (!YoungerStackVar(Tagp(SVA,Offset(E,EToY0)),vr209)) {
LoadHVA(vr209,H);
BindSVA(vr210,vr209);
          }

break;
        }

vr209 = vr210;
      }
 while (TaggedIsSVA(vr209));
    }

Xb(BcP(f_x,0+Fs(f_x)+Fs(f_y))) = vr209;
P+=Fs(f_x)+Fs(f_y)+Fs(f_x)+Fs(f_y);
goto w_dispatch;
    }
    }
case 88:
{
w_op88:
{
tagged_t vr211;
tagged_t vr212;
vr211 = Yb(BcP(f_y,0+Fs(f_x)));
if (TaggedIsSVA(vr211)) {
do {
RefSVA(vr212,vr211);
if (vr212==vr211) {
if (!YoungerStackVar(Tagp(SVA,Offset(E,EToY0)),vr211)) {
LoadHVA(vr211,H);
BindSVA(vr212,vr211);
          }

break;
        }

vr211 = vr212;
      }
 while (TaggedIsSVA(vr211));
    }

Xb(BcP(f_x,0)) = vr211;
Xb(BcP(f_x,0+Fs(f_x)+Fs(f_y))) = Yb(BcP(f_y,0+Fs(f_x)+Fs(f_y)+Fs(f_x)));
P+=Fs(f_x)+Fs(f_y)+Fs(f_x)+Fs(f_y);
goto w_dispatch;
    }
    }
case 89:
{
w_op89:
{
tagged_t vr213;
tagged_t vr214;
vr213 = Yb(BcP(f_y,0+Fs(f_x)));
if (TaggedIsSVA(vr213)) {
do {
RefSVA(vr214,vr213);
if (vr214==vr213) {
if (!YoungerStackVar(Tagp(SVA,Offset(E,EToY0)),vr213)) {
LoadHVA(vr213,H);
BindSVA(vr214,vr213);
          }

break;
        }

vr213 = vr214;
      }
 while (TaggedIsSVA(vr213));
    }

Xb(BcP(f_x,0)) = vr213;
tagged_t vr215;
tagged_t vr216;
vr215 = Yb(BcP(f_y,0+Fs(f_x)+Fs(f_y)+Fs(f_x)));
if (TaggedIsSVA(vr215)) {
do {
RefSVA(vr216,vr215);
if (vr216==vr215) {
if (!YoungerStackVar(Tagp(SVA,Offset(E,EToY0)),vr215)) {
LoadHVA(vr215,H);
BindSVA(vr216,vr215);
          }

break;
        }

vr215 = vr216;
      }
 while (TaggedIsSVA(vr215));
    }

Xb(BcP(f_x,0+Fs(f_x)+Fs(f_y))) = vr215;
P+=Fs(f_x)+Fs(f_y)+Fs(f_x)+Fs(f_y);
goto w_dispatch;
    }
    }
case 91:
w->heap_top = H;
goto r_op91;
case 94:
w->heap_top = H;
goto r_op94;
case 95:
w->heap_top = H;
goto r_op95;
case 96:
P+=Fs(f_Q);
goto w_op97;
case 97:
w_op97:
w->heap_top = H;
goto r_op97;
case 254:
P+=Fs(f_Q);
goto w_op255;
case 255:
w_op255:
w->heap_top = H;
goto r_op255;
case 98:
P+=Fs(f_Q);
goto w_op99;
case 99:
w_op99:
w->heap_top = H;
goto r_op99;
case 100:
w->heap_top = H;
goto r_op100;
case 101:
w->heap_top = H;
goto r_op101;
case 111:
P+=Fs(f_Q);
goto w_op112;
case 112:
w_op112:
w->heap_top = H;
goto r_op112;
case 113:
w->heap_top = H;
goto r_op113;
case 208:
w->heap_top = H;
goto r_op208;
case 210:
w->heap_top = H;
goto r_op210;
case 211:
w->heap_top = H;
goto r_op211;
case 212:
w->heap_top = H;
goto r_op212;
case 213:
w->heap_top = H;
goto r_op213;
case 214:
w->heap_top = H;
goto r_op214;
case 216:
w->heap_top = H;
goto r_op216;
case 217:
w->heap_top = H;
goto r_op217;
case 215:
w->heap_top = H;
goto r_op215;
case 209:
w->heap_top = H;
goto r_op209;
case 218:
w->heap_top = H;
goto r_op218;
case 219:
Xb(BcP(f_x,0)) = ChoiceToTagged(w->previous_choice);
P+=Fs(f_x);
goto w_dispatch;
case 220:
CODE_ALLOC(E);
goto w_op221;
case 221:
w_op221:
Yb(BcP(f_y,0)) = ChoiceToTagged(w->previous_choice);
P+=Fs(f_y);
goto w_dispatch;
case 233:
{
w_op233:
{
Setfunc(TaggedToFunctor(Y(0)));
for (intmach_t vr217 = 0;
vr217<Func->arity;vr217++) {
X(vr217) = Y(vr217+1);
    }

w->next_insn = E->next_insn;
w->frame = E->frame;
goto enter_predicate;
    }
    }
case 234:
w->heap_top = H;
goto r_op234;
case 235:
w->heap_top = H;
goto r_op235;
case 237:
w->heap_top = H;
goto r_op237;
case 238:
w->heap_top = H;
goto r_op238;
case 104:
P+=Fs(f_Q);
goto w_op105;
case 105:
{
w_op105:
{
tagged_t vr218 = Tagp(STR,H);
tagged_t vr219 = X(0);
if (TaggedIsHVA(vr219)) {
BindHVA(vr219,vr218);
    }
 else if (vr219&TagBitSVA) {
BindSVA(vr219,vr218);
    }
 else {
BindCVA(vr219,vr218);
    }

HeapPush(H,BcP(f_f,0));
P+=Fs(f_f);
goto w_dispatch;
    }
    }
case 256:
P+=Fs(f_Q);
goto w_op257;
case 257:
{
w_op257:
{
w->heap_top = H;
tagged_t vr220 = BC_MakeBlob(w,&BcP(f_t,0));
H = w->heap_top;
tagged_t vr221 = X(0);
if (TaggedIsHVA(vr221)) {
BindHVA(vr221,vr220);
    }
 else if (vr221&TagBitSVA) {
BindSVA(vr221,vr220);
    }
 else {
BindCVA(vr221,vr220);
    }

P+=LargeSize(*&BcP(f_t,0));
goto w_dispatch;
    }
    }
case 102:
P+=Fs(f_Q);
goto w_op103;
case 103:
{
w_op103:
{
tagged_t vr222 = X(0);
if (TaggedIsHVA(vr222)) {
BindHVA(vr222,BcP(f_t,0));
    }
 else if (vr222&TagBitSVA) {
BindSVA(vr222,BcP(f_t,0));
    }
 else {
BindCVA(vr222,BcP(f_t,0));
    }

P+=Fs(f_t);
goto w_dispatch;
    }
    }
case 106:
{
{
tagged_t vr223 = X(0);
if (TaggedIsHVA(vr223)) {
BindHVA(vr223,atom_nil);
    }
 else if (vr223&TagBitSVA) {
BindSVA(vr223,atom_nil);
    }
 else {
BindCVA(vr223,atom_nil);
    }

P+=0;
goto w_dispatch;
    }
    }
case 107:
{
{
tagged_t vr224 = Tagp(LST,H);
tagged_t vr225 = X(0);
if (TaggedIsHVA(vr225)) {
BindHVA(vr225,vr224);
    }
 else if (vr225&TagBitSVA) {
BindSVA(vr225,vr224);
    }
 else {
BindCVA(vr225,vr224);
    }

P+=0;
goto w_dispatch;
    }
    }
case 108:
Xb(BcP(f_x,0+Fs(f_x))) = Xb(BcP(f_x,0));
Xb(BcP(f_x,0+Fs(f_x)+Fs(f_x)+Fs(f_x))) = Xb(BcP(f_x,0+Fs(f_x)+Fs(f_x)));
P+=Fs(f_x)+Fs(f_x)+Fs(f_x)+Fs(f_x);
goto w_dispatch;
case 90:
Xb(BcP(f_x,0+Fs(f_x))) = Xb(BcP(f_x,0));
P+=Fs(f_x)+Fs(f_x);
goto w_dispatch;
case 92:
CODE_ALLOC(E);
goto w_op93;
case 93:
w_op93:
Yb(BcP(f_y,0+Fs(f_x))) = Xb(BcP(f_x,0));
P+=Fs(f_x)+Fs(f_y);
goto w_dispatch;
case 109:
CODE_ALLOC(E);
goto w_op110;
case 110:
w_op110:
Yb(BcP(f_y,0+Fs(f_x))) = Xb(BcP(f_x,0));
Yb(BcP(f_y,0+Fs(f_x)+Fs(f_y)+Fs(f_x))) = Xb(BcP(f_x,0+Fs(f_x)+Fs(f_y)));
P+=Fs(f_x)+Fs(f_y)+Fs(f_x)+Fs(f_y);
goto w_dispatch;
case 68:
P = BCoff(P,BcP(f_i,0));
goto w_dispatch;
case 222:
w->heap_top = H;
goto r_op222;
case 223:
w->heap_top = H;
goto r_op223;
case 224:
w->heap_top = H;
goto r_op224;
case 225:
w->heap_top = H;
goto r_op225;
case 226:
w->heap_top = H;
goto r_op226;
case 227:
w->heap_top = H;
goto r_op227;
case 228:
w->heap_top = H;
goto r_op228;
case 229:
w->heap_top = H;
goto r_op229;
case 230:
w->heap_top = H;
goto r_op230;
case 231:
w->heap_top = H;
goto r_op231;
case 232:
w->heap_top = H;
goto r_op232;
case 247:
{
w_op247:
{
tagged_t vr226 = Xb(BcP(f_x,0));
tagged_t vr227;
LoadCVA(vr227,H);
DerefSw_HVA_CVA_SVA_Other(vr226,{
BindHVA(vr226,vr227);
Xb(BcP(f_x,0)) = vr227;
    }
,{
BindCVA(vr227,vr226);
    }
,{
BindSVA(vr226,vr227);
Xb(BcP(f_x,0)) = vr227;
    }
,{
BindCVA(vr227,vr226);
    }
);
P+=Fs(f_x);
goto w_dispatch;
    }
    }
case 114:
{
{
intmach_t vr228 = (FTYPE_ctype(f_i_signed))BcP(f_i,0);
P+=Fs(f_i);
for (intmach_t vr229 = vr228;
vr229>4;vr229--) {
ConstrHVA(H);
    }

goto w_op118;
    }
    }
case 115:
w_op115:
ConstrHVA(H);
P+=0;
goto w_dispatch;
case 116:
w_op116:
ConstrHVA(H);
goto w_op115;
case 117:
w_op117:
ConstrHVA(H);
goto w_op116;
case 118:
w_op118:
ConstrHVA(H);
goto w_op117;
case 119:
LoadHVA(Xb(BcP(f_x,0)),H);
P+=Fs(f_x);
goto w_dispatch;
case 120:
HeapPush(H,Xb(BcP(f_x,0)));
P+=Fs(f_x);
goto w_dispatch;
case 121:
{
{
{tagged_t vr230 = Xb(BcP(f_x,0));
if (TaggedIsSVA(vr230)) {
tagged_t vr231;
do {
RefSVA(vr231,vr230);
if (vr231==vr230) {
BindSVA(vr230,Tagp(HVA,H));
PreLoadHVA(vr230,H);
break;
        }

vr230 = vr231;
      }
 while (TaggedIsSVA(vr230));
    }

HeapPush(H,vr230);
}P+=Fs(f_x);
goto w_dispatch;
    }
    }
case 122:
CODE_ALLOC(E);
goto w_op123;
case 123:
w_op123:
LoadHVA(Yb(BcP(f_y,0)),H);
P+=Fs(f_y);
goto w_dispatch;
case 124:
{
{
{tagged_t vr232;
LoadHVA(vr232,H);
if (CondStackvar(Yb(BcP(f_y,0)))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0))));
    }

Yb(BcP(f_y,0)) = vr232;
}P+=Fs(f_y);
goto w_dispatch;
    }
    }
case 125:
HeapPush(H,Yb(BcP(f_y,0)));
P+=Fs(f_y);
goto w_dispatch;
case 126:
{
{
{tagged_t vr233 = Yb(BcP(f_y,0));
if (TaggedIsSVA(vr233)) {
tagged_t vr234;
do {
RefSVA(vr234,vr233);
if (vr234==vr233) {
BindSVA(vr233,Tagp(HVA,H));
PreLoadHVA(vr233,H);
break;
        }

vr233 = vr234;
      }
 while (TaggedIsSVA(vr233));
    }

HeapPush(H,vr233);
}P+=Fs(f_y);
goto w_dispatch;
    }
    }
case 127:
HeapPush(H,BcP(f_t,0+Fs(f_Q)));
P+=Fs(f_Q)+Fs(f_t);
goto w_dispatch;
case 128:
HeapPush(H,BcP(f_t,0));
P+=Fs(f_t);
goto w_dispatch;
case 258:
P+=Fs(f_Q);
goto w_op259;
case 259:
w_op259:
w->heap_top = HeapOffset(H,1);
*H = BC_MakeBlob(w,&BcP(f_t,0));
P+=LargeSize(*&BcP(f_t,0));
goto r_dispatch;
case 129:
HeapPush(H,Tagp(STR,HeapOffset(H,1)));
HeapPush(H,BcP(f_f,0+Fs(f_Q)));
P+=Fs(f_Q)+Fs(f_f);
goto w_dispatch;
case 130:
HeapPush(H,Tagp(STR,HeapOffset(H,1)));
HeapPush(H,BcP(f_f,0));
P+=Fs(f_f);
goto w_dispatch;
case 131:
HeapPush(H,atom_nil);
P+=0;
goto w_dispatch;
case 132:
HeapPush(H,Tagp(LST,HeapOffset(H,1)));
P+=0;
goto w_dispatch;
case 133:
HeapPush(H,BcP(f_t,0+Fs(f_Q)));
goto w_op66;
case 134:
HeapPush(H,BcP(f_t,0));
goto w_op66;
case 135:
HeapPush(H,atom_nil);
goto w_op66;
case 136:
{
{
intmach_t vr235 = (FTYPE_ctype(f_i_signed))BcP(f_i,0);
do {
ConstrHVA(H);
    }
 while (--vr235);
LoadHVA(Xb(BcP(f_x,0+Fs(f_i))),H);
P+=Fs(f_i)+Fs(f_x);
goto w_dispatch;
    }
    }
case 139:
CODE_ALLOC(E);
goto w_op140;
case 140:
{
w_op140:
{
intmach_t vr236 = (FTYPE_ctype(f_i_signed))BcP(f_i,0);
do {
ConstrHVA(H);
    }
 while (--vr236);
LoadHVA(Yb(BcP(f_y,0+Fs(f_i))),H);
P+=Fs(f_i)+Fs(f_y);
goto w_dispatch;
    }
    }
case 137:
{
{
intmach_t vr237 = (FTYPE_ctype(f_i_signed))BcP(f_i,0);
do {
ConstrHVA(H);
    }
 while (--vr237);
HeapPush(H,Xb(BcP(f_x,0+Fs(f_i))));
P+=Fs(f_i)+Fs(f_x);
goto w_dispatch;
    }
    }
case 138:
{
{
intmach_t vr238 = (FTYPE_ctype(f_i_signed))BcP(f_i,0);
do {
ConstrHVA(H);
    }
 while (--vr238);
{tagged_t vr239 = Xb(BcP(f_x,0+Fs(f_i)));
if (TaggedIsSVA(vr239)) {
tagged_t vr240;
do {
RefSVA(vr240,vr239);
if (vr240==vr239) {
BindSVA(vr239,Tagp(HVA,H));
PreLoadHVA(vr239,H);
break;
        }

vr239 = vr240;
      }
 while (TaggedIsSVA(vr239));
    }

HeapPush(H,vr239);
}P+=Fs(f_i)+Fs(f_x);
goto w_dispatch;
    }
    }
case 141:
{
{
intmach_t vr241 = (FTYPE_ctype(f_i_signed))BcP(f_i,0);
do {
ConstrHVA(H);
    }
 while (--vr241);
{tagged_t vr242;
LoadHVA(vr242,H);
if (CondStackvar(Yb(BcP(f_y,0+Fs(f_i))))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0+Fs(f_i)))));
    }

Yb(BcP(f_y,0+Fs(f_i))) = vr242;
}P+=Fs(f_i)+Fs(f_y);
goto w_dispatch;
    }
    }
case 142:
{
{
intmach_t vr243 = (FTYPE_ctype(f_i_signed))BcP(f_i,0);
do {
ConstrHVA(H);
    }
 while (--vr243);
HeapPush(H,Yb(BcP(f_y,0+Fs(f_i))));
P+=Fs(f_i)+Fs(f_y);
goto w_dispatch;
    }
    }
case 143:
{
{
intmach_t vr244 = (FTYPE_ctype(f_i_signed))BcP(f_i,0);
do {
ConstrHVA(H);
    }
 while (--vr244);
{tagged_t vr245 = Yb(BcP(f_y,0+Fs(f_i)));
if (TaggedIsSVA(vr245)) {
tagged_t vr246;
do {
RefSVA(vr246,vr245);
if (vr246==vr245) {
BindSVA(vr245,Tagp(HVA,H));
PreLoadHVA(vr245,H);
break;
        }

vr245 = vr246;
      }
 while (TaggedIsSVA(vr245));
    }

HeapPush(H,vr245);
}P+=Fs(f_i)+Fs(f_y);
goto w_dispatch;
    }
    }
case 144:
{
{
LoadHVA(Xb(BcP(f_x,0)),H);
intmach_t vr247 = (FTYPE_ctype(f_i_signed))BcP(f_i,0+Fs(f_x));
do {
ConstrHVA(H);
    }
 while (--vr247);
P+=Fs(f_x)+Fs(f_i);
goto w_dispatch;
    }
    }
case 145:
LoadHVA(Xb(BcP(f_x,0)),H);
LoadHVA(Xb(BcP(f_x,0+Fs(f_x))),H);
P+=Fs(f_x)+Fs(f_x);
goto w_dispatch;
case 148:
CODE_ALLOC(E);
goto w_op149;
case 149:
w_op149:
LoadHVA(Xb(BcP(f_x,0)),H);
LoadHVA(Yb(BcP(f_y,0+Fs(f_x))),H);
P+=Fs(f_x)+Fs(f_y);
goto w_dispatch;
case 146:
LoadHVA(Xb(BcP(f_x,0)),H);
HeapPush(H,Xb(BcP(f_x,0+Fs(f_x))));
P+=Fs(f_x)+Fs(f_x);
goto w_dispatch;
case 147:
{
{
LoadHVA(Xb(BcP(f_x,0)),H);
{tagged_t vr248 = Xb(BcP(f_x,0+Fs(f_x)));
if (TaggedIsSVA(vr248)) {
tagged_t vr249;
do {
RefSVA(vr249,vr248);
if (vr249==vr248) {
BindSVA(vr248,Tagp(HVA,H));
PreLoadHVA(vr248,H);
break;
        }

vr248 = vr249;
      }
 while (TaggedIsSVA(vr248));
    }

HeapPush(H,vr248);
}P+=Fs(f_x)+Fs(f_x);
goto w_dispatch;
    }
    }
case 150:
{
{
LoadHVA(Xb(BcP(f_x,0)),H);
{tagged_t vr250;
LoadHVA(vr250,H);
if (CondStackvar(Yb(BcP(f_y,0+Fs(f_x))))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0+Fs(f_x)))));
    }

Yb(BcP(f_y,0+Fs(f_x))) = vr250;
}P+=Fs(f_x)+Fs(f_y);
goto w_dispatch;
    }
    }
case 151:
LoadHVA(Xb(BcP(f_x,0)),H);
HeapPush(H,Yb(BcP(f_y,0+Fs(f_x))));
P+=Fs(f_x)+Fs(f_y);
goto w_dispatch;
case 152:
{
{
LoadHVA(Xb(BcP(f_x,0)),H);
{tagged_t vr251 = Yb(BcP(f_y,0+Fs(f_x)));
if (TaggedIsSVA(vr251)) {
tagged_t vr252;
do {
RefSVA(vr252,vr251);
if (vr252==vr251) {
BindSVA(vr251,Tagp(HVA,H));
PreLoadHVA(vr251,H);
break;
        }

vr251 = vr252;
      }
 while (TaggedIsSVA(vr251));
    }

HeapPush(H,vr251);
}P+=Fs(f_x)+Fs(f_y);
goto w_dispatch;
    }
    }
case 153:
CODE_ALLOC(E);
goto w_op154;
case 154:
{
w_op154:
{
LoadHVA(Yb(BcP(f_y,0)),H);
intmach_t vr253 = (FTYPE_ctype(f_i_signed))BcP(f_i,0+Fs(f_y));
do {
ConstrHVA(H);
    }
 while (--vr253);
P+=Fs(f_y)+Fs(f_i);
goto w_dispatch;
    }
    }
case 155:
CODE_ALLOC(E);
goto w_op156;
case 156:
w_op156:
LoadHVA(Yb(BcP(f_y,0)),H);
LoadHVA(Xb(BcP(f_x,0+Fs(f_y))),H);
P+=Fs(f_y)+Fs(f_x);
goto w_dispatch;
case 157:
CODE_ALLOC(E);
goto w_op158;
case 158:
w_op158:
LoadHVA(Yb(BcP(f_y,0)),H);
LoadHVA(Yb(BcP(f_y,0+Fs(f_y))),H);
P+=Fs(f_y)+Fs(f_y);
goto w_dispatch;
case 159:
CODE_ALLOC(E);
goto w_op160;
case 161:
CODE_ALLOC(E);
goto w_op162;
case 160:
w_op160:
LoadHVA(Yb(BcP(f_y,0)),H);
HeapPush(H,Xb(BcP(f_x,0+Fs(f_y))));
P+=Fs(f_y)+Fs(f_x);
goto w_dispatch;
case 162:
{
w_op162:
{
LoadHVA(Yb(BcP(f_y,0)),H);
{tagged_t vr254 = Xb(BcP(f_x,0+Fs(f_y)));
if (TaggedIsSVA(vr254)) {
tagged_t vr255;
do {
RefSVA(vr255,vr254);
if (vr255==vr254) {
BindSVA(vr254,Tagp(HVA,H));
PreLoadHVA(vr254,H);
break;
        }

vr254 = vr255;
      }
 while (TaggedIsSVA(vr254));
    }

HeapPush(H,vr254);
}P+=Fs(f_y)+Fs(f_x);
goto w_dispatch;
    }
    }
case 163:
CODE_ALLOC(E);
goto w_op164;
case 165:
CODE_ALLOC(E);
goto w_op166;
case 164:
w_op164:
LoadHVA(Yb(BcP(f_y,0)),H);
HeapPush(H,Yb(BcP(f_y,0+Fs(f_y))));
P+=Fs(f_y)+Fs(f_y);
goto w_dispatch;
case 166:
{
w_op166:
{
LoadHVA(Yb(BcP(f_y,0)),H);
{tagged_t vr256 = Yb(BcP(f_y,0+Fs(f_y)));
if (TaggedIsSVA(vr256)) {
tagged_t vr257;
do {
RefSVA(vr257,vr256);
if (vr257==vr256) {
BindSVA(vr256,Tagp(HVA,H));
PreLoadHVA(vr256,H);
break;
        }

vr256 = vr257;
      }
 while (TaggedIsSVA(vr256));
    }

HeapPush(H,vr256);
}P+=Fs(f_y)+Fs(f_y);
goto w_dispatch;
    }
    }
case 185:
{
{
{tagged_t vr258;
LoadHVA(vr258,H);
if (CondStackvar(Yb(BcP(f_y,0)))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0))));
    }

Yb(BcP(f_y,0)) = vr258;
}intmach_t vr259 = (FTYPE_ctype(f_i_signed))BcP(f_i,0+Fs(f_y));
do {
ConstrHVA(H);
    }
 while (--vr259);
P+=Fs(f_y)+Fs(f_i);
goto w_dispatch;
    }
    }
case 188:
{
{
{tagged_t vr260;
LoadHVA(vr260,H);
if (CondStackvar(Yb(BcP(f_y,0)))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0))));
    }

Yb(BcP(f_y,0)) = vr260;
}LoadHVA(Xb(BcP(f_x,0+Fs(f_y))),H);
P+=Fs(f_y)+Fs(f_x);
goto w_dispatch;
    }
    }
case 199:
{
{
{tagged_t vr261;
LoadHVA(vr261,H);
if (CondStackvar(Yb(BcP(f_y,0)))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0))));
    }

Yb(BcP(f_y,0)) = vr261;
}{tagged_t vr262;
LoadHVA(vr262,H);
if (CondStackvar(Yb(BcP(f_y,0+Fs(f_y))))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0+Fs(f_y)))));
    }

Yb(BcP(f_y,0+Fs(f_y))) = vr262;
}P+=Fs(f_y)+Fs(f_y);
goto w_dispatch;
    }
    }
case 193:
{
{
{tagged_t vr263;
LoadHVA(vr263,H);
if (CondStackvar(Yb(BcP(f_y,0)))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0))));
    }

Yb(BcP(f_y,0)) = vr263;
}HeapPush(H,Xb(BcP(f_x,0+Fs(f_y))));
P+=Fs(f_y)+Fs(f_x);
goto w_dispatch;
    }
    }
case 196:
{
{
{tagged_t vr264;
LoadHVA(vr264,H);
if (CondStackvar(Yb(BcP(f_y,0)))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0))));
    }

Yb(BcP(f_y,0)) = vr264;
}{tagged_t vr265 = Xb(BcP(f_x,0+Fs(f_y)));
if (TaggedIsSVA(vr265)) {
tagged_t vr266;
do {
RefSVA(vr266,vr265);
if (vr266==vr265) {
BindSVA(vr265,Tagp(HVA,H));
PreLoadHVA(vr265,H);
break;
        }

vr265 = vr266;
      }
 while (TaggedIsSVA(vr265));
    }

HeapPush(H,vr265);
}P+=Fs(f_y)+Fs(f_x);
goto w_dispatch;
    }
    }
case 202:
{
{
{tagged_t vr267;
LoadHVA(vr267,H);
if (CondStackvar(Yb(BcP(f_y,0)))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0))));
    }

Yb(BcP(f_y,0)) = vr267;
}HeapPush(H,Yb(BcP(f_y,0+Fs(f_y))));
P+=Fs(f_y)+Fs(f_y);
goto w_dispatch;
    }
    }
case 205:
{
{
{tagged_t vr268;
LoadHVA(vr268,H);
if (CondStackvar(Yb(BcP(f_y,0)))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0))));
    }

Yb(BcP(f_y,0)) = vr268;
}{tagged_t vr269 = Yb(BcP(f_y,0+Fs(f_y)));
if (TaggedIsSVA(vr269)) {
tagged_t vr270;
do {
RefSVA(vr270,vr269);
if (vr270==vr269) {
BindSVA(vr269,Tagp(HVA,H));
PreLoadHVA(vr269,H);
break;
        }

vr269 = vr270;
      }
 while (TaggedIsSVA(vr269));
    }

HeapPush(H,vr269);
}P+=Fs(f_y)+Fs(f_y);
goto w_dispatch;
    }
    }
case 167:
{
{
HeapPush(H,Xb(BcP(f_x,0)));
intmach_t vr271 = (FTYPE_ctype(f_i_signed))BcP(f_i,0+Fs(f_x));
do {
ConstrHVA(H);
    }
 while (--vr271);
P+=Fs(f_x)+Fs(f_i);
goto w_dispatch;
    }
    }
case 168:
{
{
{tagged_t vr272 = Xb(BcP(f_x,0));
if (TaggedIsSVA(vr272)) {
tagged_t vr273;
do {
RefSVA(vr273,vr272);
if (vr273==vr272) {
BindSVA(vr272,Tagp(HVA,H));
PreLoadHVA(vr272,H);
break;
        }

vr272 = vr273;
      }
 while (TaggedIsSVA(vr272));
    }

HeapPush(H,vr272);
}intmach_t vr274 = (FTYPE_ctype(f_i_signed))BcP(f_i,0+Fs(f_x));
do {
ConstrHVA(H);
    }
 while (--vr274);
P+=Fs(f_x)+Fs(f_i);
goto w_dispatch;
    }
    }
case 169:
HeapPush(H,Xb(BcP(f_x,0)));
LoadHVA(Xb(BcP(f_x,0+Fs(f_x))),H);
P+=Fs(f_x)+Fs(f_x);
goto w_dispatch;
case 170:
{
{
{tagged_t vr275 = Xb(BcP(f_x,0));
if (TaggedIsSVA(vr275)) {
tagged_t vr276;
do {
RefSVA(vr276,vr275);
if (vr276==vr275) {
BindSVA(vr275,Tagp(HVA,H));
PreLoadHVA(vr275,H);
break;
        }

vr275 = vr276;
      }
 while (TaggedIsSVA(vr275));
    }

HeapPush(H,vr275);
}LoadHVA(Xb(BcP(f_x,0+Fs(f_x))),H);
P+=Fs(f_x)+Fs(f_x);
goto w_dispatch;
    }
    }
case 171:
CODE_ALLOC(E);
goto w_op173;
case 172:
CODE_ALLOC(E);
goto w_op174;
case 173:
w_op173:
HeapPush(H,Xb(BcP(f_x,0)));
LoadHVA(Yb(BcP(f_y,0+Fs(f_x))),H);
P+=Fs(f_x)+Fs(f_y);
goto w_dispatch;
case 174:
{
w_op174:
{
{tagged_t vr277 = Xb(BcP(f_x,0));
if (TaggedIsSVA(vr277)) {
tagged_t vr278;
do {
RefSVA(vr278,vr277);
if (vr278==vr277) {
BindSVA(vr277,Tagp(HVA,H));
PreLoadHVA(vr277,H);
break;
        }

vr277 = vr278;
      }
 while (TaggedIsSVA(vr277));
    }

HeapPush(H,vr277);
}LoadHVA(Yb(BcP(f_y,0+Fs(f_x))),H);
P+=Fs(f_x)+Fs(f_y);
goto w_dispatch;
    }
    }
case 175:
HeapPush(H,Xb(BcP(f_x,0)));
HeapPush(H,Xb(BcP(f_x,0+Fs(f_x))));
P+=Fs(f_x)+Fs(f_x);
goto w_dispatch;
case 177:
{
{
HeapPush(H,Xb(BcP(f_x,0)));
{tagged_t vr279 = Xb(BcP(f_x,0+Fs(f_x)));
if (TaggedIsSVA(vr279)) {
tagged_t vr280;
do {
RefSVA(vr280,vr279);
if (vr280==vr279) {
BindSVA(vr279,Tagp(HVA,H));
PreLoadHVA(vr279,H);
break;
        }

vr279 = vr280;
      }
 while (TaggedIsSVA(vr279));
    }

HeapPush(H,vr279);
}P+=Fs(f_x)+Fs(f_x);
goto w_dispatch;
    }
    }
case 176:
{
{
{tagged_t vr281 = Xb(BcP(f_x,0));
if (TaggedIsSVA(vr281)) {
tagged_t vr282;
do {
RefSVA(vr282,vr281);
if (vr282==vr281) {
BindSVA(vr281,Tagp(HVA,H));
PreLoadHVA(vr281,H);
break;
        }

vr281 = vr282;
      }
 while (TaggedIsSVA(vr281));
    }

HeapPush(H,vr281);
}HeapPush(H,Xb(BcP(f_x,0+Fs(f_x))));
P+=Fs(f_x)+Fs(f_x);
goto w_dispatch;
    }
    }
case 178:
{
{
{tagged_t vr283 = Xb(BcP(f_x,0));
if (TaggedIsSVA(vr283)) {
tagged_t vr284;
do {
RefSVA(vr284,vr283);
if (vr284==vr283) {
BindSVA(vr283,Tagp(HVA,H));
PreLoadHVA(vr283,H);
break;
        }

vr283 = vr284;
      }
 while (TaggedIsSVA(vr283));
    }

HeapPush(H,vr283);
}{tagged_t vr285 = Xb(BcP(f_x,0+Fs(f_x)));
if (TaggedIsSVA(vr285)) {
tagged_t vr286;
do {
RefSVA(vr286,vr285);
if (vr286==vr285) {
BindSVA(vr285,Tagp(HVA,H));
PreLoadHVA(vr285,H);
break;
        }

vr285 = vr286;
      }
 while (TaggedIsSVA(vr285));
    }

HeapPush(H,vr285);
}P+=Fs(f_x)+Fs(f_x);
goto w_dispatch;
    }
    }
case 179:
{
{
HeapPush(H,Xb(BcP(f_x,0)));
{tagged_t vr287;
LoadHVA(vr287,H);
if (CondStackvar(Yb(BcP(f_y,0+Fs(f_x))))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0+Fs(f_x)))));
    }

Yb(BcP(f_y,0+Fs(f_x))) = vr287;
}P+=Fs(f_x)+Fs(f_y);
goto w_dispatch;
    }
    }
case 180:
{
{
{tagged_t vr288 = Xb(BcP(f_x,0));
if (TaggedIsSVA(vr288)) {
tagged_t vr289;
do {
RefSVA(vr289,vr288);
if (vr289==vr288) {
BindSVA(vr288,Tagp(HVA,H));
PreLoadHVA(vr288,H);
break;
        }

vr288 = vr289;
      }
 while (TaggedIsSVA(vr288));
    }

HeapPush(H,vr288);
}{tagged_t vr290;
LoadHVA(vr290,H);
if (CondStackvar(Yb(BcP(f_y,0+Fs(f_x))))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0+Fs(f_x)))));
    }

Yb(BcP(f_y,0+Fs(f_x))) = vr290;
}P+=Fs(f_x)+Fs(f_y);
goto w_dispatch;
    }
    }
case 181:
HeapPush(H,Xb(BcP(f_x,0)));
HeapPush(H,Yb(BcP(f_y,0+Fs(f_x))));
P+=Fs(f_x)+Fs(f_y);
goto w_dispatch;
case 183:
{
{
HeapPush(H,Xb(BcP(f_x,0)));
{tagged_t vr291 = Yb(BcP(f_y,0+Fs(f_x)));
if (TaggedIsSVA(vr291)) {
tagged_t vr292;
do {
RefSVA(vr292,vr291);
if (vr292==vr291) {
BindSVA(vr291,Tagp(HVA,H));
PreLoadHVA(vr291,H);
break;
        }

vr291 = vr292;
      }
 while (TaggedIsSVA(vr291));
    }

HeapPush(H,vr291);
}P+=Fs(f_x)+Fs(f_y);
goto w_dispatch;
    }
    }
case 182:
{
{
{tagged_t vr293 = Xb(BcP(f_x,0));
if (TaggedIsSVA(vr293)) {
tagged_t vr294;
do {
RefSVA(vr294,vr293);
if (vr294==vr293) {
BindSVA(vr293,Tagp(HVA,H));
PreLoadHVA(vr293,H);
break;
        }

vr293 = vr294;
      }
 while (TaggedIsSVA(vr293));
    }

HeapPush(H,vr293);
}HeapPush(H,Yb(BcP(f_y,0+Fs(f_x))));
P+=Fs(f_x)+Fs(f_y);
goto w_dispatch;
    }
    }
case 184:
{
{
{tagged_t vr295 = Xb(BcP(f_x,0));
if (TaggedIsSVA(vr295)) {
tagged_t vr296;
do {
RefSVA(vr296,vr295);
if (vr296==vr295) {
BindSVA(vr295,Tagp(HVA,H));
PreLoadHVA(vr295,H);
break;
        }

vr295 = vr296;
      }
 while (TaggedIsSVA(vr295));
    }

HeapPush(H,vr295);
}{tagged_t vr297 = Yb(BcP(f_y,0+Fs(f_x)));
if (TaggedIsSVA(vr297)) {
tagged_t vr298;
do {
RefSVA(vr298,vr297);
if (vr298==vr297) {
BindSVA(vr297,Tagp(HVA,H));
PreLoadHVA(vr297,H);
break;
        }

vr297 = vr298;
      }
 while (TaggedIsSVA(vr297));
    }

HeapPush(H,vr297);
}P+=Fs(f_x)+Fs(f_y);
goto w_dispatch;
    }
    }
case 186:
{
{
HeapPush(H,Yb(BcP(f_y,0)));
intmach_t vr299 = (FTYPE_ctype(f_i_signed))BcP(f_i,0+Fs(f_y));
do {
ConstrHVA(H);
    }
 while (--vr299);
P+=Fs(f_y)+Fs(f_i);
goto w_dispatch;
    }
    }
case 187:
{
{
{tagged_t vr300 = Yb(BcP(f_y,0));
if (TaggedIsSVA(vr300)) {
tagged_t vr301;
do {
RefSVA(vr301,vr300);
if (vr301==vr300) {
BindSVA(vr300,Tagp(HVA,H));
PreLoadHVA(vr300,H);
break;
        }

vr300 = vr301;
      }
 while (TaggedIsSVA(vr300));
    }

HeapPush(H,vr300);
}intmach_t vr302 = (FTYPE_ctype(f_i_signed))BcP(f_i,0+Fs(f_y));
do {
ConstrHVA(H);
    }
 while (--vr302);
P+=Fs(f_y)+Fs(f_i);
goto w_dispatch;
    }
    }
case 189:
HeapPush(H,Yb(BcP(f_y,0)));
LoadHVA(Xb(BcP(f_x,0+Fs(f_y))),H);
P+=Fs(f_y)+Fs(f_x);
goto w_dispatch;
case 190:
{
{
{tagged_t vr303 = Yb(BcP(f_y,0));
if (TaggedIsSVA(vr303)) {
tagged_t vr304;
do {
RefSVA(vr304,vr303);
if (vr304==vr303) {
BindSVA(vr303,Tagp(HVA,H));
PreLoadHVA(vr303,H);
break;
        }

vr303 = vr304;
      }
 while (TaggedIsSVA(vr303));
    }

HeapPush(H,vr303);
}LoadHVA(Xb(BcP(f_x,0+Fs(f_y))),H);
P+=Fs(f_y)+Fs(f_x);
goto w_dispatch;
    }
    }
case 191:
HeapPush(H,Yb(BcP(f_y,0)));
LoadHVA(Yb(BcP(f_y,0+Fs(f_y))),H);
P+=Fs(f_y)+Fs(f_y);
goto w_dispatch;
case 192:
{
{
{tagged_t vr305 = Yb(BcP(f_y,0));
if (TaggedIsSVA(vr305)) {
tagged_t vr306;
do {
RefSVA(vr306,vr305);
if (vr306==vr305) {
BindSVA(vr305,Tagp(HVA,H));
PreLoadHVA(vr305,H);
break;
        }

vr305 = vr306;
      }
 while (TaggedIsSVA(vr305));
    }

HeapPush(H,vr305);
}LoadHVA(Yb(BcP(f_y,0+Fs(f_y))),H);
P+=Fs(f_y)+Fs(f_y);
goto w_dispatch;
    }
    }
case 200:
{
{
HeapPush(H,Yb(BcP(f_y,0)));
{tagged_t vr307;
LoadHVA(vr307,H);
if (CondStackvar(Yb(BcP(f_y,0+Fs(f_y))))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0+Fs(f_y)))));
    }

Yb(BcP(f_y,0+Fs(f_y))) = vr307;
}P+=Fs(f_y)+Fs(f_y);
goto w_dispatch;
    }
    }
case 201:
{
{
{tagged_t vr308 = Yb(BcP(f_y,0));
if (TaggedIsSVA(vr308)) {
tagged_t vr309;
do {
RefSVA(vr309,vr308);
if (vr309==vr308) {
BindSVA(vr308,Tagp(HVA,H));
PreLoadHVA(vr308,H);
break;
        }

vr308 = vr309;
      }
 while (TaggedIsSVA(vr308));
    }

HeapPush(H,vr308);
}{tagged_t vr310;
LoadHVA(vr310,H);
if (CondStackvar(Yb(BcP(f_y,0+Fs(f_y))))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0+Fs(f_y)))));
    }

Yb(BcP(f_y,0+Fs(f_y))) = vr310;
}P+=Fs(f_y)+Fs(f_y);
goto w_dispatch;
    }
    }
case 194:
HeapPush(H,Yb(BcP(f_y,0)));
HeapPush(H,Xb(BcP(f_x,0+Fs(f_y))));
P+=Fs(f_y)+Fs(f_x);
goto w_dispatch;
case 197:
{
{
HeapPush(H,Yb(BcP(f_y,0)));
{tagged_t vr311 = Xb(BcP(f_x,0+Fs(f_y)));
if (TaggedIsSVA(vr311)) {
tagged_t vr312;
do {
RefSVA(vr312,vr311);
if (vr312==vr311) {
BindSVA(vr311,Tagp(HVA,H));
PreLoadHVA(vr311,H);
break;
        }

vr311 = vr312;
      }
 while (TaggedIsSVA(vr311));
    }

HeapPush(H,vr311);
}P+=Fs(f_y)+Fs(f_x);
goto w_dispatch;
    }
    }
case 195:
{
{
{tagged_t vr313 = Yb(BcP(f_y,0));
if (TaggedIsSVA(vr313)) {
tagged_t vr314;
do {
RefSVA(vr314,vr313);
if (vr314==vr313) {
BindSVA(vr313,Tagp(HVA,H));
PreLoadHVA(vr313,H);
break;
        }

vr313 = vr314;
      }
 while (TaggedIsSVA(vr313));
    }

HeapPush(H,vr313);
}HeapPush(H,Xb(BcP(f_x,0+Fs(f_y))));
P+=Fs(f_y)+Fs(f_x);
goto w_dispatch;
    }
    }
case 198:
{
{
{tagged_t vr315 = Yb(BcP(f_y,0));
if (TaggedIsSVA(vr315)) {
tagged_t vr316;
do {
RefSVA(vr316,vr315);
if (vr316==vr315) {
BindSVA(vr315,Tagp(HVA,H));
PreLoadHVA(vr315,H);
break;
        }

vr315 = vr316;
      }
 while (TaggedIsSVA(vr315));
    }

HeapPush(H,vr315);
}{tagged_t vr317 = Xb(BcP(f_x,0+Fs(f_y)));
if (TaggedIsSVA(vr317)) {
tagged_t vr318;
do {
RefSVA(vr318,vr317);
if (vr318==vr317) {
BindSVA(vr317,Tagp(HVA,H));
PreLoadHVA(vr317,H);
break;
        }

vr317 = vr318;
      }
 while (TaggedIsSVA(vr317));
    }

HeapPush(H,vr317);
}P+=Fs(f_y)+Fs(f_x);
goto w_dispatch;
    }
    }
case 203:
HeapPush(H,Yb(BcP(f_y,0)));
HeapPush(H,Yb(BcP(f_y,0+Fs(f_y))));
P+=Fs(f_y)+Fs(f_y);
goto w_dispatch;
case 206:
{
{
HeapPush(H,Yb(BcP(f_y,0)));
{tagged_t vr319 = Yb(BcP(f_y,0+Fs(f_y)));
if (TaggedIsSVA(vr319)) {
tagged_t vr320;
do {
RefSVA(vr320,vr319);
if (vr320==vr319) {
BindSVA(vr319,Tagp(HVA,H));
PreLoadHVA(vr319,H);
break;
        }

vr319 = vr320;
      }
 while (TaggedIsSVA(vr319));
    }

HeapPush(H,vr319);
}P+=Fs(f_y)+Fs(f_y);
goto w_dispatch;
    }
    }
case 204:
{
{
{tagged_t vr321 = Yb(BcP(f_y,0));
if (TaggedIsSVA(vr321)) {
tagged_t vr322;
do {
RefSVA(vr322,vr321);
if (vr322==vr321) {
BindSVA(vr321,Tagp(HVA,H));
PreLoadHVA(vr321,H);
break;
        }

vr321 = vr322;
      }
 while (TaggedIsSVA(vr321));
    }

HeapPush(H,vr321);
}HeapPush(H,Yb(BcP(f_y,0+Fs(f_y))));
P+=Fs(f_y)+Fs(f_y);
goto w_dispatch;
    }
    }
case 207:
{
{
{tagged_t vr323 = Yb(BcP(f_y,0));
if (TaggedIsSVA(vr323)) {
tagged_t vr324;
do {
RefSVA(vr324,vr323);
if (vr324==vr323) {
BindSVA(vr323,Tagp(HVA,H));
PreLoadHVA(vr323,H);
break;
        }

vr323 = vr324;
      }
 while (TaggedIsSVA(vr323));
    }

HeapPush(H,vr323);
}{tagged_t vr325 = Yb(BcP(f_y,0+Fs(f_y)));
if (TaggedIsSVA(vr325)) {
tagged_t vr326;
do {
RefSVA(vr326,vr325);
if (vr326==vr325) {
BindSVA(vr325,Tagp(HVA,H));
PreLoadHVA(vr325,H);
break;
        }

vr325 = vr326;
      }
 while (TaggedIsSVA(vr325));
    }

HeapPush(H,vr325);
}P+=Fs(f_y)+Fs(f_y);
goto w_dispatch;
    }
    }
case 248:
P+=Fs(f_Q);
goto w_op249;
case 249:
w_op249:
#if defined(GAUGE)
INCR_COUNTER(BcP(f_l,0));
#endif
P+=Fs(f_l);
goto w_dispatch;
case 250:
P+=Fs(f_Q);
goto w_op251;
case 251:
w_op251:
#if defined(GAUGE)
if (!IsDeep()) {
B = w->choice;
if (!IsShallowTry()) {
#if defined(GAUGE)
INCR_COUNTER(BcP(f_l,0));
#endif
      }
 else {
#if defined(GAUGE)
INCR_COUNTER(BcP(f_l,0+Fs(f_l)));
#endif
      }

    }

#endif
P+=Fs(f_l)+Fs(f_l);
goto w_op65;
case 67:
goto fail;
case 245:
P+=Fs(f_Q);
goto w_op246;
case 246:
w_op246:
if (HeapCharDifference(H,Heap_End)<(intmach_t)BcP(f_l,0)) {
w->heap_top = H;
explicit_heap_overflow(w,(intmach_t)BcP(f_l,0)*2,(FTYPE_ctype(f_i_signed))BcP(f_i,0+Fs(f_l)));
H = w->heap_top;
    }

P+=Fs(f_l)+Fs(f_i);
goto w_dispatch;
case 65:
{
w_op65:
{
if (!IsDeep()) {
B = w->choice;
if (!IsShallowTry()) {
NECK_RETRY_PATCH(B);
      }
 else {
B->next_alt = w->next_alt;
B->frame = w->frame;
B->next_insn = w->next_insn;
B->local_top = w->local_top;
intmach_t vr327 = ChoiceArity(B);
for (intmach_t vr328 = 0;
vr328<vr327;vr328++) {
B->x[vr328] = w->x[vr328];
        }

if (ChoiceYounger(ChoiceOffset(B,CHOICEPAD),w->trail_top)) {
choice_overflow(w,2*CHOICEPAD*sizeof(tagged_t),TRUE);
        }

      }

SetDeep();
SetE(w->local_top);
    }

P+=0;
goto w_dispatch;
    }
    }
case 236:
{
w_op236:
{
tagged_t vr329 = X(3);
if (vr329&TagBitSVA) {
BindSVA(vr329,PointerToTerm(w->misc->ins));
    }
 else {
BindHVA(vr329,PointerToTerm(w->misc->ins));
    }

if (IsDeep()) {
goto w_op64;
    }

B = w->choice;
if (IsShallowTry()) {
def_clock = use_clock+1;
if (def_clock==65535) {
w->heap_top = H;
clock_overflow(w);
H = w->heap_top;
      }

    }

goto w_op66;
    }
    }
case 66:
{
w_op66:
{
if (!IsDeep()) {
B = w->choice;
if (!IsShallowTry()) {
NECK_RETRY_PATCH(B);
      }
 else {
B->next_alt = w->next_alt;
B->frame = w->frame;
B->next_insn = w->next_insn;
B->local_top = w->local_top;
intmach_t vr330 = ChoiceArity(B);
for (intmach_t vr331 = 0;
vr331<vr330;vr331++) {
B->x[vr331] = w->x[vr331];
        }

if (ChoiceYounger(ChoiceOffset(B,CHOICEPAD),w->trail_top)) {
choice_overflow(w,2*CHOICEPAD*sizeof(tagged_t),TRUE);
        }

      }

SetDeep();
    }
 else {
w->local_top = 0;
    }

SetE(w->frame);
P = w->next_insn;
PROFILE__HOOK_PROCEED;
P+=0;
goto w_dispatch;
    }
    }
case 64:
w_op64:
w->local_top = 0;
SetE(w->frame);
P = w->next_insn;
PROFILE__HOOK_PROCEED;
P+=0;
goto w_dispatch;
#if defined(PARBACK)
case 262:
w->heap_top = TaggedToPointer(w->choice->x[0]);
H = w->heap_top;
P = (bcp_t)*TaggedToPointer(w->choice->x[0]);
w->next_insn = w->choice->next_insn;
pop_choicept(w);
goto enter_predicate;
#endif
default:
goto illop;
  }
  }
exit_toplevel:
w->insn = P;
if (desc!=NULL&&desc->action&KEEP_STACKS) {
SAVE_WAM_STATE;
  }

if (Stop_This_Goal(w)) {
w->misc->exit_code = WAM_INTERRUPTED;
  }

ON_DEBUG({
  }
);
return;
illop:
SERIOUS_FAULT("unimplemented WAM instruction");
}
