/***************************************************************************/
/*                             WARNING!!!                                  */
/*                      D O   N O T   M O D I F Y                          */
/*                This file is autogenerated by emugen                     */
/***************************************************************************/

extern instance_clock_t def_clock;
extern instance_clock_t use_clock;
#define BcOPCODE BcFetchOPCODE()
#define BcP(Ty,X) ((*(FTYPE_ctype(Ty) *)BCoff(P,(X))))
#define Fs(Ty) FTYPE_size(Ty)
CVOID__PROTO(wam__2,goal_descriptor_t * desc,definition_t * start_func);
CVOID__PROTO(wam,goal_descriptor_t * desc) {
definition_t * func = (definition_t *)NULL;
goto again;
again:
{
EXCEPTION__CATCH({
CVOID__CALL(wam__2, desc, func);
return;
}
, {
choice_t * b;
if (!IsDeep()) {
B = w->choice;
if (!IsShallowTry()) {
NECK_RETRY_PATCH(B);
    }
 else {
B->next_alt = w->next_alt;
B->frame = w->frame;
B->next_insn = w->next_insn;
B->local_top = w->local_top;
intmach_t vr0 = ChoiceArity(B);
for (intmach_t vr1 = 0;
vr1<vr0;vr1++) {
B->x[vr1] = w->x[vr1];
      }

if (ChoiceYounger(ChoiceOffset(B,CHOICEPAD),w->trail_top)) {
choice_overflow(w,2*CHOICEPAD*sizeof(tagged_t),TRUE);
      }

    }

SetDeep();
  }

X(0) = MakeSmall(ErrCode);
X(1) = GET_ATOM(ErrFuncName);
X(2) = MakeSmall(ErrFuncArity);
X(4) = Culprit;
X(3) = MakeSmall(ErrArgNo);
func = address_error;
goto again;
}
);
}
}
CVOID__PROTO(wam__2,goal_descriptor_t * desc,definition_t * start_func) {
bcp_t p;
try_node_t * alts;
choice_t * b;
frame_t * e;
tagged_t * cached_r_h;
tagged_t * r_s;
intmach_t ei;
bcp_t ptemp = NULL;
alts = NULL;
b = NULL;
e = NULL;
cached_r_h = NULL;
r_s = NULL;
ei = ~0;
ON_DEBUG({
if (debug_threads) {
fprintf(stderr,"Worker state address is %p\n",desc);
    }

  }
);
if (start_func!=NULL) {
P = (bcp_t)start_func;
B = w->choice;
H = w->heap_top;
goto switch_on_pred;
  }

if (desc!=NULL&&desc->action&BACKTRACKING) {
RECOVER_WAM_STATE;
goto fail;
  }

goto r_op64;
escape_to_p2:
{
tagged_t vr2;
tagged_t vr3;
vr2 = PointerToTerm(Func->code.intinfo);
if (Func->arity==0) {
vr3 = Func->printname;
  }
 else {
vr3 = Tagp(STR,H);
HeapPush(H,SetArity(Func->printname,Func->arity));
for (intmach_t vr4 = 0;
vr4<Func->arity;vr4++) {
tagged_t vr5 = X(vr4);
if (TaggedIsSVA(vr5)) {
tagged_t vr6;
do {
RefSVA(vr6,vr5);
if (vr6==vr5) {
BindSVA(vr5,Tagp(HVA,H));
PreLoadHVA(vr5,H);
break;
          }

vr5 = vr6;
        }
 while (TaggedIsSVA(vr5));
      }

HeapPush(H,vr5);
    }

  }

P = ptemp;
X(0) = vr3;
X(1) = vr2;
goto switch_on_pred;
  }
escape_to_p:
{
tagged_t vr7;
if (Func->arity==0) {
vr7 = Func->printname;
  }
 else {
vr7 = Tagp(STR,H);
HeapPush(H,SetArity(Func->printname,Func->arity));
for (intmach_t vr8 = 0;
vr8<Func->arity;vr8++) {
tagged_t vr9 = X(vr8);
if (TaggedIsSVA(vr9)) {
tagged_t vr10;
do {
RefSVA(vr10,vr9);
if (vr10==vr9) {
BindSVA(vr9,Tagp(HVA,H));
PreLoadHVA(vr9,H);
break;
          }

vr9 = vr10;
        }
 while (TaggedIsSVA(vr9));
      }

HeapPush(H,vr9);
    }

  }

P = ptemp;
X(0) = vr7;
goto switch_on_pred;
  }
enter_predicate:
{
ON_ANDPARALLEL({
if (Suspend==TOSUSPEND) {
Suspend = SUSPENDED;
Wait_Acquire_lock(Waiting_For_Work_Lock);
Cond_Var_Wait(Waiting_For_Work_Cond_Var,Waiting_For_Work_Lock);
Suspend = RELEASED;
Release_lock(Waiting_For_Work_Lock);
    }

  }
);
if (TestEventOrHeapWarnOverflow(H)) {
int wake_cnt;
if (Stop_This_Goal(w)) {
goto exit_toplevel;
    }

wake_cnt = WakeCount();
if (HeapCharAvailable(H)<=CALLPAD+4*wake_cnt*sizeof(tagged_t)) {
SETUP_PENDING_CALL(E,address_true);
w->heap_top = H;
heap_overflow(w,2*(CALLPAD+4*wake_cnt*sizeof(tagged_t)));
H = w->heap_top;
    }

if (wake_cnt>0) {
if (wake_cnt==1) {
SETUP_PENDING_CALL(E,address_uvc);
collect_one_pending_unification(w);
tagged_t vr11;
DEREF(vr11,X(1));
if (TaggedIsCVA(vr11)) {
X(1) = vr11;
Setfunc(address_ucc);
        }

      }
 else {
SETUP_PENDING_CALL(E,address_pending_unifications);
w->heap_top = H;
collect_pending_unifications(w,wake_cnt);
H = w->heap_top;
      }

    }

if (OffStacktop(w->frame,Stack_Warn)) {
SETUP_PENDING_CALL(E,address_true);
stack_overflow(w);
    }

UnsetEvent();
if (TestCIntEvent()) {
SETUP_PENDING_CALL(E,address_help);
control_c_normal(w);
    }

  }

goto switch_on_pred;
  }
switch_on_pred:
ei = Func->enter_instr;
goto switch_on_pred_sub;
switch_on_pred_sub:
{
switch (ei) {
case ENTER_FASTCODE_INDEXED:
goto enter_undefined;
case ENTER_FASTCODE:
goto enter_undefined;
case ENTER_UNDEFINED:
enter_undefined:
PredTrace("U",Func);
ptemp = (bcp_t)address_undefined_goal;
goto escape_to_p;
case ENTER_INTERPRETED:
ptemp = (bcp_t)address_interpret_c_goal;
goto escape_to_p2;
case ENTER_C:
{
PredTrace("C",Func);
w->heap_top = H;
intmach_t vr12 = ((cbool0_t)Func->code.proc)(w);
if (Expanded_Worker!=NULL) {
ON_DEBUG({
fprintf(stderr,"wam() detected worker expanded by C predicate\n");
      }
);
if (desc==NULL) {
fprintf(stderr,"bug: invalid WAM expansion\n");
abort();
      }

w = Expanded_Worker;
desc->worker_registers = w;
Expanded_Worker = NULL;
    }

if (vr12) {
goto r_op64;
    }
 else {
goto fail;
    }

    }
case BUILTIN_TRUE:
PredTrace("B",Func);
goto w_op64;
case BUILTIN_FAIL:
PredTrace("B",Func);
goto fail;
case BUILTIN_CURRENT_INSTANCE:
PredTrace("B",Func);
w->heap_top = H;
w->misc->ins = CFUN__EVAL(current_instance0);
if (w->misc->ins==NULL) {
goto fail;
    }

P = (bcp_t)w->misc->ins->emulcode;
goto r_dispatch;
case BUILTIN_COMPILE_TERM:
{
PredTrace("B",Func);
w->heap_top = H;
{worker_t * vr13;
if (!compile_term(w,&vr13)) {
goto fail;
    }

if (vr13!=NULL) {
if (desc==NULL) {
fprintf(stderr,"bug: invalid WAM expansion\n");
abort();
      }

w = vr13;
desc->worker_registers = w;
ON_DEBUG({
fprintf(stderr,"Reallocation of wrb detected in wam()\n");
      }
);
    }

}goto r_op64;
    }
case BUILTIN_INSTANCE:
PredTrace("B",Func);
LoadHVA(X(3),H);
w->misc->ins = TaggedToInstance(X(2));
P = (bcp_t)w->misc->ins->emulcode;
goto w_dispatch;
case BUILTIN_GELER:
{
PredTrace("B",Func);
tagged_t vr14 = X(0);
DerefSwitch0(vr14,{
;    }
);
tagged_t vr15;
vr15 = X(1);
DerefSwitch0(vr15,{
;    }
);
Setfunc(find_definition(predicates_location,vr15,&w->structure,TRUE));
w->heap_top = H;
CVOID__CALL(SUSPEND_T3_ON_T1,Func,vr15,vr14);
H = w->heap_top;
goto w_op64;
    }
case BUILTIN_NODEBUGCALL:
{
PredTrace("B",Func);
tagged_t vr16 = X(0);
DerefSwitch(vr16,X(0),{
;    }
);
Setfunc(find_definition(predicates_location,vr16,&w->structure,FALSE));
if (Func==NULL) {
goto fail;
    }

ei = Func->enter_instr;
goto call4;
    }
case BUILTIN_SYSCALL:
{
PredTrace("B",Func);
tagged_t vr17 = X(0);
DerefSwitch(vr17,X(0),{
;    }
);
Setfunc(find_definition(predicates_location,vr17,&w->structure,FALSE));
if (Func==NULL) {
Setfunc(address_undefined_goal);
goto switch_on_pred;
    }

ei = Func->enter_instr;
goto call4;
    }
call4:
{
switch (ei) {
case ENTER_INTERPRETED:
X(1) = PointerToTerm(Func->code.intinfo);
Setfunc(address_interpret_goal);
goto switch_on_pred;
case BUILTIN_DIF:
{
PredTrace("B",Func);
tagged_t * vr18 = w->structure;
tagged_t vr19;
RefHeapNext(vr19,vr18);
X(0) = vr19;
tagged_t vr20;
RefHeapNext(vr20,vr18);
X(1) = vr20;
goto dif0;
      }
case SPYPOINT:
if (!Func->properties.wait) {
goto call5;
      }

goto call_waitpoint;
case WAITPOINT:
{
call_waitpoint:
{
tagged_t vr21;
tagged_t vr22;
RefHeap(vr21,w->structure);
DerefSwitch(vr21,vr22,{
tagged_t vr23;
vr23 = X(0);
w->heap_top = H;
CVOID__CALL(SUSPEND_T3_ON_T1,Func,vr23,vr22);
H = w->heap_top;
goto w_op64;
      }
);
goto call5;
      }
      }
call5:
ei = Func->predtyp;
goto call4;
default:
{
intmach_t vr24 = Func->arity;
if (vr24!=0) {
tagged_t * vr25 = w->x;
tagged_t * vr26 = w->structure;
do {
PushRefHeapNext(vr25,vr26);
        }
 while (--vr24);
      }

goto switch_on_pred_sub;
      }
    }
    }
case BUILTIN_CALL:
{
PredTrace("B",Func);
tagged_t vr27 = X(0);
DerefSwitch(vr27,X(0),{
;    }
);
Setfunc(find_definition(predicates_location,vr27,&w->structure,FALSE));
if (Func==NULL) {
Setfunc(address_undefined_goal);
goto switch_on_pred;
    }

if (Current_Debugger_Mode!=atom_off) {
Setfunc(address_trace);
goto switch_on_pred;
    }

ei = Func->enter_instr;
goto call4;
    }
case BUILTIN_DIF:
{
dif0:
{
PredTrace("B",Func);
tagged_t vr28 = X(0);
DerefSwitch0(vr28,{
;    }
);
tagged_t vr29 = X(1);
DerefSwitch0(vr29,{
;    }
);
w->structure = NULL;
if (vr28==vr29) {
goto fail;
    }
 else if (!IsVar(vr28&vr29)&&(IsAtomic(vr28)||IsAtomic(vr29))) {
goto w_op64;
    }
 else {
X(0) = vr28;
X(1) = vr29;
w->heap_top = H;
if (!prolog_dif(w,Func)) {
goto fail;
      }

goto r_op64;
    }

    }
    }
case BUILTIN_ABORT:
{
PredTrace("B",Func);
tagged_t vr30 = X(0);
DerefSwitch0(vr30,{
;    }
);
w->misc->exit_code = GetSmall(vr30);
w->previous_choice = InitialChoice;
PROFILE__HOOK_CUT;
B = w->previous_choice;
SetChoice(B);
TRACE_CHPT_CUT(w->choice);
ConcChptCleanUp(TopConcChpt,w->choice);
goto fail;
    }
case SPYPOINT:
if (Current_Debugger_Mode!=atom_off) {
ptemp = (bcp_t)address_trace;
goto escape_to_p;
    }

if (!Func->properties.wait) {
goto nowait;
    }

goto waitpoint;
case WAITPOINT:
{
waitpoint:
{
tagged_t vr31 = X(0);
DerefSwitch(vr31,X(0),{
tagged_t vr32;
if (Func->arity==0) {
vr32 = Func->printname;
      }
 else {
vr32 = Tagp(STR,H);
HeapPush(H,SetArity(Func->printname,Func->arity));
for (intmach_t vr33 = 0;
vr33<Func->arity;vr33++) {
tagged_t vr34 = X(vr33);
if (TaggedIsSVA(vr34)) {
tagged_t vr35;
do {
RefSVA(vr35,vr34);
if (vr35==vr34) {
BindSVA(vr34,Tagp(HVA,H));
PreLoadHVA(vr34,H);
break;
              }

vr34 = vr35;
            }
 while (TaggedIsSVA(vr34));
          }

HeapPush(H,vr34);
        }

      }

vr31 = X(0);
if (TaggedIsSVA(vr31)) {
RefSVA(vr31,X(0));
      }

w->heap_top = H;
CVOID__CALL(SUSPEND_T3_ON_T1,Func,vr32,vr31);
H = w->heap_top;
goto w_op64;
    }
);
goto nowait;
nowait:
ei = Func->predtyp;
goto switch_on_pred_sub;
    }
    }
case BREAKPOINT:
ei = Func->predtyp;
goto switch_on_pred_sub;
case ENTER_PROFILEDCODE_INDEXED:
goto enter_compactcode_indexed;
case ENTER_COMPACTCODE_INDEXED:
{
enter_compactcode_indexed:
{
PredTrace("E",Func);
tagged_t vr36 = X(0);
DerefSwitch(vr36,X(0),{
alts = Func->code.incoreinfo->varcase;
goto w_tryeach;
    }
);
tagged_t vr37;
w->heap_top = H;
if (vr36&TagBitComplex) {
if (vr36&TagBitFunctor) {
S = TaggedToArg(vr36,0);
vr37 = HeapNext(S);
      }
 else {
S = TagpPtr(LST,vr36);
alts = Func->code.incoreinfo->lstcase;
goto r_tryeach;
      }

    }
 else {
vr37 = vr36;
    }

intmach_t vr38;
sw_on_key_t * Htab = Func->code.incoreinfo->othercase;
vr38 = 0;
tagged_t vr39;
vr39 = vr37;
vr37&=Htab->mask;
sw_on_key_node_t * HtabNode;
do {
HtabNode = SW_ON_KEY_NODE_FROM_OFFSET(Htab,vr37);
if (HtabNode->key==vr39||!HtabNode->key) {
break;
      }

vr38+=sizeof(sw_on_key_node_t);
vr37 = (vr37+vr38)&Htab->mask;
    }
 while (TRUE);
alts = HtabNode->value.try_chain;
goto r_tryeach;
    }
    }
case ENTER_PROFILEDCODE:
goto enter_compactcode;
case ENTER_COMPACTCODE:
enter_compactcode:
PredTrace("E",Func);
alts = Func->code.incoreinfo->varcase;
goto w_tryeach;
  }
  }
fail:
{
PROFILE__HOOK_FAIL;
ON_DEBUG({
if (debug_choicepoints) {
fprintf(stderr,"Failing: node = %p, previous_choice = %p, conc. node = %p\n",w->choice,w->previous_choice,TopConcChpt);
    }

if (w->misc->top_conc_chpt<w->choice&&w->misc->top_conc_chpt<w->previous_choice) {
fprintf(stderr,"********** what happened here?\n");
    }

  }
);
ResetWakeCount();
B = w->choice;
ON_TABLING({
MAKE_TRAIL_CACTUS_STACK;  }
);
{tagged_t vr40;
tagged_t vr41;
tagged_t * vr42;
vr42 = w->trail_top;
vr41 = (tagged_t)TrailTopUnmark(B->trail_top);
if (TrailYounger(vr42,vr41)) {
do {
PlainUntrail(vr42,vr40,{
w->trail_top = vr42;
w->frame = B->frame;
w->next_insn = B->next_insn;
SetE(NodeLocalTop(B));
E->frame = w->frame;
E->next_insn = w->next_insn;
w->frame = E;
w->next_insn = failcode;
w->local_top = (frame_t *)Offset(E,EToY0);
H = w->heap_top;
X(0) = vr40;
Setfunc(find_definition(predicates_location,vr40,&w->structure,FALSE));
if (Func==NULL) {
Setfunc(address_undefined_goal);
goto switch_on_pred;
        }

ei = Func->enter_instr;
goto call4;
      }
);
    }
 while (TrailYounger(vr42,vr41));
w->trail_top = vr42;
  }

}w->heap_top = NodeGlobalTop(B);
if (IsDeep()) {
ON_DEBUG({
if (debug_choicepoints) {
fprintf(stderr,"deep backtracking, node = %p\n",w->choice);
      }

    }
);
w->frame = B->frame;
w->next_insn = B->next_insn;
w->next_alt = B->next_alt;
w->local_top = NodeLocalTop(B);
intmach_t vr43 = B->next_alt->arity;
w->previous_choice = ChoiceCont0(B,vr43);
SetShallowRetry();
for (intmach_t vr44 = 0;
vr44<vr43;vr44++) {
w->x[vr44] = B->x[vr44];
    }

  }

PROFILE__HOOK_REDO;
P = (bcp_t)w->next_alt;
try_node_t * vr45;
vr45 = ((try_node_t *)P)->next;
if (vr45==NULL) {
SetDeep();
B = w->previous_choice;
SetChoice(B);
ON_TABLING({
if (FrozenChpt(B)) {
push_choicept(w,address_nd_fake_choicept);
      }

    }
);
P = ((try_node_t *)P)->emul_p;
if (!IsVar(X(0))) {
goto r_dispatch;
    }

H = w->heap_top;
goto w_dispatch;
  }
 else {
CODE_CHOICE_PATCH(w->choice,vr45);
P = ((try_node_t *)P)->emul_p;
if (!IsVar(X(0))) {
goto r_dispatch;
    }

H = w->heap_top;
goto w_dispatch;
  }

  }
r_tryeach:
{
#if defined(GAUGE)
INCR_COUNTER(alts->entry_counter+1);
#endif
P = alts->emul_p2;
w->previous_choice = w->choice;
try_node_t * vr46 = alts->next;
if (vr46!=NULL) {
B = w->choice;
GetFrameTop(w->local_top,B,G->frame);
CODE_CHOICE_NEW0(B,vr46,w->heap_top);
ON_DEBUG({
if (debug_choicepoints) {
fprintf(stderr,"WAM created choicepoint (r), node = %p\n",w->choice);
      }

    }
);
if (ChoiceYounger(ChoiceOffset(B,CHOICEPAD),w->trail_top)) {
choice_overflow(w,2*CHOICEPAD*sizeof(tagged_t),TRUE);
    }

  }
 else {
SetDeep();
  }

goto r_dispatch;
  }
r_dispatch:
{
switch (BcOPCODE) {
case 260:
H = w->heap_top;
goto w_op260;
case 261:
H = w->heap_top;
goto w_op261;
case 0:
P+=Fs(f_Q);
goto r_op1;
case 1:
r_op1:
H = w->heap_top;
goto w_op1;
case 20:
P+=Fs(f_Q);
goto r_op21;
case 21:
r_op21:
H = w->heap_top;
goto w_op21;
case 18:
P+=Fs(f_Q);
goto r_op19;
case 19:
r_op19:
H = w->heap_top;
goto w_op19;
case 16:
P+=Fs(f_Q);
goto r_op17;
case 17:
r_op17:
H = w->heap_top;
goto w_op17;
case 14:
P+=Fs(f_Q);
goto r_op15;
case 15:
r_op15:
H = w->heap_top;
goto w_op15;
case 12:
P+=Fs(f_Q);
goto r_op13;
case 13:
r_op13:
H = w->heap_top;
goto w_op13;
case 10:
P+=Fs(f_Q);
goto r_op11;
case 11:
r_op11:
H = w->heap_top;
goto w_op11;
case 8:
P+=Fs(f_Q);
goto r_op9;
case 9:
r_op9:
H = w->heap_top;
goto w_op9;
case 6:
P+=Fs(f_Q);
goto r_op7;
case 7:
r_op7:
H = w->heap_top;
goto w_op7;
case 4:
P+=Fs(f_Q);
goto r_op5;
case 5:
r_op5:
H = w->heap_top;
goto w_op5;
case 2:
P+=Fs(f_Q);
goto r_op3;
case 3:
r_op3:
H = w->heap_top;
goto w_op3;
case 40:
P+=Fs(f_Q);
goto r_op41;
case 41:
r_op41:
H = w->heap_top;
goto w_op41;
case 38:
P+=Fs(f_Q);
goto r_op39;
case 39:
r_op39:
H = w->heap_top;
goto w_op39;
case 36:
P+=Fs(f_Q);
goto r_op37;
case 37:
r_op37:
H = w->heap_top;
goto w_op37;
case 34:
P+=Fs(f_Q);
goto r_op35;
case 35:
r_op35:
H = w->heap_top;
goto w_op35;
case 32:
P+=Fs(f_Q);
goto r_op33;
case 33:
r_op33:
H = w->heap_top;
goto w_op33;
case 30:
P+=Fs(f_Q);
goto r_op31;
case 31:
r_op31:
H = w->heap_top;
goto w_op31;
case 28:
P+=Fs(f_Q);
goto r_op29;
case 29:
r_op29:
H = w->heap_top;
goto w_op29;
case 26:
P+=Fs(f_Q);
goto r_op27;
case 27:
r_op27:
H = w->heap_top;
goto w_op27;
case 24:
P+=Fs(f_Q);
goto r_op25;
case 25:
r_op25:
H = w->heap_top;
goto w_op25;
case 22:
P+=Fs(f_Q);
goto r_op23;
case 23:
r_op23:
H = w->heap_top;
goto w_op23;
case 60:
P+=Fs(f_Q);
goto r_op61;
case 61:
r_op61:
H = w->heap_top;
goto w_op61;
case 58:
P+=Fs(f_Q);
goto r_op59;
case 59:
r_op59:
H = w->heap_top;
goto w_op59;
case 56:
P+=Fs(f_Q);
goto r_op57;
case 57:
r_op57:
H = w->heap_top;
goto w_op57;
case 54:
P+=Fs(f_Q);
goto r_op55;
case 55:
r_op55:
H = w->heap_top;
goto w_op55;
case 52:
P+=Fs(f_Q);
goto r_op53;
case 53:
r_op53:
H = w->heap_top;
goto w_op53;
case 50:
P+=Fs(f_Q);
goto r_op51;
case 51:
r_op51:
H = w->heap_top;
goto w_op51;
case 48:
P+=Fs(f_Q);
goto r_op49;
case 49:
r_op49:
H = w->heap_top;
goto w_op49;
case 46:
P+=Fs(f_Q);
goto r_op47;
case 47:
r_op47:
H = w->heap_top;
goto w_op47;
case 44:
P+=Fs(f_Q);
goto r_op45;
case 45:
r_op45:
H = w->heap_top;
goto w_op45;
case 42:
P+=Fs(f_Q);
goto r_op43;
case 43:
r_op43:
H = w->heap_top;
goto w_op43;
case 62:
H = w->heap_top;
P = BcP(f_p,0+Fs(f_Q));
goto enter_predicate;
case 63:
H = w->heap_top;
P = BcP(f_p,0);
goto enter_predicate;
case 69:
H = w->heap_top;
goto w_op69;
case 70:
H = w->heap_top;
goto w_op70;
case 85:
Xb(BcP(f_x,0)) = Xb(BcP(f_x,0+Fs(f_x)));
Xb(BcP(f_x,0+Fs(f_x)+Fs(f_x))) = Xb(BcP(f_x,0+Fs(f_x)+Fs(f_x)+Fs(f_x)));
P+=Fs(f_x)+Fs(f_x)+Fs(f_x)+Fs(f_x);
goto r_dispatch;
case 71:
Xb(BcP(f_x,0)) = Xb(BcP(f_x,0+Fs(f_x)));
P+=Fs(f_x)+Fs(f_x);
goto r_dispatch;
case 72:
H = w->heap_top;
goto w_op72;
case 73:
H = w->heap_top;
goto w_op73;
case 74:
H = w->heap_top;
goto w_op74;
case 83:
H = w->heap_top;
goto w_op83;
case 84:
H = w->heap_top;
goto w_op84;
case 75:
Xb(BcP(f_x,0)) = Yb(BcP(f_y,0+Fs(f_x)));
P+=Fs(f_x)+Fs(f_y);
goto r_dispatch;
case 76:
H = w->heap_top;
goto w_op76;
case 77:
Xb(BcP(f_x,0+Fs(f_Q))) = BcP(f_t,0+Fs(f_Q)+Fs(f_x));
P+=Fs(f_Q)+Fs(f_x)+Fs(f_t);
goto r_dispatch;
case 78:
Xb(BcP(f_x,0)) = BcP(f_t,0+Fs(f_x));
P+=Fs(f_x)+Fs(f_t);
goto r_dispatch;
case 81:
Xb(BcP(f_x,0)) = atom_nil;
P+=Fs(f_x);
goto r_dispatch;
case 252:
H = w->heap_top;
goto w_op252;
case 253:
H = w->heap_top;
goto w_op253;
case 79:
H = w->heap_top;
goto w_op79;
case 80:
H = w->heap_top;
goto w_op80;
case 82:
H = w->heap_top;
goto w_op82;
case 86:
Xb(BcP(f_x,0)) = Yb(BcP(f_y,0+Fs(f_x)));
Xb(BcP(f_x,0+Fs(f_x)+Fs(f_y))) = Yb(BcP(f_y,0+Fs(f_x)+Fs(f_y)+Fs(f_x)));
P+=Fs(f_x)+Fs(f_y)+Fs(f_x)+Fs(f_y);
goto r_dispatch;
case 87:
H = w->heap_top;
goto w_op87;
case 88:
H = w->heap_top;
goto w_op88;
case 89:
H = w->heap_top;
goto w_op89;
case 91:
r_op91:
if (!CBOOL__SUCCEED(cunify,Xb(BcP(f_x,0)),Xb(BcP(f_x,0+Fs(f_x))))) {
goto fail;
    }

P+=Fs(f_x)+Fs(f_x);
goto r_dispatch;
case 94:
r_op94:
if (CondStackvar(Yb(BcP(f_y,0+Fs(f_x))))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0+Fs(f_x)))));
    }

Yb(BcP(f_y,0+Fs(f_x))) = Xb(BcP(f_x,0));
P+=Fs(f_x)+Fs(f_y);
goto r_dispatch;
case 95:
r_op95:
if (!CBOOL__SUCCEED(cunify,Xb(BcP(f_x,0)),Yb(BcP(f_y,0+Fs(f_x))))) {
goto fail;
    }

P+=Fs(f_x)+Fs(f_y);
goto r_dispatch;
case 96:
P+=Fs(f_Q);
goto r_op97;
case 97:
{
r_op97:
{
tagged_t vr47 = Xb(BcP(f_x,0));
tagged_t vr48;
SwitchOnVar(vr47,vr48,{
BindHVA(vr47,BcP(f_t,0+Fs(f_x)));
    }
,{
BindCVA(vr47,BcP(f_t,0+Fs(f_x)));
    }
,{
BindSVA(vr47,BcP(f_t,0+Fs(f_x)));
    }
,{
if (vr47!=BcP(f_t,0+Fs(f_x))) {
goto fail;
      }

    }
);
P+=Fs(f_x)+Fs(f_t);
goto r_dispatch;
    }
    }
case 254:
P+=Fs(f_Q);
goto r_op255;
case 255:
{
r_op255:
{
{tagged_t vr49;
vr49 = Xb(BcP(f_x,0));
tagged_t vr50;
SwitchOnVar(vr49,vr50,{
BindHVA(vr49,BC_MakeBlob(w,&BcP(f_t,0+Fs(f_x))));
    }
,{
BindCVA(vr49,BC_MakeBlob(w,&BcP(f_t,0+Fs(f_x))));
    }
,{
BindSVA(vr49,BC_MakeBlob(w,&BcP(f_t,0+Fs(f_x))));
    }
,{
BC_EqBlob(vr49,&BcP(f_t,0+Fs(f_x)),{
goto fail;
      }
)    }
);
}P+=Fs(f_x)+LargeSize(*&BcP(f_t,0+Fs(f_x)));
goto r_dispatch;
    }
    }
case 98:
P+=Fs(f_Q);
goto r_op99;
case 99:
{
r_op99:
{
tagged_t vr51 = Xb(BcP(f_x,0));
tagged_t vr52;
SwitchOnVar(vr51,vr52,{
H = w->heap_top;
BindHVA(vr51,Tagp(STR,H));
HeapPush(H,BcP(f_f,0+Fs(f_x)));
P+=Fs(f_x)+Fs(f_f);
goto w_dispatch;
    }
,{
H = w->heap_top;
BindCVA(vr51,Tagp(STR,H));
HeapPush(H,BcP(f_f,0+Fs(f_x)));
P+=Fs(f_x)+Fs(f_f);
goto w_dispatch;
    }
,{
H = w->heap_top;
BindSVA(vr51,Tagp(STR,H));
HeapPush(H,BcP(f_f,0+Fs(f_x)));
P+=Fs(f_x)+Fs(f_f);
goto w_dispatch;
    }
,{
if (!TaggedIsSTR(vr51)||TaggedToHeadfunctor(vr51)!=BcP(f_f,0+Fs(f_x))) {
goto fail;
      }

S = TaggedToArg(vr51,1);
P+=Fs(f_x)+Fs(f_f);
goto r_dispatch;
    }
);
    }
    }
case 100:
{
r_op100:
{
tagged_t vr53 = Xb(BcP(f_x,0));
tagged_t vr54;
SwitchOnVar(vr53,vr54,{
BindHVA(vr53,atom_nil);
    }
,{
BindCVA(vr53,atom_nil);
    }
,{
BindSVA(vr53,atom_nil);
    }
,{
if (vr53!=atom_nil) {
goto fail;
      }

    }
);
P+=Fs(f_x);
goto r_dispatch;
    }
    }
case 101:
{
r_op101:
{
{tagged_t vr55 = Xb(BcP(f_x,0));
tagged_t vr56;
SwitchOnVar(vr55,vr56,{
H = w->heap_top;
BindHVA(vr55,Tagp(LST,H));
P+=Fs(f_x);
goto w_dispatch;
    }
,{
H = w->heap_top;
BindCVA(vr55,Tagp(LST,H));
P+=Fs(f_x);
goto w_dispatch;
    }
,{
H = w->heap_top;
BindSVA(vr55,Tagp(LST,H));
P+=Fs(f_x);
goto w_dispatch;
    }
,{
if (!TermIsLST(vr55)) {
goto fail;
      }

S = TagpPtr(LST,vr55);
P+=Fs(f_x);
goto r_dispatch;
    }
);
}    }
    }
case 111:
P+=Fs(f_Q);
goto r_op112;
case 112:
{
r_op112:
{
tagged_t vr57 = Xb(BcP(f_x,0));
tagged_t vr58;
SwitchOnVar(vr57,vr58,{
BindHVA(vr57,BcP(f_t,0+Fs(f_x)));
    }
,{
BindCVA(vr57,BcP(f_t,0+Fs(f_x)));
    }
,{
BindSVA(vr57,BcP(f_t,0+Fs(f_x)));
    }
,{
if (vr57!=BcP(f_t,0+Fs(f_x))) {
goto fail;
      }

    }
);
H = w->heap_top;
goto w_op66;
    }
    }
case 113:
{
r_op113:
{
tagged_t vr59 = Xb(BcP(f_x,0));
tagged_t vr60;
SwitchOnVar(vr59,vr60,{
BindHVA(vr59,atom_nil);
    }
,{
BindCVA(vr59,atom_nil);
    }
,{
BindSVA(vr59,atom_nil);
    }
,{
if (vr59!=atom_nil) {
goto fail;
      }

    }
);
H = w->heap_top;
goto w_op66;
    }
    }
case 208:
r_op208:
w->local_top = 0;
w->previous_choice = ChoiceFromTagged(Xb(BcP(f_x,0)));
PROFILE__HOOK_CUT;
B = w->previous_choice;
SetChoice(B);
TRACE_CHPT_CUT(w->choice);
ConcChptCleanUp(TopConcChpt,w->choice);
P+=Fs(f_x);
goto r_dispatch;
case 210:
r_op210:
w->local_top = 0;
w->previous_choice = ChoiceFromTagged(Xb(BcP(f_x,0)));
P+=Fs(f_x);
goto r_op211;
case 211:
r_op211:
PROFILE__HOOK_CUT;
B = w->previous_choice;
SetChoice(B);
TRACE_CHPT_CUT(w->choice);
ConcChptCleanUp(TopConcChpt,w->choice);
if (!IsDeep()) {
SetDeep();
if (ChoiceYounger(ChoiceOffset(B,CHOICEPAD),w->trail_top)) {
choice_overflow(w,2*CHOICEPAD*sizeof(tagged_t),TRUE);
      }

    }

P+=0;
goto r_dispatch;
case 212:
r_op212:
w->previous_choice = ChoiceFromTagged(Xb(BcP(f_x,0)));
goto r_op213;
case 213:
r_op213:
PROFILE__HOOK_CUT;
B = w->previous_choice;
SetChoice(B);
TRACE_CHPT_CUT(w->choice);
ConcChptCleanUp(TopConcChpt,w->choice);
if (!IsDeep()) {
SetDeep();
if (ChoiceYounger(ChoiceOffset(B,CHOICEPAD),w->trail_top)) {
choice_overflow(w,2*CHOICEPAD*sizeof(tagged_t),TRUE);
      }

    }

goto r_op64;
case 214:
r_op214:
w->previous_choice = ChoiceFromTagged(Xb(BcP(f_x,0)));
w->local_top = E;
PROFILE__HOOK_CUT;
B = w->previous_choice;
SetChoice(B);
TRACE_CHPT_CUT(w->choice);
ConcChptCleanUp(TopConcChpt,w->choice);
SetE(w->local_top);
P+=Fs(f_x);
goto r_dispatch;
case 216:
r_op216:
w->previous_choice = ChoiceFromTagged(Xb(BcP(f_x,0)));
P+=Fs(f_x);
goto r_op217;
case 217:
r_op217:
w->local_top = E;
PROFILE__HOOK_CUT;
B = w->previous_choice;
SetChoice(B);
TRACE_CHPT_CUT(w->choice);
ConcChptCleanUp(TopConcChpt,w->choice);
SetDeep();
if (ChoiceYounger(ChoiceOffset(B,CHOICEPAD),w->trail_top)) {
choice_overflow(w,2*CHOICEPAD*sizeof(tagged_t),TRUE);
    }

SetE(w->local_top);
P+=0;
goto r_dispatch;
case 215:
r_op215:
w->previous_choice = ChoiceFromTagged(Xb(BcP(f_x,0)));
P+=Fs(f_x);
goto r_op209;
case 209:
r_op209:
PROFILE__HOOK_CUT;
B = w->previous_choice;
SetChoice(B);
TRACE_CHPT_CUT(w->choice);
ConcChptCleanUp(TopConcChpt,w->choice);
SetE(w->frame);
P+=0;
goto r_dispatch;
case 218:
{
r_op218:
{
tagged_t vr61;
vr61 = Yb(BcP(f_y,0));
w->previous_choice = ChoiceFromTagged(vr61);
PROFILE__HOOK_CUT;
B = w->previous_choice;
SetChoice(B);
TRACE_CHPT_CUT(w->choice);
ConcChptCleanUp(TopConcChpt,w->choice);
SetE(w->frame);
P+=Fs(f_y);
goto r_dispatch;
P+=Fs(f_y);
goto r_dispatch;
    }
    }
case 219:
Xb(BcP(f_x,0)) = ChoiceToTagged(w->previous_choice);
P+=Fs(f_x);
goto r_dispatch;
case 220:
CODE_ALLOC(E);
goto r_op221;
case 221:
r_op221:
Yb(BcP(f_y,0)) = ChoiceToTagged(w->previous_choice);
P+=Fs(f_y);
goto r_dispatch;
case 233:
H = w->heap_top;
goto w_op233;
case 234:
r_op234:
goto r_op235;
case 235:
r_op235:
goto exit_toplevel;
case 237:
r_op237:
if (!IsDeep()) {
NECK_RETRY_PATCH(B);
SetDeep();
    }

if (!((cbool0_t)BcP(f_C,0+Fs(f_Q)))(w)) {
goto fail;
    }

goto r_op64;
case 238:
r_op238:
if (!IsDeep()) {
NECK_RETRY_PATCH(B);
SetDeep();
    }

if (!((cbool0_t)BcP(f_C,0))(w)) {
goto fail;
    }

goto r_op64;
case 104:
{
{
tagged_t vr62 = X(0);
S = TaggedToArg(vr62,1);
P+=Fs(f_Q)+Fs(f_f);
goto r_dispatch;
    }
    }
case 105:
{
{
tagged_t vr63 = X(0);
S = TaggedToArg(vr63,1);
P+=Fs(f_f);
goto r_dispatch;
    }
    }
case 256:
{
{
tagged_t vr64 = X(0);
{tagged_t vr65;
vr65 = vr64;
tagged_t vr66;
SwitchOnVar(vr65,vr66,{
BindHVA(vr65,BC_MakeBlob(w,&BcP(f_t,0+Fs(f_Q))));
    }
,{
BindCVA(vr65,BC_MakeBlob(w,&BcP(f_t,0+Fs(f_Q))));
    }
,{
BindSVA(vr65,BC_MakeBlob(w,&BcP(f_t,0+Fs(f_Q))));
    }
,{
BC_EqBlob(vr65,&BcP(f_t,0+Fs(f_Q)),{
goto fail;
      }
)    }
);
}P+=Fs(f_Q)+LargeSize(*&BcP(f_t,0+Fs(f_Q)));
goto r_dispatch;
    }
    }
case 257:
{
{
tagged_t vr67 = X(0);
{tagged_t vr68;
vr68 = vr67;
tagged_t vr69;
SwitchOnVar(vr68,vr69,{
BindHVA(vr68,BC_MakeBlob(w,&BcP(f_t,0)));
    }
,{
BindCVA(vr68,BC_MakeBlob(w,&BcP(f_t,0)));
    }
,{
BindSVA(vr68,BC_MakeBlob(w,&BcP(f_t,0)));
    }
,{
BC_EqBlob(vr68,&BcP(f_t,0),{
goto fail;
      }
)    }
);
}P+=LargeSize(*&BcP(f_t,0));
goto r_dispatch;
    }
    }
case 102:
P+=Fs(f_Q)+Fs(f_t);
goto r_dispatch;
case 103:
P+=Fs(f_t);
goto r_dispatch;
case 106:
P+=0;
goto r_dispatch;
case 107:
{
{
tagged_t vr70 = X(0);
S = TagpPtr(LST,vr70);
P+=0;
goto r_dispatch;
    }
    }
case 108:
Xb(BcP(f_x,0+Fs(f_x))) = Xb(BcP(f_x,0));
Xb(BcP(f_x,0+Fs(f_x)+Fs(f_x)+Fs(f_x))) = Xb(BcP(f_x,0+Fs(f_x)+Fs(f_x)));
P+=Fs(f_x)+Fs(f_x)+Fs(f_x)+Fs(f_x);
goto r_dispatch;
case 90:
Xb(BcP(f_x,0+Fs(f_x))) = Xb(BcP(f_x,0));
P+=Fs(f_x)+Fs(f_x);
goto r_dispatch;
case 92:
CODE_ALLOC(E);
goto r_op93;
case 93:
r_op93:
Yb(BcP(f_y,0+Fs(f_x))) = Xb(BcP(f_x,0));
P+=Fs(f_x)+Fs(f_y);
goto r_dispatch;
case 109:
CODE_ALLOC(E);
goto r_op110;
case 110:
r_op110:
Yb(BcP(f_y,0+Fs(f_x))) = Xb(BcP(f_x,0));
Yb(BcP(f_y,0+Fs(f_x)+Fs(f_y)+Fs(f_x))) = Xb(BcP(f_x,0+Fs(f_x)+Fs(f_y)));
P+=Fs(f_x)+Fs(f_y)+Fs(f_x)+Fs(f_y);
goto r_dispatch;
case 68:
P = BCoff(P,BcP(f_i,0));
goto r_dispatch;
case 222:
{
r_op222:
{
w->liveinfo = &BcP(f_l,0+Fs(f_Q)+Fs(f_x)+Fs(f_x)+Fs(f_C));
tagged_t vr71 = (tagged_t)((ctagged1_t)BcP(f_C,0+Fs(f_Q)+Fs(f_x)+Fs(f_x)))(w,Xb(BcP(f_x,0+Fs(f_Q)+Fs(f_x))));
Xb(BcP(f_x,0+Fs(f_Q))) = vr71;
if (ERRORTAG==vr71) {
goto fail;
    }

P+=Fs(f_Q)+Fs(f_x)+Fs(f_x)+Fs(f_C)+Fs(f_g);
goto r_dispatch;
    }
    }
case 223:
{
r_op223:
{
w->liveinfo = &BcP(f_l,0+Fs(f_x)+Fs(f_x)+Fs(f_C));
tagged_t vr72 = (tagged_t)((ctagged1_t)BcP(f_C,0+Fs(f_x)+Fs(f_x)))(w,Xb(BcP(f_x,0+Fs(f_x))));
Xb(BcP(f_x,0)) = vr72;
if (ERRORTAG==vr72) {
goto fail;
    }

P+=Fs(f_x)+Fs(f_x)+Fs(f_C)+Fs(f_g);
goto r_dispatch;
    }
    }
case 224:
{
r_op224:
{
w->liveinfo = &BcP(f_l,0+Fs(f_Q)+Fs(f_x)+Fs(f_x)+Fs(f_x)+Fs(f_C));
tagged_t vr73 = (tagged_t)((ctagged2_t)BcP(f_C,0+Fs(f_Q)+Fs(f_x)+Fs(f_x)+Fs(f_x)))(w,Xb(BcP(f_x,0+Fs(f_Q)+Fs(f_x))),Xb(BcP(f_x,0+Fs(f_Q)+Fs(f_x)+Fs(f_x))));
Xb(BcP(f_x,0+Fs(f_Q))) = vr73;
if (ERRORTAG==vr73) {
goto fail;
    }

P+=Fs(f_Q)+Fs(f_x)+Fs(f_x)+Fs(f_x)+Fs(f_C)+Fs(f_g);
goto r_dispatch;
    }
    }
case 225:
{
r_op225:
{
w->liveinfo = &BcP(f_l,0+Fs(f_x)+Fs(f_x)+Fs(f_x)+Fs(f_C));
tagged_t vr74 = (tagged_t)((ctagged2_t)BcP(f_C,0+Fs(f_x)+Fs(f_x)+Fs(f_x)))(w,Xb(BcP(f_x,0+Fs(f_x))),Xb(BcP(f_x,0+Fs(f_x)+Fs(f_x))));
Xb(BcP(f_x,0)) = vr74;
if (ERRORTAG==vr74) {
goto fail;
    }

P+=Fs(f_x)+Fs(f_x)+Fs(f_x)+Fs(f_C)+Fs(f_g);
goto r_dispatch;
    }
    }
case 226:
r_op226:
if (!((cbool1_t)BcP(f_C,0+Fs(f_Q)+Fs(f_x)))(w,Xb(BcP(f_x,0+Fs(f_Q))))) {
goto fail;
    }

P+=Fs(f_Q)+Fs(f_x)+Fs(f_C);
goto r_dispatch;
case 227:
r_op227:
if (!((cbool1_t)BcP(f_C,0+Fs(f_x)))(w,Xb(BcP(f_x,0)))) {
goto fail;
    }

P+=Fs(f_x)+Fs(f_C);
goto r_dispatch;
case 228:
r_op228:
if (!((cbool2_t)BcP(f_C,0+Fs(f_Q)+Fs(f_x)+Fs(f_x)))(w,Xb(BcP(f_x,0+Fs(f_Q))),Xb(BcP(f_x,0+Fs(f_Q)+Fs(f_x))))) {
goto fail;
    }

P+=Fs(f_Q)+Fs(f_x)+Fs(f_x)+Fs(f_C);
goto r_dispatch;
case 229:
r_op229:
if (!((cbool2_t)BcP(f_C,0+Fs(f_x)+Fs(f_x)))(w,Xb(BcP(f_x,0)),Xb(BcP(f_x,0+Fs(f_x))))) {
goto fail;
    }

P+=Fs(f_x)+Fs(f_x)+Fs(f_C);
goto r_dispatch;
case 230:
r_op230:
if (!((cbool3_t)BcP(f_C,0+Fs(f_Q)+Fs(f_x)+Fs(f_x)+Fs(f_x)))(w,Xb(BcP(f_x,0+Fs(f_Q))),Xb(BcP(f_x,0+Fs(f_Q)+Fs(f_x))),Xb(BcP(f_x,0+Fs(f_Q)+Fs(f_x)+Fs(f_x))))) {
goto fail;
    }

P+=Fs(f_Q)+Fs(f_x)+Fs(f_x)+Fs(f_x)+Fs(f_C);
goto r_dispatch;
case 231:
r_op231:
if (!((cbool3_t)BcP(f_C,0+Fs(f_x)+Fs(f_x)+Fs(f_x)))(w,Xb(BcP(f_x,0)),Xb(BcP(f_x,0+Fs(f_x))),Xb(BcP(f_x,0+Fs(f_x)+Fs(f_x))))) {
goto fail;
    }

P+=Fs(f_x)+Fs(f_x)+Fs(f_x)+Fs(f_C);
goto r_dispatch;
case 232:
r_op232:
if ((TaggedToRoot(X(RootArg))->behavior_on_failure!=DYNAMIC&&!next_instance_conc(w,&w->misc->ins))||(TaggedToRoot(X(RootArg))->behavior_on_failure==DYNAMIC&&!next_instance(w,&w->misc->ins))) {
SetDeep();
B = w->previous_choice;
SetChoice(B);
    }

if (w->misc->ins==NULL) {
ON_DEBUG({
if (debug_concchoicepoints) {
if (TaggedToRoot(X(RootArg))->behavior_on_failure!=CONC_CLOSED&&IS_BLOCKING(X(InvocationAttr))) {
fprintf(stderr,"**wam(): failing on a concurrent closed pred, chpt=%p, failing chpt=%p .\n",w->choice,TopConcChpt);
          }

        }

if (debug_conc) {
if (TaggedToRoot(X(RootArg))->x2_pending_on_instance||TaggedToRoot(X(RootArg))->x5_pending_on_instance) {
fprintf(stderr,"**wam(): failing with invokations pending from root, type = %d.\n",TaggedToRoot(X(RootArg))->behavior_on_failure);
          }

        }

      }
);
TopConcChpt = TermToPointerOrNull(choice_t,X(PrevDynChpt));
ON_DEBUG({
if (debug_concchoicepoints) {
fprintf(stderr,"New topmost concurrent chpt = %x\n",TopConcChpt);
        }

      }
);
goto fail;
    }

ON_DEBUG({
if (debug_conc&&TaggedToRoot(X(RootArg))->behavior_on_failure!=DYNAMIC) {
fprintf(stderr,"*** " PRIdm "backtracking on a concurrent predicate.\n",(intmach_t)Thread_Id,(intmach_t)GET_INC_COUNTER);
      }

if (debug_concchoicepoints&&TaggedToRoot(X(RootArg))->behavior_on_failure!=DYNAMIC) {
fprintf(stderr,"backtracking to chpt. = %p\n",w->choice);
      }

    }
);
P = (bcp_t)w->misc->ins->emulcode;
goto r_dispatch;
case 247:
H = w->heap_top;
goto w_op247;
case 114:
S = HeapOffset(S,BcP(f_i,0));
P+=Fs(f_i);
goto r_dispatch;
case 115:
S = HeapOffset(S,1);
P+=0;
goto r_dispatch;
case 116:
S = HeapOffset(S,2);
P+=0;
goto r_dispatch;
case 117:
S = HeapOffset(S,3);
P+=0;
goto r_dispatch;
case 118:
S = HeapOffset(S,4);
P+=0;
goto r_dispatch;
case 119:
RefHeapNext(Xb(BcP(f_x,0)),S);
P+=Fs(f_x);
goto r_dispatch;
case 120:
goto r_op121;
case 121:
{
r_op121:
{
{tagged_t vr75;
RefHeapNext(vr75,S);
if (!CBOOL__SUCCEED(cunify,Xb(BcP(f_x,0)),vr75)) {
goto fail;
    }

}P+=Fs(f_x);
goto r_dispatch;
    }
    }
case 122:
CODE_ALLOC(E);
goto r_op123;
case 123:
r_op123:
RefHeapNext(Yb(BcP(f_y,0)),S);
P+=Fs(f_y);
goto r_dispatch;
case 124:
{
{
{tagged_t vr76;
RefHeapNext(vr76,S);
if (CondStackvar(Yb(BcP(f_y,0)))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0))));
    }

Yb(BcP(f_y,0)) = vr76;
}P+=Fs(f_y);
goto r_dispatch;
    }
    }
case 125:
goto r_op126;
case 126:
{
r_op126:
{
{tagged_t vr77;
RefHeapNext(vr77,S);
if (!CBOOL__SUCCEED(cunify,Yb(BcP(f_y,0)),vr77)) {
goto fail;
    }

}P+=Fs(f_y);
goto r_dispatch;
    }
    }
case 127:
P+=Fs(f_Q);
goto r_op128;
case 128:
{
r_op128:
{
tagged_t vr78;
RefHeapNext(vr78,S);
tagged_t vr79 = vr78;
tagged_t vr80;
SwitchOnHeapVar(vr79,vr80,{
BindHVA(vr79,BcP(f_t,0));
    }
,{
BindCVA(vr79,BcP(f_t,0));
    }
,{
if (vr79!=BcP(f_t,0)) {
goto fail;
      }

    }
);
P+=Fs(f_t);
goto r_dispatch;
    }
    }
case 258:
P+=Fs(f_Q);
goto r_op259;
case 259:
{
r_op259:
{
tagged_t vr81;
RefHeapNext(vr81,S);
{tagged_t vr82 = vr81;
tagged_t vr83;
SwitchOnHeapVar(vr82,vr83,{
BindHVA(vr82,BC_MakeBlob(w,&BcP(f_t,0)));
    }
,{
BindCVA(vr82,BC_MakeBlob(w,&BcP(f_t,0)));
    }
,{
BC_EqBlob(vr82,&BcP(f_t,0),{
goto fail;
      }
)    }
);
}P+=LargeSize(*&BcP(f_t,0));
goto r_dispatch;
    }
    }
case 129:
P+=Fs(f_Q);
goto r_op130;
case 130:
{
r_op130:
{
tagged_t vr84;
RefHeapNext(vr84,S);
tagged_t vr85 = vr84;
tagged_t vr86;
SwitchOnHeapVar(vr85,vr86,{
H = w->heap_top;
BindHVA(vr85,Tagp(STR,H));
HeapPush(H,BcP(f_f,0));
P+=Fs(f_f);
goto w_dispatch;
    }
,{
H = w->heap_top;
BindCVA(vr85,Tagp(STR,H));
HeapPush(H,BcP(f_f,0));
P+=Fs(f_f);
goto w_dispatch;
    }
,{
if (!TaggedIsSTR(vr85)||TaggedToHeadfunctor(vr85)!=BcP(f_f,0)) {
goto fail;
      }

S = TaggedToArg(vr85,1);
P+=Fs(f_f);
goto r_dispatch;
    }
);
    }
    }
case 131:
{
{
tagged_t vr87;
RefHeapNext(vr87,S);
tagged_t vr88 = vr87;
tagged_t vr89;
SwitchOnHeapVar(vr88,vr89,{
BindHVA(vr88,atom_nil);
    }
,{
BindCVA(vr88,atom_nil);
    }
,{
if (vr88!=atom_nil) {
goto fail;
      }

    }
);
P+=0;
goto r_dispatch;
    }
    }
case 132:
{
{
tagged_t vr90;
RefHeapNext(vr90,S);
{tagged_t vr91 = vr90;
tagged_t vr92;
SwitchOnHeapVar(vr91,vr92,{
H = w->heap_top;
BindHVA(vr91,Tagp(LST,H));
P+=0;
goto w_dispatch;
    }
,{
H = w->heap_top;
BindCVA(vr91,Tagp(LST,H));
P+=0;
goto w_dispatch;
    }
,{
if (!TermIsLST(vr91)) {
goto fail;
      }

S = TagpPtr(LST,vr91);
P+=0;
goto r_dispatch;
    }
);
}    }
    }
case 133:
P+=Fs(f_Q);
goto r_op134;
case 134:
{
r_op134:
{
tagged_t vr93;
RefHeapNext(vr93,S);
tagged_t vr94 = vr93;
tagged_t vr95;
SwitchOnHeapVar(vr94,vr95,{
BindHVA(vr94,BcP(f_t,0));
    }
,{
BindCVA(vr94,BcP(f_t,0));
    }
,{
if (vr94!=BcP(f_t,0)) {
goto fail;
      }

    }
);
H = w->heap_top;
goto w_op66;
    }
    }
case 135:
{
{
tagged_t vr96;
RefHeapNext(vr96,S);
tagged_t vr97 = vr96;
tagged_t vr98;
SwitchOnHeapVar(vr97,vr98,{
BindHVA(vr97,atom_nil);
    }
,{
BindCVA(vr97,atom_nil);
    }
,{
if (vr97!=atom_nil) {
goto fail;
      }

    }
);
H = w->heap_top;
goto w_op66;
    }
    }
case 136:
S = HeapOffset(S,BcP(f_i,0));
RefHeapNext(Xb(BcP(f_x,0+Fs(f_i))),S);
P+=Fs(f_i)+Fs(f_x);
goto r_dispatch;
case 139:
CODE_ALLOC(E);
goto r_op140;
case 140:
r_op140:
S = HeapOffset(S,BcP(f_i,0));
RefHeapNext(Yb(BcP(f_y,0+Fs(f_i))),S);
P+=Fs(f_i)+Fs(f_y);
goto r_dispatch;
case 137:
goto r_op138;
case 138:
{
r_op138:
{
S = HeapOffset(S,BcP(f_i,0));
{tagged_t vr99;
RefHeapNext(vr99,S);
if (!CBOOL__SUCCEED(cunify,Xb(BcP(f_x,0+Fs(f_i))),vr99)) {
goto fail;
    }

}P+=Fs(f_i)+Fs(f_x);
goto r_dispatch;
    }
    }
case 141:
{
{
S = HeapOffset(S,BcP(f_i,0));
{tagged_t vr100;
RefHeapNext(vr100,S);
if (CondStackvar(Yb(BcP(f_y,0+Fs(f_i))))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0+Fs(f_i)))));
    }

Yb(BcP(f_y,0+Fs(f_i))) = vr100;
}P+=Fs(f_i)+Fs(f_y);
goto r_dispatch;
    }
    }
case 142:
goto r_op143;
case 143:
{
r_op143:
{
S = HeapOffset(S,BcP(f_i,0));
{tagged_t vr101;
RefHeapNext(vr101,S);
if (!CBOOL__SUCCEED(cunify,Yb(BcP(f_y,0+Fs(f_i))),vr101)) {
goto fail;
    }

}P+=Fs(f_i)+Fs(f_y);
goto r_dispatch;
    }
    }
case 144:
RefHeapNext(Xb(BcP(f_x,0)),S);
S = HeapOffset(S,BcP(f_i,0+Fs(f_x)));
P+=Fs(f_x)+Fs(f_i);
goto r_dispatch;
case 145:
RefHeapNext(Xb(BcP(f_x,0)),S);
RefHeapNext(Xb(BcP(f_x,0+Fs(f_x))),S);
P+=Fs(f_x)+Fs(f_x);
goto r_dispatch;
case 148:
CODE_ALLOC(E);
goto r_op149;
case 149:
r_op149:
RefHeapNext(Xb(BcP(f_x,0)),S);
RefHeapNext(Yb(BcP(f_y,0+Fs(f_x))),S);
P+=Fs(f_x)+Fs(f_y);
goto r_dispatch;
case 146:
goto r_op147;
case 147:
{
r_op147:
{
RefHeapNext(Xb(BcP(f_x,0)),S);
{tagged_t vr102;
RefHeapNext(vr102,S);
if (!CBOOL__SUCCEED(cunify,Xb(BcP(f_x,0+Fs(f_x))),vr102)) {
goto fail;
    }

}P+=Fs(f_x)+Fs(f_x);
goto r_dispatch;
    }
    }
case 150:
{
{
RefHeapNext(Xb(BcP(f_x,0)),S);
{tagged_t vr103;
RefHeapNext(vr103,S);
if (CondStackvar(Yb(BcP(f_y,0+Fs(f_x))))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0+Fs(f_x)))));
    }

Yb(BcP(f_y,0+Fs(f_x))) = vr103;
}P+=Fs(f_x)+Fs(f_y);
goto r_dispatch;
    }
    }
case 151:
goto r_op152;
case 152:
{
r_op152:
{
RefHeapNext(Xb(BcP(f_x,0)),S);
{tagged_t vr104;
RefHeapNext(vr104,S);
if (!CBOOL__SUCCEED(cunify,Yb(BcP(f_y,0+Fs(f_x))),vr104)) {
goto fail;
    }

}P+=Fs(f_x)+Fs(f_y);
goto r_dispatch;
    }
    }
case 153:
CODE_ALLOC(E);
goto r_op154;
case 154:
r_op154:
RefHeapNext(Yb(BcP(f_y,0)),S);
S = HeapOffset(S,BcP(f_i,0+Fs(f_y)));
P+=Fs(f_y)+Fs(f_i);
goto r_dispatch;
case 155:
CODE_ALLOC(E);
goto r_op156;
case 156:
r_op156:
RefHeapNext(Yb(BcP(f_y,0)),S);
RefHeapNext(Xb(BcP(f_x,0+Fs(f_y))),S);
P+=Fs(f_y)+Fs(f_x);
goto r_dispatch;
case 157:
CODE_ALLOC(E);
goto r_op158;
case 158:
r_op158:
RefHeapNext(Yb(BcP(f_y,0)),S);
RefHeapNext(Yb(BcP(f_y,0+Fs(f_y))),S);
P+=Fs(f_y)+Fs(f_y);
goto r_dispatch;
case 159:
goto r_op161;
case 161:
r_op161:
CODE_ALLOC(E);
goto r_op162;
case 160:
goto r_op162;
case 162:
{
r_op162:
{
RefHeapNext(Yb(BcP(f_y,0)),S);
{tagged_t vr105;
RefHeapNext(vr105,S);
if (!CBOOL__SUCCEED(cunify,Xb(BcP(f_x,0+Fs(f_y))),vr105)) {
goto fail;
    }

}P+=Fs(f_y)+Fs(f_x);
goto r_dispatch;
    }
    }
case 163:
goto r_op165;
case 165:
r_op165:
CODE_ALLOC(E);
goto r_op166;
case 164:
goto r_op166;
case 166:
{
r_op166:
{
RefHeapNext(Yb(BcP(f_y,0)),S);
{tagged_t vr106;
RefHeapNext(vr106,S);
if (!CBOOL__SUCCEED(cunify,Yb(BcP(f_y,0+Fs(f_y))),vr106)) {
goto fail;
    }

}P+=Fs(f_y)+Fs(f_y);
goto r_dispatch;
    }
    }
case 185:
{
{
{tagged_t vr107;
RefHeapNext(vr107,S);
if (CondStackvar(Yb(BcP(f_y,0)))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0))));
    }

Yb(BcP(f_y,0)) = vr107;
}S = HeapOffset(S,BcP(f_i,0+Fs(f_y)));
P+=Fs(f_y)+Fs(f_i);
goto r_dispatch;
    }
    }
case 188:
{
{
{tagged_t vr108;
RefHeapNext(vr108,S);
if (CondStackvar(Yb(BcP(f_y,0)))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0))));
    }

Yb(BcP(f_y,0)) = vr108;
}RefHeapNext(Xb(BcP(f_x,0+Fs(f_y))),S);
P+=Fs(f_y)+Fs(f_x);
goto r_dispatch;
    }
    }
case 199:
{
{
{tagged_t vr109;
RefHeapNext(vr109,S);
if (CondStackvar(Yb(BcP(f_y,0)))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0))));
    }

Yb(BcP(f_y,0)) = vr109;
}{tagged_t vr110;
RefHeapNext(vr110,S);
if (CondStackvar(Yb(BcP(f_y,0+Fs(f_y))))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0+Fs(f_y)))));
    }

Yb(BcP(f_y,0+Fs(f_y))) = vr110;
}P+=Fs(f_y)+Fs(f_y);
goto r_dispatch;
    }
    }
case 193:
goto r_op196;
case 196:
{
r_op196:
{
{tagged_t vr111;
RefHeapNext(vr111,S);
if (CondStackvar(Yb(BcP(f_y,0)))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0))));
    }

Yb(BcP(f_y,0)) = vr111;
}{tagged_t vr112;
RefHeapNext(vr112,S);
if (!CBOOL__SUCCEED(cunify,Xb(BcP(f_x,0+Fs(f_y))),vr112)) {
goto fail;
    }

}P+=Fs(f_y)+Fs(f_x);
goto r_dispatch;
    }
    }
case 202:
goto r_op205;
case 205:
{
r_op205:
{
{tagged_t vr113;
RefHeapNext(vr113,S);
if (CondStackvar(Yb(BcP(f_y,0)))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0))));
    }

Yb(BcP(f_y,0)) = vr113;
}{tagged_t vr114;
RefHeapNext(vr114,S);
if (!CBOOL__SUCCEED(cunify,Yb(BcP(f_y,0+Fs(f_y))),vr114)) {
goto fail;
    }

}P+=Fs(f_y)+Fs(f_y);
goto r_dispatch;
    }
    }
case 167:
goto r_op168;
case 168:
{
r_op168:
{
{tagged_t vr115;
RefHeapNext(vr115,S);
if (!CBOOL__SUCCEED(cunify,Xb(BcP(f_x,0)),vr115)) {
goto fail;
    }

}S = HeapOffset(S,BcP(f_i,0+Fs(f_x)));
P+=Fs(f_x)+Fs(f_i);
goto r_dispatch;
    }
    }
case 169:
goto r_op170;
case 170:
{
r_op170:
{
{tagged_t vr116;
RefHeapNext(vr116,S);
if (!CBOOL__SUCCEED(cunify,Xb(BcP(f_x,0)),vr116)) {
goto fail;
    }

}RefHeapNext(Xb(BcP(f_x,0+Fs(f_x))),S);
P+=Fs(f_x)+Fs(f_x);
goto r_dispatch;
    }
    }
case 171:
goto r_op172;
case 172:
r_op172:
CODE_ALLOC(E);
goto r_op174;
case 173:
goto r_op174;
case 174:
{
r_op174:
{
{tagged_t vr117;
RefHeapNext(vr117,S);
if (!CBOOL__SUCCEED(cunify,Xb(BcP(f_x,0)),vr117)) {
goto fail;
    }

}RefHeapNext(Yb(BcP(f_y,0+Fs(f_x))),S);
P+=Fs(f_x)+Fs(f_y);
goto r_dispatch;
    }
    }
case 175:
goto r_op177;
case 177:
r_op177:
goto r_op176;
case 176:
r_op176:
goto r_op178;
case 178:
{
r_op178:
{
{tagged_t vr118;
RefHeapNext(vr118,S);
if (!CBOOL__SUCCEED(cunify,Xb(BcP(f_x,0)),vr118)) {
goto fail;
    }

}{tagged_t vr119;
RefHeapNext(vr119,S);
if (!CBOOL__SUCCEED(cunify,Xb(BcP(f_x,0+Fs(f_x))),vr119)) {
goto fail;
    }

}P+=Fs(f_x)+Fs(f_x);
goto r_dispatch;
    }
    }
case 179:
goto r_op180;
case 180:
{
r_op180:
{
{tagged_t vr120;
RefHeapNext(vr120,S);
if (!CBOOL__SUCCEED(cunify,Xb(BcP(f_x,0)),vr120)) {
goto fail;
    }

}{tagged_t vr121;
RefHeapNext(vr121,S);
if (CondStackvar(Yb(BcP(f_y,0+Fs(f_x))))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0+Fs(f_x)))));
    }

Yb(BcP(f_y,0+Fs(f_x))) = vr121;
}P+=Fs(f_x)+Fs(f_y);
goto r_dispatch;
    }
    }
case 181:
goto r_op183;
case 183:
r_op183:
goto r_op182;
case 182:
r_op182:
goto r_op184;
case 184:
{
r_op184:
{
{tagged_t vr122;
RefHeapNext(vr122,S);
if (!CBOOL__SUCCEED(cunify,Xb(BcP(f_x,0)),vr122)) {
goto fail;
    }

}{tagged_t vr123;
RefHeapNext(vr123,S);
if (!CBOOL__SUCCEED(cunify,Yb(BcP(f_y,0+Fs(f_x))),vr123)) {
goto fail;
    }

}P+=Fs(f_x)+Fs(f_y);
goto r_dispatch;
    }
    }
case 186:
goto r_op187;
case 187:
{
r_op187:
{
{tagged_t vr124;
RefHeapNext(vr124,S);
if (!CBOOL__SUCCEED(cunify,Yb(BcP(f_y,0)),vr124)) {
goto fail;
    }

}S = HeapOffset(S,BcP(f_i,0+Fs(f_y)));
P+=Fs(f_y)+Fs(f_i);
goto r_dispatch;
    }
    }
case 189:
goto r_op190;
case 190:
{
r_op190:
{
{tagged_t vr125;
RefHeapNext(vr125,S);
if (!CBOOL__SUCCEED(cunify,Yb(BcP(f_y,0)),vr125)) {
goto fail;
    }

}RefHeapNext(Xb(BcP(f_x,0+Fs(f_y))),S);
P+=Fs(f_y)+Fs(f_x);
goto r_dispatch;
    }
    }
case 191:
goto r_op192;
case 192:
{
r_op192:
{
{tagged_t vr126;
RefHeapNext(vr126,S);
if (!CBOOL__SUCCEED(cunify,Yb(BcP(f_y,0)),vr126)) {
goto fail;
    }

}RefHeapNext(Yb(BcP(f_y,0+Fs(f_y))),S);
P+=Fs(f_y)+Fs(f_y);
goto r_dispatch;
    }
    }
case 200:
goto r_op201;
case 201:
{
r_op201:
{
{tagged_t vr127;
RefHeapNext(vr127,S);
if (!CBOOL__SUCCEED(cunify,Yb(BcP(f_y,0)),vr127)) {
goto fail;
    }

}{tagged_t vr128;
RefHeapNext(vr128,S);
if (CondStackvar(Yb(BcP(f_y,0+Fs(f_y))))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0+Fs(f_y)))));
    }

Yb(BcP(f_y,0+Fs(f_y))) = vr128;
}P+=Fs(f_y)+Fs(f_y);
goto r_dispatch;
    }
    }
case 194:
goto r_op197;
case 197:
r_op197:
goto r_op195;
case 195:
r_op195:
goto r_op198;
case 198:
{
r_op198:
{
{tagged_t vr129;
RefHeapNext(vr129,S);
if (!CBOOL__SUCCEED(cunify,Yb(BcP(f_y,0)),vr129)) {
goto fail;
    }

}{tagged_t vr130;
RefHeapNext(vr130,S);
if (!CBOOL__SUCCEED(cunify,Xb(BcP(f_x,0+Fs(f_y))),vr130)) {
goto fail;
    }

}P+=Fs(f_y)+Fs(f_x);
goto r_dispatch;
    }
    }
case 203:
goto r_op206;
case 206:
r_op206:
goto r_op204;
case 204:
r_op204:
goto r_op207;
case 207:
{
r_op207:
{
{tagged_t vr131;
RefHeapNext(vr131,S);
if (!CBOOL__SUCCEED(cunify,Yb(BcP(f_y,0)),vr131)) {
goto fail;
    }

}{tagged_t vr132;
RefHeapNext(vr132,S);
if (!CBOOL__SUCCEED(cunify,Yb(BcP(f_y,0+Fs(f_y))),vr132)) {
goto fail;
    }

}P+=Fs(f_y)+Fs(f_y);
goto r_dispatch;
    }
    }
case 248:
P+=Fs(f_Q);
goto r_op249;
case 249:
r_op249:
#if defined(GAUGE)
INCR_COUNTER(BcP(f_l,0));
#endif
P+=Fs(f_l);
goto r_dispatch;
case 250:
P+=Fs(f_Q);
goto r_op251;
case 251:
r_op251:
#if defined(GAUGE)
if (!IsDeep()) {
B = w->choice;
if (!IsShallowTry()) {
#if defined(GAUGE)
INCR_COUNTER(BcP(f_l,0));
#endif
      }
 else {
#if defined(GAUGE)
INCR_COUNTER(BcP(f_l,0+Fs(f_l)));
#endif
      }

    }

#endif
P+=Fs(f_l)+Fs(f_l);
goto r_op65;
case 67:
goto fail;
case 245:
P+=Fs(f_Q);
goto r_op246;
case 246:
r_op246:
if (HeapCharDifference(w->heap_top,Heap_End)<(intmach_t)BcP(f_l,0)) {
explicit_heap_overflow(w,(intmach_t)BcP(f_l,0)*2,(FTYPE_ctype(f_i_signed))BcP(f_i,0+Fs(f_l)));
    }

P+=Fs(f_l)+Fs(f_i);
goto r_dispatch;
case 65:
{
r_op65:
{
if (!IsDeep()) {
B = w->choice;
if (!IsShallowTry()) {
NECK_RETRY_PATCH(B);
      }
 else {
B->next_alt = w->next_alt;
B->frame = w->frame;
B->next_insn = w->next_insn;
B->local_top = w->local_top;
intmach_t vr133 = ChoiceArity(B);
for (intmach_t vr134 = 0;
vr134<vr133;vr134++) {
B->x[vr134] = w->x[vr134];
        }

if (ChoiceYounger(ChoiceOffset(B,CHOICEPAD),w->trail_top)) {
choice_overflow(w,2*CHOICEPAD*sizeof(tagged_t),TRUE);
        }

      }

SetDeep();
SetE(w->local_top);
    }

P+=0;
goto r_dispatch;
    }
    }
case 236:
H = w->heap_top;
goto w_op236;
case 66:
H = w->heap_top;
goto w_op66;
case 64:
r_op64:
w->local_top = 0;
SetE(w->frame);
P = w->next_insn;
PROFILE__HOOK_PROCEED;
P+=0;
goto r_dispatch;
#if defined(PARBACK)
case 262:
w->heap_top = TaggedToPointer(w->choice->x[0]);
H = w->heap_top;
P = (bcp_t)*TaggedToPointer(w->choice->x[0]);
w->next_insn = w->choice->next_insn;
pop_choicept(w);
goto enter_predicate;
#endif
default:
goto illop;
  }
  }
w_tryeach:
{
#if defined(GAUGE)
INCR_COUNTER(alts->entry_counter);
#endif
P = alts->emul_p;
w->previous_choice = w->choice;
try_node_t * vr135 = alts->next;
if (vr135!=NULL) {
B = w->choice;
GetFrameTop(w->local_top,B,G->frame);
CODE_CHOICE_NEW0(B,vr135,H);
ON_DEBUG({
if (debug_choicepoints) {
fprintf(stderr,"WAM created choicepoint (r), node = %p\n",w->choice);
      }

    }
);
if (ChoiceYounger(ChoiceOffset(B,CHOICEPAD),w->trail_top)) {
choice_overflow(w,2*CHOICEPAD*sizeof(tagged_t),TRUE);
    }

  }
 else {
SetDeep();
  }

goto w_dispatch;
  }
w_dispatch:
{
switch (BcOPCODE) {
case 260:
{
w_op260:
{
CODE_ALLOC(E);
for (intmach_t vr136 = BcP(f_e,0)-sizeof(tagged_t);
vr136>=EToY0*sizeof(tagged_t);vr136-=sizeof(tagged_t)) {
LoadSVA(Yb(vr136));
    }

goto firsttrue;
    }
    }
case 261:
{
w_op261:
{
intmach_t vr137 = (FTYPE_ctype(f_i_signed))BcP(f_i,0);
P+=Fs(f_i);
for (intmach_t vr138 = vr137;
vr138>0;vr138--) {
tagged_t vr139 = BcP(f_y,0);
P+=Fs(f_y);
LoadSVA(Yb(vr139));
    }

goto firsttrue;
firsttrue:
E->next_insn = w->next_insn;
E->frame = w->frame;
w->frame = E;
w->next_insn = BCoff(P,Fs(f_e));
w->local_top = StackCharOffset(E,BcP(f_e,0));
if (OffStacktop(E,Stack_Warn)) {
SetEvent();
    }

P+=Fs(f_e);
goto w_dispatch;
    }
    }
case 0:
P+=Fs(f_Q);
goto w_op1;
case 1:
{
w_op1:
{
CODE_ALLOC(E);
for (intmach_t vr140 = BcP(f_e,0+Fs(f_E))-sizeof(tagged_t);
vr140>=EToY0*sizeof(tagged_t);vr140-=sizeof(tagged_t)) {
LoadSVA(Yb(vr140));
    }

goto w_op3;
    }
    }
case 20:
P+=Fs(f_Q);
goto w_op21;
case 21:
{
w_op21:
{
intmach_t vr141 = (FTYPE_ctype(f_i_signed))BcP(f_i,0);
P+=Fs(f_i);
for (intmach_t vr142 = vr141;
vr142>8;vr142--) {
tagged_t vr143 = BcP(f_y,0);
P+=Fs(f_y);
LoadSVA(Yb(vr143));
    }

goto w_op19;
    }
    }
case 18:
P+=Fs(f_Q);
goto w_op19;
case 19:
{
w_op19:
{
{
tagged_t vr144 = BcP(f_y,0);
P+=Fs(f_y);
LoadSVA(Yb(vr144));
    }
goto w_op17;
    }
    }
case 16:
P+=Fs(f_Q);
goto w_op17;
case 17:
{
w_op17:
{
{
tagged_t vr145 = BcP(f_y,0);
P+=Fs(f_y);
LoadSVA(Yb(vr145));
    }
goto w_op15;
    }
    }
case 14:
P+=Fs(f_Q);
goto w_op15;
case 15:
{
w_op15:
{
{
tagged_t vr146 = BcP(f_y,0);
P+=Fs(f_y);
LoadSVA(Yb(vr146));
    }
goto w_op13;
    }
    }
case 12:
P+=Fs(f_Q);
goto w_op13;
case 13:
{
w_op13:
{
{
tagged_t vr147 = BcP(f_y,0);
P+=Fs(f_y);
LoadSVA(Yb(vr147));
    }
goto w_op11;
    }
    }
case 10:
P+=Fs(f_Q);
goto w_op11;
case 11:
{
w_op11:
{
{
tagged_t vr148 = BcP(f_y,0);
P+=Fs(f_y);
LoadSVA(Yb(vr148));
    }
goto w_op9;
    }
    }
case 8:
P+=Fs(f_Q);
goto w_op9;
case 9:
{
w_op9:
{
{
tagged_t vr149 = BcP(f_y,0);
P+=Fs(f_y);
LoadSVA(Yb(vr149));
    }
goto w_op7;
    }
    }
case 6:
P+=Fs(f_Q);
goto w_op7;
case 7:
{
w_op7:
{
{
tagged_t vr150 = BcP(f_y,0);
P+=Fs(f_y);
LoadSVA(Yb(vr150));
    }
goto w_op5;
    }
    }
case 4:
P+=Fs(f_Q);
goto w_op5;
case 5:
{
w_op5:
{
{
tagged_t vr151 = BcP(f_y,0);
P+=Fs(f_y);
LoadSVA(Yb(vr151));
    }
goto w_op3;
    }
    }
case 2:
P+=Fs(f_Q);
goto w_op3;
case 3:
w_op3:
E->next_insn = w->next_insn;
E->frame = w->frame;
w->frame = E;
w->next_insn = BCoff(P,Fs(f_E)+Fs(f_e));
w->local_top = StackCharOffset(E,BcP(f_e,0+Fs(f_E)));
if (OffStacktop(E,Stack_Warn)) {
SetEvent();
    }

P = BcP(f_p,0);
goto enter_predicate;
case 40:
P+=Fs(f_Q);
goto w_op41;
case 41:
{
w_op41:
{
intmach_t vr152 = (FTYPE_ctype(f_i_signed))BcP(f_i,0);
P+=Fs(f_i);
for (intmach_t vr153 = vr152;
vr153>8;vr153--) {
tagged_t vr154 = BcP(f_z,0);
P+=Fs(f_z);
if (vr154&1) {
tagged_t vr155;
tagged_t vr156;
vr155 = Yb(vr154+1);
if (TaggedIsSVA(vr155)) {
do {
RefSVA(vr156,vr155);
if (vr156==vr155) {
if (!YoungerStackVar(Tagp(SVA,Offset(E,EToY0)),vr155)) {
LoadHVA(vr155,H);
BindSVA(vr156,vr155);
              }

break;
            }

vr155 = vr156;
          }
 while (TaggedIsSVA(vr155));
        }

X(vr153-1) = vr155;
      }
 else {
X(vr153-1) = Yb(vr154);
      }

    }

goto w_op39;
    }
    }
case 38:
P+=Fs(f_Q);
goto w_op39;
case 39:
{
w_op39:
{
{
tagged_t vr157 = BcP(f_z,0);
P+=Fs(f_z);
if (vr157&1) {
tagged_t vr158;
tagged_t vr159;
vr158 = Yb(vr157+1);
if (TaggedIsSVA(vr158)) {
do {
RefSVA(vr159,vr158);
if (vr159==vr158) {
if (!YoungerStackVar(Tagp(SVA,Offset(E,EToY0)),vr158)) {
LoadHVA(vr158,H);
BindSVA(vr159,vr158);
            }

break;
          }

vr158 = vr159;
        }
 while (TaggedIsSVA(vr158));
      }

X(7) = vr158;
    }
 else {
X(7) = Yb(vr157);
    }

    }
goto w_op37;
    }
    }
case 36:
P+=Fs(f_Q);
goto w_op37;
case 37:
{
w_op37:
{
{
tagged_t vr160 = BcP(f_z,0);
P+=Fs(f_z);
if (vr160&1) {
tagged_t vr161;
tagged_t vr162;
vr161 = Yb(vr160+1);
if (TaggedIsSVA(vr161)) {
do {
RefSVA(vr162,vr161);
if (vr162==vr161) {
if (!YoungerStackVar(Tagp(SVA,Offset(E,EToY0)),vr161)) {
LoadHVA(vr161,H);
BindSVA(vr162,vr161);
            }

break;
          }

vr161 = vr162;
        }
 while (TaggedIsSVA(vr161));
      }

X(6) = vr161;
    }
 else {
X(6) = Yb(vr160);
    }

    }
goto w_op35;
    }
    }
case 34:
P+=Fs(f_Q);
goto w_op35;
case 35:
{
w_op35:
{
{
tagged_t vr163 = BcP(f_z,0);
P+=Fs(f_z);
if (vr163&1) {
tagged_t vr164;
tagged_t vr165;
vr164 = Yb(vr163+1);
if (TaggedIsSVA(vr164)) {
do {
RefSVA(vr165,vr164);
if (vr165==vr164) {
if (!YoungerStackVar(Tagp(SVA,Offset(E,EToY0)),vr164)) {
LoadHVA(vr164,H);
BindSVA(vr165,vr164);
            }

break;
          }

vr164 = vr165;
        }
 while (TaggedIsSVA(vr164));
      }

X(5) = vr164;
    }
 else {
X(5) = Yb(vr163);
    }

    }
goto w_op33;
    }
    }
case 32:
P+=Fs(f_Q);
goto w_op33;
case 33:
{
w_op33:
{
{
tagged_t vr166 = BcP(f_z,0);
P+=Fs(f_z);
if (vr166&1) {
tagged_t vr167;
tagged_t vr168;
vr167 = Yb(vr166+1);
if (TaggedIsSVA(vr167)) {
do {
RefSVA(vr168,vr167);
if (vr168==vr167) {
if (!YoungerStackVar(Tagp(SVA,Offset(E,EToY0)),vr167)) {
LoadHVA(vr167,H);
BindSVA(vr168,vr167);
            }

break;
          }

vr167 = vr168;
        }
 while (TaggedIsSVA(vr167));
      }

X(4) = vr167;
    }
 else {
X(4) = Yb(vr166);
    }

    }
goto w_op31;
    }
    }
case 30:
P+=Fs(f_Q);
goto w_op31;
case 31:
{
w_op31:
{
{
tagged_t vr169 = BcP(f_z,0);
P+=Fs(f_z);
if (vr169&1) {
tagged_t vr170;
tagged_t vr171;
vr170 = Yb(vr169+1);
if (TaggedIsSVA(vr170)) {
do {
RefSVA(vr171,vr170);
if (vr171==vr170) {
if (!YoungerStackVar(Tagp(SVA,Offset(E,EToY0)),vr170)) {
LoadHVA(vr170,H);
BindSVA(vr171,vr170);
            }

break;
          }

vr170 = vr171;
        }
 while (TaggedIsSVA(vr170));
      }

X(3) = vr170;
    }
 else {
X(3) = Yb(vr169);
    }

    }
goto w_op29;
    }
    }
case 28:
P+=Fs(f_Q);
goto w_op29;
case 29:
{
w_op29:
{
{
tagged_t vr172 = BcP(f_z,0);
P+=Fs(f_z);
if (vr172&1) {
tagged_t vr173;
tagged_t vr174;
vr173 = Yb(vr172+1);
if (TaggedIsSVA(vr173)) {
do {
RefSVA(vr174,vr173);
if (vr174==vr173) {
if (!YoungerStackVar(Tagp(SVA,Offset(E,EToY0)),vr173)) {
LoadHVA(vr173,H);
BindSVA(vr174,vr173);
            }

break;
          }

vr173 = vr174;
        }
 while (TaggedIsSVA(vr173));
      }

X(2) = vr173;
    }
 else {
X(2) = Yb(vr172);
    }

    }
goto w_op27;
    }
    }
case 26:
P+=Fs(f_Q);
goto w_op27;
case 27:
{
w_op27:
{
{
tagged_t vr175 = BcP(f_z,0);
P+=Fs(f_z);
if (vr175&1) {
tagged_t vr176;
tagged_t vr177;
vr176 = Yb(vr175+1);
if (TaggedIsSVA(vr176)) {
do {
RefSVA(vr177,vr176);
if (vr177==vr176) {
if (!YoungerStackVar(Tagp(SVA,Offset(E,EToY0)),vr176)) {
LoadHVA(vr176,H);
BindSVA(vr177,vr176);
            }

break;
          }

vr176 = vr177;
        }
 while (TaggedIsSVA(vr176));
      }

X(1) = vr176;
    }
 else {
X(1) = Yb(vr175);
    }

    }
goto w_op25;
    }
    }
case 24:
P+=Fs(f_Q);
goto w_op25;
case 25:
{
w_op25:
{
{
tagged_t vr178 = BcP(f_z,0);
P+=Fs(f_z);
if (vr178&1) {
tagged_t vr179;
tagged_t vr180;
vr179 = Yb(vr178+1);
if (TaggedIsSVA(vr179)) {
do {
RefSVA(vr180,vr179);
if (vr180==vr179) {
if (!YoungerStackVar(Tagp(SVA,Offset(E,EToY0)),vr179)) {
LoadHVA(vr179,H);
BindSVA(vr180,vr179);
            }

break;
          }

vr179 = vr180;
        }
 while (TaggedIsSVA(vr179));
      }

X(0) = vr179;
    }
 else {
X(0) = Yb(vr178);
    }

    }
goto w_op23;
    }
    }
case 22:
P+=Fs(f_Q);
goto w_op23;
case 23:
w_op23:
w->next_insn = BCoff(P,Fs(f_E)+Fs(f_e));
P = BcP(f_p,0);
goto enter_predicate;
case 60:
P+=Fs(f_Q);
goto w_op61;
case 61:
{
w_op61:
{
intmach_t vr181 = (FTYPE_ctype(f_i_signed))BcP(f_i,0);
P+=Fs(f_i);
for (intmach_t vr182 = vr181;
vr182>8;vr182--) {
tagged_t vr183 = BcP(f_z,0);
P+=Fs(f_z);
if (vr183&1) {
tagged_t vr184;
tagged_t vr185;
vr184 = Yb(vr183+1);
if (TaggedIsSVA(vr184)) {
do {
RefSVA(vr185,vr184);
if (vr185==vr184) {
if (!YoungerStackVar(Tagp(SVA,Offset(E,EToY0)),vr184)) {
LoadHVA(vr184,H);
BindSVA(vr185,vr184);
              }

break;
            }

vr184 = vr185;
          }
 while (TaggedIsSVA(vr184));
        }

X(vr182-1) = vr184;
      }
 else {
X(vr182-1) = Yb(vr183);
      }

    }

goto w_op59;
    }
    }
case 58:
P+=Fs(f_Q);
goto w_op59;
case 59:
{
w_op59:
{
{
tagged_t vr186 = BcP(f_z,0);
P+=Fs(f_z);
if (vr186&1) {
tagged_t vr187;
tagged_t vr188;
vr187 = Yb(vr186+1);
if (TaggedIsSVA(vr187)) {
do {
RefSVA(vr188,vr187);
if (vr188==vr187) {
if (!YoungerStackVar(Tagp(SVA,Offset(E,EToY0)),vr187)) {
LoadHVA(vr187,H);
BindSVA(vr188,vr187);
            }

break;
          }

vr187 = vr188;
        }
 while (TaggedIsSVA(vr187));
      }

X(7) = vr187;
    }
 else {
X(7) = Yb(vr186);
    }

    }
goto w_op57;
    }
    }
case 56:
P+=Fs(f_Q);
goto w_op57;
case 57:
{
w_op57:
{
{
tagged_t vr189 = BcP(f_z,0);
P+=Fs(f_z);
if (vr189&1) {
tagged_t vr190;
tagged_t vr191;
vr190 = Yb(vr189+1);
if (TaggedIsSVA(vr190)) {
do {
RefSVA(vr191,vr190);
if (vr191==vr190) {
if (!YoungerStackVar(Tagp(SVA,Offset(E,EToY0)),vr190)) {
LoadHVA(vr190,H);
BindSVA(vr191,vr190);
            }

break;
          }

vr190 = vr191;
        }
 while (TaggedIsSVA(vr190));
      }

X(6) = vr190;
    }
 else {
X(6) = Yb(vr189);
    }

    }
goto w_op55;
    }
    }
case 54:
P+=Fs(f_Q);
goto w_op55;
case 55:
{
w_op55:
{
{
tagged_t vr192 = BcP(f_z,0);
P+=Fs(f_z);
if (vr192&1) {
tagged_t vr193;
tagged_t vr194;
vr193 = Yb(vr192+1);
if (TaggedIsSVA(vr193)) {
do {
RefSVA(vr194,vr193);
if (vr194==vr193) {
if (!YoungerStackVar(Tagp(SVA,Offset(E,EToY0)),vr193)) {
LoadHVA(vr193,H);
BindSVA(vr194,vr193);
            }

break;
          }

vr193 = vr194;
        }
 while (TaggedIsSVA(vr193));
      }

X(5) = vr193;
    }
 else {
X(5) = Yb(vr192);
    }

    }
goto w_op53;
    }
    }
case 52:
P+=Fs(f_Q);
goto w_op53;
case 53:
{
w_op53:
{
{
tagged_t vr195 = BcP(f_z,0);
P+=Fs(f_z);
if (vr195&1) {
tagged_t vr196;
tagged_t vr197;
vr196 = Yb(vr195+1);
if (TaggedIsSVA(vr196)) {
do {
RefSVA(vr197,vr196);
if (vr197==vr196) {
if (!YoungerStackVar(Tagp(SVA,Offset(E,EToY0)),vr196)) {
LoadHVA(vr196,H);
BindSVA(vr197,vr196);
            }

break;
          }

vr196 = vr197;
        }
 while (TaggedIsSVA(vr196));
      }

X(4) = vr196;
    }
 else {
X(4) = Yb(vr195);
    }

    }
goto w_op51;
    }
    }
case 50:
P+=Fs(f_Q);
goto w_op51;
case 51:
{
w_op51:
{
{
tagged_t vr198 = BcP(f_z,0);
P+=Fs(f_z);
if (vr198&1) {
tagged_t vr199;
tagged_t vr200;
vr199 = Yb(vr198+1);
if (TaggedIsSVA(vr199)) {
do {
RefSVA(vr200,vr199);
if (vr200==vr199) {
if (!YoungerStackVar(Tagp(SVA,Offset(E,EToY0)),vr199)) {
LoadHVA(vr199,H);
BindSVA(vr200,vr199);
            }

break;
          }

vr199 = vr200;
        }
 while (TaggedIsSVA(vr199));
      }

X(3) = vr199;
    }
 else {
X(3) = Yb(vr198);
    }

    }
goto w_op49;
    }
    }
case 48:
P+=Fs(f_Q);
goto w_op49;
case 49:
{
w_op49:
{
{
tagged_t vr201 = BcP(f_z,0);
P+=Fs(f_z);
if (vr201&1) {
tagged_t vr202;
tagged_t vr203;
vr202 = Yb(vr201+1);
if (TaggedIsSVA(vr202)) {
do {
RefSVA(vr203,vr202);
if (vr203==vr202) {
if (!YoungerStackVar(Tagp(SVA,Offset(E,EToY0)),vr202)) {
LoadHVA(vr202,H);
BindSVA(vr203,vr202);
            }

break;
          }

vr202 = vr203;
        }
 while (TaggedIsSVA(vr202));
      }

X(2) = vr202;
    }
 else {
X(2) = Yb(vr201);
    }

    }
goto w_op47;
    }
    }
case 46:
P+=Fs(f_Q);
goto w_op47;
case 47:
{
w_op47:
{
{
tagged_t vr204 = BcP(f_z,0);
P+=Fs(f_z);
if (vr204&1) {
tagged_t vr205;
tagged_t vr206;
vr205 = Yb(vr204+1);
if (TaggedIsSVA(vr205)) {
do {
RefSVA(vr206,vr205);
if (vr206==vr205) {
if (!YoungerStackVar(Tagp(SVA,Offset(E,EToY0)),vr205)) {
LoadHVA(vr205,H);
BindSVA(vr206,vr205);
            }

break;
          }

vr205 = vr206;
        }
 while (TaggedIsSVA(vr205));
      }

X(1) = vr205;
    }
 else {
X(1) = Yb(vr204);
    }

    }
goto w_op45;
    }
    }
case 44:
P+=Fs(f_Q);
goto w_op45;
case 45:
{
w_op45:
{
{
tagged_t vr207 = BcP(f_z,0);
P+=Fs(f_z);
if (vr207&1) {
tagged_t vr208;
tagged_t vr209;
vr208 = Yb(vr207+1);
if (TaggedIsSVA(vr208)) {
do {
RefSVA(vr209,vr208);
if (vr209==vr208) {
if (!YoungerStackVar(Tagp(SVA,Offset(E,EToY0)),vr208)) {
LoadHVA(vr208,H);
BindSVA(vr209,vr208);
            }

break;
          }

vr208 = vr209;
        }
 while (TaggedIsSVA(vr208));
      }

X(0) = vr208;
    }
 else {
X(0) = Yb(vr207);
    }

    }
goto w_op43;
    }
    }
case 42:
P+=Fs(f_Q);
goto w_op43;
case 43:
w_op43:
w->next_insn = E->next_insn;
w->frame = E->frame;
goto w_op63;
case 62:
P = BcP(f_p,0+Fs(f_Q));
goto enter_predicate;
case 63:
w_op63:
P = BcP(f_p,0);
goto enter_predicate;
case 69:
w_op69:
LoadHVA(Xb(BcP(f_x,0)),H);
P+=Fs(f_x);
goto w_dispatch;
case 70:
{
w_op70:
{
{
tagged_t vr210;
vr210 = Tagp(HVA,H);
Xb(BcP(f_x,0+Fs(f_x))) = vr210;
Xb(BcP(f_x,0)) = vr210;
HeapPush(H,vr210);
    }
P+=Fs(f_x)+Fs(f_x);
goto w_dispatch;
    }
    }
case 85:
Xb(BcP(f_x,0)) = Xb(BcP(f_x,0+Fs(f_x)));
Xb(BcP(f_x,0+Fs(f_x)+Fs(f_x))) = Xb(BcP(f_x,0+Fs(f_x)+Fs(f_x)+Fs(f_x)));
P+=Fs(f_x)+Fs(f_x)+Fs(f_x)+Fs(f_x);
goto w_dispatch;
case 71:
Xb(BcP(f_x,0)) = Xb(BcP(f_x,0+Fs(f_x)));
P+=Fs(f_x)+Fs(f_x);
goto w_dispatch;
case 72:
{
w_op72:
{
tagged_t vr211;
tagged_t vr212;
tagged_t vr213;
vr212 = Xb(BcP(f_x,0+Fs(f_x)));
if (TaggedIsSVA(vr212)) {
do {
RefSVA(vr213,vr212);
if (vr213==vr212) {
if (!YoungerStackVar(Tagp(SVA,Offset(E,EToY0)),vr212)) {
LoadHVA(vr212,H);
BindSVA(vr213,vr212);
          }

break;
        }

vr212 = vr213;
      }
 while (TaggedIsSVA(vr212));
    }

vr211 = vr212;
Xb(BcP(f_x,0)) = vr211;
Xb(BcP(f_x,0+Fs(f_x))) = vr211;
P+=Fs(f_x)+Fs(f_x);
goto w_dispatch;
    }
    }
case 73:
w_op73:
CODE_ALLOC(E);
goto w_op74;
case 74:
{
w_op74:
{
{
tagged_t vr214;
vr214 = Tagp(SVA,&Yb(BcP(f_y,0+Fs(f_x))));
Yb(BcP(f_y,0+Fs(f_x))) = vr214;
Xb(BcP(f_x,0)) = vr214;
    }
P+=Fs(f_x)+Fs(f_y);
goto w_dispatch;
    }
    }
case 83:
w_op83:
CODE_ALLOC(E);
goto w_op84;
case 84:
{
w_op84:
{
{
tagged_t vr215;
vr215 = Tagp(SVA,&Yb(BcP(f_y,0+Fs(f_x))));
Yb(BcP(f_y,0+Fs(f_x))) = vr215;
Xb(BcP(f_x,0)) = vr215;
    }
{
tagged_t vr216;
vr216 = Tagp(SVA,&Yb(BcP(f_y,0+Fs(f_x)+Fs(f_y)+Fs(f_x))));
Yb(BcP(f_y,0+Fs(f_x)+Fs(f_y)+Fs(f_x))) = vr216;
Xb(BcP(f_x,0+Fs(f_x)+Fs(f_y))) = vr216;
    }
P+=Fs(f_x)+Fs(f_y)+Fs(f_x)+Fs(f_y);
goto w_dispatch;
    }
    }
case 75:
Xb(BcP(f_x,0)) = Yb(BcP(f_y,0+Fs(f_x)));
P+=Fs(f_x)+Fs(f_y);
goto w_dispatch;
case 76:
{
w_op76:
{
tagged_t vr217;
tagged_t vr218;
vr217 = Yb(BcP(f_y,0+Fs(f_x)));
if (TaggedIsSVA(vr217)) {
do {
RefSVA(vr218,vr217);
if (vr218==vr217) {
if (!YoungerStackVar(Tagp(SVA,Offset(E,EToY0)),vr217)) {
LoadHVA(vr217,H);
BindSVA(vr218,vr217);
          }

break;
        }

vr217 = vr218;
      }
 while (TaggedIsSVA(vr217));
    }

Xb(BcP(f_x,0)) = vr217;
P+=Fs(f_x)+Fs(f_y);
goto w_dispatch;
    }
    }
case 77:
Xb(BcP(f_x,0+Fs(f_Q))) = BcP(f_t,0+Fs(f_Q)+Fs(f_x));
P+=Fs(f_Q)+Fs(f_x)+Fs(f_t);
goto w_dispatch;
case 78:
Xb(BcP(f_x,0)) = BcP(f_t,0+Fs(f_x));
P+=Fs(f_x)+Fs(f_t);
goto w_dispatch;
case 81:
Xb(BcP(f_x,0)) = atom_nil;
P+=Fs(f_x);
goto w_dispatch;
case 252:
w_op252:
w->heap_top = H;
Xb(BcP(f_x,0+Fs(f_Q))) = BC_MakeBlob(w,&BcP(f_t,0+Fs(f_Q)+Fs(f_x)));
H = w->heap_top;
P+=Fs(f_Q)+Fs(f_x)+LargeSize(*&BcP(f_t,0+Fs(f_Q)+Fs(f_x)));
goto w_dispatch;
case 253:
w_op253:
w->heap_top = H;
Xb(BcP(f_x,0)) = BC_MakeBlob(w,&BcP(f_t,0+Fs(f_x)));
H = w->heap_top;
P+=Fs(f_x)+LargeSize(*&BcP(f_t,0+Fs(f_x)));
goto w_dispatch;
case 79:
w_op79:
Xb(BcP(f_x,0+Fs(f_Q))) = Tagp(STR,H);
HeapPush(H,BcP(f_f,0+Fs(f_Q)+Fs(f_x)));
P+=Fs(f_Q)+Fs(f_x)+Fs(f_f);
goto w_dispatch;
case 80:
w_op80:
Xb(BcP(f_x,0)) = Tagp(STR,H);
HeapPush(H,BcP(f_f,0+Fs(f_x)));
P+=Fs(f_x)+Fs(f_f);
goto w_dispatch;
case 82:
w_op82:
Xb(BcP(f_x,0)) = Tagp(LST,H);
P+=Fs(f_x);
goto w_dispatch;
case 86:
Xb(BcP(f_x,0)) = Yb(BcP(f_y,0+Fs(f_x)));
Xb(BcP(f_x,0+Fs(f_x)+Fs(f_y))) = Yb(BcP(f_y,0+Fs(f_x)+Fs(f_y)+Fs(f_x)));
P+=Fs(f_x)+Fs(f_y)+Fs(f_x)+Fs(f_y);
goto w_dispatch;
case 87:
{
w_op87:
{
Xb(BcP(f_x,0)) = Yb(BcP(f_y,0+Fs(f_x)));
tagged_t vr219;
tagged_t vr220;
vr219 = Yb(BcP(f_y,0+Fs(f_x)+Fs(f_y)+Fs(f_x)));
if (TaggedIsSVA(vr219)) {
do {
RefSVA(vr220,vr219);
if (vr220==vr219) {
if (!YoungerStackVar(Tagp(SVA,Offset(E,EToY0)),vr219)) {
LoadHVA(vr219,H);
BindSVA(vr220,vr219);
          }

break;
        }

vr219 = vr220;
      }
 while (TaggedIsSVA(vr219));
    }

Xb(BcP(f_x,0+Fs(f_x)+Fs(f_y))) = vr219;
P+=Fs(f_x)+Fs(f_y)+Fs(f_x)+Fs(f_y);
goto w_dispatch;
    }
    }
case 88:
{
w_op88:
{
tagged_t vr221;
tagged_t vr222;
vr221 = Yb(BcP(f_y,0+Fs(f_x)));
if (TaggedIsSVA(vr221)) {
do {
RefSVA(vr222,vr221);
if (vr222==vr221) {
if (!YoungerStackVar(Tagp(SVA,Offset(E,EToY0)),vr221)) {
LoadHVA(vr221,H);
BindSVA(vr222,vr221);
          }

break;
        }

vr221 = vr222;
      }
 while (TaggedIsSVA(vr221));
    }

Xb(BcP(f_x,0)) = vr221;
Xb(BcP(f_x,0+Fs(f_x)+Fs(f_y))) = Yb(BcP(f_y,0+Fs(f_x)+Fs(f_y)+Fs(f_x)));
P+=Fs(f_x)+Fs(f_y)+Fs(f_x)+Fs(f_y);
goto w_dispatch;
    }
    }
case 89:
{
w_op89:
{
tagged_t vr223;
tagged_t vr224;
vr223 = Yb(BcP(f_y,0+Fs(f_x)));
if (TaggedIsSVA(vr223)) {
do {
RefSVA(vr224,vr223);
if (vr224==vr223) {
if (!YoungerStackVar(Tagp(SVA,Offset(E,EToY0)),vr223)) {
LoadHVA(vr223,H);
BindSVA(vr224,vr223);
          }

break;
        }

vr223 = vr224;
      }
 while (TaggedIsSVA(vr223));
    }

Xb(BcP(f_x,0)) = vr223;
tagged_t vr225;
tagged_t vr226;
vr225 = Yb(BcP(f_y,0+Fs(f_x)+Fs(f_y)+Fs(f_x)));
if (TaggedIsSVA(vr225)) {
do {
RefSVA(vr226,vr225);
if (vr226==vr225) {
if (!YoungerStackVar(Tagp(SVA,Offset(E,EToY0)),vr225)) {
LoadHVA(vr225,H);
BindSVA(vr226,vr225);
          }

break;
        }

vr225 = vr226;
      }
 while (TaggedIsSVA(vr225));
    }

Xb(BcP(f_x,0+Fs(f_x)+Fs(f_y))) = vr225;
P+=Fs(f_x)+Fs(f_y)+Fs(f_x)+Fs(f_y);
goto w_dispatch;
    }
    }
case 91:
w->heap_top = H;
goto r_op91;
case 94:
w->heap_top = H;
goto r_op94;
case 95:
w->heap_top = H;
goto r_op95;
case 96:
P+=Fs(f_Q);
goto w_op97;
case 97:
w_op97:
w->heap_top = H;
goto r_op97;
case 254:
P+=Fs(f_Q);
goto w_op255;
case 255:
w_op255:
w->heap_top = H;
goto r_op255;
case 98:
P+=Fs(f_Q);
goto w_op99;
case 99:
w_op99:
w->heap_top = H;
goto r_op99;
case 100:
w->heap_top = H;
goto r_op100;
case 101:
w->heap_top = H;
goto r_op101;
case 111:
P+=Fs(f_Q);
goto w_op112;
case 112:
w_op112:
w->heap_top = H;
goto r_op112;
case 113:
w->heap_top = H;
goto r_op113;
case 208:
w->heap_top = H;
goto r_op208;
case 210:
w->heap_top = H;
goto r_op210;
case 211:
w->heap_top = H;
goto r_op211;
case 212:
w->heap_top = H;
goto r_op212;
case 213:
w->heap_top = H;
goto r_op213;
case 214:
w->heap_top = H;
goto r_op214;
case 216:
w->heap_top = H;
goto r_op216;
case 217:
w->heap_top = H;
goto r_op217;
case 215:
w->heap_top = H;
goto r_op215;
case 209:
w->heap_top = H;
goto r_op209;
case 218:
w->heap_top = H;
goto r_op218;
case 219:
Xb(BcP(f_x,0)) = ChoiceToTagged(w->previous_choice);
P+=Fs(f_x);
goto w_dispatch;
case 220:
CODE_ALLOC(E);
goto w_op221;
case 221:
w_op221:
Yb(BcP(f_y,0)) = ChoiceToTagged(w->previous_choice);
P+=Fs(f_y);
goto w_dispatch;
case 233:
{
w_op233:
{
Setfunc(TaggedToFunctor(Y(0)));
for (intmach_t vr227 = 0;
vr227<Func->arity;vr227++) {
X(vr227) = Y(vr227+1);
    }

w->next_insn = E->next_insn;
w->frame = E->frame;
goto enter_predicate;
    }
    }
case 234:
w->heap_top = H;
goto r_op234;
case 235:
w->heap_top = H;
goto r_op235;
case 237:
w->heap_top = H;
goto r_op237;
case 238:
w->heap_top = H;
goto r_op238;
case 104:
P+=Fs(f_Q);
goto w_op105;
case 105:
{
w_op105:
{
tagged_t vr228 = Tagp(STR,H);
tagged_t vr229 = X(0);
if (TaggedIsHVA(vr229)) {
BindHVA(vr229,vr228);
    }
 else if (vr229&TagBitSVA) {
BindSVA(vr229,vr228);
    }
 else {
BindCVA(vr229,vr228);
    }

HeapPush(H,BcP(f_f,0));
P+=Fs(f_f);
goto w_dispatch;
    }
    }
case 256:
P+=Fs(f_Q);
goto w_op257;
case 257:
{
w_op257:
{
w->heap_top = H;
tagged_t vr230 = BC_MakeBlob(w,&BcP(f_t,0));
H = w->heap_top;
tagged_t vr231 = X(0);
if (TaggedIsHVA(vr231)) {
BindHVA(vr231,vr230);
    }
 else if (vr231&TagBitSVA) {
BindSVA(vr231,vr230);
    }
 else {
BindCVA(vr231,vr230);
    }

P+=LargeSize(*&BcP(f_t,0));
goto w_dispatch;
    }
    }
case 102:
P+=Fs(f_Q);
goto w_op103;
case 103:
{
w_op103:
{
tagged_t vr232 = X(0);
if (TaggedIsHVA(vr232)) {
BindHVA(vr232,BcP(f_t,0));
    }
 else if (vr232&TagBitSVA) {
BindSVA(vr232,BcP(f_t,0));
    }
 else {
BindCVA(vr232,BcP(f_t,0));
    }

P+=Fs(f_t);
goto w_dispatch;
    }
    }
case 106:
{
{
tagged_t vr233 = X(0);
if (TaggedIsHVA(vr233)) {
BindHVA(vr233,atom_nil);
    }
 else if (vr233&TagBitSVA) {
BindSVA(vr233,atom_nil);
    }
 else {
BindCVA(vr233,atom_nil);
    }

P+=0;
goto w_dispatch;
    }
    }
case 107:
{
{
tagged_t vr234 = Tagp(LST,H);
tagged_t vr235 = X(0);
if (TaggedIsHVA(vr235)) {
BindHVA(vr235,vr234);
    }
 else if (vr235&TagBitSVA) {
BindSVA(vr235,vr234);
    }
 else {
BindCVA(vr235,vr234);
    }

P+=0;
goto w_dispatch;
    }
    }
case 108:
Xb(BcP(f_x,0+Fs(f_x))) = Xb(BcP(f_x,0));
Xb(BcP(f_x,0+Fs(f_x)+Fs(f_x)+Fs(f_x))) = Xb(BcP(f_x,0+Fs(f_x)+Fs(f_x)));
P+=Fs(f_x)+Fs(f_x)+Fs(f_x)+Fs(f_x);
goto w_dispatch;
case 90:
Xb(BcP(f_x,0+Fs(f_x))) = Xb(BcP(f_x,0));
P+=Fs(f_x)+Fs(f_x);
goto w_dispatch;
case 92:
CODE_ALLOC(E);
goto w_op93;
case 93:
w_op93:
Yb(BcP(f_y,0+Fs(f_x))) = Xb(BcP(f_x,0));
P+=Fs(f_x)+Fs(f_y);
goto w_dispatch;
case 109:
CODE_ALLOC(E);
goto w_op110;
case 110:
w_op110:
Yb(BcP(f_y,0+Fs(f_x))) = Xb(BcP(f_x,0));
Yb(BcP(f_y,0+Fs(f_x)+Fs(f_y)+Fs(f_x))) = Xb(BcP(f_x,0+Fs(f_x)+Fs(f_y)));
P+=Fs(f_x)+Fs(f_y)+Fs(f_x)+Fs(f_y);
goto w_dispatch;
case 68:
P = BCoff(P,BcP(f_i,0));
goto w_dispatch;
case 222:
w->heap_top = H;
goto r_op222;
case 223:
w->heap_top = H;
goto r_op223;
case 224:
w->heap_top = H;
goto r_op224;
case 225:
w->heap_top = H;
goto r_op225;
case 226:
w->heap_top = H;
goto r_op226;
case 227:
w->heap_top = H;
goto r_op227;
case 228:
w->heap_top = H;
goto r_op228;
case 229:
w->heap_top = H;
goto r_op229;
case 230:
w->heap_top = H;
goto r_op230;
case 231:
w->heap_top = H;
goto r_op231;
case 232:
w->heap_top = H;
goto r_op232;
case 247:
{
w_op247:
{
tagged_t vr236 = Xb(BcP(f_x,0));
tagged_t vr237;
LoadCVA(vr237,H);
tagged_t vr238;
SwitchOnVar(vr236,vr238,{
BindHVA(vr236,vr237);
Xb(BcP(f_x,0)) = vr237;
    }
,{
BindCVA(vr237,vr236);
    }
,{
BindSVA(vr236,vr237);
Xb(BcP(f_x,0)) = vr237;
    }
,{
BindCVA(vr237,vr236);
    }
);
P+=Fs(f_x);
goto w_dispatch;
    }
    }
case 114:
{
{
intmach_t vr239 = (FTYPE_ctype(f_i_signed))BcP(f_i,0);
P+=Fs(f_i);
for (intmach_t vr240 = vr239;
vr240>4;vr240--) {
ConstrHVA(H);
    }

goto w_op118;
    }
    }
case 115:
w_op115:
ConstrHVA(H);
P+=0;
goto w_dispatch;
case 116:
w_op116:
ConstrHVA(H);
goto w_op115;
case 117:
w_op117:
ConstrHVA(H);
goto w_op116;
case 118:
w_op118:
ConstrHVA(H);
goto w_op117;
case 119:
LoadHVA(Xb(BcP(f_x,0)),H);
P+=Fs(f_x);
goto w_dispatch;
case 120:
HeapPush(H,Xb(BcP(f_x,0)));
P+=Fs(f_x);
goto w_dispatch;
case 121:
{
{
{tagged_t vr241 = Xb(BcP(f_x,0));
if (TaggedIsSVA(vr241)) {
tagged_t vr242;
do {
RefSVA(vr242,vr241);
if (vr242==vr241) {
BindSVA(vr241,Tagp(HVA,H));
PreLoadHVA(vr241,H);
break;
        }

vr241 = vr242;
      }
 while (TaggedIsSVA(vr241));
    }

HeapPush(H,vr241);
}P+=Fs(f_x);
goto w_dispatch;
    }
    }
case 122:
CODE_ALLOC(E);
goto w_op123;
case 123:
w_op123:
LoadHVA(Yb(BcP(f_y,0)),H);
P+=Fs(f_y);
goto w_dispatch;
case 124:
{
{
{tagged_t vr243;
LoadHVA(vr243,H);
if (CondStackvar(Yb(BcP(f_y,0)))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0))));
    }

Yb(BcP(f_y,0)) = vr243;
}P+=Fs(f_y);
goto w_dispatch;
    }
    }
case 125:
HeapPush(H,Yb(BcP(f_y,0)));
P+=Fs(f_y);
goto w_dispatch;
case 126:
{
{
{tagged_t vr244 = Yb(BcP(f_y,0));
if (TaggedIsSVA(vr244)) {
tagged_t vr245;
do {
RefSVA(vr245,vr244);
if (vr245==vr244) {
BindSVA(vr244,Tagp(HVA,H));
PreLoadHVA(vr244,H);
break;
        }

vr244 = vr245;
      }
 while (TaggedIsSVA(vr244));
    }

HeapPush(H,vr244);
}P+=Fs(f_y);
goto w_dispatch;
    }
    }
case 127:
HeapPush(H,BcP(f_t,0+Fs(f_Q)));
P+=Fs(f_Q)+Fs(f_t);
goto w_dispatch;
case 128:
HeapPush(H,BcP(f_t,0));
P+=Fs(f_t);
goto w_dispatch;
case 258:
P+=Fs(f_Q);
goto w_op259;
case 259:
w_op259:
w->heap_top = HeapOffset(H,1);
*H = BC_MakeBlob(w,&BcP(f_t,0));
P+=LargeSize(*&BcP(f_t,0));
goto r_dispatch;
case 129:
HeapPush(H,Tagp(STR,HeapOffset(H,1)));
HeapPush(H,BcP(f_f,0+Fs(f_Q)));
P+=Fs(f_Q)+Fs(f_f);
goto w_dispatch;
case 130:
HeapPush(H,Tagp(STR,HeapOffset(H,1)));
HeapPush(H,BcP(f_f,0));
P+=Fs(f_f);
goto w_dispatch;
case 131:
HeapPush(H,atom_nil);
P+=0;
goto w_dispatch;
case 132:
HeapPush(H,Tagp(LST,HeapOffset(H,1)));
P+=0;
goto w_dispatch;
case 133:
HeapPush(H,BcP(f_t,0+Fs(f_Q)));
goto w_op66;
case 134:
HeapPush(H,BcP(f_t,0));
goto w_op66;
case 135:
HeapPush(H,atom_nil);
goto w_op66;
case 136:
{
{
intmach_t vr246 = (FTYPE_ctype(f_i_signed))BcP(f_i,0);
do {
ConstrHVA(H);
    }
 while (--vr246);
LoadHVA(Xb(BcP(f_x,0+Fs(f_i))),H);
P+=Fs(f_i)+Fs(f_x);
goto w_dispatch;
    }
    }
case 139:
CODE_ALLOC(E);
goto w_op140;
case 140:
{
w_op140:
{
intmach_t vr247 = (FTYPE_ctype(f_i_signed))BcP(f_i,0);
do {
ConstrHVA(H);
    }
 while (--vr247);
LoadHVA(Yb(BcP(f_y,0+Fs(f_i))),H);
P+=Fs(f_i)+Fs(f_y);
goto w_dispatch;
    }
    }
case 137:
{
{
intmach_t vr248 = (FTYPE_ctype(f_i_signed))BcP(f_i,0);
do {
ConstrHVA(H);
    }
 while (--vr248);
HeapPush(H,Xb(BcP(f_x,0+Fs(f_i))));
P+=Fs(f_i)+Fs(f_x);
goto w_dispatch;
    }
    }
case 138:
{
{
intmach_t vr249 = (FTYPE_ctype(f_i_signed))BcP(f_i,0);
do {
ConstrHVA(H);
    }
 while (--vr249);
{tagged_t vr250 = Xb(BcP(f_x,0+Fs(f_i)));
if (TaggedIsSVA(vr250)) {
tagged_t vr251;
do {
RefSVA(vr251,vr250);
if (vr251==vr250) {
BindSVA(vr250,Tagp(HVA,H));
PreLoadHVA(vr250,H);
break;
        }

vr250 = vr251;
      }
 while (TaggedIsSVA(vr250));
    }

HeapPush(H,vr250);
}P+=Fs(f_i)+Fs(f_x);
goto w_dispatch;
    }
    }
case 141:
{
{
intmach_t vr252 = (FTYPE_ctype(f_i_signed))BcP(f_i,0);
do {
ConstrHVA(H);
    }
 while (--vr252);
{tagged_t vr253;
LoadHVA(vr253,H);
if (CondStackvar(Yb(BcP(f_y,0+Fs(f_i))))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0+Fs(f_i)))));
    }

Yb(BcP(f_y,0+Fs(f_i))) = vr253;
}P+=Fs(f_i)+Fs(f_y);
goto w_dispatch;
    }
    }
case 142:
{
{
intmach_t vr254 = (FTYPE_ctype(f_i_signed))BcP(f_i,0);
do {
ConstrHVA(H);
    }
 while (--vr254);
HeapPush(H,Yb(BcP(f_y,0+Fs(f_i))));
P+=Fs(f_i)+Fs(f_y);
goto w_dispatch;
    }
    }
case 143:
{
{
intmach_t vr255 = (FTYPE_ctype(f_i_signed))BcP(f_i,0);
do {
ConstrHVA(H);
    }
 while (--vr255);
{tagged_t vr256 = Yb(BcP(f_y,0+Fs(f_i)));
if (TaggedIsSVA(vr256)) {
tagged_t vr257;
do {
RefSVA(vr257,vr256);
if (vr257==vr256) {
BindSVA(vr256,Tagp(HVA,H));
PreLoadHVA(vr256,H);
break;
        }

vr256 = vr257;
      }
 while (TaggedIsSVA(vr256));
    }

HeapPush(H,vr256);
}P+=Fs(f_i)+Fs(f_y);
goto w_dispatch;
    }
    }
case 144:
{
{
LoadHVA(Xb(BcP(f_x,0)),H);
intmach_t vr258 = (FTYPE_ctype(f_i_signed))BcP(f_i,0+Fs(f_x));
do {
ConstrHVA(H);
    }
 while (--vr258);
P+=Fs(f_x)+Fs(f_i);
goto w_dispatch;
    }
    }
case 145:
LoadHVA(Xb(BcP(f_x,0)),H);
LoadHVA(Xb(BcP(f_x,0+Fs(f_x))),H);
P+=Fs(f_x)+Fs(f_x);
goto w_dispatch;
case 148:
CODE_ALLOC(E);
goto w_op149;
case 149:
w_op149:
LoadHVA(Xb(BcP(f_x,0)),H);
LoadHVA(Yb(BcP(f_y,0+Fs(f_x))),H);
P+=Fs(f_x)+Fs(f_y);
goto w_dispatch;
case 146:
LoadHVA(Xb(BcP(f_x,0)),H);
HeapPush(H,Xb(BcP(f_x,0+Fs(f_x))));
P+=Fs(f_x)+Fs(f_x);
goto w_dispatch;
case 147:
{
{
LoadHVA(Xb(BcP(f_x,0)),H);
{tagged_t vr259 = Xb(BcP(f_x,0+Fs(f_x)));
if (TaggedIsSVA(vr259)) {
tagged_t vr260;
do {
RefSVA(vr260,vr259);
if (vr260==vr259) {
BindSVA(vr259,Tagp(HVA,H));
PreLoadHVA(vr259,H);
break;
        }

vr259 = vr260;
      }
 while (TaggedIsSVA(vr259));
    }

HeapPush(H,vr259);
}P+=Fs(f_x)+Fs(f_x);
goto w_dispatch;
    }
    }
case 150:
{
{
LoadHVA(Xb(BcP(f_x,0)),H);
{tagged_t vr261;
LoadHVA(vr261,H);
if (CondStackvar(Yb(BcP(f_y,0+Fs(f_x))))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0+Fs(f_x)))));
    }

Yb(BcP(f_y,0+Fs(f_x))) = vr261;
}P+=Fs(f_x)+Fs(f_y);
goto w_dispatch;
    }
    }
case 151:
LoadHVA(Xb(BcP(f_x,0)),H);
HeapPush(H,Yb(BcP(f_y,0+Fs(f_x))));
P+=Fs(f_x)+Fs(f_y);
goto w_dispatch;
case 152:
{
{
LoadHVA(Xb(BcP(f_x,0)),H);
{tagged_t vr262 = Yb(BcP(f_y,0+Fs(f_x)));
if (TaggedIsSVA(vr262)) {
tagged_t vr263;
do {
RefSVA(vr263,vr262);
if (vr263==vr262) {
BindSVA(vr262,Tagp(HVA,H));
PreLoadHVA(vr262,H);
break;
        }

vr262 = vr263;
      }
 while (TaggedIsSVA(vr262));
    }

HeapPush(H,vr262);
}P+=Fs(f_x)+Fs(f_y);
goto w_dispatch;
    }
    }
case 153:
CODE_ALLOC(E);
goto w_op154;
case 154:
{
w_op154:
{
LoadHVA(Yb(BcP(f_y,0)),H);
intmach_t vr264 = (FTYPE_ctype(f_i_signed))BcP(f_i,0+Fs(f_y));
do {
ConstrHVA(H);
    }
 while (--vr264);
P+=Fs(f_y)+Fs(f_i);
goto w_dispatch;
    }
    }
case 155:
CODE_ALLOC(E);
goto w_op156;
case 156:
w_op156:
LoadHVA(Yb(BcP(f_y,0)),H);
LoadHVA(Xb(BcP(f_x,0+Fs(f_y))),H);
P+=Fs(f_y)+Fs(f_x);
goto w_dispatch;
case 157:
CODE_ALLOC(E);
goto w_op158;
case 158:
w_op158:
LoadHVA(Yb(BcP(f_y,0)),H);
LoadHVA(Yb(BcP(f_y,0+Fs(f_y))),H);
P+=Fs(f_y)+Fs(f_y);
goto w_dispatch;
case 159:
CODE_ALLOC(E);
goto w_op160;
case 161:
CODE_ALLOC(E);
goto w_op162;
case 160:
w_op160:
LoadHVA(Yb(BcP(f_y,0)),H);
HeapPush(H,Xb(BcP(f_x,0+Fs(f_y))));
P+=Fs(f_y)+Fs(f_x);
goto w_dispatch;
case 162:
{
w_op162:
{
LoadHVA(Yb(BcP(f_y,0)),H);
{tagged_t vr265 = Xb(BcP(f_x,0+Fs(f_y)));
if (TaggedIsSVA(vr265)) {
tagged_t vr266;
do {
RefSVA(vr266,vr265);
if (vr266==vr265) {
BindSVA(vr265,Tagp(HVA,H));
PreLoadHVA(vr265,H);
break;
        }

vr265 = vr266;
      }
 while (TaggedIsSVA(vr265));
    }

HeapPush(H,vr265);
}P+=Fs(f_y)+Fs(f_x);
goto w_dispatch;
    }
    }
case 163:
CODE_ALLOC(E);
goto w_op164;
case 165:
CODE_ALLOC(E);
goto w_op166;
case 164:
w_op164:
LoadHVA(Yb(BcP(f_y,0)),H);
HeapPush(H,Yb(BcP(f_y,0+Fs(f_y))));
P+=Fs(f_y)+Fs(f_y);
goto w_dispatch;
case 166:
{
w_op166:
{
LoadHVA(Yb(BcP(f_y,0)),H);
{tagged_t vr267 = Yb(BcP(f_y,0+Fs(f_y)));
if (TaggedIsSVA(vr267)) {
tagged_t vr268;
do {
RefSVA(vr268,vr267);
if (vr268==vr267) {
BindSVA(vr267,Tagp(HVA,H));
PreLoadHVA(vr267,H);
break;
        }

vr267 = vr268;
      }
 while (TaggedIsSVA(vr267));
    }

HeapPush(H,vr267);
}P+=Fs(f_y)+Fs(f_y);
goto w_dispatch;
    }
    }
case 185:
{
{
{tagged_t vr269;
LoadHVA(vr269,H);
if (CondStackvar(Yb(BcP(f_y,0)))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0))));
    }

Yb(BcP(f_y,0)) = vr269;
}intmach_t vr270 = (FTYPE_ctype(f_i_signed))BcP(f_i,0+Fs(f_y));
do {
ConstrHVA(H);
    }
 while (--vr270);
P+=Fs(f_y)+Fs(f_i);
goto w_dispatch;
    }
    }
case 188:
{
{
{tagged_t vr271;
LoadHVA(vr271,H);
if (CondStackvar(Yb(BcP(f_y,0)))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0))));
    }

Yb(BcP(f_y,0)) = vr271;
}LoadHVA(Xb(BcP(f_x,0+Fs(f_y))),H);
P+=Fs(f_y)+Fs(f_x);
goto w_dispatch;
    }
    }
case 199:
{
{
{tagged_t vr272;
LoadHVA(vr272,H);
if (CondStackvar(Yb(BcP(f_y,0)))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0))));
    }

Yb(BcP(f_y,0)) = vr272;
}{tagged_t vr273;
LoadHVA(vr273,H);
if (CondStackvar(Yb(BcP(f_y,0+Fs(f_y))))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0+Fs(f_y)))));
    }

Yb(BcP(f_y,0+Fs(f_y))) = vr273;
}P+=Fs(f_y)+Fs(f_y);
goto w_dispatch;
    }
    }
case 193:
{
{
{tagged_t vr274;
LoadHVA(vr274,H);
if (CondStackvar(Yb(BcP(f_y,0)))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0))));
    }

Yb(BcP(f_y,0)) = vr274;
}HeapPush(H,Xb(BcP(f_x,0+Fs(f_y))));
P+=Fs(f_y)+Fs(f_x);
goto w_dispatch;
    }
    }
case 196:
{
{
{tagged_t vr275;
LoadHVA(vr275,H);
if (CondStackvar(Yb(BcP(f_y,0)))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0))));
    }

Yb(BcP(f_y,0)) = vr275;
}{tagged_t vr276 = Xb(BcP(f_x,0+Fs(f_y)));
if (TaggedIsSVA(vr276)) {
tagged_t vr277;
do {
RefSVA(vr277,vr276);
if (vr277==vr276) {
BindSVA(vr276,Tagp(HVA,H));
PreLoadHVA(vr276,H);
break;
        }

vr276 = vr277;
      }
 while (TaggedIsSVA(vr276));
    }

HeapPush(H,vr276);
}P+=Fs(f_y)+Fs(f_x);
goto w_dispatch;
    }
    }
case 202:
{
{
{tagged_t vr278;
LoadHVA(vr278,H);
if (CondStackvar(Yb(BcP(f_y,0)))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0))));
    }

Yb(BcP(f_y,0)) = vr278;
}HeapPush(H,Yb(BcP(f_y,0+Fs(f_y))));
P+=Fs(f_y)+Fs(f_y);
goto w_dispatch;
    }
    }
case 205:
{
{
{tagged_t vr279;
LoadHVA(vr279,H);
if (CondStackvar(Yb(BcP(f_y,0)))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0))));
    }

Yb(BcP(f_y,0)) = vr279;
}{tagged_t vr280 = Yb(BcP(f_y,0+Fs(f_y)));
if (TaggedIsSVA(vr280)) {
tagged_t vr281;
do {
RefSVA(vr281,vr280);
if (vr281==vr280) {
BindSVA(vr280,Tagp(HVA,H));
PreLoadHVA(vr280,H);
break;
        }

vr280 = vr281;
      }
 while (TaggedIsSVA(vr280));
    }

HeapPush(H,vr280);
}P+=Fs(f_y)+Fs(f_y);
goto w_dispatch;
    }
    }
case 167:
{
{
HeapPush(H,Xb(BcP(f_x,0)));
intmach_t vr282 = (FTYPE_ctype(f_i_signed))BcP(f_i,0+Fs(f_x));
do {
ConstrHVA(H);
    }
 while (--vr282);
P+=Fs(f_x)+Fs(f_i);
goto w_dispatch;
    }
    }
case 168:
{
{
{tagged_t vr283 = Xb(BcP(f_x,0));
if (TaggedIsSVA(vr283)) {
tagged_t vr284;
do {
RefSVA(vr284,vr283);
if (vr284==vr283) {
BindSVA(vr283,Tagp(HVA,H));
PreLoadHVA(vr283,H);
break;
        }

vr283 = vr284;
      }
 while (TaggedIsSVA(vr283));
    }

HeapPush(H,vr283);
}intmach_t vr285 = (FTYPE_ctype(f_i_signed))BcP(f_i,0+Fs(f_x));
do {
ConstrHVA(H);
    }
 while (--vr285);
P+=Fs(f_x)+Fs(f_i);
goto w_dispatch;
    }
    }
case 169:
HeapPush(H,Xb(BcP(f_x,0)));
LoadHVA(Xb(BcP(f_x,0+Fs(f_x))),H);
P+=Fs(f_x)+Fs(f_x);
goto w_dispatch;
case 170:
{
{
{tagged_t vr286 = Xb(BcP(f_x,0));
if (TaggedIsSVA(vr286)) {
tagged_t vr287;
do {
RefSVA(vr287,vr286);
if (vr287==vr286) {
BindSVA(vr286,Tagp(HVA,H));
PreLoadHVA(vr286,H);
break;
        }

vr286 = vr287;
      }
 while (TaggedIsSVA(vr286));
    }

HeapPush(H,vr286);
}LoadHVA(Xb(BcP(f_x,0+Fs(f_x))),H);
P+=Fs(f_x)+Fs(f_x);
goto w_dispatch;
    }
    }
case 171:
CODE_ALLOC(E);
goto w_op173;
case 172:
CODE_ALLOC(E);
goto w_op174;
case 173:
w_op173:
HeapPush(H,Xb(BcP(f_x,0)));
LoadHVA(Yb(BcP(f_y,0+Fs(f_x))),H);
P+=Fs(f_x)+Fs(f_y);
goto w_dispatch;
case 174:
{
w_op174:
{
{tagged_t vr288 = Xb(BcP(f_x,0));
if (TaggedIsSVA(vr288)) {
tagged_t vr289;
do {
RefSVA(vr289,vr288);
if (vr289==vr288) {
BindSVA(vr288,Tagp(HVA,H));
PreLoadHVA(vr288,H);
break;
        }

vr288 = vr289;
      }
 while (TaggedIsSVA(vr288));
    }

HeapPush(H,vr288);
}LoadHVA(Yb(BcP(f_y,0+Fs(f_x))),H);
P+=Fs(f_x)+Fs(f_y);
goto w_dispatch;
    }
    }
case 175:
HeapPush(H,Xb(BcP(f_x,0)));
HeapPush(H,Xb(BcP(f_x,0+Fs(f_x))));
P+=Fs(f_x)+Fs(f_x);
goto w_dispatch;
case 177:
{
{
HeapPush(H,Xb(BcP(f_x,0)));
{tagged_t vr290 = Xb(BcP(f_x,0+Fs(f_x)));
if (TaggedIsSVA(vr290)) {
tagged_t vr291;
do {
RefSVA(vr291,vr290);
if (vr291==vr290) {
BindSVA(vr290,Tagp(HVA,H));
PreLoadHVA(vr290,H);
break;
        }

vr290 = vr291;
      }
 while (TaggedIsSVA(vr290));
    }

HeapPush(H,vr290);
}P+=Fs(f_x)+Fs(f_x);
goto w_dispatch;
    }
    }
case 176:
{
{
{tagged_t vr292 = Xb(BcP(f_x,0));
if (TaggedIsSVA(vr292)) {
tagged_t vr293;
do {
RefSVA(vr293,vr292);
if (vr293==vr292) {
BindSVA(vr292,Tagp(HVA,H));
PreLoadHVA(vr292,H);
break;
        }

vr292 = vr293;
      }
 while (TaggedIsSVA(vr292));
    }

HeapPush(H,vr292);
}HeapPush(H,Xb(BcP(f_x,0+Fs(f_x))));
P+=Fs(f_x)+Fs(f_x);
goto w_dispatch;
    }
    }
case 178:
{
{
{tagged_t vr294 = Xb(BcP(f_x,0));
if (TaggedIsSVA(vr294)) {
tagged_t vr295;
do {
RefSVA(vr295,vr294);
if (vr295==vr294) {
BindSVA(vr294,Tagp(HVA,H));
PreLoadHVA(vr294,H);
break;
        }

vr294 = vr295;
      }
 while (TaggedIsSVA(vr294));
    }

HeapPush(H,vr294);
}{tagged_t vr296 = Xb(BcP(f_x,0+Fs(f_x)));
if (TaggedIsSVA(vr296)) {
tagged_t vr297;
do {
RefSVA(vr297,vr296);
if (vr297==vr296) {
BindSVA(vr296,Tagp(HVA,H));
PreLoadHVA(vr296,H);
break;
        }

vr296 = vr297;
      }
 while (TaggedIsSVA(vr296));
    }

HeapPush(H,vr296);
}P+=Fs(f_x)+Fs(f_x);
goto w_dispatch;
    }
    }
case 179:
{
{
HeapPush(H,Xb(BcP(f_x,0)));
{tagged_t vr298;
LoadHVA(vr298,H);
if (CondStackvar(Yb(BcP(f_y,0+Fs(f_x))))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0+Fs(f_x)))));
    }

Yb(BcP(f_y,0+Fs(f_x))) = vr298;
}P+=Fs(f_x)+Fs(f_y);
goto w_dispatch;
    }
    }
case 180:
{
{
{tagged_t vr299 = Xb(BcP(f_x,0));
if (TaggedIsSVA(vr299)) {
tagged_t vr300;
do {
RefSVA(vr300,vr299);
if (vr300==vr299) {
BindSVA(vr299,Tagp(HVA,H));
PreLoadHVA(vr299,H);
break;
        }

vr299 = vr300;
      }
 while (TaggedIsSVA(vr299));
    }

HeapPush(H,vr299);
}{tagged_t vr301;
LoadHVA(vr301,H);
if (CondStackvar(Yb(BcP(f_y,0+Fs(f_x))))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0+Fs(f_x)))));
    }

Yb(BcP(f_y,0+Fs(f_x))) = vr301;
}P+=Fs(f_x)+Fs(f_y);
goto w_dispatch;
    }
    }
case 181:
HeapPush(H,Xb(BcP(f_x,0)));
HeapPush(H,Yb(BcP(f_y,0+Fs(f_x))));
P+=Fs(f_x)+Fs(f_y);
goto w_dispatch;
case 183:
{
{
HeapPush(H,Xb(BcP(f_x,0)));
{tagged_t vr302 = Yb(BcP(f_y,0+Fs(f_x)));
if (TaggedIsSVA(vr302)) {
tagged_t vr303;
do {
RefSVA(vr303,vr302);
if (vr303==vr302) {
BindSVA(vr302,Tagp(HVA,H));
PreLoadHVA(vr302,H);
break;
        }

vr302 = vr303;
      }
 while (TaggedIsSVA(vr302));
    }

HeapPush(H,vr302);
}P+=Fs(f_x)+Fs(f_y);
goto w_dispatch;
    }
    }
case 182:
{
{
{tagged_t vr304 = Xb(BcP(f_x,0));
if (TaggedIsSVA(vr304)) {
tagged_t vr305;
do {
RefSVA(vr305,vr304);
if (vr305==vr304) {
BindSVA(vr304,Tagp(HVA,H));
PreLoadHVA(vr304,H);
break;
        }

vr304 = vr305;
      }
 while (TaggedIsSVA(vr304));
    }

HeapPush(H,vr304);
}HeapPush(H,Yb(BcP(f_y,0+Fs(f_x))));
P+=Fs(f_x)+Fs(f_y);
goto w_dispatch;
    }
    }
case 184:
{
{
{tagged_t vr306 = Xb(BcP(f_x,0));
if (TaggedIsSVA(vr306)) {
tagged_t vr307;
do {
RefSVA(vr307,vr306);
if (vr307==vr306) {
BindSVA(vr306,Tagp(HVA,H));
PreLoadHVA(vr306,H);
break;
        }

vr306 = vr307;
      }
 while (TaggedIsSVA(vr306));
    }

HeapPush(H,vr306);
}{tagged_t vr308 = Yb(BcP(f_y,0+Fs(f_x)));
if (TaggedIsSVA(vr308)) {
tagged_t vr309;
do {
RefSVA(vr309,vr308);
if (vr309==vr308) {
BindSVA(vr308,Tagp(HVA,H));
PreLoadHVA(vr308,H);
break;
        }

vr308 = vr309;
      }
 while (TaggedIsSVA(vr308));
    }

HeapPush(H,vr308);
}P+=Fs(f_x)+Fs(f_y);
goto w_dispatch;
    }
    }
case 186:
{
{
HeapPush(H,Yb(BcP(f_y,0)));
intmach_t vr310 = (FTYPE_ctype(f_i_signed))BcP(f_i,0+Fs(f_y));
do {
ConstrHVA(H);
    }
 while (--vr310);
P+=Fs(f_y)+Fs(f_i);
goto w_dispatch;
    }
    }
case 187:
{
{
{tagged_t vr311 = Yb(BcP(f_y,0));
if (TaggedIsSVA(vr311)) {
tagged_t vr312;
do {
RefSVA(vr312,vr311);
if (vr312==vr311) {
BindSVA(vr311,Tagp(HVA,H));
PreLoadHVA(vr311,H);
break;
        }

vr311 = vr312;
      }
 while (TaggedIsSVA(vr311));
    }

HeapPush(H,vr311);
}intmach_t vr313 = (FTYPE_ctype(f_i_signed))BcP(f_i,0+Fs(f_y));
do {
ConstrHVA(H);
    }
 while (--vr313);
P+=Fs(f_y)+Fs(f_i);
goto w_dispatch;
    }
    }
case 189:
HeapPush(H,Yb(BcP(f_y,0)));
LoadHVA(Xb(BcP(f_x,0+Fs(f_y))),H);
P+=Fs(f_y)+Fs(f_x);
goto w_dispatch;
case 190:
{
{
{tagged_t vr314 = Yb(BcP(f_y,0));
if (TaggedIsSVA(vr314)) {
tagged_t vr315;
do {
RefSVA(vr315,vr314);
if (vr315==vr314) {
BindSVA(vr314,Tagp(HVA,H));
PreLoadHVA(vr314,H);
break;
        }

vr314 = vr315;
      }
 while (TaggedIsSVA(vr314));
    }

HeapPush(H,vr314);
}LoadHVA(Xb(BcP(f_x,0+Fs(f_y))),H);
P+=Fs(f_y)+Fs(f_x);
goto w_dispatch;
    }
    }
case 191:
HeapPush(H,Yb(BcP(f_y,0)));
LoadHVA(Yb(BcP(f_y,0+Fs(f_y))),H);
P+=Fs(f_y)+Fs(f_y);
goto w_dispatch;
case 192:
{
{
{tagged_t vr316 = Yb(BcP(f_y,0));
if (TaggedIsSVA(vr316)) {
tagged_t vr317;
do {
RefSVA(vr317,vr316);
if (vr317==vr316) {
BindSVA(vr316,Tagp(HVA,H));
PreLoadHVA(vr316,H);
break;
        }

vr316 = vr317;
      }
 while (TaggedIsSVA(vr316));
    }

HeapPush(H,vr316);
}LoadHVA(Yb(BcP(f_y,0+Fs(f_y))),H);
P+=Fs(f_y)+Fs(f_y);
goto w_dispatch;
    }
    }
case 200:
{
{
HeapPush(H,Yb(BcP(f_y,0)));
{tagged_t vr318;
LoadHVA(vr318,H);
if (CondStackvar(Yb(BcP(f_y,0+Fs(f_y))))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0+Fs(f_y)))));
    }

Yb(BcP(f_y,0+Fs(f_y))) = vr318;
}P+=Fs(f_y)+Fs(f_y);
goto w_dispatch;
    }
    }
case 201:
{
{
{tagged_t vr319 = Yb(BcP(f_y,0));
if (TaggedIsSVA(vr319)) {
tagged_t vr320;
do {
RefSVA(vr320,vr319);
if (vr320==vr319) {
BindSVA(vr319,Tagp(HVA,H));
PreLoadHVA(vr319,H);
break;
        }

vr319 = vr320;
      }
 while (TaggedIsSVA(vr319));
    }

HeapPush(H,vr319);
}{tagged_t vr321;
LoadHVA(vr321,H);
if (CondStackvar(Yb(BcP(f_y,0+Fs(f_y))))) {
TrailPushCheck(w->trail_top,Tagp(SVA,&Yb(BcP(f_y,0+Fs(f_y)))));
    }

Yb(BcP(f_y,0+Fs(f_y))) = vr321;
}P+=Fs(f_y)+Fs(f_y);
goto w_dispatch;
    }
    }
case 194:
HeapPush(H,Yb(BcP(f_y,0)));
HeapPush(H,Xb(BcP(f_x,0+Fs(f_y))));
P+=Fs(f_y)+Fs(f_x);
goto w_dispatch;
case 197:
{
{
HeapPush(H,Yb(BcP(f_y,0)));
{tagged_t vr322 = Xb(BcP(f_x,0+Fs(f_y)));
if (TaggedIsSVA(vr322)) {
tagged_t vr323;
do {
RefSVA(vr323,vr322);
if (vr323==vr322) {
BindSVA(vr322,Tagp(HVA,H));
PreLoadHVA(vr322,H);
break;
        }

vr322 = vr323;
      }
 while (TaggedIsSVA(vr322));
    }

HeapPush(H,vr322);
}P+=Fs(f_y)+Fs(f_x);
goto w_dispatch;
    }
    }
case 195:
{
{
{tagged_t vr324 = Yb(BcP(f_y,0));
if (TaggedIsSVA(vr324)) {
tagged_t vr325;
do {
RefSVA(vr325,vr324);
if (vr325==vr324) {
BindSVA(vr324,Tagp(HVA,H));
PreLoadHVA(vr324,H);
break;
        }

vr324 = vr325;
      }
 while (TaggedIsSVA(vr324));
    }

HeapPush(H,vr324);
}HeapPush(H,Xb(BcP(f_x,0+Fs(f_y))));
P+=Fs(f_y)+Fs(f_x);
goto w_dispatch;
    }
    }
case 198:
{
{
{tagged_t vr326 = Yb(BcP(f_y,0));
if (TaggedIsSVA(vr326)) {
tagged_t vr327;
do {
RefSVA(vr327,vr326);
if (vr327==vr326) {
BindSVA(vr326,Tagp(HVA,H));
PreLoadHVA(vr326,H);
break;
        }

vr326 = vr327;
      }
 while (TaggedIsSVA(vr326));
    }

HeapPush(H,vr326);
}{tagged_t vr328 = Xb(BcP(f_x,0+Fs(f_y)));
if (TaggedIsSVA(vr328)) {
tagged_t vr329;
do {
RefSVA(vr329,vr328);
if (vr329==vr328) {
BindSVA(vr328,Tagp(HVA,H));
PreLoadHVA(vr328,H);
break;
        }

vr328 = vr329;
      }
 while (TaggedIsSVA(vr328));
    }

HeapPush(H,vr328);
}P+=Fs(f_y)+Fs(f_x);
goto w_dispatch;
    }
    }
case 203:
HeapPush(H,Yb(BcP(f_y,0)));
HeapPush(H,Yb(BcP(f_y,0+Fs(f_y))));
P+=Fs(f_y)+Fs(f_y);
goto w_dispatch;
case 206:
{
{
HeapPush(H,Yb(BcP(f_y,0)));
{tagged_t vr330 = Yb(BcP(f_y,0+Fs(f_y)));
if (TaggedIsSVA(vr330)) {
tagged_t vr331;
do {
RefSVA(vr331,vr330);
if (vr331==vr330) {
BindSVA(vr330,Tagp(HVA,H));
PreLoadHVA(vr330,H);
break;
        }

vr330 = vr331;
      }
 while (TaggedIsSVA(vr330));
    }

HeapPush(H,vr330);
}P+=Fs(f_y)+Fs(f_y);
goto w_dispatch;
    }
    }
case 204:
{
{
{tagged_t vr332 = Yb(BcP(f_y,0));
if (TaggedIsSVA(vr332)) {
tagged_t vr333;
do {
RefSVA(vr333,vr332);
if (vr333==vr332) {
BindSVA(vr332,Tagp(HVA,H));
PreLoadHVA(vr332,H);
break;
        }

vr332 = vr333;
      }
 while (TaggedIsSVA(vr332));
    }

HeapPush(H,vr332);
}HeapPush(H,Yb(BcP(f_y,0+Fs(f_y))));
P+=Fs(f_y)+Fs(f_y);
goto w_dispatch;
    }
    }
case 207:
{
{
{tagged_t vr334 = Yb(BcP(f_y,0));
if (TaggedIsSVA(vr334)) {
tagged_t vr335;
do {
RefSVA(vr335,vr334);
if (vr335==vr334) {
BindSVA(vr334,Tagp(HVA,H));
PreLoadHVA(vr334,H);
break;
        }

vr334 = vr335;
      }
 while (TaggedIsSVA(vr334));
    }

HeapPush(H,vr334);
}{tagged_t vr336 = Yb(BcP(f_y,0+Fs(f_y)));
if (TaggedIsSVA(vr336)) {
tagged_t vr337;
do {
RefSVA(vr337,vr336);
if (vr337==vr336) {
BindSVA(vr336,Tagp(HVA,H));
PreLoadHVA(vr336,H);
break;
        }

vr336 = vr337;
      }
 while (TaggedIsSVA(vr336));
    }

HeapPush(H,vr336);
}P+=Fs(f_y)+Fs(f_y);
goto w_dispatch;
    }
    }
case 248:
P+=Fs(f_Q);
goto w_op249;
case 249:
w_op249:
#if defined(GAUGE)
INCR_COUNTER(BcP(f_l,0));
#endif
P+=Fs(f_l);
goto w_dispatch;
case 250:
P+=Fs(f_Q);
goto w_op251;
case 251:
w_op251:
#if defined(GAUGE)
if (!IsDeep()) {
B = w->choice;
if (!IsShallowTry()) {
#if defined(GAUGE)
INCR_COUNTER(BcP(f_l,0));
#endif
      }
 else {
#if defined(GAUGE)
INCR_COUNTER(BcP(f_l,0+Fs(f_l)));
#endif
      }

    }

#endif
P+=Fs(f_l)+Fs(f_l);
goto w_op65;
case 67:
goto fail;
case 245:
P+=Fs(f_Q);
goto w_op246;
case 246:
w_op246:
if (HeapCharDifference(H,Heap_End)<(intmach_t)BcP(f_l,0)) {
w->heap_top = H;
explicit_heap_overflow(w,(intmach_t)BcP(f_l,0)*2,(FTYPE_ctype(f_i_signed))BcP(f_i,0+Fs(f_l)));
H = w->heap_top;
    }

P+=Fs(f_l)+Fs(f_i);
goto w_dispatch;
case 65:
{
w_op65:
{
if (!IsDeep()) {
B = w->choice;
if (!IsShallowTry()) {
NECK_RETRY_PATCH(B);
      }
 else {
B->next_alt = w->next_alt;
B->frame = w->frame;
B->next_insn = w->next_insn;
B->local_top = w->local_top;
intmach_t vr338 = ChoiceArity(B);
for (intmach_t vr339 = 0;
vr339<vr338;vr339++) {
B->x[vr339] = w->x[vr339];
        }

if (ChoiceYounger(ChoiceOffset(B,CHOICEPAD),w->trail_top)) {
choice_overflow(w,2*CHOICEPAD*sizeof(tagged_t),TRUE);
        }

      }

SetDeep();
SetE(w->local_top);
    }

P+=0;
goto w_dispatch;
    }
    }
case 236:
{
w_op236:
{
tagged_t vr340 = X(3);
if (vr340&TagBitSVA) {
BindSVA(vr340,PointerToTerm(w->misc->ins));
    }
 else {
BindHVA(vr340,PointerToTerm(w->misc->ins));
    }

if (IsDeep()) {
goto w_op64;
    }

B = w->choice;
if (IsShallowTry()) {
def_clock = use_clock+1;
if (def_clock==65535) {
w->heap_top = H;
clock_overflow(w);
H = w->heap_top;
      }

    }

goto w_op66;
    }
    }
case 66:
{
w_op66:
{
if (!IsDeep()) {
B = w->choice;
if (!IsShallowTry()) {
NECK_RETRY_PATCH(B);
      }
 else {
B->next_alt = w->next_alt;
B->frame = w->frame;
B->next_insn = w->next_insn;
B->local_top = w->local_top;
intmach_t vr341 = ChoiceArity(B);
for (intmach_t vr342 = 0;
vr342<vr341;vr342++) {
B->x[vr342] = w->x[vr342];
        }

if (ChoiceYounger(ChoiceOffset(B,CHOICEPAD),w->trail_top)) {
choice_overflow(w,2*CHOICEPAD*sizeof(tagged_t),TRUE);
        }

      }

SetDeep();
    }
 else {
w->local_top = 0;
    }

SetE(w->frame);
P = w->next_insn;
PROFILE__HOOK_PROCEED;
goto w_dispatch;
    }
    }
case 64:
w_op64:
w->local_top = 0;
SetE(w->frame);
P = w->next_insn;
PROFILE__HOOK_PROCEED;
P+=0;
goto w_dispatch;
#if defined(PARBACK)
case 262:
w->heap_top = TaggedToPointer(w->choice->x[0]);
H = w->heap_top;
P = (bcp_t)*TaggedToPointer(w->choice->x[0]);
w->next_insn = w->choice->next_insn;
pop_choicept(w);
goto enter_predicate;
#endif
default:
goto illop;
  }
  }
exit_toplevel:
w->insn = P;
if (desc!=NULL&&desc->action&KEEP_STACKS) {
SAVE_WAM_STATE;
  }

if (Stop_This_Goal(w)) {
w->misc->exit_code = WAM_INTERRUPTED;
  }

ON_DEBUG({
  }
);
return;
illop:
SERIOUS_FAULT("unimplemented WAM instruction");
}
