#!/bin/sh

# Physical directory where the script is located
_base=$(e=$0;while test -L "$e";do d=$(dirname "$e");e=$(readlink "$e");\
        cd "$d";done;cd "$(dirname "$e")";pwd -P)

# Options

target=sh
reloc=no

while [ $# -gt 0 ]; do
    case "$1" in
	--sh|--bash) target=sh ;;
	--csh|--tcsh) target=csh ;;
#	--reloc) reloc=yes ;;
	*) 
	    cat <<EOF 
ERROR: Unrecognized option $1
EOF
	    exit 1
	    ;;
    esac
    shift
done

# Use DOTprofile
. "$_base"/DOTprofile

add_bindir() { # bindir
    bindir=$1
    if [ "${PATH:-0}" = "0" ] ; then
	PATH=$bindir
    else
	PATH=$bindir:$(printf "%s" "$PATH"|sed -e s:'\:'"$bindir"::g)
    fi
}

# Add additional paths from CIAOPATH
get_paths() {
    IFS=: get_paths_
}
get_paths_() {
    for i in $CIAOPATH; do
	add_bindir "$i"/build/bin
    done
}
get_paths

# DOTprofile contains info for relocatable
if [ x"${CIAOENGINE}" != x"" ]; then
    reloc=yes
fi

# ---------------------------------------------------------------------------

env_sh_help() {
    cat <<EOF
# Run this command to setup your environment:
# 
# eval "\$(ciao-env --sh)"
EOF
}

env_sh() {
    cat <<EOF
export PATH="$PATH"
export MANPATH="$MANPATH"
export INFOPATH="$INFOPATH"
EOF
}

env_sh_reloc() {
    cat <<EOF
export CIAOENGINE="$CIAOENGINE"
export CIAOHDIR="$CIAOHDIR"
export CIAOLIB="$CIAOLIB"
EOF
}

env_csh() {
    cat <<EOF
setenv PATH "$PATH"
setenv MANPATH "$MANPATH"
setenv INFOPATH "$INFOPATH"
EOF
}

env_csh_reloc() {
    cat <<EOF
setenv CIAOENGINE "$CIAOENGINE"
setenv CIAOHDIR "$CIAOHDIR"
setenv CIAOLIB "$CIAOLIB"
EOF
}

case $target in 
    sh) env_sh ;;
    csh) env_csh ;;
esac
if [ $reloc = yes ]; then
    case $target in 
	sh) env_sh_reloc ;;
	csh) env_csh_reloc ;;
    esac
fi
case $target in 
    sh) env_sh_help ;;
    # csh) ...
    #   # comments are not valid in eval for csh
    #   eval `ciao-env --csh`
esac

    
